import{chromium}from'/Users/panglaohu/Downloads/TigerInBamboo/tools/shot/node_modules/playwright/index.mjs';import{writeFile}from'node:fs/promises';
const b=await chromium.launch({channel:'chrome',headless:true,args:['--use-angle=metal']});try{const p=await b.newPage({viewport:{width:1400,height:1000}});await p.goto('http://localhost:8931/TigerMessenger/?autostart=1&baseReview=1');await p.waitForFunction(()=>window.__tm?.messenger?.landmarks?.bookshop?.userData.steampunkRobots,null,{timeout:180000});const report=await p.evaluate(async()=>{
 const t=window.__tm,T=t.THREE,shop=t.messenger.landmarks.bookshop,base=shop.userData.steampunkRobots;
 t.P.daySpeed=0;t.P.timeOfDay=.38;await new Promise(r=>setTimeout(r,2000));
 const sample=async()=>{const times=[],calls=[],triangles=[];await new Promise(resolve=>{let last=performance.now(),n=0;const frame=now=>{if(n++>=12){times.push(now-last);calls.push(t.renderer.info.render.calls);triangles.push(t.renderer.info.render.triangles);}last=now;if(n<100)requestAnimationFrame(frame);else resolve();};requestAnimationFrame(frame);});times.sort((a,b)=>a-b);calls.sort((a,b)=>a-b);triangles.sort((a,b)=>a-b);return{medianMs:times[Math.floor(times.length*.5)],p95Ms:times[Math.floor(times.length*.95)],medianDrawCalls:calls[Math.floor(calls.length*.5)],medianTriangles:triangles[Math.floor(triangles.length*.5)]};};
 const entry=await sample();const update=base.userData.update;let meshes=0,triangles=0;base.traverse(o=>{if(o.isMesh){meshes++;triangles+=(o.geometry.index?.count||o.geometry.attributes.position.count)/3;}});
 base.visible=false;shop.visible=false;base.userData.update=()=>{};await new Promise(r=>setTimeout(r,500));const withoutBase=await sample();base.visible=true;shop.visible=true;base.userData.update=update;
 return{environment:'Headless installed Chrome, Metal, 1400×1000, full original world, single test browser',entry,withoutBase,base:{meshes,triangles},limitation:'Diagnostic measurements on this host, not a 60 FPS guarantee; unrelated world rendering remains active.'};
 });await writeFile('artifacts/pipeline/bookshop-two-hour/performance.json',JSON.stringify(report,null,2));console.log(report);}finally{await b.close()}
