import fs from'node:fs';import * as T from'three';
import{actualUserMarkedStructureFixture}from'../../tests/world/targetUserMarkedStructure.fixture.mjs';
import{buildMountainSurfaceIndex}from'../../src/world/citadel/mountainSurfaceIndex.js';
import{createTargetTransitLandwardContactField}from'../../src/world/citadel/targetTransitLandwardContactField.js';
import{TARGET_CITY_PLATFORMS}from'../../src/world/citadel/targetTerrainCandidate.js';
const f=actualUserMarkedStructureFixture(),matrix=f.castle.matrixWorld.clone(),inv=matrix.clone().invert(),down=new T.Vector3(0,-1,0).transformDirection(matrix),terrainIndex=buildMountainSurfaceIndex([f.terrain]),seaIndex=buildMountainSurfaceIndex([f.ocean]);
const sampler=index=>(x,z)=>{const h=index.sample(new T.Ray(new T.Vector3(x,250,z).applyMatrix4(matrix),down),0,700);return h?h.point.clone().applyMatrix4(inv).y:null;},sampleTerrain=sampler(terrainIndex),sampleSea=sampler(seaIndex),field=createTargetTransitLandwardContactField({release:f.release,sampleTerrain,sampleSea,platforms:TARGET_CITY_PLATFORMS});
const summary={};for(const shore of['oldShore','newShore']){const rows=field.rows.filter(r=>r.shore===shore),gaps=rows.filter(r=>r.gap!==null).map(r=>r.gap).sort((a,b)=>a-b);summary[shore]={stations:rows.length,counts:{},min:gaps[0],median:gaps[Math.floor(gaps.length/2)],max:gaps.at(-1)};for(const r of rows)summary[shore].counts[r.status]=(summary[shore].counts[r.status]??0)+1;}
const samples=[];for(let x=-143;x<=143;x+=1)for(let z=-72;z<=107;z+=1){const h=sampleTerrain(x,z),sea=sampleSea(x,z);if(h===null||sea===null)continue;const out=field.height(x,z,h,sea);if(out!==h)samples.push({x,z,before:h,after:out});}
const dir=new URL('../../artifacts/pipeline/citadel-transit-contact-20261006/',import.meta.url);fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(new URL('survey.json',dir),JSON.stringify({release:f.release.version,fixture:'actualUserMarkedStructureFixture: production applyTargetTerrainCandidate plus actual rendered ocean triangles',summary,field:field.report,changed:samples},null,2));console.log(JSON.stringify({summary,segments:field.report.segments,changed:samples.length,maxRaise:field.report.maxRaise},null,2));

// Preserve the exact final indexed topology, including sea-domain boundary and bottom.
const geometry=f.terrain.geometry.clone(),position=geometry.attributes.position,toChart=inv.clone().multiply(f.terrain.matrixWorld),toMesh=toChart.clone().invert();let changedVertices=0,protectedChanged=0;
for(let i=0;i<position.count;i++){const q=new T.Vector3().fromBufferAttribute(position,i).applyMatrix4(toChart),before=sampleTerrain(q.x,q.z),sea=sampleSea(q.x,q.z);if(before===null||sea===null||Math.abs(before-q.y)>.02)continue;const y=field.height(q.x,q.z,q.y,sea);if(y>q.y+1e-7){changedVertices++;if(TARGET_CITY_PLATFORMS.some(p=>Math.hypot((q.x-p.center[0])/p.radii[0],(q.z-p.center[1])/p.radii[1])<=1))protectedChanged++;q.y=y;q.applyMatrix4(toMesh);position.setXYZ(i,q.x,q.y,q.z);}}
geometry.computeVertexNormals();geometry.computeBoundingBox();geometry.computeBoundingSphere();const mesh=new T.Mesh(geometry,new T.MeshBasicMaterial({side:T.DoubleSide}));mesh.matrixAutoUpdate=false;mesh.matrix.copy(f.terrain.matrixWorld);mesh.updateMatrixWorld(true);
const triangles=[],grid=new Map(),cell=16;function keys(box){const list=[];for(let x=Math.floor(box.min.x/cell);x<=Math.floor(box.max.x/cell);x++)for(let y=Math.floor(box.min.y/cell);y<=Math.floor(box.max.y/cell);y++)for(let z=Math.floor(box.min.z/cell);z<=Math.floor(box.max.z/cell);z++)list.push(x+','+y+','+z);return list;}
const idx=geometry.index;for(let i=0;i<idx.count;i+=3){const points=[0,1,2].map(j=>new T.Vector3().fromBufferAttribute(position,idx.getX(i+j)).applyMatrix4(mesh.matrixWorld)),box=new T.Box3().setFromPoints(points),id=triangles.length;triangles.push({points,box});for(const key of keys(box)){if(!grid.has(key))grid.set(key,[]);grid.get(key).push(id);}}
const changedIndex=buildMountainSurfaceIndex([mesh]),body=new T.Box3(new T.Vector3(-2.32,-.6,-3.49),new T.Vector3(2.32,5.71,3.49)),checks={poses:0,triangleHits:[],soilHits:[],missing:0};
for(const lane of['red','blue']){const c=f.release.curves[lane],n=Math.ceil(c.getLength());for(let i=0;i<=n;i++){checks.poses++;const w=c.getPointAt(i/n),t=c.getTangentAt(i/n).normalize(),right=w.clone().normalize().cross(t).normalize(),up=t.clone().cross(right).normalize(),m=new T.Matrix4().makeBasis(right,up,t).setPosition(w),mi=m.clone().invert(),box=body.clone().applyMatrix4(m),ids=new Set(keys(box).flatMap(k=>grid.get(k)??[]));for(const id of ids){const tri=triangles[id];if(box.intersectsBox(tri.box)&&body.intersectsTriangle(new T.Triangle(...tri.points.map(p=>p.clone().applyMatrix4(mi))))){const oldPoints=[0,1,2].map(j=>new T.Vector3().fromBufferAttribute(f.terrain.geometry.attributes.position,idx.getX(id*3+j)).applyMatrix4(f.terrain.matrixWorld).applyMatrix4(mi));checks.triangleHits.push({lane,i,id,center:w.clone().applyMatrix4(inv).toArray(),alsoBefore:body.intersectsTriangle(new T.Triangle(...oldPoints)),triangle:tri.points.map(p=>p.clone().applyMatrix4(inv).toArray())});break;}}
for(const x of[-2.32,0,2.32])for(const z of[-3.49,0,3.49]){const q=w.clone().addScaledVector(right,x).addScaledVector(t,z).addScaledVector(up,-.6).applyMatrix4(inv),hit=changedIndex.sample(new T.Ray(new T.Vector3(q.x,250,q.z).applyMatrix4(matrix),down),0,700);if(!hit)checks.missing++;else if(hit.point.clone().applyMatrix4(inv).y>q.y-.08)checks.soilHits.push({lane,i});}}}
fs.writeFileSync(new URL('mesh-audit.json',dir),JSON.stringify({changedVertices,protectedChanged,originalVertices:f.terrain.geometry.attributes.position.count,outputVertices:position.count,checks,limitations:['Exact production fixture terrain topology retained; top vertices only changed.','Only the altered terrain is included in this audit, not gallery structure or every world object.','Finite 1m loaded OBB and nine underbody probes, not continuous collision.','Missing surface remains unverified; no automatic installation.']},null,2));console.log(JSON.stringify({changedVertices,protectedChanged,poses:checks.poses,triangleHits:checks.triangleHits.length,soilHits:checks.soilHits.length,missing:checks.missing}));geometry.dispose();mesh.material.dispose();f.dispose();
