import * as T from 'three';import fs from 'node:fs';
import {actualCliffTransitFixture} from '../../tests/world/targetCliffTransitStructure.fixture.mjs';
import {createTargetUserMarkedProductionRelease} from '../../src/world/citadel/targetUserMarkedProductionRelease.js';
import {createTargetEastCliffProductionRelease} from '../../src/world/citadel/targetEastCliffProductionRelease.js';
import {createTargetEastGlobalCrossingCandidate} from '../../src/world/citadel/targetEastGlobalCrossingCandidate.js';
class OBB{constructor(center,halfSize,rotation){this.center=center;this.halfSize=halfSize.toArray();this.axes=[0,1,2].map(i=>new T.Vector3().fromArray(rotation.elements,i*3));}intersectsOBB(b){const d=b.center.clone().sub(this.center),axes=[...this.axes,...b.axes,...this.axes.flatMap(a=>b.axes.map(v=>a.clone().cross(v)))];for(const a of axes){if(a.lengthSq()<1e-18)continue;const ra=this.axes.reduce((s,v,i)=>s+Math.abs(a.dot(v))*this.halfSize[i],0),rb=b.axes.reduce((s,v,i)=>s+Math.abs(a.dot(v))*b.halfSize[i],0);if(Math.abs(d.dot(a))>ra+rb+1e-9)return false;}return true;}}
const ROOT=new URL('../../',import.meta.url),read=n=>JSON.parse(fs.readFileSync(new URL('artifacts/pipeline/citadel-east-shore-route-20261006/'+n,ROOT))),f=actualCliffTransitFixture();
try{const base=createTargetEastCliffProductionRelease({enabled:true,sourceCurves:f.sourceCurves,retainedRelease:createTargetUserMarkedProductionRelease({sourceCurves:f.sourceCurves}),candidateInput:read('remesh-expanded-shift-audit.json').candidateInput,terrainArtifact:read('remesh-final-surface-geometry.json'),cityGalleryScope:true}),candidate=createTargetEastGlobalCrossingCandidate({enabled:true,release:base.release,sourceCurves:f.sourceCurves,lateral:0,sourceExtensionMetres:50,startMetres:10,endMetres:300,frontLoadedGrade:.0395,independentRadialProfiles:true,tailGrade:-.004});
 const curves=candidate.curves,tables=Object.fromEntries(['red','blue'].map(l=>[l,Array.from({length:1025},(_,i)=>curves[l].getPointAt(i/1024))]));
 function nearest(l,p){let j=0,d=Infinity;tables[l].forEach((q,i)=>{const v=p.distanceToSquared(q);if(v<d){j=i;d=v;}});let lo=Math.max(0,(j-1)/1024),hi=Math.min(1,(j+1)/1024);for(let i=0;i<32;i++){const a=lo+(hi-lo)/3,b=hi-(hi-lo)/3;if(curves[l].getPointAt(a).distanceToSquared(p)<curves[l].getPointAt(b).distanceToSquared(p))hi=b;else lo=a;}return(lo+hi)/2;}
 function body(l,u){const p=curves[l].getPointAt(u),t=curves[l].getTangentAt(u).normalize(),right=p.clone().normalize().cross(t).normalize(),up=t.clone().cross(right).normalize();return new OBB(p.clone().addScaledVector(up,(5.36-.036)/2),new T.Vector3(1.75,(5.36+.036)/2,3.49),new T.Matrix3().setFromMatrix4(new T.Matrix4().makeBasis(right,up,t)));}
 const records=[],hits=[];let maxMid=0,minSpacing=Infinity,maxSpacing=0,maxRadialDelta=0;const n=Math.ceil(curves.center.getLength()/.5);
 for(let i=0;i<=n;i++){const u=i/n,p=curves.center.getPointAt(u),r=nearest('red',p),b=nearest('blue',p),rp=curves.red.getPointAt(r),bp=curves.blue.getPointAt(b),spacing=rp.distanceTo(bp),mid=rp.clone().add(bp).multiplyScalar(.5).distanceTo(p),radialDelta=rp.length()-bp.length();minSpacing=Math.min(minSpacing,spacing);maxSpacing=Math.max(maxSpacing,spacing);maxMid=Math.max(maxMid,mid);maxRadialDelta=Math.max(maxRadialDelta,Math.abs(radialDelta));
  // Longitudinal opposition around the matched section, not equal u lanes.
  for(const ds of[-7,-5,-3,-1,0,1,3,5,7]){const v=b+ds/curves.blue.getLength();if(v<0||v>1)continue;if(body('red',r).intersectsOBB(body('blue',v)))hits.push({u,redU:r,blueU:v,ds});}
  records.push({centerU:u,redU:r,blueU:b,spacing,midpointDistance:mid,radialDelta});
 }
 const interfaces=Object.fromEntries(['center','red','blue'].map(l=>{const old=base.release.specs[l],now=candidate.specs[l],source=f.sourceCurves[l],oldEntry=base.release.cityGalleryCoverage.boundaries[l],newEntry=candidate.release.cityGalleryCoverage.boundaries[l],inverse=f.castle.matrixWorld.clone().invert();return[l,{oldSource:[old.startU,old.endU],newSource:[now.startU,now.endU],sourceExtensionMetres:(old.startU-now.startU)*source.getLength(),oldWorld:source.getPointAt(old.startU).toArray(),newWorld:source.getPointAt(now.startU).toArray(),oldLocal:source.getPointAt(old.startU).applyMatrix4(inverse).toArray(),newLocal:source.getPointAt(now.startU).applyMatrix4(inverse).toArray(),globalLengthBefore:base.startupPreview.curves[l].getLength(),globalLengthAfter:candidate.startup.curves[l].getLength(),netGlobalLengthDelta:candidate.startup.curves[l].getLength()-base.startupPreview.curves[l].getLength(),oldEntry,newEntry,entryChartHeightDifference:newEntry.castleLocal[1]-oldEntry.castleLocal[1],untouchedSourceIntervals:[[0,now.startU],[now.endU,1]],centralReferenceRetained:candidate.release.segments[l].central===base.release.segments[l].central,oldShoreReferenceRetained:candidate.release.segments[l].oldShore===base.release.segments[l].oldShore}];}));
 const report={accepted:false,installed:false,routeReport:candidate.report,ranges:candidate.release.ranges,method:'Each center sample independently finds nearest actual red and blue curve geometry; no equal lane arc-fraction assumption. Loaded boxes include all cargo and wheels; nine longitudinal opposition phases, finite SAT, no animation or continuous proof.',poses:n+1,minSpacing,maxSpacing,maxMidpointDistance:maxMid,maxAbsoluteRadialDelta:maxRadialDelta,opposingBodyContacts:hits,interfaces,records};fs.writeFileSync(new URL('artifacts/pipeline/citadel-global-approach-support-20261006/crossing-50-correspondence.json',ROOT),JSON.stringify(report,null,2));console.log(JSON.stringify({...report,records:undefined,interfaces:undefined}));
}finally{f.dispose();}
