import {chromium} from '../../../tools/shot/node_modules/playwright/index.mjs';import {mkdir,writeFile} from 'node:fs/promises';const out=new URL('../../artifacts/pipeline/citadel-camp-overlap/',import.meta.url);await mkdir(out,{recursive:true});const b=await chromium.launch({channel:'chrome',headless:true,args:['--use-angle=metal']});try{const p=await b.newPage();await p.addInitScript(()=>{const raf=requestAnimationFrame.bind(window);window.requestAnimationFrame=cb=>cb.name==='animate'?0:raf(cb);});await p.goto('http://localhost:8931/TigerMessenger/?autostart=1',{timeout:180000});await p.waitForFunction(()=>window.__tm?.messenger,null,{timeout:180000});const report=await p.evaluate(async()=>{
 const t=window.__tm,T=t.THREE,c=t.scene.getObjectByName('castleContainer'),city=c.getObjectByName('highland-west-city'),camp=t.scene.getObjectByName('starting-camp'),terrain=c.getObjectByName('citadel-oskar-grid-mountain-surface');
 const {officialOceanLevelAt}=await import('/TigerMessenger/src/world/waterV8/officialOcean.js');t.scene.updateMatrixWorld(true);
 const ray=new T.Raycaster();ray.layers.enableAll();const patches=[];
 for(const o of camp.children){if(o.name!=='camp-flat-patch')continue;
  const points=[o.getWorldPosition(new T.Vector3())];const a=o.geometry.attributes.position;for(let i=1;i<a.count;i++)points.push(o.localToWorld(new T.Vector3().fromBufferAttribute(a,i)));
  let covered=0,maxBurial=0;for(const w of points){const d=w.clone().normalize();ray.set(d.clone().multiplyScalar(400),d.clone().negate());const h=ray.intersectObject(terrain,false)[0];if(h&&h.point.length()>w.length()+.1){covered++;maxBurial=Math.max(maxBurial,h.point.length()-w.length());}}
  const w=points[0];patches.push({castle:c.worldToLocal(w.clone()).toArray(),city:city.worldToLocal(w.clone()).toArray(),seaAltitude:w.length()-160-officialOceanLevelAt(w),covered,samples:points.length,maxBurial});
 }
 const objects=[];for(const o of camp.children){if(o.name==='camp-flat-patch'||o.type==='Object3D'||o.geometry?.type==='RingGeometry')continue;const w=o.getWorldPosition(new T.Vector3()),dir=w.clone().normalize();ray.set(dir.clone().multiplyScalar(400),dir.clone().negate());const h=ray.intersectObject(terrain,false)[0];objects.push({name:o.name||o.type,uuid:o.uuid,castle:c.worldToLocal(w.clone()).toArray(),burial:h?Math.max(0,h.point.length()-w.length()):0});}const anchors=[];for(const name of ['music-elder','fox-ali','hard-to-find-bookshop','player']){const o=t.scene.getObjectByName(name);if(o){const w=o.getWorldPosition(new T.Vector3()),dir=w.clone().normalize();ray.set(dir.clone().multiplyScalar(400),dir.clone().negate());const hit=ray.intersectObject(terrain,false)[0];anchors.push({name,castle:c.worldToLocal(w.clone()).toArray(),burial:hit?Math.max(0,hit.point.length()-w.length()):0});}}
 return {patches,anchors,objects,totalCovered:patches.reduce((n,r)=>n+r.covered,0),scope:'Radial intersection with main citadel terrain at actual camp decoration centers and perimeter vertices; not a full collision sweep.'};
 });await writeFile(new URL('report.json',out),JSON.stringify(report,null,2));console.log(JSON.stringify(report));}finally{await b.close();}
