import{createTargetCliffTransitRelease}from'../../src/world/citadel/targetCliffTransitRelease.js';
import{createTargetCityBayBridge}from'../../src/world/citadel/targetCityBayBridge.js';
import{createPlanet,paintPlanetOceanBed}from'../../src/world/planet.js';
import{createTargetCoastalCliffCutField}from'../../src/world/citadel/targetCoastalCliffCutField.js';
import{buildTargetTerrainHeightfield}from'../../src/world/citadel/targetTerrainHeightfield.js';
import{buildMountainSurfaceIndex}from'../../src/world/citadel/mountainSurfaceIndex.js';
import{replayTargetCliffShoreCurve,createTargetCliffOffsetCurve}from'../../src/world/citadel/targetCliffShoreRoute.js';
import fs from'node:fs';import * as T from'three';import{buildTargetCliffShoreBezier}from'../../src/world/citadel/targetCliffShoreRoute.js';import{createTargetNewCityRetreatField}from'../../src/world/citadel/targetNewCityRetreatField.js';import{createTargetRailCliffField}from'../../src/world/citadel/targetRailCliffField.js';import{targetTerrainHeight,TARGET_CITY_PLATFORMS}from'../../src/world/citadel/targetTerrainCandidate.js';import{createCastleOceanSampler}from'../../src/world/citadel/newCityRidgeCandidate.js';import{officialOceanLevelAt}from'../../src/world/waterV8/officialOcean.js';
const root=new URL('../../',import.meta.url),read=p=>JSON.parse(fs.readFileSync(new URL(p,root))),live=read('artifacts/pipeline/citadel-live-tram-clearance-20261006/global-tram-samples.json'),plan=read('artifacts/pipeline/citadel-cliff-transit-plan-20261006/sections.json').trials.at(-1),matrix=new T.Matrix4().fromArray(live.castleMatrix),sea=createCastleOceanSampler(matrix,160),retreat=createTargetNewCityRetreatField({platforms:TARGET_CITY_PLATFORMS}),rail=createTargetRailCliffField({...live,platforms:TARGET_CITY_PLATFORMS}),terrain=(x,z)=>{if(x< -143||x>143||z< -72||z>107)return null;const s=sea(x,z);return s===null?null:retreat.height(x,z,rail.height(x,z,targetTerrainHeight(x,z,s,{aprons:true,saddle:true,valleyBenches:true}),s),s);};


globalThis.document={getElementById:()=>null};globalThis.window={addEventListener(){}};const{createChristchurchTramSourceCurves}=await import('../../src/world/tramSystem.js'),sources=createChristchurchTramSourceCurves(160),release=createTargetCliffTransitRelease({sourceCurves:sources}),cut=createTargetCoastalCliffCutField({...release.coastalCliffCuts,platforms:TARGET_CITY_PLATFORMS}),height=(x,z)=>{const h=terrain(x,z),s=sea(x,z);return h===null||s===null?null:cut.height(x,z,h,s);},built=buildTargetTerrainHeightfield({bounds:release.report.terrainDomain,step:1.7,heightAt:height,floorAt:(x,z)=>{const s=sea(x,z);return s===null?null:s-12;}}),mesh=new T.Mesh(built.geometry,new T.MeshBasicMaterial({side:T.DoubleSide}));mesh.name='final-target-terrain-with-cliff-cut';mesh.matrixAutoUpdate=false;mesh.matrix.copy(matrix);mesh.updateMatrixWorld();
const saved=read('artifacts/pipeline/citadel-four-hour-20261005/r47-arches-clouds-target-front-plants-terrain.json'),bridge=createTargetCityBayBridge({path:saved.cityDetail.bridge.path,width:saved.cityDetail.bridge.width,maxSpan:36,pierWidth:1.8,groundHeightAt:height,oceanHeightAt:sea});bridge.group.matrixAutoUpdate=false;bridge.group.matrix.copy(matrix);bridge.group.updateMatrixWorld(true);const scene=new T.Group(),planet=paintPlanetOceanBed(createPlanet(scene));scene.updateMatrixWorld(true);
const triangles=[],grid=new Map(),cell=16;function keys(box){const list=[];for(let x=Math.floor(box.min.x/cell);x<=Math.floor(box.max.x/cell);x++)for(let y=Math.floor(box.min.y/cell);y<=Math.floor(box.max.y/cell);y++)for(let z=Math.floor(box.min.z/cell);z<=Math.floor(box.max.z/cell);z++)list.push(x+','+y+','+z);return list;}
for(const root of[mesh,bridge.group,planet])root.traverse(o=>{if(!o.isMesh)return;const p=o.geometry.attributes.position,idx=o.geometry.index;for(let i=0;i<(idx?.count??p.count);i+=3){const points=[0,1,2].map(j=>new T.Vector3().fromBufferAttribute(p,idx?idx.getX(i+j):i+j).applyMatrix4(o.matrixWorld)),box=new T.Box3().setFromPoints(points),id=triangles.length;triangles.push({name:o.name,points,box});for(const key of keys(box)){if(!grid.has(key))grid.set(key,[]);grid.get(key).push(id);}}});
const surfaceIndex=buildMountainSurfaceIndex([mesh]),castleUp=new T.Vector3(0,1,0).transformDirection(matrix),chartInverse=matrix.clone().invert();
const body=new T.Box3(new T.Vector3(-2.32,-.6,-3.49),new T.Vector3(2.32,3.242,3.49)),audits={},allLines={};
for(const lane of['red','blue'])for(const part of['replacement','retainedOld']){const curve=part==='replacement'?release.curves[lane]:release.segments[lane].retainedOld,n=Math.ceil(curve.getLength()),hits=[],counts={},points=[],solidFailures=[],missingUnderbody=[];for(let i=0;i<=n;i++){const w=curve.getPointAt(i/n),t=curve.getTangentAt(i/n),rad=w.clone().normalize(),right=rad.clone().cross(t).normalize(),up=t.clone().cross(right).normalize(),m=new T.Matrix4().makeBasis(right,up,t).setPosition(w),inv=m.clone().invert(),box=body.clone().applyMatrix4(m),ids=new Set(keys(box).flatMap(k=>grid.get(k)??[])),names=new Set();for(const id of ids){const tri=triangles[id];if(box.intersectsBox(tri.box)&&body.intersectsTriangle(new T.Triangle(...tri.points.map(p=>p.clone().applyMatrix4(inv)))))names.add(tri.name);}for(const name of names)counts[name]=(counts[name]??0)+1;const local=w.clone().applyMatrix4(matrix.clone().invert()).toArray();if(names.size)hits.push({i,u:i/n,local,names:[...names]});for(const xx of[-2.32,0,2.32])for(const zz of[-3.49,0,3.49]){const bottom=w.clone().addScaledVector(right,xx).addScaledVector(t,zz).addScaledVector(up,-.6),q=bottom.clone().applyMatrix4(chartInverse),origin=new T.Vector3(q.x,100,q.z).applyMatrix4(matrix),hit=surfaceIndex.sample(new T.Ray(origin,castleUp.clone().negate()),0,500);if(!hit)missingUnderbody.push({i,local:q.toArray(),direct:missingUnderbody.length<5?new T.Raycaster(origin,castleUp.clone().negate(),0,500).intersectObject(mesh,false).length:null});else if(hit.point.clone().applyMatrix4(chartInverse).y>q.y-.08)solidFailures.push({i,local:q.toArray(),surface:hit.point.clone().applyMatrix4(chartInverse).y});}points.push(local);}audits[lane+'-'+part]={samples:n+1,length:curve.getLength(),counts,hits,solidFailures,missingUnderbodyCount:missingUnderbody.length,missingExamples:missingUnderbody.slice(0,5)};allLines[lane+'-'+part]=points;}
const terrainPositions=mesh.geometry.attributes.position,terrainIndex=mesh.geometry.index,topTriangles=[];for(let i=0;i<terrainIndex.count;i+=3){const p=[0,1,2].map(j=>new T.Vector3().fromBufferAttribute(terrainPositions,terrainIndex.getX(i+j))),normal=new T.Triangle(...p).getNormal(new T.Vector3());const center=p.reduce((v,q)=>v.add(q),new T.Vector3()).multiplyScalar(1/3),s=sea(center.x,center.z);if(normal.y>.05&&s!==null&&center.y>s+.2)topTriangles.push(p.map(p=>p.toArray()));}
const dir=new URL('artifacts/pipeline/citadel-cliff-shore-route-20261006/',root);fs.writeFileSync(new URL('independent-scene-audit.json',dir),JSON.stringify({coverage:['Current target terrain factory with real source rail cut, new-city retreat, explicit old exterior cut; exact generated mesh triangles','Original r47 bridge reconstructed by same factory against new terrain','Production legacy planet sphere/canyon and ocean-bed material factory'],limitations:['No actual loaded V8/V9 terrain manifest snapshot available; do not claim every planet terrain compiled here matches current runtime.','Vehicle OBB sampled at one meter, static triangles; not continuous swept collision or loaded cargo.','Inside a closed terrain solid can require separate point inclusion; previous underbody vertical triangle audit retained.','No saved live ship trajectory/hull snapshot; boat route cannot be approved from a guessed straight line.'],triangles:triangles.length,audits},null,2));fs.writeFileSync(new URL('engineering-layout-data.json',dir),JSON.stringify({topTriangles,lines:allLines,oldBridge:saved.cityDetail.bridge.path,camera:saved.camera,castleMatrix:matrix.elements,platforms:TARGET_CITY_PLATFORMS,junctions:release.report.junctions,cuts:release.coastalCliffCuts.cuts}));console.log(JSON.stringify(Object.fromEntries(Object.entries(audits).map(([k,a])=>[k,{samples:a.samples,counts:a.counts,solidFailures:a.solidFailures.length,missing:a.missingUnderbodyCount}])),null,2));
