import fs from 'node:fs';import path from 'node:path';import {pathToFileURL}from'node:url';import crypto from'node:crypto';
const project=path.resolve(import.meta.dirname,'../..'),out=path.join(project,'artifacts/pipeline/citadel-east-wall-simplification-20261006');fs.mkdirSync(out,{recursive:true});
const builderPath=path.join(project,'src/world/citadel/targetEastCliffRemeshPatch.js'),originalSource=fs.readFileSync(builderPath,'utf8');
let traced=originalSource.replace("from 'three'",`from '${import.meta.resolve('three')}'`).replace('push({a,b,ay,by});','push({a,b,ay,by,cut:piece.cut});').replace('let wallEdges=0;','const recordedWalls=[];let wallEdges=0;').replace('wall([vertex(a.a,a.ay)', 'const faceStart=indices.length/3;wall([vertex(a.a,a.ay)').replace('wallEdges++;','if(b&&a.cut!==b.cut)recordedWalls.push({start:faceStart,end:indices.length/3,top:[a.a,a.b],height:[a.ay,a.by,lowA,lowB]});wallEdges++;').replace('return{geometry,origin,report};','return{geometry,origin,report,recordedWalls};');
if(!traced.includes('const faceStart='))throw Error('trace insertion no longer matches builder');
const traceURL='data:text/javascript;base64,'+Buffer.from(traced).toString('base64'),sourceScript=path.join(project,'tools/pipeline/audit_east_cliff_remesh_expanded.mjs');
let prefix=fs.readFileSync(sourceScript,'utf8').split('const exterior=')[0];prefix=prefix.replace(/from\s*(['"])(\.[^'"]+)\1/g,(_,q,s)=>`from '${pathToFileURL(path.resolve(path.dirname(sourceScript),s)).href}'`);
const call=prefix.match(/const patch=buildEastCliffRemeshPatch\(([^;]+)\);/);if(!call)throw Error('fixture patch call missing');prefix=prefix.replace(call[0],`const baselinePatch=buildEastCliffRemeshPatch(${call[1]}); const patch=tracedBuild(${call[1]});`);
const pre=`const {buildEastCliffRemeshPatch:tracedBuild}=await import(${JSON.stringify(traceURL)});\nimport{simplifyEastCliffWalls,cliffWallGeometryEpoch}from '${pathToFileURL(path.join(project,'src/world/citadel/targetEastCliffWallSimplification.js'))}';\n`;
const post=`
const same=JSON.stringify(cliffWallGeometryEpoch(patch.geometry))===JSON.stringify(cliffWallGeometryEpoch(baselinePatch.geometry));if(!same)throw Error('diagnostic trace changed builder geometry');
const wallFaces=patch.recordedWalls.flatMap(r=>Array.from({length:r.end-r.start},(_,i)=>r.start+i));
const provenance={kind:'recorded-builder-new-cliff-faces',builderSourceHash:${JSON.stringify(crypto.createHash('sha256').update(originalSource).digest('hex'))},geometryEpoch:cliffWallGeometryEpoch(patch.geometry),faces:wallFaces};
const result=simplifyEastCliffWalls({enabled:true,geometry:patch.geometry,provenance,faceFilter:({points})=>{const p=points.map(v=>v.clone().add(new T.Vector3(...patch.origin)));return p.every(v=>v.x>=83&&v.x<=85&&v.z>=79&&v.z<=84);}});
const selected=wallFaces.filter(i=>{const pts=[0,1,2].map(j=>new T.Vector3().fromBufferAttribute(patch.geometry.attributes.position,patch.geometry.index.getX(i*3+j)).add(new T.Vector3(...patch.origin)));return pts.every(v=>v.x>=83&&v.x<=85&&v.z>=79&&v.z<=84);});
function tris(g,faces){return faces.map(f=>[0,1,2].map(j=>new T.Vector3().fromBufferAttribute(g.attributes.position,g.index.getX(f*3+j)).add(new T.Vector3(...patch.origin)).toArray()));}
const {createEastCliffAlignmentCandidate}=await import('${pathToFileURL(path.join(project,'src/world/citadel/targetEastCliffAlignmentCandidate.js'))}');
const savedInput=JSON.parse(fs.readFileSync('${path.join(project,'artifacts/pipeline/citadel-east-shore-route-20261006/remesh-final-surface-audit.json')}','utf8')).candidateInput;
const replay=createEastCliffAlignmentCandidate({enabled:true,input:savedInput,sourceCurves:f.sourceCurves,retainedRelease:f.release,castleMatrix:matrix});
const removed=new Set(result.report.clusters.flatMap(c=>c.sourceFaces));
const unchangedSelected=selected.filter(f=>!removed.has(f));
const afterTriangles=[...tris(patch.geometry,unchangedSelected),...tris(result.geometry,Array.from({length:result.report.addedFaces},(_,i)=>result.geometry.index.count/3-result.report.addedFaces+i))];
const beforeTriangles=tris(patch.geometry,selected),toWorld=t=>t.map(p=>new T.Vector3(...p).applyMatrix4(matrix));
const oldT=beforeTriangles.map(toWorld),newT=afterTriangles.map(toWorld),wallBox=new T.Box3().setFromPoints(oldT.flat());
const envelope=new T.Box3(new T.Vector3(-2.32,-.6,-3.49),new T.Vector3(2.32,5.71,3.49));
const loaded={tested:0,beforeHits:0,afterHits:0,changedResults:0};for(const curve of[replay.curves.red,replay.curves.blue]){const n=Math.ceil(curve.getLength()/.5);for(let i=0;i<=n;i++){const pos=curve.getPointAt(i/n),t=curve.getTangentAt(i/n).normalize(),right=pos.clone().normalize().cross(t).normalize(),up=t.clone().cross(right).normalize(),mat=new T.Matrix4().makeBasis(right,up,t).setPosition(pos),invMat=mat.clone().invert();if(!envelope.clone().applyMatrix4(mat).intersectsBox(wallBox))continue;const hit=ts=>ts.some(tr=>envelope.intersectsTriangle(new T.Triangle(...tr.map(p=>p.clone().applyMatrix4(invMat)))));const a=hit(oldT),b=hit(newT);loaded.tested++;loaded.beforeHits+=+a;loaded.afterHits+=+b;loaded.changedResults+=+(a!==b);}}
const oldPatchMesh=new T.Mesh(patch.geometry),newPatchMesh=new T.Mesh(result.geometry);for(const m of[oldPatchMesh,newPatchMesh]){m.matrixAutoUpdate=false;m.matrix.copy(matrix).multiply(new T.Matrix4().makeTranslation(...patch.origin));m.updateMatrixWorld(true);}const oldPI=buildMountainSurfaceIndex([oldPatchMesh]),newPI=buildMountainSurfaceIndex([newPatchMesh]);
const support={publicVertices:0,insidePatch:0,rayDifferences:0,maxDifference:0,scope:'All public vertices in existing audit x60..108/z54..105; compare patch ray only where inside patch. Not a new full-scene installation audit.'};for(const mesh of publicMeshes){const p=mesh.geometry.attributes.position;for(let i=0;i<p.count;i++){const q=new T.Vector3().fromBufferAttribute(p,i).applyMatrix4(mesh.matrixWorld).applyMatrix4(inv);if(q.x<60||q.x>108||q.z<54||q.z>105)continue;const oldH=sourceHeightAt(q.x,q.z);if(oldH===null||Math.abs(q.y-oldH)>.15)continue;support.publicVertices++;if(q.x<patchBounds.minX||q.x>patchBounds.maxX||q.z<patchBounds.minZ||q.z>patchBounds.maxZ)continue;support.insidePatch++;const ray=new T.Ray(new T.Vector3(q.x,250,q.z).applyMatrix4(matrix),localDown),a=oldPI.sample(ray,0,700),b=newPI.sample(ray,0,700);if(!!a!==!!b){support.rayDifferences++;continue;}if(a&&b){const d=a.point.distanceTo(b.point);support.maxDifference=Math.max(support.maxDifference,d);if(d>1e-5)support.rayDifferences++;}}}
const evidence={loaded,support,afterTriangles,traceGeometryIdentical:same,builderSourceHash:provenance.builderSourceHash,recordedWallFaces:wallFaces.length,selectedFaces:selected.length,report:result.report,sourceTriangles:tris(patch.geometry,selected),candidate:result.geometry?.toJSON()??null,origin:patch.origin,provenance,supportAndRail:'No position or boundary changes. Local surface equivalence only; existing 2949/full loaded audit not rerun and not promoted to a new pass.'};
fs.writeFileSync(${JSON.stringify(path.join(out,'audit.json'))},JSON.stringify(evidence));console.log(JSON.stringify({traceGeometryIdentical:same,selected:selected.length,loaded,support,report:result.report}));
`;
const generated=path.join(project,'tools/pipeline/.east_wall_trace_generated.mjs');fs.writeFileSync(generated,pre+prefix+post);try{await import(pathToFileURL(generated));}finally{fs.unlinkSync(generated);}
