import * as T from 'three';import {readFileSync,writeFileSync}from'node:fs';import{buildMountainSurfaceIndex}from'../../src/world/citadel/mountainSurfaceIndex.js';
const folder=new URL('../../artifacts/pipeline/citadel-live-tram-clearance-20261006/',import.meta.url),data=JSON.parse(readFileSync(new URL('global-tram-samples.json',folder))),terrain=JSON.parse(readFileSync(new URL('actual-final-terrain.json',folder))),g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(terrain.positions,3));if(terrain.index)g.setIndex(terrain.index);const mesh=new T.Mesh(g,new T.MeshBasicMaterial({side:T.DoubleSide}));mesh.matrixAutoUpdate=false;mesh.matrixWorld.fromArray(terrain.matrixWorld);const index=buildMountainSurfaceIndex([mesh]),normal=new T.Matrix3().getNormalMatrix(mesh.matrixWorld),triangles=[];
for(let i=0;i<(g.index?.count??g.attributes.position.count);i+=3){const points=[0,1,2].map(j=>new T.Vector3().fromBufferAttribute(g.attributes.position,g.index?g.index.getX(i+j):i+j).applyMatrix4(mesh.matrixWorld));triangles.push({points,faceIndex:i/3,box:new T.Box3().setFromPoints(points)});}
const result={at:new Date().toISOString(),sourceAt:data.at,source:data.source,castleMatrix:data.castleMatrix,chart:{x:[-160,175],y:[-100,80],z:[-125,150]},method:'Actual final terrain triangles and actual global tram curves; rail-centre radial depth plus oriented union vehicle bounding envelope at each ~1m station. Envelope/triangle contact is conservative, not exact loaded train mesh collision.',lanes:{},limitations:[...data.limitations,'No continuous between-sample guarantee; union envelope can report empty space inside vehicle bounds.','Positive radial depth assumes the r17 mountain is a filled heightfield; only upward actual surface intersections are used.','Track, trains and terrain are read-only snapshots; no route or mountain edit.']};
function runs(rows,key){const out=[];let run=null;for(const r of rows){if(r[key]){if(!run||r.i!==run.lastIndex+1){run={firstIndex:r.i,lastIndex:r.i,uStart:r.u,uEnd:r.u,from:r.local,to:r.local,count:1};out.push(run);}else{run.lastIndex=r.i;run.uEnd=r.u;run.to=r.local;run.count++;}}else run=null;}return out;}
for(const[lane,l]of Object.entries(data.lanes)){
 const bodies=data.bodyBounds[lane],body=new T.Box3();for(const b of bodies){body.expandByPoint(new T.Vector3(...b.min));body.expandByPoint(new T.Vector3(...b.max));}const rows=[];
 for(const s of l.samples){const[x,y,z]=s.local;if(x< -160||x>175||y< -100||y>80||z< -125||z>150)continue;
  const p=new T.Vector3(...s.world),forward=new T.Vector3(...s.tangent).multiplyScalar(data.vehiclePlacement.directions[lane]),up=p.clone().normalize(),right=new T.Vector3().crossVectors(up,forward).normalize();up.crossVectors(forward,right).normalize();const mat=new T.Matrix4().makeBasis(right,up,forward).multiply(new T.Matrix4().makeRotationY(-Math.PI/2));mat.setPosition(p.clone().addScaledVector(up,.12));const inverse=mat.clone().invert(),box=body.clone().applyMatrix4(mat);let contact=null;for(const tri of triangles){if(!tri.box.intersectsBox(box))continue;const localTri=new T.Triangle(...tri.points.map(v=>v.clone().applyMatrix4(inverse)));if(body.intersectsTriangle(localTri)){contact={faceIndex:tri.faceIndex,worldTriangle:tri.points.map(v=>v.toArray())};break;}}
  const radial=p.clone().normalize(),hit=index.sample(new T.Ray(radial.clone().multiplyScalar(320),radial.clone().negate()),0,320,h=>h.face.normal.clone().applyMatrix3(normal).normalize().dot(radial)>.35);const depth=hit?hit.point.length()-p.length():null;
  rows.push({...s,terrainRadius:hit?.point.length()??null,terrainAboveRail:depth,railBuried:depth!==null&&depth>.15,bodyEnvelopeTerrainContact:!!contact,contact});
 }
 result.lanes[lane]={length:l.length,arcStep:l.arcStep,unionBody:{min:body.min.toArray(),max:body.max.toArray(),size:body.getSize(new T.Vector3()).toArray()},sampled:rows.length,railBuriedSamples:rows.filter(r=>r.railBuried).length,bodyEnvelopeContactSamples:rows.filter(r=>r.bodyEnvelopeTerrainContact).length,maxTerrainAboveRail:Math.max(...rows.map(r=>r.terrainAboveRail??-Infinity)),buriedRuns:runs(rows,'railBuried'),envelopeRuns:runs(rows,'bodyEnvelopeTerrainContact'),rows};
}
writeFileSync(new URL('global-tram-terrain-audit.json',folder),JSON.stringify(result,null,2));console.log(JSON.stringify(Object.fromEntries(Object.entries(result.lanes).map(([k,v])=>[k,{...v,rows:undefined}]))));g.dispose();mesh.material.dispose();
