import fs from'node:fs';import{createTargetCityDetailCandidate}from'../../src/world/citadel/targetCityDetailCandidate.js';import{createEastLoadedCliffCandidate}from'../../src/world/citadel/targetEastLoadedCliffCandidate.js';import * as T from'three';import{actualUserMarkedStructureFixture}from'../../tests/world/targetUserMarkedStructure.fixture.mjs';import{createCastleOceanSampler}from'../../src/world/citadel/newCityRidgeCandidate.js';import{createSphericalShoreArcCandidate,applySphericalShoreGradeProfile}from'../../src/world/citadel/targetSphericalShoreArcCandidate.js';
import{createTargetCliffOffsetCurve}from'../../src/world/citadel/targetCliffShoreRoute.js';import{buildMountainSurfaceIndex}from'../../src/world/citadel/mountainSurfaceIndex.js';
const f=actualUserMarkedStructureFixture(),matrix=f.castle.matrixWorld,inv=matrix.clone().invert(),r=168.6,shell=createCastleOceanSampler(matrix,r),source=f.sourceCurves.red,baseline=f.release.curves.red,startU=0.59,start=source.getPointAt(startU),startT=source.getTangentAt(startU);let endFraction=0,best=Infinity;for(let i=0;i<=1200;i++){const p=baseline.getPointAt(i/1200).applyMatrix4(inv),d=Math.hypot(p.x-52,p.z-104);if(d<best){best=d;endFraction=i/1200;}}const end=baseline.getPointAt(endFraction),endT=baseline.getTangentAt(endFraction),advance=(p,t,d)=>{const u=p.clone().normalize(),v=t.clone().addScaledVector(u,-t.dot(u)).normalize();return u.multiplyScalar(Math.cos(d/p.length())).addScaledVector(v,Math.sin(d/p.length())).multiplyScalar(p.length());},point=(x,z)=>new T.Vector3(x,shell(x,z),z).applyMatrix4(matrix);
const baselineGeometry=f.terrain.geometry.clone();
const detail=createTargetCityDetailCandidate({castle:f.castle,sceneRoot:f.scene,terrainMeshes:[f.terrain],oceanMesh:f.ocean,fitSunShadow:false,includeFrontRail:false,cliffTransitRelease:f.release});f.castle.add(detail.root);f.scene.updateMatrixWorld(true);
const publicMeshes=[];detail.root.traverse(o=>{if(!o.isMesh||o.isInstancedMesh)return;const names=[];for(let p=o;p&&p!==detail.root;p=p.parent)names.push(p.name);if(names.some(n=>/new-city|surveyed-route|plaza|approach/.test(n))&&!/window|leaf|turf|cloud|water|roof|dome/.test(o.name))publicMeshes.push(o);});
const firstPoints=[start,advance(start,startT,45),point(94,64),advance(end,endT,-27),end];
const red=createSphericalShoreArcCandidate({enabled:true,points:firstPoints.map(p=>p.toArray()),startTangent:startT.toArray(),endTangent:endT.toArray(),turnRadius:32}).curve;
const blueU=startU+.0025844302347414,blueSource=f.sourceCurves.blue;
const blue=applySphericalShoreGradeProfile(createTargetCliffOffsetCurve({base:red,offset:4.1,startWorld:blueSource.getPointAt(blueU).toArray(),endWorld:f.release.curves.blue.getPointAt(endFraction).toArray(),startTangent:blueSource.getTangentAt(blueU).toArray(),endTangent:f.release.curves.blue.getTangentAt(endFraction).toArray(),blendLength:30}).curve,{startTangent:blueSource.getTangentAt(blueU).toArray(),endTangent:f.release.curves.blue.getTangentAt(endFraction).toArray()});
const preSea=buildMountainSurfaceIndex([f.ocean]),localDown=new T.Vector3(0,-1,0).transformDirection(matrix),sampleSea=(x,z)=>{const hit=preSea.sample(new T.Ray(new T.Vector3(x,250,z).applyMatrix4(matrix),localDown),0,700);return hit?hit.point.clone().applyMatrix4(inv).y:null;};
const cut=createEastLoadedCliffCandidate({enabled:true,curves:[red,blue],castleMatrix:matrix,publicMeshes,sampleSea,bearingMargin:2.8});
const original= f.terrain.geometry.attributes.position.array.slice(),geom=f.terrain.geometry.clone(),position=geom.attributes.position;
for(let i=0;i<position.count;i++){const local=new T.Vector3().fromBufferAttribute(position,i).applyMatrix4(f.terrain.matrixWorld).applyMatrix4(inv),y=cut.height(local.x,local.z,local.y);if(y!==local.y){local.y=y;local.applyMatrix4(matrix).applyMatrix4(f.terrain.matrixWorld.clone().invert());position.setXYZ(i,local.x,local.y,local.z);}}
geom.computeVertexNormals();geom.computeBoundingBox();geom.computeBoundingSphere();f.terrain.geometry=geom;
const oldMesh=new T.Mesh(baselineGeometry);oldMesh.matrixAutoUpdate=false;oldMesh.matrix.copy(f.terrain.matrixWorld);oldMesh.updateMatrixWorld(true);const oldIndex=buildMountainSurfaceIndex([oldMesh]),newIndex=buildMountainSurfaceIndex([f.terrain]);
function topAt(index,x,z){const q=index.sample(new T.Ray(new T.Vector3(x,250,z).applyMatrix4(matrix),localDown),0,700);return q?q.point.clone().applyMatrix4(inv).y:null;}
const crossSections=[];for(const z of[64,70,80,90,98]){const row=[];for(let x=60;x<=110;x+=.5)row.push({x,z,before:topAt(oldIndex,x,z),after:topAt(newIndex,x,z),sea:sampleSea(x,z),protected:cut.protectedAt(x,z)});crossSections.push({z,row});}
const support={tested:0,lost:[],maxDrop:0};for(const mesh of publicMeshes){const pos=mesh.geometry.attributes.position;for(let i=0;i<pos.count;i++){const p=new T.Vector3().fromBufferAttribute(pos,i).applyMatrix4(mesh.matrixWorld).applyMatrix4(inv);if(p.x<60||p.x>108||p.z<54||p.z>105)continue;const a=topAt(oldIndex,p.x,p.z);if(a===null||Math.abs(p.y-a)>.15)continue;const b=topAt(newIndex,p.x,p.z);support.tested++;const drop=b===null?Infinity:a-b;support.maxDrop=Math.max(support.maxDrop,drop);if(drop>.02&&support.lost.length<100)support.lost.push({name:mesh.name,local:p.toArray(),before:a,after:b,drop});}}
const triGrid=new Map(),triangles=[],cell=16,keys=box=>{const list=[];for(let x=Math.floor(box.min.x/cell);x<=Math.floor(box.max.x/cell);x++)for(let y=Math.floor(box.min.y/cell);y<=Math.floor(box.max.y/cell);y++)for(let z=Math.floor(box.min.z/cell);z<=Math.floor(box.max.z/cell);z++)list.push(x+','+y+','+z);return list;};const gp=f.terrain.geometry.attributes.position,gi=f.terrain.geometry.index;for(let i=0;i<gi.count;i+=3){const points=[0,1,2].map(j=>new T.Vector3().fromBufferAttribute(gp,gi.getX(i+j)).applyMatrix4(f.terrain.matrixWorld)),box=new T.Box3().setFromPoints(points),id=triangles.length;triangles.push({points,box});for(const k of keys(box)){if(!triGrid.has(k))triGrid.set(k,[]);triGrid.get(k).push(id);}}const envelope=new T.Box3(new T.Vector3(-2.32,-.6,-3.49),new T.Vector3(2.32,5.71,3.49));
const seaIndex=buildMountainSurfaceIndex([f.ocean]);
function insideWorld(p){const ray=new T.Ray(p,new T.Vector3(1,0,0)),ids=new Set();for(let x=Math.floor(p.x/cell);x<=16;x++)for(const id of triGrid.get(x+','+Math.floor(p.y/cell)+','+Math.floor(p.z/cell))??[])ids.add(id);const distances=[];for(const id of ids){const q=ray.intersectTriangle(...triangles[id].points,false,new T.Vector3());if(q&&q.distanceTo(p)>1e-5)distances.push(q.distanceTo(p));}distances.sort((a,b)=>a-b);return distances.filter((x,i)=>i===0||x-distances[i-1]>1e-5).length%2===1;}
function loaded(curve){const out={poses:0,surfaceHits:[],inside:[],seaWet:0,seaSafetyMarginFailures:0,minStaticSeaClearance:Infinity,seaMissing:0,minRadius:Infinity,maxGrade:0};const n=Math.ceil(curve.getLength()/1.5),points=Array.from({length:n+1},(_,i)=>curve.getPointAt(i/n));for(let i=0;i<=n;i++){out.poses++;const w=points[i],t=curve.getTangentAt(i/n).normalize(),right=w.clone().normalize().cross(t).normalize(),up=t.clone().cross(right).normalize(),mat=new T.Matrix4().makeBasis(right,up,t).setPosition(w),inverse=mat.clone().invert(),box=envelope.clone().applyMatrix4(mat),ids=new Set(keys(box).flatMap(k=>triGrid.get(k)??[])),v=Math.abs(t.dot(w.clone().normalize()));out.maxGrade=Math.max(out.maxGrade,v/Math.sqrt(1-v*v));if(i&&i<n){const a=points[i-1],c=points[i+1],cross=w.clone().sub(a).cross(c.clone().sub(a)).length();if(cross>1e-9)out.minRadius=Math.min(out.minRadius,a.distanceTo(w)*w.distanceTo(c)*c.distanceTo(a)/(2*cross));}for(const id of ids){const tri=triangles[id];if(box.intersectsBox(tri.box)&&envelope.intersectsTriangle(new T.Triangle(...tri.points.map(p=>p.clone().applyMatrix4(inverse))))){out.surfaceHits.push({i,local:w.clone().applyMatrix4(inv).toArray()});break;}}
let wasInside=false;for(const dx of[-2.32,0,2.32])for(const dz of[-3.49,0,3.49])for(const h of[-.6,2.55,5.71]){const q=new T.Vector3(dx,h,dz).applyMatrix4(mat);if(insideWorld(q)){wasInside=true;if(out.inside.length<3000)out.inside.push({i,local:q.clone().applyMatrix4(inv).toArray()});}if(h===-.6){const hit=seaIndex.sample(new T.Ray(q.clone().normalize().multiplyScalar(250),q.clone().normalize().negate()),0,500);if(!hit)out.seaMissing++;else{const clearance=q.length()-hit.point.length();out.minStaticSeaClearance=Math.min(out.minStaticSeaClearance,clearance);if(clearance<0)out.seaWet++;if(clearance<.3)out.seaSafetyMarginFailures++;}}}}
return out;}
const terrainIndex=buildMountainSurfaceIndex([f.terrain]),down=new T.Vector3(0,-1,0).transformDirection(matrix);
function surface(index,x,z){const hit=index.sample(new T.Ray(new T.Vector3(x,250,z).applyMatrix4(matrix),down),0,700);return hit?hit.point.clone().applyMatrix4(inv).y:null;}
function gaps(curve){const rows=[],n=Math.ceil(curve.getLength()/2);for(let i=0;i<=n;i++){const p=curve.getPointAt(i/n),t=curve.getTangentAt(i/n),right=p.clone().normalize().cross(t).normalize(),up=t.clone().cross(right).normalize(),local=p.clone().applyMatrix4(inv);if(local.x<82||local.x>124||local.z<45||local.z>110)continue;const lr=right.clone().transformDirection(inv),side=Math.sign(lr.x*(62-local.x)+lr.z*(76-local.z)),edge=p.clone().addScaledVector(right,side*5.62).addScaledVector(up,6.72).applyMatrix4(inv);let found=null;for(let r=0;r<=36&&found===null;r+=1)for(let a=0;a<24;a++){const x=edge.x+r*Math.cos(a*Math.PI/12),z=edge.z+r*Math.sin(a*Math.PI/12),h=surface(terrainIndex,x,z),sea=surface(seaIndex,x,z);if(h!==null&&sea!==null&&h>sea+.3){found=r;break;}}rows.push({local:edge.toArray(),gap:found});}return{rows,mean:rows.reduce((s,r)=>s+(r.gap??36),0)/rows.length,max:Math.max(...rows.map(r=>r.gap??36))};}
const oceanScale=new T.Vector3();f.ocean.matrixWorld.decompose(new T.Vector3(),new T.Quaternion(),oceanScale);const waterEnvelope={shaderLocalMaximum:.067,worldMaximum:.067*Math.max(...oceanScale.toArray().map(Math.abs)),worldScale:oceanScale.toArray(),sampledBottom:'expanded vehicle OBB up=-0.6; not literal lowest physical vehicle vertex',engineeringReserve:.3,actualVehicleGeometryWaveCollisionVerified:false};
const baselineGap=gaps(f.release.curves.center);const results=[];for(const option of[{id:'shore-directed-32',radius:32,shoulder:[94,64],lead:45,tail:27}]){const pts=[start,advance(start,startT,option.lead),point(...option.shoulder),advance(end,endT,-option.tail),end];const c=createSphericalShoreArcCandidate({enabled:true,points:pts.map(p=>p.toArray()),startTangent:startT.toArray(),endTangent:endT.toArray(),turnRadius:option.radius});const joint={};if(c.curve&&c.report.issues.length===0){for(const lane of['red','blue']){let curve=c.curve;if(lane==='blue'){const sourceU=startU+.0025844302347414,bc=f.release.curves.blue;curve=createTargetCliffOffsetCurve({base:c.curve,offset:4.1,startWorld:f.sourceCurves.blue.getPointAt(sourceU).toArray(),endWorld:bc.getPointAt(endFraction).toArray(),startTangent:f.sourceCurves.blue.getTangentAt(sourceU).toArray(),endTangent:bc.getTangentAt(endFraction).toArray(),blendLength:30}).curve;curve=applySphericalShoreGradeProfile(curve,{startTangent:f.sourceCurves.blue.getTangentAt(sourceU).toArray(),endTangent:bc.getTangentAt(endFraction).toArray()});}joint[lane]=loaded(curve);}}results.push({option,...c.report,joint,approximateRedRoofGap:c.curve?gaps(c.curve):null,castlePoints:pts.map(p=>p.clone().applyMatrix4(inv).toArray()),samples:c.curve?Array.from({length:Math.ceil(c.curve.getLength())+1},(_,i)=>c.curve.getPointAt(i/Math.ceil(c.curve.getLength())).toArray()):null});console.log(option.id,JSON.stringify(c.report.issues),c.report.minRadius,c.report.maxGrade);}
const dir=new URL('../../artifacts/pipeline/citadel-east-shore-route-20261006/',import.meta.url);fs.writeFileSync(new URL('loaded-cliff-candidate-audit.json',dir),JSON.stringify({waterEnvelope,support,cutReport:cut.report,crossSections,baselineGap,sourceStartU:startU,retainedReleaseEndFraction:endFraction,results,accepted:false},null,2));detail.dispose();baselineGeometry.dispose();f.dispose();
