import {chromium} from '../../../tools/shot/node_modules/playwright/index.mjs';import {mkdir,writeFile} from 'node:fs/promises';
const out=new URL('../../artifacts/pipeline/citadel-old-city-slope/',import.meta.url);await mkdir(out,{recursive:true});const b=await chromium.launch({channel:'chrome',headless:true,args:['--use-angle=metal']});
try{const p=await b.newPage({viewport:{width:1440,height:1000}});await p.route('**/src/world/citadel/oldCityCoastalSlope.js*',r=>r.fulfill({contentType:'text/javascript',body:'export function applyOldCityCoastalSlope(){}'}));await p.goto('http://localhost:8931/TigerMessenger/?autostart=1',{timeout:180000});await p.waitForFunction(()=>window.__tm?.scene.getObjectByName('citadel-front-harbor'),null,{timeout:180000});
const report=await p.evaluate(async()=>{const t=window.__tm,T=t.THREE,c=t.scene.getObjectByName('castleContainer'),f=c.getObjectByName('highland-town-foundation-platform'),front=c.getObjectByName('citadel-front-harbor');c.updateWorldMatrix(true,true);
 const {createOceanHeightSampler}=await import('/TigerMessenger/src/world/citadel/oceanSurface.js');const sea=createOceanHeightSampler(f,160),ray=new T.Raycaster();ray.layers.enableAll();const down=new T.Vector3(0,-1,0).transformDirection(f.matrixWorld),meshes=[];c.traverse(o=>{if(!o.isMesh||o.userData.backlitHighlight||o.userData.isOutline||/water|shadow|outline|highlight/i.test(o.name))return;let visible=true;for(let q=o;q;q=q.parent)visible&&=q.visible;if(visible)meshes.push(o);});
 const edges=[],outline=f.userData.footprintOutline;
 for(let i=0;i<outline.length;i++){const a=outline[i],b=outline[(i+1)%outline.length],n=Math.ceil(Math.hypot(b[0]-a[0],b[1]-a[1])/3);for(let j=0;j<n;j++){const u=j/n,x=a[0]+(b[0]-a[0])*u,z=a[1]+(b[1]-a[1])*u;ray.set(f.localToWorld(new T.Vector3(x,-.15,z)),down);ray.far=100;const hits=ray.intersectObjects(meshes,false).filter(h=>h.object!==f&&h.object.parent!==f);edges.push({x,z,sea:sea(x,z),support:hits[0]?{name:hits[0].object.name,local:f.worldToLocal(hits[0].point.clone()).toArray()}:null});}}
 t.cameraRig.update=()=>{};t.P.daySpeed=0;t.P.timeOfDay=.85;t.camera.position.copy(front.localToWorld(new T.Vector3(65,16,124)));t.camera.up.set(0,1,0).transformDirection(front.matrixWorld);t.camera.lookAt(front.localToWorld(new T.Vector3(35,1,91)));t.camera.fov=48;t.camera.updateProjectionMatrix();await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));t.renderer.render(t.scene,t.camera);
 const picks=[];for(const [x,y]of [[.5,.36],[.42,.45],[.57,.4],[.37,.37],[.67,.41],[.2,.27]]){ray.setFromCamera(new T.Vector2(x*2-1,1-y*2),t.camera);ray.far=500;const hit=ray.intersectObjects(meshes,false)[0];picks.push({screen:[x,y],hit:hit?.object.name,point:hit?f.worldToLocal(hit.point.clone()).toArray():null});}
 const image=t.renderer.domElement.toDataURL('image/png');
 const route=c.userData.oldShoreApproach.route.map(v=>f.worldToLocal(c.localToWorld(new T.Vector3(...v))).toArray());
 const seal=c.getObjectByName('citadel-coastal-cliff-seal'),g=seal.geometry.index?seal.geometry.toNonIndexed():seal.geometry;
 let digest=2166136261;for(const v of g.attributes.position.array)digest=Math.imul(digest^Math.round(v*1e4),16777619)>>>0;
 const main=c.getObjectByName('citadel-oskar-grid-mountain-surface'),mg=main.geometry.index?main.geometry.toNonIndexed():main.geometry;let mh=2166136261;for(const v of mg.attributes.position.array)mh=Math.imul(mh^Math.round(v*1e4),16777619)>>>0;
 return {outline,foundationMatrix:f.matrixWorld.toArray(),castleMatrix:c.matrixWorld.toArray(),edges,picks,route,image,seal:{positions:Array.from(g.attributes.position.array),colors:g.attributes.color?Array.from(g.attributes.color.array):null,colorSize:g.attributes.color?.itemSize??3,toFoundation:f.matrixWorld.clone().invert().multiply(seal.matrixWorld).toArray(),digest},main:{positions:Array.from(mg.attributes.position.array),colors:Array.from(mg.attributes.color.array),colorSize:mg.attributes.color.itemSize,toFoundation:f.matrixWorld.clone().invert().multiply(main.matrixWorld).toArray(),digest:mh}};});
await writeFile(new URL('before.png',out),Buffer.from(report.image.split(',')[1],'base64'));delete report.image;await writeFile(new URL('source.json',out),JSON.stringify(report,null,2));console.log(JSON.stringify({picks:report.picks,edges:report.edges.length,outline:report.outline}));
}finally{await b.close();}
