import {chromium} from '../../../tools/shot/node_modules/playwright/index.mjs';import {writeFile} from 'node:fs/promises';
const out=new URL('../../artifacts/pipeline/citadel-compact-ascent/',import.meta.url);const b=await chromium.launch({channel:'chrome',headless:true,args:['--use-angle=metal']});
try{const p=await b.newPage();await p.route('**/compactFoundationsR02.js*',r=>r.fulfill({contentType:'text/javascript',body:'export default {parts:[]};'}));await p.goto('http://localhost:8931/TigerMessenger/?autostart=1&citadelCompact=1',{timeout:180000});await p.waitForFunction(()=>window.__tm?.scene.getObjectByName('citadel-plaza-retaining-wall'),null,{timeout:180000});
const data=await p.evaluate(()=>{const t=window.__tm,T=t.THREE,c=t.scene.getObjectByName('highland-west-city'),terrain=t.scene.getObjectByName('citadel-oskar-grid-mountain-surface');c.updateWorldMatrix(true,true);const ray=new T.Raycaster();ray.layers.enableAll();ray.far=200;const up=new T.Vector3(0,1,0).transformDirection(c.matrixWorld);const parts=[];
c.traverseVisible(m=>{if(!m.isMesh||!(m.name.startsWith('west-city-crown-retaining-wall')||m.name==='middle-terrace-solid'))return;const geo=m.geometry.index?m.geometry.toNonIndexed():m.geometry;const positions=Array.from(geo.attributes.position.array),matrix=new T.Matrix4().multiplyMatrices(c.matrixWorld.clone().invert(),m.matrixWorld),back=matrix.clone().invert(),bottom=m.name==='middle-terrace-solid'?5.9:11.9,changes=[],samples=[];
for(let i=0;i<positions.length;i+=3){const v=new T.Vector3().fromArray(positions,i).applyMatrix4(matrix);if(Math.abs(v.y-bottom)>.036)continue;ray.set(c.localToWorld(new T.Vector3(v.x,100,v.z)),up.clone().negate());const hit=ray.intersectObjects([terrain,t.scene.getObjectByName('citadel-coastal-cliff-seal')].filter(Boolean),false)[0];if(!hit){samples.push({point:v.toArray(),missing:true});continue;}const y=c.worldToLocal(hit.point.clone()).y;const gap=v.y-y;samples.push({point:v.toArray(),rockY:y,gap});if(gap>.04){v.y-=gap+.12;v.applyMatrix4(back);changes.push([i/3,...v.toArray()]);}}
let digest=2166136261;for(const v of positions)digest=Math.imul(digest^Math.round(v*1e4),16777619)>>>0;
parts.push({name:m.name,positions,changes,samples,matrix:matrix.toArray(),sourceDigest:digest,color:m.material.color.toArray()});});return {parts};});await writeFile(new URL('foundation-source.json',out),JSON.stringify(data));console.log(JSON.stringify(data.parts.map(p=>({name:p.name,vertices:p.positions.length/3,changes:p.changes.length,maxGap:Math.max(...p.samples.map(s=>s.gap||0)),missing:p.samples.filter(s=>s.missing).length}))));
}finally{await b.close();}
