import {chromium} from '../../../tools/shot/node_modules/playwright/index.mjs';import {mkdir,writeFile} from 'node:fs/promises';
const out=new URL('../../artifacts/pipeline/citadel-old-harbor-grade/',import.meta.url);await mkdir(out,{recursive:true});
const browser=await chromium.launch({channel:'chrome',headless:true,args:['--use-angle=metal']});
try{const page=await browser.newPage({viewport:{width:1440,height:900}});await page.goto('http://localhost:8931/TigerMessenger/?autostart=1&citadelCommonFrame=1',{timeout:180000});await page.waitForFunction(()=>window.__tm?.messenger,null,{timeout:180000});
const result=await page.evaluate(async()=>{const t=window.__tm,T=t.THREE,c=t.scene.getObjectByName('castleContainer'),h=t.scene.getObjectByName('old-harbor-scene'),{officialOceanLevelAt}=await import('/TigerMessenger/src/world/waterV8/officialOcean.js');t.P.daySpeed=0;t.P.timeOfDay=.85;t.cameraRig.update=()=>{};await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));t.scene.updateMatrixWorld(true);
const original={position:h.position.toArray(),quaternion:h.quaternion.toArray()},children=h.children.filter(o=>o.isGroup).map(o=>({name:o.name,position:o.position.toArray(),keys:Object.keys(o.userData)}));
const altitude=p=>p.length()-160-officialOceanLevelAt(p);const deck=h.getObjectByName('pier-deck');const pts=[[-3.6,.51,-2.1],[-3.6,.51,2.1],[3.6,.51,-2.1],[3.6,.51,2.1]];
const baseline=pts.map(p=>altitude(h.localToWorld(new T.Vector3(...p))));const terrain=c.getObjectByName('citadel-oskar-grid-mountain-surface'),ray=new T.Raycaster();ray.layers.enableAll();const up=new T.Vector3(0,1,0).transformDirection(c.matrixWorld);const terrainMeshes=[terrain,c.getObjectByName('highland-ravine-wall-west'),c.getObjectByName('citadel-coastal-cliff-seal')].filter(Boolean);const candidates=[];const sourceX=new T.Vector3(0,0,-1).transformDirection(h.matrixWorld);const parentInverse=h.parent.getWorldQuaternion(new T.Quaternion()).invert();const pose=(x,y,z)=>{h.position.copy(c.localToWorld(new T.Vector3(x,y,z)));const up=h.position.clone().normalize(),side=sourceX.clone().addScaledVector(up,-sourceX.dot(up)).normalize(),forward=new T.Vector3().crossVectors(side,up).normalize();h.quaternion.copy(parentInverse).multiply(new T.Quaternion().setFromRotationMatrix(new T.Matrix4().makeBasis(side,up,forward)));h.updateMatrixWorld(true);};
for(const [x,z] of [[-72,52],[-66,52],[-60,52],[-72,60],[-66,60],[-60,60],[-72,68],[-66,68],[-60,68]]){let low=-100,high=50;for(let i=0;i<44;i++){const y=(low+high)/2;pose(x,y,z);const min=Math.min(...pts.map(p=>altitude(h.localToWorld(new T.Vector3(...p)))));if(min>.7)high=y;else low=y;}
const y=(low+high)/2;pose(x,y,z);const terrainAtDeck=[...pts,[3,-.1,-4],[3,-.1,2],[16,-.1,-4],[16,-.1,2]].map(p=>{const v=h.localToWorld(new T.Vector3(...p));ray.set(v.clone().addScaledVector(up,80),up.clone().negate());ray.far=150;const hit=ray.intersectObjects(terrainMeshes,false)[0];return hit?{name:hit.object.name,relativeHeight:hit.point.clone().sub(v).dot(up),point:c.worldToLocal(hit.point.clone()).toArray()}:null;});candidates.push({frame:'harbor-local-ocean-tangent',matrix:h.matrixWorld.toArray(),castleLocal:[x,y,z],deckClearances:pts.map(p=>altitude(h.localToWorld(new T.Vector3(...p)))),terrainAtDeck});}
h.position.fromArray(original.position);h.quaternion.fromArray(original.quaternion);h.updateMatrixWorld(true);
return {baseline,original,children,candidates,scope:'Read-only berth placement measurements; actual harbor restored, no actor/story movement committed'};});await writeFile(new URL('seaward-clearance.json',out),JSON.stringify(result,null,2));console.log(JSON.stringify(result));}finally{await browser.close();}
