import * as T from 'three';import fs from 'node:fs';
import {orientedRayCrossings} from './oriented_ray_crossings.mjs';
import {actualCliffTransitFixture} from '../../tests/world/targetCliffTransitStructure.fixture.mjs';
import {createTargetUserMarkedProductionRelease} from '../../src/world/citadel/targetUserMarkedProductionRelease.js';
import {createTargetEastCliffProductionRelease} from '../../src/world/citadel/targetEastCliffProductionRelease.js';
import {createTargetEastGlobalCrossingCandidate} from '../../src/world/citadel/targetEastGlobalCrossingCandidate.js';
import {buildHills,carveHillsForTrack} from '../../src/world/hills.js';
const ROOT=new URL('../../',import.meta.url),read=n=>JSON.parse(fs.readFileSync(new URL('artifacts/pipeline/citadel-east-shore-route-20261006/'+n,ROOT))),artifact=read('remesh-final-surface-geometry.json'),f=actualCliffTransitFixture(),base=createTargetEastCliffProductionRelease({enabled:true,sourceCurves:f.sourceCurves,retainedRelease:createTargetUserMarkedProductionRelease({sourceCurves:f.sourceCurves}),candidateInput:read('remesh-expanded-shift-audit.json').candidateInput,terrainArtifact:artifact,cityGalleryScope:true}),c=createTargetEastGlobalCrossingCandidate({enabled:true,release:base.release,sourceCurves:f.sourceCurves,lateral:0,sourceExtensionMetres:50,startMetres:10,endMetres:300,frontLoadedGrade:.0395,independentRadialProfiles:true,tailGrade:-.004}),g=new T.BufferGeometryLoader().parse(artifact.geometry),m=new T.MeshBasicMaterial(),terrain=new T.Mesh(g,m),hills=buildHills(f.scene,160);terrain.name='final-remesh';terrain.position.fromArray(artifact.origin);f.castle.add(terrain);carveHillsForTrack(hills.mesh,Object.values(c.startup.curves),160);f.scene.updateMatrixWorld(true);
const grid=new Map(),tris=[],cell=12,bounds=new T.Box3(),keys=box=>{const out=[];for(let x=Math.floor(box.min.x/cell);x<=Math.floor(box.max.x/cell);x++)for(let y=Math.floor(box.min.y/cell);y<=Math.floor(box.max.y/cell);y++)for(let z=Math.floor(box.min.z/cell);z<=Math.floor(box.max.z/cell);z++)out.push(x+','+y+','+z);return out;};
for(const mesh of[terrain,f.scene.getObjectByName('planet-surface'),hills.mesh,hills.skirt]){if(!mesh)continue;const p=mesh.geometry.attributes.position,ix=mesh.geometry.index;for(let i=0;i<(ix?.count??p.count);i+=3){const points=[0,1,2].map(j=>new T.Vector3().fromBufferAttribute(p,ix?ix.getX(i+j):i+j).applyMatrix4(mesh.matrixWorld)),box=new T.Box3().setFromPoints(points),normal=points[1].clone().sub(points[0]).cross(points[2].clone().sub(points[0])).normalize(),id=tris.length;tris.push({points,box,normal,name:mesh.name,closed:mesh===terrain||mesh.name==='planet-surface'});bounds.union(box);for(const k of keys(box)){if(!grid.has(k))grid.set(k,[]);grid.get(k).push(id);}}}
function inside(p){const ray=new T.Ray(p,new T.Vector3(1,0,0)),ids=new Set();for(let x=Math.floor(p.x/cell);x<=Math.ceil(bounds.max.x/cell);x++)for(const id of grid.get(x+','+Math.floor(p.y/cell)+','+Math.floor(p.z/cell))??[])if(tris[id].closed)ids.add(id);const groups=new Map();for(const id of ids){const t=tris[id],q=ray.intersectTriangle(...t.points,false,new T.Vector3());if(!q||q.distanceTo(p)<=1e-5)continue;if(!groups.has(t.name))groups.set(t.name,[]);groups.get(t.name).push({distance:q.distanceTo(p),normalDot:t.normal.x});}for(const[name,hits]of groups)if(orientedRayCrossings(hits).inside)return name;return null;}
try{const inverse=f.castle.matrixWorld.clone().invert(),body=new T.Box3(new T.Vector3(-2.35,-.136,-3.59),new T.Vector3(2.35,5.71,3.59)),results=[];for(const lane of['red','blue']){const curve=c.curves[lane],n=Math.ceil(curve.getLength()/.5),surfaceHits=[],insideHits=[];let tests=0,insideProbes=0;for(let i=0;i<=n;i++){const u=i/n,p=curve.getPointAt(u),t=curve.getTangentAt(u).normalize(),right=p.clone().normalize().cross(t).normalize(),up=t.clone().cross(right).normalize(),pose=new T.Matrix4().makeBasis(right,up,t).setPosition(p),inv=pose.clone().invert(),bb=body.clone().applyMatrix4(pose),ids=new Set(keys(bb).flatMap(k=>grid.get(k)??[]));for(const id of ids){const q=tris[id];if(!bb.intersectsBox(q.box))continue;tests++;if(body.intersectsTriangle(new T.Triangle(...q.points.map(v=>v.clone().applyMatrix4(inv))))){surfaceHits.push({i,u,mesh:q.name,world:p.toArray(),local:p.clone().applyMatrix4(inverse).toArray()});break;}}
 for(const x of[-2.35,0,2.35])for(const y of[-.136,2.7,5.71])for(const z of[-3.59,0,3.59]){insideProbes++;const q=new T.Vector3(x,y,z).applyMatrix4(pose),name=inside(q);if(name)insideHits.push({i,u,mesh:name,local:q.clone().applyMatrix4(inverse).toArray()});}}
 results.push({lane,poses:n+1,step:curve.getLength()/n,triangleTests:tests,insideProbes,surfaceHits,insideHits});console.log(lane,JSON.stringify({...results.at(-1),surfaceHits:surfaceHits.length,insideHits:insideHits.length}));}
 const out={version:'global-crossing-final-terrain-audit-1',accepted:false,installed:false,artifactSourceHash:artifact.sourceHash,artifactOrigin:artifact.origin,sourceFrameUnmodified:true,scope:'NEW full replacement red/blue, not inherited old route acceptance. Exact final remesh plus real planet/hills generated and carved by NEW final global curves. Oriented parity separately per closed remesh/planet; hills only surface triangles.',body:body.toArray?.()??{min:body.min.toArray(),max:body.max.toArray()},results,limitations:['Finite .5m poses and 27 body probes, not continuous collision.','Final remesh source hash is artifact provenance, not a new live epoch check.','Retained global actors, roads and bridge structures not included.']};fs.writeFileSync(new URL('artifacts/pipeline/citadel-global-approach-support-20261006/crossing-50-final-terrain.json',ROOT),JSON.stringify(out,null,2));
}finally{g.dispose();m.dispose();for(const mesh of[hills.mesh,hills.skirt]){mesh.geometry.dispose();mesh.material.dispose();}f.dispose();}
