import fs from 'node:fs';
import * as T from 'three';
import {actualUserMarkedStructureFixture} from '../../tests/world/targetUserMarkedStructure.fixture.mjs';
import {createTargetCityDetailCandidate} from '../../src/world/citadel/targetCityDetailCandidate.js';
import {buildMountainSurfaceIndex} from '../../src/world/citadel/mountainSurfaceIndex.js';
const dir=new URL('../../artifacts/pipeline/citadel-east-shore-route-20261006/',import.meta.url);
const prior=JSON.parse(fs.readFileSync(new URL('spherical-audit-0.59.json',dir))),route=prior.results.find(x=>x.option.id==='shore-directed-32');
const f=actualUserMarkedStructureFixture(),m=f.castle.matrixWorld,inv=m.clone().invert(),down=new T.Vector3(0,-1,0).transformDirection(m);
const c=createTargetCityDetailCandidate({castle:f.castle,sceneRoot:f.scene,terrainMeshes:[f.terrain],oceanMesh:f.ocean,fitSunShadow:false,includeFrontRail:false,cliffTransitRelease:f.release});f.castle.add(c.root);f.scene.updateMatrixWorld(true);
const physical=[],inventory=[];c.root.traverse(o=>{if(!o.isMesh||o.isInstancedMesh)return;const ancestry=[];for(let p=o;p&&p!==c.root;p=p.parent)ancestry.push(p.name);if(!ancestry.some(n=>/new-city|surveyed-route|plaza|approach/.test(n)))return;if(/window|leaf|turf|cloud|water|roof|dome/.test(o.name))return;physical.push(o);inventory.push({name:o.name,ancestry,positionCount:o.geometry.attributes.position.count});});
const city=buildMountainSurfaceIndex(physical),terrain=buildMountainSurfaceIndex([f.terrain]);
function hit(index,x,z){const q=index.sample(new T.Ray(new T.Vector3(x,220,z).applyMatrix4(m),down),0,700);return q?{height:q.point.clone().applyMatrix4(inv).y,world:q.point.toArray(),name:q.object?.name??q.mesh?.name,faceIndex:q.faceIndex}:null;}
const rows=[];for(const lane of ['red','blue'])for(const row of route.joint[lane].inside){const [x,y,z]=row.local,p=new T.Vector3(x,y,z).applyMatrix4(m),rock=hit(terrain,x,z),structure=hit(city,x,z);rows.push({lane,pose:row.i,local:row.local,world:p.toArray(),rock,structure,rockAboveProbe:rock?rock.height-y:null,structureAboveProbe:structure?structure.height-y:null});}
const under=rows.filter(r=>r.structure),names={};for(const r of under)names[r.structure.name]=(names[r.structure.name]??0)+1;
const samples=route.samples.map(p=>new T.Vector3().fromArray(p));const sections=[];
for(let i=1;i<samples.length-1;i+=4){const p=samples[i],local=p.clone().applyMatrix4(inv);if(local.x<60||local.x>110||local.z<50||local.z>104)continue;const tangent=samples[i+1].clone().sub(samples[i-1]).normalize(),right=p.clone().normalize().cross(tangent).normalize(),up=tangent.clone().cross(right).normalize();const landSign=Math.sign(right.clone().transformDirection(inv).dot(new T.Vector3(62-local.x,0,76-local.z)));
const profile=[];for(let offset=-6;offset<=18;offset+=2){const q=p.clone().addScaledVector(right,landSign*offset),l=q.clone().applyMatrix4(inv),r=hit(terrain,l.x,l.z),b=hit(city,l.x,l.z);profile.push({offset,local:l.toArray(),rock:r?.height??null,public:b??null,rockRadialAboveRail:r?new T.Vector3().fromArray(r.world).sub(p).dot(up):null});}sections.push({i,railLocal:local.toArray(),railWorld:p.toArray(),landSign,profile});}
const cityTriangles=[];for(const mesh of physical){const g=mesh.geometry,p=g.attributes.position,idx=g.index;for(let i=0;i<(idx?.count??p.count);i+=3){const points=[0,1,2].map(j=>new T.Vector3().fromBufferAttribute(p,idx?idx.getX(i+j):i+j).applyMatrix4(mesh.matrixWorld));cityTriangles.push({name:mesh.name,points,box:new T.Box3().setFromPoints(points)});}}
const envelope=new T.Box3(new T.Vector3(-2.32,-.6,-3.49),new T.Vector3(2.32,5.71,3.49)),cityCollisions=[],raiseBounds=[];
for(let i=1;i<samples.length-1;i++){const p=samples[i],l=p.clone().applyMatrix4(inv);if(l.x<60||l.x>110||l.z<50||l.z>104)continue;const t=samples[i+1].clone().sub(samples[i-1]).normalize(),right=p.clone().normalize().cross(t).normalize(),up=t.clone().cross(right).normalize(),basis=new T.Matrix4().makeBasis(right,up,t).setPosition(p),bi=basis.clone().invert(),box=envelope.clone().applyMatrix4(basis);for(const tri of cityTriangles){if(box.intersectsBox(tri.box)&&envelope.intersectsTriangle(new T.Triangle(...tri.points.map(q=>q.clone().applyMatrix4(bi))))){cityCollisions.push({sample:i,local:l.toArray(),mesh:tri.name});break;}}
let required=0;for(const dx of[-2.32,0,2.32])for(const dz of[-3.49,0,3.49]){const q=p.clone().addScaledVector(right,dx).addScaledVector(t,dz),hit=terrain.sample(new T.Ray(q.clone().addScaledVector(up,150),up.clone().negate()),0,300);if(hit)required=Math.max(required,hit.point.clone().sub(q).dot(up)+.6);}raiseBounds.push({sample:i,local:l.toArray(),raiseToTopSurface:required,minimumRampLengthAt4pct:required/.04});}
const report={cityTriangleCount:cityTriangles.length,redCityOBBHits:cityCollisions,redRaiseBounds:raiseBounds,method:'Read-only CPU actual production terrain fixture + current city factory; triangle first hits along castle -Y. Not GPU, not ray-exact support integrity or complete actor volume audit.',accepted:false,installed:false,route:'shore-directed-32 source .59',inventory,summary:{insidePoints:rows.length,underActualCityTriangles:under.length,names,minStructureVerticalSeparation:under.length?Math.min(...under.map(r=>r.structureAboveProbe)):null,maxStructureVerticalSeparation:under.length?Math.max(...under.map(r=>r.structureAboveProbe)):null},rows,sections,limitations:['Instanced decoration excluded; original live actors not instantiated by fixture','First hit is upper city surface, not foundation underside; cannot establish load-bearing stability','Read-only samples do not certify proposed cuts or changed alignment']};fs.writeFileSync(new URL('east-cliff-boundary-audit.json',dir),JSON.stringify(report,null,2));console.log(JSON.stringify(report.summary));c.dispose();f.dispose();
