import fs from 'node:fs';import * as T from 'three';
import {actualUserMarkedStructureFixture} from '../../tests/world/targetUserMarkedStructure.fixture.mjs';
import {buildMountainSurfaceIndex} from '../../src/world/citadel/mountainSurfaceIndex.js';
import {TARGET_CITY_PLATFORMS} from '../../src/world/citadel/targetTerrainCandidate.js';
import {createTargetEastShoreRouteCandidate,EAST_SHORE_ROUTE_TRIALS} from '../../src/world/citadel/targetEastShoreRouteCandidate.js';
const f=actualUserMarkedStructureFixture(),m=f.castle.matrixWorld,inv=m.clone().invert(),down=new T.Vector3(0,-1,0).transformDirection(m),ti=buildMountainSurfaceIndex([f.terrain]),si=buildMountainSurfaceIndex([f.ocean]);const sampler=index=>(x,z)=>{const hit=index.sample(new T.Ray(new T.Vector3(x,250,z).applyMatrix4(m),down),0,700);return hit?hit.point.clone().applyMatrix4(inv).y:null;},terrain=sampler(ti),sea=sampler(si);
const triGrid=new Map(),triangles=[],cell=16,keys=box=>{const list=[];for(let x=Math.floor(box.min.x/cell);x<=Math.floor(box.max.x/cell);x++)for(let y=Math.floor(box.min.y/cell);y<=Math.floor(box.max.y/cell);y++)for(let z=Math.floor(box.min.z/cell);z<=Math.floor(box.max.z/cell);z++)list.push(x+','+y+','+z);return list;};const gp=f.terrain.geometry.attributes.position,gi=f.terrain.geometry.index;for(let i=0;i<gi.count;i+=3){const points=[0,1,2].map(j=>new T.Vector3().fromBufferAttribute(gp,gi.getX(i+j)).applyMatrix4(f.terrain.matrixWorld)),box=new T.Box3().setFromPoints(points),id=triangles.length;triangles.push({points,box});for(const k of keys(box)){if(!triGrid.has(k))triGrid.set(k,[]);triGrid.get(k).push(id);}}const envelope=new T.Box3(new T.Vector3(-2.32,-.6,-3.49),new T.Vector3(2.32,5.71,3.49));
const results=[];for(const trial of EAST_SHORE_ROUTE_TRIALS.filter(t=>!process.env.EAST_SCAN_ONLY||t.id.startsWith('scanned-'))){const p=createTargetEastShoreRouteCandidate({enabled:true,trial,sourceCurves:f.sourceCurves,sampleTerrain:terrain,sampleSea:sea,platforms:TARGET_CITY_PLATFORMS});const r=p.report,rows=[];const c=p.curves.center,n=Math.ceil(c.getLength()/2);for(let i=0;i<=n;i++){const world=c.getPointAt(i/n),local=world.clone().applyMatrix4(inv);if(local.x<80||local.x>125||local.z<45||local.z>110)continue;let dry=null;for(let radius=0;radius<=36&&!dry;radius+=1)for(let a=0;a<24;a++){const x=local.x+radius*Math.cos(a*Math.PI/12),z=local.z+radius*Math.sin(a*Math.PI/12),h=terrain(x,z),s=sea(x,z);if(h!==null&&s!==null&&h>s+.3){dry={radius,local:[x,h,z]};break;}}rows.push({local:local.toArray(),world:world.toArray(),nearestDry:dry});}
const result={id:trial.id,trial,intervals:Object.fromEntries(Object.entries(p.specs).map(([k,s])=>[k,[s.startU,s.endU]])),extraSourceLength:trial.startU===null?0:(f.release.specs.red.startU-trial.startU)*f.sourceCurves.red.getLength(),laneAudit:r.laneAudit,report:r.rail,rows,meanCentreDryDistance:rows.reduce((s,x)=>s+(x.nearestDry?.radius??36),0)/rows.length,shapePass:Object.values(r.laneAudit).every(a=>a.pass)};result.endpointGrades=Object.fromEntries(Object.entries(p.specs).map(([lane,spec])=>{const q=f.sourceCurves[lane].getPointAt(spec.startU),t=f.sourceCurves[lane].getTangentAt(spec.startU),v=Math.abs(t.dot(q.normalize()));return[lane,v/Math.sqrt(1-v*v)];}));
if(['long-entry-640-wide','same-start-shoulder-8'].includes(trial.id)){const body={poses:0,hits:[]};for(const lane of['red','blue']){const curve=p.curves[lane],n=Math.ceil(curve.getLength());for(let i=0;i<=n;i++){body.poses++;const w=curve.getPointAt(i/n),t=curve.getTangentAt(i/n).normalize(),right=w.clone().normalize().cross(t).normalize(),up=t.clone().cross(right).normalize(),mat=new T.Matrix4().makeBasis(right,up,t).setPosition(w),inverse=mat.clone().invert(),box=envelope.clone().applyMatrix4(mat),ids=new Set(keys(box).flatMap(k=>triGrid.get(k)??[]));for(const id of ids){const tri=triangles[id];if(box.intersectsBox(tri.box)&&envelope.intersectsTriangle(new T.Triangle(...tri.points.map(p=>p.clone().applyMatrix4(inverse))))){body.hits.push({lane,i,local:w.clone().applyMatrix4(inv).toArray()});break;}}}}result.fullLoadedTerrain=body;}
results.push(result);console.log(trial.id,result.shapePass,result.meanCentreDryDistance,Math.min(...Object.values(r.laneAudit).map(a=>a.minRadius)),r.rail.cuts.length);}
const dir=new URL('../../artifacts/pipeline/citadel-east-shore-route-20261006/',import.meta.url);fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(new URL(process.env.EAST_SCAN_ONLY?'scanned-candidates.json':'audit.json',dir),JSON.stringify({accepted:false,installed:false,fixture:'actualUserMarkedStructureFixture final production cut terrain + actual compiled ocean',results},null,2));f.dispose();
