// Bake the holy-city terrain heightfield used by the ridge-flow cloud system.
// Grid in castle-local x/z (castleContainer frame), radial rays against the real
// scene. Each cell: altitude above sea (0.1 m) and class 0 sea/low, 1 mountain, 2 built.
import {chromium} from '../../../tools/shot/node_modules/playwright/index.mjs';
import {writeFile} from 'node:fs/promises';
const HALF = 150, STEP = 3;
const b = await chromium.launch({channel: 'chrome', headless: true, args: ['--use-angle=metal']});
try {
  const p = await b.newPage();
  await p.goto('http://localhost:8931/TigerMessenger/?autostart=1', {waitUntil: 'domcontentloaded'});
  await p.waitForFunction(() => window.__tm?.scene.getObjectByName('highland-west-city'), null, {timeout: 240000});
  await p.waitForTimeout(2500);
  const data = await p.evaluate(([HALF, STEP]) => {
    const t = window.__tm, T = t.THREE, R = 160;
    const castle = t.scene.getObjectByName('castleContainer');
    // Restore authored visibility so the current camera does not omit distant solids.
    t.distanceCulling?.dispose();
    t.scene.updateMatrixWorld(true);
    const skip = /cloud|^sky|bird|ocean|water|sea-|tram|culvert|lamp|flag|banner|tree|cypress|pine|canopy|leaf|shrub|flower|planting|grass|soldier|trooper|boat|ship|warship|horse|statue|crate|volume|glow|light|mist|plinth/i;
    const mountain = /mountain|backdrop|ridge|range|cliff|massif|ravine|rock|crag|peak|slope|terrain|hills|outcrop|spur|skirt|gorge|highland-(?!town)|snow/i;
    const builtRe = /west-city|town|city|house|harbor|harbour|plaza|stair|bridge|wall|tower|gate|keep|arcade|quay|dock|pier|navona|station|court|building|dome|roof|palace|church|cathedral|temple|colonnade|promenade|parapet|moat|shore-arcade|elder|library|shop/i;
    const solids = [];
    t.scene.traverse(o => {
      if (!o.isMesh || !o.visible || o.userData.isOutline) return;
      let a = o; while (a) { if (!a.visible || skip.test(a.name)) return; a = a.parent; }
      const ms = Array.isArray(o.material) ? o.material : [o.material];
      if (ms.every(m => !m || m.visible === false || (m.transparent && m.opacity < .2))) return;
      solids.push(o);
    });
    const ray = new T.Raycaster(), n = Math.round(HALF * 2 / STEP) + 1, alt = [], cls = [];
    for (let iz = 0; iz < n; iz++) for (let ix = 0; ix < n; ix++) {
      const x = -HALF + ix * STEP, z = -HALF + iz * STEP;
      const up = castle.localToWorld(new T.Vector3(x, 0, z)).normalize();
      ray.set(up.clone().multiplyScalar(R + 140), up.clone().negate()); ray.far = 180;
      const h = ray.intersectObjects(solids, false)[0];
      const a = h ? h.point.length() - R : 0;
      alt.push(Math.round(Math.max(-2, a) * 10) / 10);
      let c = 0;
      if (h && a > 0.8) { let o = h.object, built = false; while (o && o !== castle) { if (builtRe.test(o.name)) { built = true; break; } o = o.parent; } const own = h.object.name + ' ' + (h.object.parent?.name || ''); c = built ? 2 : (mountain.test(own) ? 1 : 2); }
      cls.push(c);
    }
    return {frame: 'castleContainer', half: HALF, step: STEP, n, radius: R, alt, cls, solids: solids.length};
  }, [HALF, STEP]);
  const js = `// Generated by tools/pipeline/bake_citadel_ridge_heightfield.mjs (${new Date().toISOString().slice(0, 10)}).\n// Castle-local grid, radial altitude above sea (m); cls 0 sea/low, 1 mountain, 2 built.\nexport default ${JSON.stringify({frame: data.frame, half: data.half, step: data.step, n: data.n, radius: data.radius, alt: data.alt, cls: data.cls})};\n`;
  await writeFile('TigerMessenger/src/assets/citadelRidgeHeightfield.js', js);
  const counts = [0, 0, 0]; data.cls.forEach(c => counts[c]++);
  console.log(JSON.stringify({n: data.n, cells: data.alt.length, solids: data.solids, classCounts: counts, maxAlt: Math.max(...data.alt)}));
} finally { await b.close(); }
