// Authored review UI. All edits are real pointer events in the game or existing panel buttons.
// No Save button invocation or localStorage writes occur in this harness.
const $=s=>document.querySelector(s),frame=$('#stage'),passageMode=Number(new URLSearchParams(location.search).get('junctionWfcPassage')||0),passageCandidate=[1,2].includes(passageMode);let t,city,e,ready=false,targetPoint=null;const errors=[],target={regionId:'left-front-coral',ix:1,iy:2,iz:0};
function select(id){const select=frame.contentDocument.querySelector('#ce-target');select.value=id;select.dispatchEvent(new frame.contentWindow.Event('change',{bubbles:true}));t.citadelEditorPanel.open();inspect();}
function gpuSample(){const gl=t.renderer.getContext(),programs=t.renderer.info.programs||[],failed=[];for(const p of programs){if(!p.program){failed.push({id:p.id,reason:'missing program'});continue;}if(!gl.getProgramParameter(p.program,gl.LINK_STATUS))failed.push({id:p.id,reason:gl.getProgramInfoLog(p.program)});for(const shader of gl.getAttachedShaders(p.program)||[])if(!gl.getShaderParameter(shader,gl.COMPILE_STATUS))failed.push({id:p.id,reason:gl.getShaderInfoLog(shader)});}const glErrors=[];for(let i=0;i<16;i++){const e=gl.getError();if(e===gl.NO_ERROR)break;glErrors.push(e);}return {programs:programs.length,failed,glErrors,note:'Current linked programs and error queue sample; not GPU timing or proof of all frames'};}
function inspect(){if(!ready)return;city.updateWorldMatrix(true,true);t.camera.updateMatrixWorld(true);const world=targetPoint?city.localToWorld(new t.THREE.Vector3(...targetPoint)):e.cellWorld(target),ndc=world.clone().project(t.camera),rect=t.renderer.domElement.getBoundingClientRect(),outer=frame.getBoundingClientRect(),x=rect.left+(ndc.x+1)*rect.width/2,y=rect.top+(1-ndc.y)*rect.height/2;const ray=new t.THREE.Raycaster();ray.setFromCamera(new t.THREE.Vector2(ndc.x,ndc.y),t.camera);const hit=e.pick(ray);$('#results').textContent=JSON.stringify({revision:e.revision,dirty:e.dirty,target,world:world.toArray(),canvasClick:{x,y},pageClick:{x:outer.left+x,y:outer.top+y},actualRayHit:hit,selectedTarget:frame.contentDocument.querySelector('#ce-target')?.value,snapshot:e.snapshot(),wfcAudit:e.audit(),gpu:gpuSample(),passageClearance:e.root.userData.passageClearance??null,errors},null,2);$('#status').textContent=`修订 ${e.revision} · ${e.dirty?'未保存':'初始/已保存'} · 目标点 页面 x=${Math.round(outer.left+x)} y=${Math.round(outer.top+y)} · 实際命中 ${hit?.regionId||'无'}/${hit?.ix},${hit?.iy},${hit?.iz}`;}
function focus(wide=false){if(!ready)return;targetPoint=null;city.updateWorldMatrix(true,true);const T=t.THREE,aim=wide?city.localToWorld(new T.Vector3(0,9,0)):e.cellWorld(target);t.cameraRig.update=()=>{};t.camera.up.copy(new T.Vector3(0,1,0).transformDirection(city.matrixWorld));const offset=new T.Vector3(wide?40:7,wide?35:10,wide?62:17).transformDirection(city.matrixWorld).multiplyScalar(wide?81:21);t.camera.position.copy(aim).add(offset);t.camera.lookAt(aim);t.camera.updateProjectionMatrix();t.camera.updateMatrixWorld(true);t.distanceCulling?.recollect();t.distanceCulling?.update(3);inspect();}
$('#focus').onclick=()=>focus();$('#wide').onclick=()=>focus(true);$('#junction').onclick=()=>select('canal-junction');$('#highland').onclick=()=>select('');$('#undo').onclick=()=>{frame.contentDocument.querySelector('#ce-undo')?.click();inspect();};$('#redo').onclick=()=>{frame.contentDocument.querySelector('#ce-redo')?.click();inspect();};$('#inspect').onclick=inspect;
if(passageCandidate){document.querySelector('header b').textContent=passageMode===2?'WFC 双层三连拱候选 · 洞高2.30m · 左端固定地基低2.70m，整条路线不通行 · 删下半会提示承托拒绝':'WFC 贯通拱门 · 默认关闭的视觉结构实验 · 净高 1.428m < 玩家 1.66m · 1处固定地基未承托，不作通行验收';const button=document.createElement('button');button.textContent='查看 WFC 贯通拱门';button.onclick=()=>{if(!ready)return;const region=e.audit().regions.find(r=>passageMode===2?r.regionId==='left-mid-yellow':r.passage?.consumed.length),p=region?.passage?.consumed.find(p=>p.half!=='upper');if(!p)return;const [ix,iy,iz]=p.cell.split(',').map(Number),aim=e.cellWorld({regionId:region.regionId,ix,iy,iz});city.updateWorldMatrix(true,true);t.cameraRig.update=()=>{};t.camera.up.copy(new t.THREE.Vector3(0,1,0).transformDirection(city.matrixWorld));const offset=new t.THREE.Vector3(p.axis==='x'?-7:2,2,p.axis==='z'?-7:2).applyQuaternion(city.getWorldQuaternion(new t.THREE.Quaternion()));t.camera.position.copy(aim).add(offset);t.camera.lookAt(aim);t.camera.updateMatrixWorld(true);t.distanceCulling?.recollect();t.distanceCulling?.update(3);inspect();};document.querySelector('header').append(button);}
if(passageMode===2)for(const [label,x,side]of [['左端地基落差',-14.8,-1],['右端地基',-9.2,1]]){
 const button=document.createElement('button');button.textContent=label;button.onclick=()=>{if(!ready)return;city.updateWorldMatrix(true,true);const aim=city.localToWorld(new t.THREE.Vector3(x,2.5,-.3));t.cameraRig.update=()=>{};t.camera.up.copy(new t.THREE.Vector3(0,1,0).transformDirection(city.matrixWorld));const offset=new t.THREE.Vector3(side*4,2.3,5).applyQuaternion(city.getWorldQuaternion(new t.THREE.Quaternion()));t.camera.position.copy(aim).add(offset);t.camera.lookAt(aim);t.camera.updateMatrixWorld(true);t.distanceCulling?.recollect();t.distanceCulling?.update(3);inspect();};document.querySelector('header').append(button);
}
if(passageMode===2)for(const [label,iy]of [['上半删除试验（允许）',1],['下半删除试验（拒绝）',0]]){
 const button=document.createElement('button');button.textContent=label;button.onclick=()=>{if(!ready)return;Object.assign(target,{regionId:'left-mid-yellow',ix:0,iy,iz:1});targetPoint=[-13.6,3.35+(iy===0?.85:2.60),.35];city.updateWorldMatrix(true,true);const aim=city.localToWorld(new t.THREE.Vector3(-13.6,3.35+(iy===0?.85:2.60),.35));t.cameraRig.update=()=>{};t.camera.up.copy(new t.THREE.Vector3(0,1,0).transformDirection(city.matrixWorld));t.camera.position.copy(city.localToWorld(new t.THREE.Vector3(-19,3.35+(iy===0?.85:2.60),.35)));t.camera.lookAt(aim);t.camera.updateMatrixWorld(true);t.distanceCulling?.recollect();t.distanceCulling?.update(3);inspect();};document.querySelector('header').append(button);
}
frame.src='/TigerMessenger/?autostart=1&junctionEditable=1'+(passageCandidate?'&junctionWfcPassage='+passageMode:'');
const poll=setInterval(()=>{try{const w=frame.contentWindow;if(!w.document.__junctionHarnessErrors){w.document.__junctionHarnessErrors=true;w.addEventListener('error',x=>errors.push(x.message));w.addEventListener('unhandledrejection',x=>errors.push(String(x.reason)));}t=w.__tm;city=t?.messenger?.landmarks?.canalJunctionCitadel;e=city?.userData.junctionEditor;if(!e||!t.citadelEditorPanel||!t.renderer||!t.distanceCulling)return;clearInterval(poll);ready=true;t.P.daySpeed=0;t.P.timeOfDay=.5;t.dayNight.update(.001);select('canal-junction');focus();frame.contentDocument.addEventListener('pointerup',()=>setTimeout(inspect,100));}catch(error){$('#status').textContent=String(error);}},300);
