import {chromium} from '../../../tools/shot/node_modules/playwright/index.mjs';
import {mkdir,writeFile,copyFile} from 'node:fs/promises';
const n=Number(process.argv[2]||1),id=`r${String(n).padStart(2,'0')}`,out='TigerMessenger/artifacts/pipeline/highland-gate-thirty-rounds/';await mkdir(out,{recursive:true});
const b=await chromium.launch({channel:'chrome',headless:true,args:['--use-angle=metal']});
try{const p=await b.newPage({viewport:{width:1500,height:1000}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(`http://localhost:8931/TigerMessenger/?autostart=1&highlandGate=${n}`,{waitUntil:'domcontentloaded'});await p.waitForFunction(()=>window.__tm?.scene.getObjectByName('highland-gate'),null,{timeout:240000});
const report=await p.evaluate(()=>{
const t=window.__tm,T=t.THREE,g=t.scene.getObjectByName('highland-gate'),sys=t.messenger.landmarks.tramSystem;t.cameraRig.update=()=>{};t.P.daySpeed=0;t.P.timeOfDay=.42;t.scene.updateMatrixWorld(true);
const meshes=[];g.traverse(o=>{if(o.isMesh)meshes.push(o)});const ray=new T.Raycaster(),hits=[];let rays=0;
for(const [lane,cv]of Object.entries(sys.curves||{center:sys.curve})){const N=Math.ceil(cv.getLength()/.6);for(let i=1;i<N;i++){const w=cv.getPointAt(i/N),l=g.worldToLocal(w.clone());if(Math.abs(l.z)>23||Math.abs(l.x)>35||Math.abs(l.y)>20)continue;const up=w.clone().normalize(),dir=cv.getTangentAt(i/N).normalize(),right=new T.Vector3().crossVectors(up,dir).normalize();for(const side of[-.9,0,.9])for(const h of[.35,1.5,2.8,3.8]){ray.set(w.clone().addScaledVector(up,h).addScaledVector(right,side).addScaledVector(dir,-.65),dir);ray.near=0;ray.far=1.3;rays++;const hit=ray.intersectObjects(meshes,false)[0];if(hit)hits.push({lane,local:l.toArray(),h,side,name:hit.object.name});}}}
const walking={samples:0,unsupported:0,blocked:0};let prev=null;const length=sys.curve.getLength();for(let d=-34;d<=34;d+=.35){const u=(g.userData.railU+d/length+1)%1,w=sys.curve.getPointAt(u),up=w.clone().normalize(),side=new T.Vector3().crossVectors(up,sys.curve.getTangentAt(u)).normalize();w.addScaledVector(side,-3.15).addScaledVector(up,.05);const ground=g.userData.sampleGroundRadius?.(w);walking.samples++;if(ground==null)walking.unsupported++;else w.normalize().multiplyScalar(ground);if(prev){const next=w.clone();g.userData.resolveWalls?.(prev,next,new T.Vector3());if(next.distanceTo(w)>.12)walking.blocked++;}prev=w.clone();}
const stairs={samples:0,unsupported:0,blocked:0,details:[]};prev=null;if(g.userData.round>=12&&g.userData.toRailWorld)for(let i=0;i<=80;i++){const v=i/80,w=g.userData.toRailWorld(-3.15-14.85*v,.05+2.42*v,-32+(g.userData.round>=25?10:13)*v);stairs.samples++;const ground=g.userData.sampleGroundRadius(w);if(ground==null)stairs.unsupported++;else w.normalize().multiplyScalar(ground);if(prev){const next=w.clone();g.userData.resolveWalls(prev,next,new T.Vector3());if(next.distanceTo(w)>.12){stairs.blocked++;const dir=w.clone().sub(prev).normalize();ray.set(prev.clone().addScaledVector(prev.clone().normalize(),.8),dir);ray.far=1;stairs.details.push({i,t:v,hits:ray.intersectObjects(meshes,false).slice(0,2).map(h=>h.object.name)});}}prev=w.clone();}
const L=a=>g.localToWorld(new T.Vector3(...a));window.__highlandView=k=>{const c=k==='context'?[[65,75,-120],[0,10,5]]:k==='front'?[[-24,17,-60],[0,12,0]]:[[52,32,-75],[0,16,0]];t.camera.position.copy(L(c[0]));t.camera.up.set(0,1,0).transformDirection(g.matrixWorld);t.camera.lookAt(L(c[1]));t.camera.fov=52;t.camera.far=4000;t.camera.updateProjectionMatrix();t.camera.updateMatrixWorld(true);t.distanceCulling?.recollect();t.distanceCulling?.update(3);};
return {stairs,walking,round:g.userData.round,railU:g.userData.railU,rays,hitCount:hits.length,hits:hits.slice(0,30),meshCount:meshes.length,position:g.position.toArray()};});
for(const view of['near','context','front']){await p.evaluate(v=>window.__highlandView(v),view);await p.waitForTimeout(400);const png=await p.evaluate(()=>{const t=window.__tm;t.renderer.render(t.scene,t.camera);return t.renderer.domElement.toDataURL('image/png')});await writeFile(`${out}${id}-${view}.png`,Buffer.from(png.split(',')[1],'base64'));}
report.errors=errors;await writeFile(`${out}${id}.json`,JSON.stringify(report,null,2));await copyFile('TigerMessenger/src/world/citadel/highlandGate.js',`${out}snapshots/${id}.js`);console.log(JSON.stringify(report));}finally{await b.close();}
