import {chromium} from '../../../tools/shot/node_modules/playwright/index.mjs';
import {writeFile} from 'node:fs/promises';
const released=process.argv.includes("--released");
const revision=process.argv.find(a=>/^--revision=\d+$/.test(a))?.split('=')[1]||'6';
const placement=process.argv.includes('--placement');
const massing=process.argv.includes('--massing');
const plaza=process.argv.includes('--plaza');
const port=process.argv.includes("--port");
const tag=released?"released":port?"placement-r04":plaza?'placement-r03':massing?'placement-r02':placement?'placement-r01':'r'+revision.padStart(2,'0');
const b=await chromium.launch({channel:'chrome',headless:true,args:['--use-angle=metal']});
try {const p=await b.newPage({viewport:{width:1600,height:1000}});
await p.goto(released?'http://localhost:8931/TigerMessenger/?autostart=1':'http://localhost:8931/TigerMessenger/?autostart=1&citadelMasterTerrain='+revision+(placement?'&citadelWater=2&citadelFrontGate=1&citadelPlacement=1':'')+(massing?'&citadelMassing=2':'')+(plaza?'&citadelPlaza=3':'')+(port?'&citadelPort=4':''));
await p.waitForFunction(()=>window.__tm?.scene.getObjectByName('west-city-plaza-paving-ring')||document.body.innerText.includes('游戏脚本启动失败'),null,{timeout:180000});
if(!await p.evaluate(()=>!!window.__tm))throw new Error(await p.locator('body').innerText());
await p.waitForFunction(()=>['ready','error'].includes(window.__tm?.scene.getObjectByName('castleContainer')?.userData.masterTerrainCandidate?.status),null,{timeout:180000});
console.log(await p.evaluate(()=>{const d=window.__tm.scene.getObjectByName('castleContainer').userData;return {terrain:d.masterTerrainCandidate,placement:d.oldCityParcelCandidate};}));
if(massing)await writeFile(new URL('../../artifacts/pipeline/citadel-master-terrain/placement-r02-massing.json',import.meta.url),JSON.stringify(await p.evaluate(()=>{const d=window.__tm.scene.getObjectByName('citadel-target-castle-silhouette').userData;return {source:d.sourceId,towers:d.towerMassing,wfc:d.facadeWfc};}),null,2));
const images=await p.evaluate(async()=>{const t=window.__tm,T=t.THREE,c=t.scene.getObjectByName('highland-west-city');t.cameraRig.update=()=>{};t.P.daySpeed=0;t.P.timeOfDay=.85;c.updateWorldMatrix(true,true);const result={};
for(const [name,eye,look,fov]of [['target-angle',[108,42,140],[59,14,65],55],['target-angle-near',[96,31,117],[60,13,61],59]]) {t.camera.position.copy(c.localToWorld(new T.Vector3(...eye)));t.camera.up.set(0,1,0).transformDirection(c.matrixWorld);t.camera.lookAt(c.localToWorld(new T.Vector3(...look)));t.camera.fov=fov;t.camera.updateProjectionMatrix();await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));t.renderer.render(t.scene,t.camera);result[name]=t.renderer.domElement.toDataURL('image/png');}return result;});
for(const [name,data]of Object.entries(images))await writeFile(new URL('../../artifacts/pipeline/citadel-master-terrain/'+tag+'-'+name+'.png',import.meta.url),Buffer.from(data.split(',')[1],'base64'));
}finally{await b.close();}
