import {chromium} from '../../../tools/shot/node_modules/playwright/index.mjs';
import {writeFile} from 'node:fs/promises';
const b=await chromium.launch({channel:'chrome',headless:true,args:['--use-angle=metal']});
try { const p=await b.newPage();await p.addInitScript(()=>{const r=requestAnimationFrame.bind(window);window.requestAnimationFrame=f=>f.name==='animate'?0:r(f);});await p.goto('http://localhost:8931/TigerMessenger/?autostart=1');await p.waitForFunction(()=>window.__tm?.messenger?.landmarks?.abandonedGate,null,{timeout:180000});
const d=await p.evaluate(async()=>{
const t=window.__tm,T=t.THREE,g=t.messenger.landmarks.abandonedGate,c=t.messenger.landmarks.tramSystem.curve,L=c.getLength();const {canyonOffsetDir}=await import('/TigerMessenger/src/world/canyon.js');const {worldToFlatXZ,groundLiftAt}=await import('/TigerMessenger/src/world/hills.js');
const fixed=new T.Vector3(23.134897,-71.740187,-141.426689).normalize();let best=Infinity,u=0;for(let i=0;i<12000;i++){const at=i/12000,dist=c.getPointAt(at).normalize().distanceToSquared(fixed);if(dist<best){best=dist;u=at;}}const center=c.getPointAt(u),up=center.clone().normalize(),f=c.getTangentAt(u).normalize(),right=new T.Vector3().crossVectors(up,f).normalize();up.crossVectors(f,right).normalize();right.negate();f.negate();const q=new T.Quaternion().setFromRotationMatrix(new T.Matrix4().makeBasis(right,up,f)),origin=center.clone().addScaledVector(up,-.8),matrix=new T.Matrix4().compose(origin,q,new T.Vector3(1,1,1)),inv=matrix.clone().invert();
function ground(x,z){let local=new T.Vector3(x,0,z),w=local.clone().applyMatrix4(matrix),dir=w.clone().normalize(),flat=worldToFlatXZ(dir,160);w.setLength(160+(flat?groundLiftAt(flat.x,flat.z):canyonOffsetDir(dir)));return w.applyMatrix4(inv).y;}
const {officialOceanLevelAt}=await import('/TigerMessenger/src/world/waterV8/officialOcean.js');const rail=[];for(let s=-140;s<=140;s+=2){const at=((u+s/L)%1+1)%1,world=c.getPointAt(at),up=world.clone().normalize(),right=new T.Vector3().crossVectors(up,c.getTangentAt(at)).normalize(),p=world.applyMatrix4(inv);rail.push({s,p:p.toArray(),up:up.transformDirection(inv).toArray(),right:right.transformDirection(inv).toArray(),ground:ground(p.x,p.z),waterRadius:160+officialOceanLevelAt(up.clone().transformDirection(matrix)),trackRadius:c.getPointAt(at).length(),groundRadius:(()=>{const dir=c.getPointAt(at).normalize(),flat=worldToFlatXZ(dir,160);return 160+(flat?groundLiftAt(flat.x,flat.z):canyonOffsetDir(dir));})()});}
const grid=[];for(let x=-65;x<=65;x+=5)for(let z=-140;z<=140;z+=5)grid.push([x,ground(x,z),z]);return {u,entryU:g.userData.anchor.entryU,matrix:matrix.toArray(),origin:origin.toArray(),quaternion:q.toArray(),rail,grid};});await writeFile('TigerMessenger/artifacts/pipeline/gate-of-sighs-build/site-source.json',JSON.stringify(d));console.log(JSON.stringify({u:d.u,samples:d.rail.length,grid:d.grid.length}));}finally{await b.close();}
