import{chromium}from'../../../tools/shot/node_modules/playwright/index.mjs';import{writeFileSync}from'node:fs';
const b=await chromium.launch({channel:'chrome',headless:true,args:['--use-angle=metal']}),p=await b.newPage({viewport:{width:1200,height:800}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://localhost:8931/TigerMessenger/?autostart=1');await p.waitForFunction(()=>window.__tm?.scene.getObjectByName('highland-gate')&&window.__tm.scene.getObjectByName('highland-west-city'),null,{timeout:120000});await p.waitForTimeout(6000);
const result=await p.evaluate(async()=>{const t=__tm,T=t.THREE,h=await import('/TigerMessenger/src/world/citadel/historicStone.js'),castle=t.scene.getObjectByName('castleContainer'),gate=t.scene.getObjectByName('highland-gate'),city=t.scene.getObjectByName('highland-west-city');
const walk=[];castle.traverse(o=>{if(o.isMesh&&(o.userData.westCityWalkable||o.userData.highlandWalkable||/stair|walkable|bridge-deck/.test(o.name)))walk.push(o);});gate.traverse(o=>{if(o.isMesh&&o.userData.highlandGateWalkable)walk.push(o);});
const stamp=o=>{const p=o.geometry.attributes.position;let sum=0;for(let i=0;i<p.array.length;i++)sum+=p.array[i]*(i%13+1);return[o.uuid,p.count,sum];};const before=walk.map(stamp);h.setHistoricRound(castle,0);h.setHistoricRound(gate,0);const noAge=walk.map(stamp);h.setHistoricRound(castle,50);h.setHistoricRound(gate,50);const after=walk.map(stamp);
const additions=[];for(const r of[castle,gate])r.traverse(o=>{if(o.isMesh){let a=o;while(a){if(a.userData.historyRound){additions.push(o);break;}a=a.parent;}}});const ray=new T.Raycaster(),rail=[];const sys=t.messenger.landmarks.tramSystem;
for(const [lane,curve]of Object.entries(sys.curves))for(let i=0;i<1600;i++){const q=curve.getPointAt(i/1600),up=q.clone().normalize(),f=curve.getTangentAt(i/1600).normalize(),right=new T.Vector3().crossVectors(up,f).normalize();for(const side of[-.9,0,.9])for(const y of[.4,1.5,3.1]){ray.set(q.clone().addScaledVector(right,side).addScaledVector(up,y).addScaledVector(f,-1),f);ray.far=2;const hits=ray.intersectObjects(additions,false);if(hits.length)rail.push({lane,i,name:hits[0].object.name});}}
const probes=city.getObjectByName('citadel-target-castle-silhouette').userData.facadeWfc.openingProbes,portalRoot=city.getObjectByName('citadel-target-castle-silhouette'),blocked=[];for(const probe of probes){const c=portalRoot.localToWorld(new T.Vector3(...probe.center)),n=new T.Vector3(...probe.normal).transformDirection(portalRoot.matrixWorld);ray.set(c.clone().addScaledVector(n,1),n.negate());ray.far=2;if(ray.intersectObjects(additions,false).length)blocked.push(probe.id);}
let nan=0,vertices=0;for(const r of[castle,gate])r.traverse(o=>{if(o.isMesh){const a=o.geometry.attributes.position.array;vertices+=a.length/3;for(const n of a)if(!Number.isFinite(n))nan++;}});
t.cameraRig.update=()=>{};t.P.daySpeed=0;t.P.timeOfDay=.5;t.camera.position.copy(castle.localToWorld(new T.Vector3(-20,70,215)));t.camera.up.set(0,1,0).transformDirection(castle.matrixWorld);t.camera.lookAt(castle.localToWorld(new T.Vector3(-5,5,40)));t.camera.updateMatrixWorld();t.distanceCulling.recollect();t.distanceCulling.update(3);const samples=[];let last=performance.now();for(let i=0;i<90;i++){await new Promise(r=>requestAnimationFrame(r));const now=performance.now();if(i>10)samples.push(now-last);last=now;}samples.sort((a,b)=>a-b);
return{defaults:[h.historicReport(castle),h.historicReport(gate)],walkMeshes:walk.length,walkGeometryUnchanged:JSON.stringify(before)===JSON.stringify(noAge)&&JSON.stringify(before)===JSON.stringify(after),newGeometryMeshes:additions.length,railSamples:3200*9,newRailObstructions:rail.slice(0,20),portalProbes:probes.length,newPortalObstructions:blocked,nan,vertices,frameMedianMs:samples[Math.floor(samples.length/2)],frameP95Ms:samples[Math.floor(samples.length*.95)],render:t.renderer.info.render};});writeFileSync(new URL('../../artifacts/pipeline/citadel-history-fifty/safety.json',import.meta.url),JSON.stringify({result,errors},null,2));console.log(JSON.stringify({result,errors}));await b.close();
