import {chromium} from '../../../tools/shot/node_modules/playwright/index.mjs';import {writeFile} from 'node:fs/promises';
const b=await chromium.launch({channel:'chrome',headless:true,args:['--use-angle=metal']});try{const page=await b.newPage();await page.goto('http://localhost:8931/TigerMessenger/?autostart=1&citadelCoastalTram=1',{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>window.__tm?.scene.getObjectByName('highland-west-city'),null,{timeout:180000});const report=await page.evaluate(()=>{const t=window.__tm,T=t.THREE,c=t.scene.getObjectByName('castleContainer'),sys=t.messenger.landmarks.tramSystem;c.updateWorldMatrix(true,true);t.camera.position.copy(c.localToWorld(new T.Vector3(0,120,130)));t.camera.lookAt(c.localToWorld(new T.Vector3(0,0,30)));t.camera.updateMatrixWorld(true);t.distanceCulling?.update(3);const meshes=[];t.scene.traverse(o=>{if(!o.isMesh||o.userData.isOutline||o.userData.backlitHighlight)return;let a=o;while(a){if(a===sys.group||/cloud|ocean|^sky|^snow|^rain/i.test(a.name))return;a=a.parent;}const materials=Array.isArray(o.material)?o.material:[o.material];if(materials.every(m=>m.visible===false))return;for(const m of materials)m.side=T.DoubleSide;meshes.push({o,box:new T.Box3().setFromObject(o)});});
const hits=[],segments=[];let maxGrade=0,minRadius=Infinity,n=0,maxGradeAt=null,minRadiusAt=null;const ray=new T.Raycaster();ray.layers.enableAll();
for(const [lane,curve] of Object.entries(sys.curves)){const L=curve.getLength(),N=Math.ceil(L/1.5);for(let i=1;i<N-1;i++){const p=curve.getPointAt(i/N),local=c.worldToLocal(p.clone());if(i/N<.44||i/N>.88)continue;const up=p.clone().normalize(),prev=curve.getPointAt((i-1)/N),next=curve.getPointAt((i+1)/N),dir=next.clone().sub(prev).normalize(),right=new T.Vector3().crossVectors(up,dir).normalize();const turn=prev.clone().sub(p).negate().normalize().angleTo(next.clone().sub(p).normalize());const radius=(L/N)/Math.max(1e-9,turn),grade=Math.abs(dir.dot(up));if(radius<minRadius){minRadius=radius;minRadiusAt={t:i/N,local:local.toArray(),altitude:p.length()-160};}if(grade>maxGrade){maxGrade=grade;maxGradeAt={t:i/N,local:local.toArray(),altitude:p.length()-160};}n++;
const terrain=meshes.map(m=>m.o);ray.set(p.clone().addScaledVector(up,150),up.clone().negate());ray.near=0;ray.far=152;const cover=ray.intersectObjects(terrain,false).find(h=>h.point.clone().sub(p).dot(up)>.1);if(cover&&hits.length<40)hits.push({lane,t:i/N,local:local.toArray(),obstacle:cover.object.name,coverHeight:cover.point.clone().sub(p).dot(up)});
const near=meshes.filter(m=>m.box.distanceToPoint(p)<7).map(m=>m.o);
for(const side of [-.7,0,.7])for(const height of [.35,1.4,2.6]){const start=p.clone().addScaledVector(right,side).addScaledVector(up,height).addScaledVector(dir,-2.5);ray.set(start,dir);ray.near=0;ray.far=5;const h=ray.intersectObjects(near,false)[0];if(h&&hits.length<40)hits.push({lane,local:local.toArray(),height,side,obstacle:h.object.name,parent:h.object.parent?.name});}
if(i%10===0)segments.push({lane,local:local.toArray()});}}
return {samples:n,maxGradeAt,minRadiusAt,maxGrade,minCurveRadius:minRadius,collisionSamples:hits,segments,passed:n>20&&hits.length===0&&maxGrade<.15&&minRadius>12,scope:'Candidate shared-curve geometry: sampled swept rays through tram volume against visible nontransparent scene. Not boarding or full boat navigation validation.'};});await writeFile('TigerMessenger/artifacts/pipeline/citadel-coastal-tram-target/rail-clearance.json',JSON.stringify(report,null,2));console.log(JSON.stringify({...report,segments:undefined}));}finally{await b.close();}
