import{chromium}from'../../../tools/shot/node_modules/playwright/index.mjs';import{writeFileSync}from'node:fs';
const extra=process.argv.includes('--no-wfc')?'&seaStackWfc=0':'';
const out=new URL('../../artifacts/pipeline/twelve-apostles-coast/',import.meta.url).pathname,legacy=process.argv.includes('--before');
const variant=extra?'compat-no-wfc':legacy?'before':'after';
const b=await chromium.launch({channel:'chrome',headless:true,args:['--use-angle=metal']}),p=await b.newPage({viewport:{width:1500,height:950}}),errors=[],shaderErrors=[];p.on('pageerror',e=>{errors.push(e.message);console.error('PAGEERROR',e.message);});p.on('console',m=>{if(m.type()==='error'){shaderErrors.push(m.text().slice(0,700));console.error('CONSOLE',m.text().slice(0,700));}});
await p.goto('http://localhost:8931/TigerMessenger/?autostart=1'+(legacy?'&seaStackTerraces=0':'')+extra);await p.waitForFunction(()=>window.__tm?.messenger?.landmarks?.abandonedGate?.userData?.seatRoot?.userData?.siteRoot?.getObjectByName('g30-distant-ridges'),null,{timeout:90000});await p.waitForTimeout(5000);
const report=await p.evaluate(async()=>{const t=__tm,T=t.THREE,site=t.messenger.landmarks.abandonedGate.userData.seatRoot.userData.siteRoot;t.cameraRig.update=()=>{};t.P.daySpeed=0;t.P.timeOfDay=.5;t.dayNight.update(.0001);document.querySelectorAll('body > :not(canvas)').forEach(e=>{if(e.tagName!=='SCRIPT')e.style.visibility='hidden';});const rocks=[];site.traverse(o=>{if(o.name==='g30-far-mountain')rocks.push(o);});const obstacles=rocks.filter(o=>!o.userData.excludedSeaStack);site.traverse(o=>{if(o.name==='gate-sea-stack-fallen-block'&&o.visible)obstacles.push(o);});const ray=new T.Raycaster(),hits=[];let probes=0,nan=0,vertices=0;for(const o of rocks){for(const n of o.geometry.attributes.position.array)if(!Number.isFinite(n))nan++;vertices+=o.geometry.attributes.position.count;}const inv=site.matrixWorld.clone().invert();for(const [lane,curve]of Object.entries(t.messenger.landmarks.tramSystem.curves))for(let i=0;i<2600;i++){const q=curve.getPointAt(i/2600),l=q.clone().applyMatrix4(inv);const up=q.clone().normalize(),f=curve.getTangentAt(i/2600),right=new T.Vector3().crossVectors(up,f).normalize();for(const side of[-2.6,0,2.6])for(const h of[.5,3,10]){ray.set(q.clone().addScaledVector(up,h).addScaledVector(right,side).addScaledVector(f,-1),f);ray.far=2;probes++;const hit=ray.intersectObjects(obstacles,false)[0];if(hit)hits.push({lane,i,h,side,name:hit.object.name,position:hit.object.position.toArray()});}}const axes=rocks.filter(o=>!o.userData.excludedSeaStack&&o.userData.seaStack?.seaAnchor).map(o=>{const axis=new T.Vector3(0,1,0).transformDirection(o.matrixWorld),up=new T.Vector3(...o.userData.seaStack.worldUp),base=new T.Vector3(0,-o.userData.seaStack.height/2,0).applyMatrix4(o.matrixWorld),sea=new T.Vector3(...o.userData.seaStack.seaAnchor);return {angle:axis.angleTo(up)*180/Math.PI,burial:sea.length()-base.length(),modules:o.geometry.userData.wfc?.modules,socketMismatches:o.geometry.userData.wfc?.socketMismatches};});const {bookshopTownPose,BOOKSHOP_SITE_OUTLINE}=await import('/TigerMessenger/src/world/bookshopTownSite.js');const townQ=bookshopTownPose(160).quaternion.clone().invert();let plazaMin=Infinity,plazaHemisphereVertices=0;for(const rock of rocks.filter(o=>!o.userData.excludedSeaStack)){const p=rock.geometry.attributes.position;for(let i=0;i<p.count;i++){const q=rock.localToWorld(new T.Vector3().fromBufferAttribute(p,i)).normalize().applyQuaternion(townQ);if(q.y>0){plazaHemisphereVertices++;plazaMin=Math.min(plazaMin,Math.hypot(q.x*160/q.y,q.z*160/q.y-BOOKSHOP_SITE_OUTLINE.centerZ)-BOOKSHOP_SITE_OUTLINE.radius);}}}const vegetation=[];for(const rock of rocks.filter(o=>!o.userData.excludedSeaStack)){
 const bush=rock.getObjectByName('sea-stack-terrace-shrubs');
 for(const local of bush?.userData.roots||[]){const q=rock.localToWorld(new T.Vector3(...local)),up=q.clone().normalize();ray.set(q.clone().addScaledVector(up,2),up.clone().negate());ray.far=3;const hit=ray.intersectObject(rock,false)[0];vegetation.push({supported:!!hit,gap:hit?q.distanceTo(hit.point):null});}
}return{vegetation,plazaMin,plazaHemisphereVertices,plazaClear:plazaMin>20,terraces:t.scene.userData.seaStackTerraceAudit,axes,rocks:rocks.length,visibleRocks:rocks.filter(o=>!o.userData.excludedSeaStack).length,vertices,nan,probes,hits: hits.slice(0,30),hitCount:hits.length,greenery:site.getObjectByName('gate-reference-greenery')?.userData.audit?.grounded};});
writeFileSync(out+variant+'.json',JSON.stringify({report,errors,shaderErrors},null,2));
for(const view of ['rail','coast','overview','hero','side','coastline','plaza']){await p.evaluate(async view=>{const t=__tm,T=t.THREE,s=t.messenger.landmarks.abandonedGate.userData.seatRoot.userData.siteRoot;if(view==='plaza'){
const {bookshopTownPose}=await import('/TigerMessenger/src/world/bookshopTownSite.js');const pose=bookshopTownPose(160),up=pose.up,right=new T.Vector3(1,0,0).applyQuaternion(pose.quaternion),forward=new T.Vector3(0,0,1).applyQuaternion(pose.quaternion);
t.camera.position.copy(pose.position).addScaledVector(up,100).addScaledVector(forward,120).addScaledVector(right,50);t.camera.up.copy(up);t.camera.lookAt(pose.position.clone().addScaledVector(forward,20));t.camera.fov=62;t.camera.far=4000;t.camera.updateProjectionMatrix();t.camera.updateMatrixWorld(true);t.distanceCulling.recollect();t.distanceCulling.update(3);return;
}if(view==='coastline'){
const rocks=s.getObjectByName('g30-distant-ridges').children.filter(o=>o.name==='g30-far-mountain'&&!o.userData.excludedSeaStack),center=new T.Vector3();for(const rock of rocks)center.add(rock.getWorldPosition(new T.Vector3()));center.divideScalar(rocks.length);const up=center.clone().normalize(),tangent=s.getWorldPosition(new T.Vector3()).sub(center);tangent.addScaledVector(up,-tangent.dot(up)).normalize();t.camera.position.copy(center).addScaledVector(up,75).addScaledVector(tangent,160);t.camera.up.copy(up);t.camera.lookAt(center);t.camera.fov=55;t.camera.far=4000;t.camera.updateProjectionMatrix();t.camera.updateMatrixWorld(true);t.distanceCulling.recollect();t.distanceCulling.update(3);return;
}if(view==='hero'||view==='side'){
const rocks=s.getObjectByName('g30-distant-ridges').children.filter(o=>o.name==='g30-far-mountain'),rock=rocks.find(o=>!o.userData.excludedSeaStack&&o.userData.seaStack.height>45)||rocks.find(o=>!o.userData.excludedSeaStack)||rocks[0];
const h=rock.userData.seaStack.height;t.camera.position.copy(rock.localToWorld(new T.Vector3(...(view==='side'?[-62,h*.04,47]:[48,h*.20,68]))));
t.camera.up.set(0,1,0).transformDirection(rock.matrixWorld);t.camera.lookAt(rock.localToWorld(new T.Vector3(0,-h*.03,0)));t.camera.fov=55;t.camera.far=4000;t.camera.updateProjectionMatrix();t.camera.updateMatrixWorld(true);t.distanceCulling.recollect();t.distanceCulling.update(3);return;
}const [eye,target]=view==='rail'?[[40,12,-100],[90,0,-10]]:view==='coast'?[[115,2,-70],[98,-4,5]]:[[155,85,150],[0,-5,0]];t.camera.position.copy(s.localToWorld(new T.Vector3(...eye)));if(view==='rail'){const curve=t.messenger.landmarks.tramSystem.curve,inv=s.matrixWorld.clone().invert();let best=0,distance=Infinity;for(let i=0;i<4000;i++){const at=curve.getPointAt(i/4000),l=at.clone().applyMatrix4(inv),d=Math.hypot(l.x-85,l.z);if(l.y>-60&&d<distance){distance=d;best=i/4000;}}const at=curve.getPointAt(best),up=at.clone().normalize();t.camera.position.copy(at).addScaledVector(up,4);const aim=curve.getPointAt((best+35/curve.getLength())%1).addScaledVector(up,5);target.splice(0,3,...s.worldToLocal(aim).toArray());}t.camera.up.copy(t.camera.position).normalize();t.camera.lookAt(s.localToWorld(new T.Vector3(...target)));t.camera.fov=58;t.camera.far=4000;t.camera.updateProjectionMatrix();t.camera.updateMatrixWorld(true);t.distanceCulling.recollect();t.distanceCulling.update(3);},view);await p.waitForTimeout(400);const img=await p.evaluate(()=>{__tm.renderer.render(__tm.scene,__tm.camera);return __tm.renderer.domElement.toDataURL('image/png');});writeFileSync(out+variant+'-'+view+'.png',Buffer.from(img.split(',')[1],'base64'));}
writeFileSync(out+variant+'.json',JSON.stringify({report,errors,shaderErrors},null,2));console.log(JSON.stringify({report,errors,shaderErrors}));await b.close();
