import {chromium} from '../../../tools/shot/node_modules/playwright/index.mjs';
import {writeFileSync} from 'node:fs';
const out=new URL('../../artifacts/pipeline/citadel-mountain-two-hour/',import.meta.url).pathname;
const browser=await chromium.launch({channel:'chrome',headless:true,args:['--use-angle=metal']}),results=[];
for(const round of [0,13]){
 const p=await browser.newPage({viewport:{width:1500,height:1000}}),errors=[];p.on('pageerror',e=>errors.push(e.message));
 await p.goto('http://localhost:8931/TigerMessenger/?autostart=1&citadelMountain='+round);await p.waitForFunction(()=>window.__tm?.scene.getObjectByName('highland-gate'),null,{timeout:120000});await p.waitForTimeout(7500);
 await p.evaluate(()=>{const t=__tm,T=t.THREE,c=t.scene.getObjectByName('castleContainer');t.cameraRig.update=()=>{};t.P.daySpeed=0;t.P.timeOfDay=.5;t.dayNight.update(.001);t.camera.position.copy(c.localToWorld(new T.Vector3(-15,95,210)));t.camera.up.set(0,1,0).transformDirection(c.matrixWorld);t.camera.lookAt(c.localToWorld(new T.Vector3(4,10,25)));t.camera.fov=55;t.camera.updateProjectionMatrix();t.distanceCulling.recollect();t.distanceCulling.update(3);document.querySelectorAll('body > :not(canvas)').forEach(e=>{if(e.tagName!=='SCRIPT')e.style.visibility='hidden';});});
 const performance=await p.evaluate(async()=>{const ms=[];let last=window.performance.now();for(let i=0;i<220;i++){await new Promise(requestAnimationFrame);const now=window.performance.now();if(i>=40)ms.push(now-last);last=now;}ms.sort((a,b)=>a-b);return {medianMs:ms[Math.floor(ms.length*.5)],p95Ms:ms[Math.floor(ms.length*.95)],render:__tm.renderer.info.render};});
 if(round===13){for(const [name,u]of [['old-shore',.842],['bay',.872],['back-coast',.899]]){
  await p.evaluate(u=>{const t=__tm,T=t.THREE,curve=t.messenger.landmarks.tramSystem.curves.red,q=curve.getPointAt(u),up=q.clone().normalize(),f=curve.getTangentAt(u);t.camera.position.copy(q).addScaledVector(up,3.8);t.camera.up.copy(up);t.camera.lookAt(q.clone().addScaledVector(f,35).addScaledVector(up,4));t.camera.fov=65;t.camera.updateProjectionMatrix();t.distanceCulling.recollect();t.distanceCulling.update(3);},u);await p.waitForTimeout(500);
  const data=await p.evaluate(()=>{__tm.renderer.render(__tm.scene,__tm.camera);return __tm.renderer.domElement.toDataURL('image/png')});writeFileSync(out+'rail-'+name+'.png',Buffer.from(data.split(',')[1],'base64'));
 }}results.push({round,performance,errors});await p.close();
}
const p=await browser.newPage({viewport:{width:1400,height:950}}),errors=[];p.on('pageerror',e=>errors.push(e.message));const response=await p.goto('http://localhost:8931/TigerMessenger/artifacts/pipeline/citadel-mountain-two-hour/review.html');await p.waitForTimeout(700);await p.selectOption('#view','old-mountain');await p.selectOption('#round','10');await p.waitForTimeout(400);const images=await p.locator('img').evaluateAll(imgs=>imgs.map(i=>({src:i.getAttribute('src'),ok:i.complete&&i.naturalWidth>0})));await p.screenshot({path:out+'review-page.png'});writeFileSync(out+'journey-check.json',JSON.stringify({results,review:{status:response.status(),images,errors}},null,2));console.log(JSON.stringify({results,review:{status:response.status(),images,errors}}));await browser.close();
