import {chromium} from '../../../tools/shot/node_modules/playwright/index.mjs';
import {writeFile} from 'node:fs/promises';
const browser=await chromium.launch({channel:'chrome',headless:true,args:['--use-angle=metal']});
try {const page=await browser.newPage({viewport:{width:1440,height:900}});await page.goto('http://localhost:8931/TigerMessenger/?autostart=1',{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>window.__tm?.messenger?.landmarks?.abandonedGate,null,{timeout:180000});
const result=await page.evaluate(async()=>{const t=window.__tm,T=t.THREE;const meeting=t.messenger.landmarks.abandonedGate.getObjectByName('gate-hero-meeting');meeting.updateWorldMatrix(true,true);let courier;t.scene.traverse(o=>{if(o.userData.isHumanCourier)courier=o});t.player.position.copy(meeting.localToWorld(new T.Vector3(-1.7,.01,0)));t.player.forward.set(0,0,-1).transformDirection(meeting.matrixWorld);t.player.facing.copy(t.player.forward);t.player.velocity.set(0,0,0);t.player.onGround=true;const {syncPlayerVisual}=await import('/TigerMessenger/src/player/player.js');for(let i=0;i<40;i++)syncPlayerVisual(t.player,courier.parent);
const {PLAYER_HEIGHT,PLAYER_RADIUS}=await import('/TigerMessenger/src/core/constants.js');const {buildHumanCourier}=await import('/TigerMessenger/src/assets/characters/humanCourier.js');const model=buildHumanCourier();model.updateMatrixWorld(true);const box=new T.Box3().setFromObject(model);
t.scene.updateMatrixWorld(true);t.camera.position.copy(meeting.localToWorld(new T.Vector3(-.5,2.1,-4.4)));t.camera.up.set(0,1,0).transformDirection(meeting.matrixWorld);t.camera.lookAt(meeting.localToWorld(new T.Vector3(-.5,.95,0)));t.camera.updateProjectionMatrix();t.distanceCulling?.update(3);t.renderer.render(t.scene,t.camera);
return {height:box.max.y-box.min.y,feet:box.min.y,width:box.max.x-box.min.x,collisionHeight:PLAYER_HEIGHT,collisionDiameter:PLAYER_RADIUS*2,image:t.renderer.domElement.toDataURL()};});
await writeFile(new URL('../../artifacts/pipeline/courier-hero-height/after.png',import.meta.url),Buffer.from(result.image.split(',')[1],'base64'));delete result.image;result.passed=Math.abs(result.height-1.66)<1e-5&&Math.abs(result.feet)<1e-5&&result.width<=result.collisionDiameter&&result.collisionHeight>=result.height-1e-6;console.log(JSON.stringify(result));await writeFile(new URL('../../artifacts/pipeline/courier-hero-height/fit-check.json',import.meta.url),JSON.stringify(result,null,2));if(!result.passed)process.exitCode=1;
}finally{await browser.close()}
