import{chromium}from'../../../tools/shot/node_modules/playwright/index.mjs';import{writeFileSync}from'node:fs';
const extra=process.argv.includes('--no-wfc')?'&seaStackWfc=0':'';
const out=new URL('../../artifacts/pipeline/twelve-apostles-coast/',import.meta.url).pathname,legacy=process.argv.includes('--before');
const variant=extra?'compat-no-wfc':legacy?'before':'after';
const b=await chromium.launch({channel:'chrome',headless:true,args:['--use-angle=metal']}),p=await b.newPage({viewport:{width:1500,height:950}}),errors=[],shaderErrors=[];p.on('pageerror',e=>{errors.push(e.message);console.error('PAGEERROR',e.message);});p.on('console',m=>{if(m.type()==='error'){shaderErrors.push(m.text().slice(0,700));console.error('CONSOLE',m.text().slice(0,700));}});
await p.goto('http://localhost:8931/TigerMessenger/?autostart=1'+(legacy?'&seaStackTerraces=0':'')+extra);await p.waitForFunction(()=>window.__tm?.messenger?.landmarks?.abandonedGate?.userData?.seatRoot?.userData?.siteRoot?.getObjectByName('g30-distant-ridges'),null,{timeout:90000});await p.waitForTimeout(5000);
await p.evaluate(()=>{__tm.cameraRig.update=()=>{};__tm.P.daySpeed=0;__tm.P.timeOfDay=.5;});
for(const view of ['rail']){await p.evaluate(async view=>{const t=__tm,T=t.THREE,s=t.messenger.landmarks.abandonedGate.userData.seatRoot.userData.siteRoot;if(view==='plaza'){
const {bookshopTownPose}=await import('/TigerMessenger/src/world/bookshopTownSite.js');const pose=bookshopTownPose(160),up=pose.up,right=new T.Vector3(1,0,0).applyQuaternion(pose.quaternion),forward=new T.Vector3(0,0,1).applyQuaternion(pose.quaternion);
t.camera.position.copy(pose.position).addScaledVector(up,100).addScaledVector(forward,120).addScaledVector(right,50);t.camera.up.copy(up);t.camera.lookAt(pose.position.clone().addScaledVector(forward,20));t.camera.fov=62;t.camera.far=4000;t.camera.updateProjectionMatrix();t.camera.updateMatrixWorld(true);t.distanceCulling.recollect();t.distanceCulling.update(3);return;
}if(view==='coastline'){
const rocks=s.getObjectByName('g30-distant-ridges').children.filter(o=>o.name==='g30-far-mountain'&&!o.userData.excludedSeaStack),center=new T.Vector3();for(const rock of rocks)center.add(rock.getWorldPosition(new T.Vector3()));center.divideScalar(rocks.length);const up=center.clone().normalize(),tangent=s.getWorldPosition(new T.Vector3()).sub(center);tangent.addScaledVector(up,-tangent.dot(up)).normalize();t.camera.position.copy(center).addScaledVector(up,75).addScaledVector(tangent,160);t.camera.up.copy(up);t.camera.lookAt(center);t.camera.fov=55;t.camera.far=4000;t.camera.updateProjectionMatrix();t.camera.updateMatrixWorld(true);t.distanceCulling.recollect();t.distanceCulling.update(3);return;
}if(view==='hero'||view==='side'){
const rocks=s.getObjectByName('g30-distant-ridges').children.filter(o=>o.name==='g30-far-mountain'),rock=rocks.find(o=>!o.userData.excludedSeaStack&&o.userData.seaStack.height>45)||rocks.find(o=>!o.userData.excludedSeaStack)||rocks[0];
const h=rock.userData.seaStack.height;t.camera.position.copy(rock.localToWorld(new T.Vector3(...(view==='side'?[-62,h*.04,47]:[48,h*.20,68]))));
t.camera.up.set(0,1,0).transformDirection(rock.matrixWorld);t.camera.lookAt(rock.localToWorld(new T.Vector3(0,-h*.03,0)));t.camera.fov=55;t.camera.far=4000;t.camera.updateProjectionMatrix();t.camera.updateMatrixWorld(true);t.distanceCulling.recollect();t.distanceCulling.update(3);return;
}const [eye,target]=view==='rail'?[[40,12,-100],[90,0,-10]]:view==='coast'?[[115,2,-70],[98,-4,5]]:[[155,85,150],[0,-5,0]];t.camera.position.copy(s.localToWorld(new T.Vector3(...eye)));if(view==='rail'){const curve=t.messenger.landmarks.tramSystem.curve,inv=s.matrixWorld.clone().invert();let best=0,distance=Infinity;for(let i=0;i<4000;i++){const at=curve.getPointAt(i/4000),l=at.clone().applyMatrix4(inv),d=Math.hypot(l.x-85,l.z);if(l.y>-60&&d<distance){distance=d;best=i/4000;}}const at=curve.getPointAt(best),up=at.clone().normalize();t.camera.position.copy(at).addScaledVector(up,4);const aim=curve.getPointAt((best+35/curve.getLength())%1).addScaledVector(up,5);target.splice(0,3,...s.worldToLocal(aim).toArray());}t.camera.up.copy(t.camera.position).normalize();t.camera.lookAt(s.localToWorld(new T.Vector3(...target)));t.camera.fov=58;t.camera.far=4000;t.camera.updateProjectionMatrix();t.camera.updateMatrixWorld(true);t.distanceCulling.recollect();t.distanceCulling.update(3);},view);await p.waitForTimeout(400);const img=await p.evaluate(()=>{__tm.renderer.render(__tm.scene,__tm.camera);return __tm.renderer.domElement.toDataURL('image/png');});writeFileSync('/Users/panglaohu/Downloads/TigerInBamboo/TigerMessenger/artifacts/pipeline/gate-rail-guard/after.png',Buffer.from(img.split(',')[1],'base64'));}
console.log(JSON.stringify(await p.evaluate(()=>{const t=__tm,T=t.THREE,ray=new T.Raycaster(),rows=[];for(const [x,y] of [[600,750],[630,690],[680,600],[750,550],[570,820]]){ray.setFromCamera(new T.Vector2(x/1500*2-1,1-y/950*2),t.camera);rows.push({x,y,hits:ray.intersectObjects(t.scene.children,true).filter(h=>{let o=h.object;while(o){if(!o.visible)return false;o=o.parent;}return h.object.isMesh;}).slice(0,4).map(h=>({name:h.object.name,parent:h.object.parent?.name,position:h.object.position.toArray(),point:h.point.toArray()}))});}return rows;})));await b.close();