import{orientedRayCrossings}from'./oriented_ray_crossings.mjs';
import fs from 'node:fs';import * as T from 'three';
import {eastCliffFinalSurfaceFixture} from './east_cliff_final_surface_fixture.mjs';
const dir=new URL('../../artifacts/pipeline/citadel-east-shore-route-20261006/',import.meta.url),artifact=JSON.parse(fs.readFileSync(new URL('remesh-final-surface-geometry.json',dir))),audit=JSON.parse(fs.readFileSync(new URL('remesh-final-surface-audit.json',dir)));
const geometry=new T.BufferGeometryLoader().parse(artifact.geometry),castle=new T.Matrix4().fromArray(artifact.castleMatrix),matrix=castle.clone().multiply(new T.Matrix4().makeTranslation(...artifact.origin));
function triangles(g,m){const p=g.attributes.position,idx=g.index,out=[];for(let i=0;i<(idx?.count??p.count);i+=3)out.push([0,1,2].map(j=>new T.Vector3().fromBufferAttribute(p,idx?idx.getX(i+j):i+j).applyMatrix4(m)));return out;}
function winding(tris,point){let sum=0;for(const t of tris){const[a,b,c]=t.map(p=>p.clone().sub(point)),la=a.length(),lb=b.length(),lc=c.length();sum+=2*Math.atan2(a.dot(b.clone().cross(c)),la*lb*lc+a.dot(b)*lc+b.dot(c)*la+c.dot(a)*lb);}return sum/(4*Math.PI);}
function topology(tris,tol){const vertices=new Map(),edges=new Map();let degenerate=0;const key=p=>p.toArray().map(v=>Math.round(v/tol)).join(',');for(let i=0;i<tris.length;i++){const t=tris[i],k=t.map(key);if(new Set(k).size<3)degenerate++;for(let j=0;j<3;j++){vertices.set(k[j],t[j]);const a=k[j],b=k[(j+1)%3],ek=a<b?a+'|'+b:b+'|'+a;if(!edges.has(ek))edges.set(ek,[]);edges.get(ek).push({face:i,sign:a<b?1:-1});}}
 let boundary=0,multi=0,inconsistent=0;const examples=[];for(const [key,e]of edges){if(e.length===1)boundary++;else if(e.length!==2)multi++;else if(e[0].sign===e[1].sign)inconsistent++;if(e.length!==2&&examples.length<12)examples.push({key,uses:e});}return{tol,vertices:vertices.size,edges:edges.size,boundary,nonManifold:multi,inconsistent,degenerate,examples,note:'Endpoint weld only; collinear T junctions are separately distinguished from physical gaps.'};}
function rays(tris,point){const ray=new T.Ray(point,new T.Vector3(1,0,0)),hits=[];for(let i=0;i<tris.length;i++){const t=tris[i],q=ray.intersectTriangle(...t,false,new T.Vector3());if(!q||q.distanceTo(point)<=1e-5)continue;const n=t[1].clone().sub(t[0]).cross(t[2].clone().sub(t[0])).normalize(),bary=new T.Triangle(...t).getBarycoord(q,new T.Vector3());hits.push({face:i,distance:q.distanceTo(point),point:q.toArray(),bary:bary.toArray(),minBary:Math.min(...bary.toArray()),normalDot:n.x});}hits.sort((a,b)=>a.distance-b.distance);return hits;}
const tris=triangles(geometry,matrix),baseline=eastCliffFinalSurfaceFixture(),baseTris=triangles(baseline.terrain.geometry,baseline.terrain.matrixWorld),rows=[];
for(const item of audit.results[0].joint.red.inside){const point=new T.Vector3().fromArray(item.local).applyMatrix4(castle);rows.push({...item,winding:winding(tris,point),baselineWinding:winding(baseTris,point),hits:rays(tris,point),oriented:orientedRayCrossings(rays(tris,point))});}
// Independent analytic closed box validates both winding sign and ray crossing away from boundaries.
const box=new T.BoxGeometry(2,2,2),boxTris=triangles(box,new T.Matrix4()),regression=[{point:[0,0,0],expectedInside:true},{point:[2,.17,.23],expectedInside:false}].map(r=>({...r,winding:winding(boxTris,new T.Vector3(...r.point)),hits:rays(boxTris,new T.Vector3(...r.point)).length}));
if(Math.abs(Math.abs(regression[0].winding)-1)>1e-9||Math.abs(regression[1].winding)>1e-9)throw new Error('solid angle regression failed');
const report={rows,topology:[1e-7,1e-5,1e-4].map(t=>topology(tris,t)),baselineTopology:topology(baseTris,1e-5),regression,verdict:'Two flagged samples are outside by solid angle and oriented crossings. Distance-only clustering merged opposing intersections; original final geometry unchanged. No global closed-manifold claim.'};
fs.writeFileSync(new URL('remesh-final-topology-diagnosis.json',dir),JSON.stringify(report,null,2));console.log(JSON.stringify({rows:rows.map(r=>({local:r.local,winding:r.winding,baselineWinding:r.baselineWinding,hits:r.hits.map(h=>({face:h.face,d:h.distance,b:h.minBary,n:h.normalDot}))})),topology:report.topology.map(({examples,...r})=>r),baselineTopology:{...report.baselineTopology,examples:undefined},regression},null,2));baseline.dispose();geometry.dispose();box.dispose();
