import * as T from 'three';
import {readFileSync,writeFileSync} from 'node:fs';
import {buildHighlandCitadelContinuousTerrain} from '../../src/world/highlandCitadelDesign.js';
import {sampleBaySurfacePatch} from '../../src/world/citadel/baySurfaceSampling.js';
import {bayWeight,bayRotation} from '../../src/world/citadel/bayLayoutMath.js';
const folder=new URL('../../artifacts/pipeline/citadel-five-hour-20261005/',import.meta.url),trace=JSON.parse(readFileSync(new URL('r15-overview-day-cloud-plants-rock-trace.json',folder))),frame=new T.Matrix4().fromArray(trace.castleMatrix),inv=frame.clone().invert(),source=buildHighlandCitadelContinuousTerrain().children[0].geometry,{geometry:g,audit}=sampleBaySurfacePatch(source);
const point=i=>{const v=new T.Vector3().fromBufferAttribute(g.attributes.position,i);v.x-=52;const w=bayWeight(v.x,v.z);v.applyMatrix4(frame).applyQuaternion(bayRotation(frame,160,w));if(w>0&&w<1)v.setLength(Math.min(v.length(),157+90*Math.abs(2*w-1)**3));return v.applyMatrix4(inv);};
const stats=records=>{const rows=[];for(const r of records)for(let f=r.start;f<r.end;f++){const [a,b,c]=[0,1,2].map(j=>point(g.index.getX(f*3+j))),area=b.clone().sub(a).cross(c.clone().sub(a)).length()/2,longest=Math.max(a.distanceTo(b),b.distanceTo(c),c.distanceTo(a));rows.push({face:f,source:r.sourceFace,aspect:longest**2/(2*area),height:Math.max(a.y,b.y,c.y)-Math.min(a.y,b.y,c.y),longest});}rows.sort((a,b)=>a.aspect-b.aspect);return {triangles:rows.length,medianAspect:rows[Math.floor(rows.length*.5)].aspect,p95Aspect:rows[Math.floor(rows.length*.95)].aspect,maxAspect:rows.at(-1).aspect,worst:rows.slice(-5)};};
const result={stage:'after bay map; before landform',selected:stats(audit.affected.filter(a=>audit.sourceFaces.includes(a.sourceFace))),transition:stats(audit.affected.filter(a=>!audit.sourceFaces.includes(a.sourceFace))),limitation:'Aspect alone does not identify exact rendered crease; downstream final face correspondence not exported for r17.'};writeFileSync(new URL('r17-bay-aspect-diagnosis.json',folder),JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));
