"""Pack actual Blender pine LOD0 buffers for synchronous Web factories.

No source GLB, Blender file or placement is modified. Base64 avoids millions
of JS numeric literals; geometry buffers are decoded once per requested seed.
"""
from pathlib import Path
import base64, hashlib, json, struct

ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / 'assets/models/optimized/saihoji-pines-v1'
manifest = json.loads((SOURCE / 'manifest.json').read_text())
result = {}
for entry in manifest['seeds']:
    seed = entry['seed']
    path = SOURCE / str(seed) / f'ancient-pine-{seed}-lod0.glb'
    raw = path.read_bytes()
    length = struct.unpack_from('<I', raw, 12)[0]
    doc = json.loads(raw[20:20+length])
    binary = raw[28+length:]
    digest = hashlib.sha256(raw).hexdigest()
    assert digest == entry['lods'][0]['sha256']
    assert len(doc['meshes']) == 5
    nodes = []
    for node in doc['nodes']:
        spec = {k: node[k] for k in ('children','mesh','matrix','translation','rotation','scale') if k in node}
        spec['id'] = node['extras']['three_node_id']
        spec['hidden'] = bool(node['extras'].get('candidate_hidden_source_geometry'))
        nodes.append(spec)
    result[str(seed)] = dict(sha256=digest, source=str(path.relative_to(ROOT)),
        nodes=nodes, meshes=doc['meshes'], accessors=doc['accessors'],
        bufferViews=doc['bufferViews'], binary=base64.b64encode(binary).decode(),
        sourceColors=[m['pbrMetallicRoughness']['baseColorFactor'] for m in doc['materials']])

out = ROOT / 'src/assets/saihojiPineData.js'
out.write_text('// Generated by tools/pipeline/export_saihoji_pines_web.py; actual GLB buffers.\nexport default '+json.dumps(result,separators=(',', ':'))+';\n')
print(json.dumps({'seeds':len(result),'bytes':out.stat().st_size,'sourcesUnchanged':True}))
