"""Replay Claude's seeded source, separating its existing merged house lots.

Runs only in an isolated background Blender. Does not modify the source blend.
"""
import ast, json, sys
from pathlib import Path
import bpy, bmesh
from mathutils.kdtree import KDTree

ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / 'artifacts/pipeline/citadel-battle-blender/scripts'
OUT = ROOT / 'artifacts/citadel-claude-import'
OUT.mkdir(exist_ok=True)
sys.path.insert(0, str(SOURCE))
from citadel_lib import P, EMIT

tree = ast.parse((SOURCE / 'build_citadel_battle.py').read_text())
# Omit the final main(): no source overwrite, lighting, rendering or scene export.
tree.body = tree.body[:-1]
env = {'__file__': str(SOURCE / 'build_citadel_battle.py')}
exec(compile(tree, 'claude-source', 'exec'), env)
env['terrain']()  # Preserve the original random sequence preceding old_city().
old = next(n for n in tree.body if isinstance(n, ast.FunctionDef) and n.name == 'old_city')
lot_loop = next(n for n in old.body if isinstance(n, ast.For) and isinstance(n.target, ast.Tuple))
lot_loop.body.insert(0, ast.parse("p = Parts('House')").body[0])
lot_loop.body.extend(ast.parse("captured.append((p, (x,y,base,w,d,h)))").body)
old.body = old.body[:old.body.index(lot_loop) + 1]
env['captured'] = []
exec(compile(ast.fix_missing_locations(ast.Module(body=[old], type_ignores=[])), 'split-houses', 'exec'), env)
env['old_city']()

# Check the reconstructed lot vertices against the actual saved Blender geometry.
saved = ROOT / 'artifacts/pipeline/citadel-battle-blender/citadel-battle-v1.blend'
bpy.ops.wm.open_mainfile(filepath=str(saved))
original = {tuple(round(float(v), 4) for v in vert.co)
            for ob in bpy.data.objects if ob.type == 'MESH' and ob.name.startswith('OldCity_')
            for vert in ob.data.vertices}
lookup = KDTree(len(original))
for i, point in enumerate(original):
    lookup.insert(point, i)
lookup.balance()
result = []
matched = checked = 0
for index, (parts, lot) in enumerate(env['captured'][:12]):
    x,y,base,w,d,h = lot
    row = {'sourceLot': index, 'size': [w,h,d], 'parts': {}}
    for key, (vertices, faces) in parts.buf.items():
        for v in vertices:
            checked += 1
            matched += lookup.find(v)[2] < .00015
        mesh = bpy.data.meshes.new('export-house')
        mesh.from_pydata(vertices, [], faces)
        # Source boxes have inward winding, hidden by Blender's two-sided render.
        # Correct connected solids before Three.js back-face culling/shadows.
        bm = bmesh.new()
        bm.from_mesh(mesh)
        bmesh.ops.recalc_face_normals(bm, faces=list(bm.faces))
        bm.to_mesh(mesh)
        bm.free()
        mesh.update()
        mesh.calc_loop_triangles()
        pos, normals = [], []
        for tri in mesh.loop_triangles:
            for vi in tri.vertices:
                v = mesh.vertices[vi].co
                pos.extend(round(c,6) for c in (v.x-x, v.z-base, -(v.y-y)))
                n = tri.normal
                normals.extend(round(c,6) for c in (n.x,n.z,-n.y))
        row['parts'][key] = {'positions':pos, 'normals':normals}
        bpy.data.meshes.remove(mesh)
    result.append(row)
assert checked and matched == checked, f'Source blend mismatch: {matched}/{checked}'
payload = {'source':'citadel-battle-v1.blend / OldCity (v2 content)',
           'palette':P, 'emission':EMIT, 'houses':result}
(ROOT/'src/assets/claudeCitadelHousesData.js').write_text(
    '// Generated by export_claude_houses.py; original source remains untouched.\nexport default '
    + json.dumps(payload,separators=(',',':')) + ';\n')
report={'houses':len(result),'matchedSourceVertices':matched,'checkedSourceVertices':checked,
        'normalRepair':'Outward connected-solid winding; original vertex positions unchanged',
        'coordinateConversion':'Blender (x,y,z) to Three (x,z,-y); individual ground-centered lots',
        'excluded':['Terrain','Water','Troops','Ships','Keep','GrandStair']}
(OUT/'export-report.json').write_text(json.dumps(report,indent=2))
print(json.dumps(report))
