import {chromium} from '../../../tools/shot/node_modules/playwright/index.mjs';
import {mkdir,writeFile} from 'node:fs/promises';
const out='TigerMessenger/assets/models/optimized/highland-gate',reportDir='TigerMessenger/artifacts/pipeline/highland-gate-thirty-rounds';await mkdir(out,{recursive:true});
const b=await chromium.launch({channel:'chrome',headless:true,args:['--use-angle=metal']});
try{const p=await b.newPage({viewport:{width:1500,height:1000}});const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://localhost:8931/TigerMessenger/?autostart=1&highlandReview=1',{waitUntil:'domcontentloaded'});await p.waitForFunction(()=>window.__tm?.scene.getObjectByName('highland-gate'),null,{timeout:240000});await p.waitForTimeout(2000);await p.screenshot({path:`${reportDir}/r30-gameplay.png`});
const result=await p.evaluate(async()=>{const t=window.__tm,T=t.THREE,g=t.scene.getObjectByName('highland-gate'),sys=t.messenger.landmarks.tramSystem;t.scene.updateMatrixWorld(true);t.distanceCulling?.recollect();
 const {exportWorldGLB}=await import('/TigerMessenger/tools/world/export_world_glb.js');const sc=new T.Scene();let nonfinite=0;g.traverse(o=>{if(!o.isMesh)return;const p=o.geometry.attributes.position;for(const value of p.array)if(!Number.isFinite(value))nonfinite++;const mesh=new T.Mesh(o.geometry,o.material);mesh.name=o.name;mesh.matrixAutoUpdate=false;mesh.matrix.copy(g.matrixWorld).invert().multiply(o.matrixWorld);sc.add(mesh);});if(nonfinite)throw Error('Nonfinite gate geometry');const exported=exportWorldGLB(sc,T,{});let binary='';for(let i=0;i<exported.bytes.length;i+=8192)binary+=String.fromCharCode(...exported.bytes.subarray(i,i+8192));
 const transit={red:{samples:0,minZ:Infinity,maxZ:-Infinity},blue:{samples:0,minZ:Infinity,maxZ:-Infinity}};const speed=t.P.tramSpeed,length=Math.max(...Object.values(sys.curves).map(c=>c.getLength())),dt=.5/Math.max(.01,speed),steps=Math.ceil(length/.5)+20;
 for(let i=0;i<steps;i++){sys.update(dt);for(const [key,tram]of[['red',sys.redTram],['blue',sys.blueTram]]){const local=g.worldToLocal(tram.position.clone());if(Math.abs(local.x)<8&&Math.abs(local.z)<24&&Math.abs(local.y)<8){const r=transit[key];r.samples++;r.minZ=Math.min(r.minZ,local.z);r.maxZ=Math.max(r.maxZ,local.z);}}}
 const player=t.player?{position:t.player.position.toArray(),support:g.userData.sampleGroundRadius(t.player.position)}:null;
 return {base64:btoa(binary),manifest:exported.manifest,nonfinite,transit,player,merge:g.userData.decorMerge,transform:{position:g.position.toArray(),quaternion:g.quaternion.toArray()}};});
await writeFile(`${out}/highland-gate-r30.glb`,Buffer.from(result.base64,'base64'));delete result.base64;result.errors=errors;await writeFile(`${reportDir}/r30-export-transit.json`,JSON.stringify(result,null,2));console.log(JSON.stringify(result));}finally{await b.close();}
