// Preserve the original town layout, export only the WFC shared-edge town layers.
import {chromium} from '../../../tools/shot/node_modules/playwright/index.mjs';
import {mkdir,writeFile,open} from 'node:fs/promises';
const out='TigerMessenger/artifacts/pipeline/castle-world-v1';await mkdir(out,{recursive:true});
const browser=await chromium.launch({channel:'chrome',headless:true,args:['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
try{
 const page=await browser.newPage();await page.route('**/castle-export-fixture.html',r=>r.fulfill({contentType:'text/html',body:'<script type="importmap">{"imports":{"three":"/TigerMessenger/vendor/three.module.js","three/addons/":"/TigerMessenger/vendor/jsm/"}}</script>'}));
 await page.goto('http://127.0.0.1:8767/TigerMessenger/castle-export-fixture.html');
 const report=await page.evaluate(async()=>{
  const T=await import('three'),M=await import('/TigerMessenger/src/world/odysseyCitadel.js'),{HIGHLAND_TOWNSCAPER_TOWN_SPEC:spec}=await import('/TigerMessenger/src/world/citadelTown.js');
  const {exportWorldGLB}=await import('/TigerMessenger/tools/world/export_world_glb.js');
  const build=topology=>{let state=20260908;const prev=Math.random;Math.random=()=>{state=(Math.imul(state,1664525)+1013904223)>>>0;return state/4294967296;};try{return M.buildOdysseyCitadel({spec:structuredClone(spec),seed:20260808,wfcTownV1:topology!==false,wfcTopology:typeof topology==='string'?topology:undefined,wfcSeed:37,latestDesign:true});}finally{Math.random=prev;}};
  const original=build(false),legacy=build(undefined),candidate=build("legacy-faces");
  const fingerprint=root=>{root.updateMatrixWorld(true);const inverse=root.matrixWorld.clone().invert(),v=new T.Vector3(),tri=[];for(const layer of root.userData.layers)layer.traverse(o=>{if(!o.isMesh||o.userData.isOutline||!o.visible)return;const p=o.geometry.attributes.position,ix=o.geometry.index;if(!p)return;const matrix=new T.Matrix4().multiplyMatrices(inverse,o.matrixWorld);for(let i=0,n=ix?.count??p.count;i<n;i+=3){let points=[];for(let k=0;k<3;k++){v.fromBufferAttribute(p,ix?ix.getX(i+k):i+k).applyMatrix4(matrix);points.push([v.x,v.y,v.z].map(a=>Math.round(a*1e4)).join(','));}tri.push([points.join(';'),[points[1],points[2],points[0]].join(';'),[points[2],points[0],points[1]].join(';')].sort()[0]);}});return tri.sort();};
  const a=fingerprint(original),oldWfc=fingerprint(legacy),b=fingerprint(candidate),same=JSON.stringify(a)===JSON.stringify(b);
  const graphParity=JSON.stringify(oldWfc)===JSON.stringify(b),layoutParity=JSON.stringify(original.userData.townSpec)===JSON.stringify(candidate.userData.townSpec);
  if(!graphParity||!layoutParity)throw Error("Shared-edge graph changed original town layout or WFC legacy-graph geometry");
  const geometryRoot=new T.Group();geometryRoot.name='castle-shared-edge-town-candidate';candidate.updateMatrixWorld(true);const inv=candidate.matrixWorld.clone().invert();let layerNames=[];
  for(const layer of [...candidate.userData.layers]){layerNames.push(layer.name);const local=new T.Matrix4().multiplyMatrices(inv,layer.matrixWorld);geometryRoot.add(layer);local.decompose(layer.position,layer.quaternion,layer.scale);layer.updateMatrix();}
  const converted=new Set(),textureReport=[];
  geometryRoot.traverse(o=>{for(const m of (Array.isArray(o.material)?o.material:[o.material]).filter(Boolean)){const t=m.map;if(!t?.isDataTexture||converted.has(t))continue;const {data,width,height}=t.image;if(!(data instanceof Uint8Array)||data.length!==width*height*4)throw Error('Unsupported castle data texture');const canvas=document.createElement('canvas');canvas.width=width;canvas.height=height;const context=canvas.getContext('2d'),rgba=new Uint8ClampedArray(data),color=new T.Color();if(t.colorSpace===T.NoColorSpace){for(let i=0;i<rgba.length;i+=4){color.setRGB(data[i]/255,data[i+1]/255,data[i+2]/255).convertLinearToSRGB();rgba[i]=Math.round(color.r*255);rgba[i+1]=Math.round(color.g*255);rgba[i+2]=Math.round(color.b*255);}}context.putImageData(new ImageData(rgba,width,height),0,0);textureReport.push({name:t.name,width,height,repeat:t.repeat.toArray(),offset:t.offset.toArray(),sourceColorSpace:t.colorSpace,pngEncoding:'sRGB; explicit linear-to-sRGB conversion for source NoColorSpace'});t.image=canvas;converted.add(t);}});
  const scene=new T.Scene();scene.add(geometryRoot);const result=exportWorldGLB(scene,T,{});window.__castleBytes=result.bytes;
  return {factory:'buildOdysseyCitadel',sourceModule:'src/world/odysseyCitadel.js',spec:'HIGHLAND_TOWNSCAPER_TOWN_SPEC',seed:20260808,wfcSeed:37,topology:'legacy-faces',wfc:candidate.userData.townStats.wfcTown,originalDefaultTownGeometryMatches:same,defaultTriangles:a.length,wfcOldGraphGeometryMatches:graphParity,originalTownLayoutMatches:layoutParity,triangles:b.length,layerNames,textureReport,export:result.manifest,scope:'Town mesh layers only; original terrain, global transform, bridges/props outside these layers retained by runtime adapter; no Godot WFC editing or collision migration.'};
 });
 const target='TigerMessenger/godot/assets/art-pilots/castle-shared-edge-town-v1.glb';const f=await open(target,'w');try{for(let start=0;start<report.export.bytes;start+=1048576){const data=await page.evaluate(start=>{const chunk=window.__castleBytes.subarray(start,start+1048576);let str='';for(let i=0;i<chunk.length;i+=8192)str+=String.fromCharCode(...chunk.subarray(i,i+8192));return btoa(str);},start);await f.write(Buffer.from(data,'base64'));}}finally{await f.close();}
 await writeFile(out+'/export-report.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({target,triangles:report.triangles,wfc:report.wfc,bytes:report.export.bytes,layers:report.layerNames}));
}finally{await browser.close();}
