import {chromium} from '../../../tools/shot/node_modules/playwright/index.mjs';import {writeFile,mkdir} from 'node:fs/promises';const out=new URL('../../artifacts/pipeline/citadel-elevation-candidates/',import.meta.url);await mkdir(out,{recursive:true});const b=await chromium.launch({channel:'chrome',headless:true,args:['--use-angle=metal']});try{for(const phase of ['current','lower-6','lower-10']){const p=await b.newPage({viewport:{width:1200,height:800}});await p.addInitScript(()=>{const raf=requestAnimationFrame.bind(window);window.requestAnimationFrame=cb=>cb.name==='animate'?0:raf(cb);});if(phase==='before')await p.route('**/frontStrataBlender.js*',r=>r.fulfill({contentType:'application/javascript',body:'export function applyFrontStrataBlender(){}'}));await p.goto('http://localhost:8931/TigerMessenger/?autostart=1',{timeout:180000});await p.waitForFunction(()=>window.__tm?.messenger,null,{timeout:180000});for(const [name,eye,look] of [['front-overview',[-35,55,170],[8,3,70]]]){const result=await p.evaluate(({eye,look,phase})=>{const t=window.__tm,T=t.THREE,c=t.scene.getObjectByName('castleContainer');const city=c.getObjectByName('highland-west-city'),depth=phase==='lower-10'?10:phase==='lower-6'?6:0;
 if(depth){
 const amount=z=>depth*T.MathUtils.smoothstep(z,35,65);
 const terrainNames=new Set(['citadel-oskar-grid-mountain-surface','backlit-highlight-citadel-oskar-grid-mountain-surface','citadel-coastal-cliff-seal']);
 const meshes=[];city.traverse(o=>{if(o.isMesh&&!o.name.includes('harbor')&&!o.name.includes('water')&&!o.name.includes('boarding'))meshes.push({o,terrain:false});});c.traverse(o=>{if(o.isMesh&&terrainNames.has(o.name))meshes.push({o,terrain:true});});
 for(const {o,terrain} of meshes){const g=o.geometry.clone(),a=g.attributes.position,frame=city.matrixWorld.clone().invert().multiply(o.matrixWorld),inverse=frame.clone().invert();for(let i=0;i<a.count;i++){const p=new T.Vector3().fromBufferAttribute(a,i).applyMatrix4(frame);const side=terrain?T.MathUtils.smoothstep(p.x,36,48)*(1-T.MathUtils.smoothstep(p.x,90,106)):1;p.y-=amount(p.z)*side;p.applyMatrix4(inverse);a.setXYZ(i,p.x,p.y,p.z);}a.needsUpdate=true;g.computeVertexNormals();g.computeBoundingBox();g.computeBoundingSphere();o.geometry=g;}
 const horse=t.scene.getObjectByName('citadel-trojan-horse');if(horse){const p=city.worldToLocal(horse.getWorldPosition(new T.Vector3()));p.y-=amount(p.z);horse.position.copy(horse.parent.worldToLocal(city.localToWorld(p)));}
 city.traverse(o=>{if(o.isLight){const p=city.worldToLocal(o.getWorldPosition(new T.Vector3()));p.y-=amount(p.z);o.position.copy(o.parent.worldToLocal(city.localToWorld(p)));}});
 c.updateWorldMatrix(true,true);
 }
 t.camera.position.copy(c.localToWorld(new T.Vector3(...eye)));t.camera.up.set(0,1,0).transformDirection(c.matrixWorld);t.camera.lookAt(c.localToWorld(new T.Vector3(...look)));t.camera.fov=55;t.camera.updateProjectionMatrix();t.renderer.render(t.scene,t.camera);return t.renderer.domElement.toDataURL('image/png');},{eye,look,phase});await writeFile(new URL(phase+'-'+name+'.png',out),Buffer.from(result.split(',')[1],'base64'));}await p.close();}}finally{await b.close();}
