import {chromium} from '../../../tools/shot/node_modules/playwright/index.mjs';import {writeFile,mkdir} from 'node:fs/promises';const out=new URL('../../artifacts/pipeline/citadel-radial-candidate/',import.meta.url);await mkdir(out,{recursive:true});const b=await chromium.launch({channel:'chrome',headless:true,args:['--use-angle=metal']});try{for(const phase of ['current','radial']){const p=await b.newPage({viewport:{width:1200,height:800}});await p.addInitScript(()=>{const raf=requestAnimationFrame.bind(window);window.requestAnimationFrame=cb=>cb.name==='animate'?0:raf(cb);});if(phase==='before')await p.route('**/frontStrataBlender.js*',r=>r.fulfill({contentType:'application/javascript',body:'export function applyFrontStrataBlender(){}'}));await p.goto('http://localhost:8931/TigerMessenger/?autostart=1',{timeout:180000});await p.waitForFunction(()=>window.__tm?.messenger,null,{timeout:180000});for(const [name,eye,look] of [['front-overview',[-35,55,170],[8,3,70]]]){const result=await p.evaluate(async({eye,look,phase})=>{const t=window.__tm,T=t.THREE,c=t.scene.getObjectByName('castleContainer');const city=c.getObjectByName('highland-west-city');
if(phase==='radial'){
 const oldCityWorld=city.matrixWorld.clone(),oldCityInverse=oldCityWorld.clone().invert(),plaza=city.localToWorld(new T.Vector3(60,4,71.5)),normal=plaza.clone().normalize();
 const {officialOceanLevelAt}=await import('/TigerMessenger/src/world/waterV8/officialOcean.js');
 const desired=normal.clone().multiplyScalar(160+officialOceanLevelAt(plaza)+6);
 const up=new T.Vector3(0,1,0).transformDirection(oldCityWorld),q=new T.Quaternion().setFromUnitVectors(up,normal);
 const delta=new T.Matrix4().makeTranslation(...desired.toArray()).multiply(new T.Matrix4().makeRotationFromQuaternion(q)).multiply(new T.Matrix4().makeTranslation(...plaza.clone().negate().toArray()));
 const adjusted=new T.Matrix4().copy(city.parent.matrixWorld).invert().multiply(delta).multiply(oldCityWorld);adjusted.decompose(city.position,city.quaternion,city.scale);
 const horse=t.scene.getObjectByName('citadel-trojan-horse');if(horse){const mat=horse.parent.matrixWorld.clone().invert().multiply(delta).multiply(horse.matrixWorld);mat.decompose(horse.position,horse.quaternion,horse.scale);}
 const names=new Set(['citadel-oskar-grid-mountain-surface','backlit-highlight-citadel-oskar-grid-mountain-surface','citadel-coastal-cliff-seal']);
 c.traverse(o=>{if(!o.isMesh||!names.has(o.name))return;const g=o.geometry.clone(),a=g.attributes.position,inv=o.matrixWorld.clone().invert();for(let i=0;i<a.count;i++){const w=new T.Vector3().fromBufferAttribute(a,i).applyMatrix4(o.matrixWorld),p=w.clone().applyMatrix4(oldCityInverse);const blend=T.MathUtils.smoothstep(p.x,32,48)*(1-T.MathUtils.smoothstep(p.x,90,108))*T.MathUtils.smoothstep(p.z,-25,-10);w.lerp(w.clone().applyMatrix4(delta),blend).applyMatrix4(inv);a.setXYZ(i,w.x,w.y,w.z);}a.needsUpdate=true;g.computeVertexNormals();g.computeBoundingBox();g.computeBoundingSphere();o.geometry=g;});
 c.updateWorldMatrix(true,true);
}
t.camera.position.copy(c.localToWorld(new T.Vector3(...eye)));t.camera.up.set(0,1,0).transformDirection(c.matrixWorld);t.camera.lookAt(c.localToWorld(new T.Vector3(...look)));t.camera.fov=55;t.camera.updateProjectionMatrix();t.renderer.render(t.scene,t.camera);return t.renderer.domElement.toDataURL('image/png');},{eye,look,phase});await writeFile(new URL(phase+'-'+name+'.png',out),Buffer.from(result.split(',')[1],'base64'));}await p.close();}}finally{await b.close();}
