import * as T from 'three';import fs from 'node:fs';
import {actualUserMarkedStructureFixture} from '../../tests/world/targetUserMarkedStructure.fixture.mjs';
import {createTargetUserMarkedProductionRelease} from '../../src/world/citadel/targetUserMarkedProductionRelease.js';
import {createTargetEastCliffProductionRelease} from '../../src/world/citadel/targetEastCliffProductionRelease.js';
import {createTargetCliffRailGallery} from '../../src/world/citadel/targetCliffRailGallery.js';
import {buildMountainSurfaceIndex} from '../../src/world/citadel/mountainSurfaceIndex.js';
const ROOT=new URL('../../',import.meta.url),read=p=>JSON.parse(fs.readFileSync(new URL(p,ROOT))),f=actualUserMarkedStructureFixture(),base='artifacts/pipeline/citadel-east-shore-route-20261006/',artifact=read(base+'remesh-final-surface-geometry.json'),audit=read(base+'remesh-expanded-shift-audit.json'),retainedRelease=createTargetUserMarkedProductionRelease({sourceCurves:f.sourceCurves}),prepared=createTargetEastCliffProductionRelease({enabled:true,sourceCurves:f.sourceCurves,retainedRelease,candidateInput:audit.candidateInput,terrainArtifact:artifact,cityGalleryScope:true});
const matrix=f.castle.matrixWorld.clone(),inverse=matrix.clone().invert(),down=new T.Vector3(0,-1,0).transformDirection(matrix),geometry=new T.BufferGeometryLoader().parse(artifact.geometry),material=new T.MeshBasicMaterial({side:T.DoubleSide}),terrain=new T.Mesh(geometry,material);terrain.position.fromArray(artifact.origin);terrain.name='actual-final-refined-artifact-cpu';f.castle.add(terrain);f.scene.updateMatrixWorld(true);
const index=buildMountainSurfaceIndex([terrain,f.scene.getObjectByName('planet-surface')]),sea=buildMountainSurfaceIndex([f.ocean]),sample=idx=>(x,z)=>{const hit=idx.sample(new T.Ray(new T.Vector3(x,250,z).applyMatrix4(matrix),down),0,900);return hit?hit.point.clone().applyMatrix4(inverse).y:null;},sampleTerrain=sample(index),sampleSea=sample(sea),curve=prepared.release.segments.center.newShore;
const trials=[],sections=[];
try{
 for(const config of[{id:'baseline',pierWidth:1.2,maxSpan:18},{id:'narrow-105',pierWidth:1.05,maxSpan:18},{id:'narrow-090',pierWidth:.9,maxSpan:18},{id:'eleven-spans',pierWidth:1.2,maxSpan:16}]){
  const a=createTargetCliffRailGallery({worldCurve:curve,castleMatrix:matrix,sampleTerrain,sampleSea,walkwayHeight:6.9,walkwayWidth:4.4,laneSpacing:4.1,vehicleEnvelope:{halfWidth:1.75,halfLength:3.49,top:5.36,topMargin:.35},sideRibThickness:.6,sampleStep:.75,...config});
  const r=a.report,failures=r.foundations.filter(p=>!p.seated).map(p=>({...p,localCenter:new T.Vector3(...p.centerWorld).applyMatrix4(inverse).toArray(),samples:p.footingSamples.map(s=>s?{...s,local:new T.Vector3(...s.world).applyMatrix4(inverse).toArray(),actualTerrainY:sampleTerrain(...[0,2].map(k=>new T.Vector3(...s.world).applyMatrix4(inverse).toArray()[k]))}:null)}));
  trials.push({config,length:r.length,foundationCount:r.foundations.length,foundationPass:r.foundationSampledPass,failures,terrainClearance:r.terrainClearance,vehicleClearance:r.vehicleClearance,performance:r.performance,issues:r.issues});
  if(config.id==='baseline')for(const f0 of failures){const center=new T.Vector3(...f0.centerWorld).applyMatrix4(inverse),bad=f0.samples.find(s=>s?.terrainAboveDeck);if(!bad)continue;const b=new T.Vector3(...bad.local),d=b.clone().sub(center),len=Math.hypot(d.x,d.z),rows=[];
   for(let i=0;i<=100;i++){const t=-1.5+3*i/100,q=center.clone().addScaledVector(d,t),y=sampleTerrain(q.x,q.z);rows.push({distance:t*len,x:q.x,z:q.z,deckPlaneY:q.y,terrainY:y,gap:y===null?null:q.y-y});}sections.push({station:f0.station,side:f0.side,center:center.toArray(),badCorner:bad.local,cornerTerrainY:bad.actualTerrainY,cornerIntrusion:bad.actualTerrainY-bad.local[1],rows});
  }
  a.dispose();
 }
 const result={version:'east-final-pier-probe-1',installed:false,accepted:false,artifact:'remesh-final-surface-geometry.json',sourceFrame:artifact.origin,sourceHash:artifact.sourceHash,rawTopology:artifact.provenance.rawCandidate,finalRefinement:artifact.provenance.finalCandidate,curveVersion:prepared.release.version,scope:'Final artifact geometry footing queries and actually rebuilt gallery candidates only. Gallery own vehicle audit uses parallel guide sections, NOT full red/blue release, so promising variants need the full structure replay.',globalApproachSupportBuilt:false,trials,sections};
 fs.writeFileSync(new URL('artifacts/pipeline/citadel-east-structure-audit-20261006/final-pier-probe.json',ROOT),JSON.stringify(result,null,2));console.log(JSON.stringify({trials:trials.map(t=>({config:t.config,foundations:t.foundationCount,pass:t.foundationPass,failures:t.failures.map(f=>({station:f.station,side:f.side,local:f.localCenter})),terrain:t.terrainClearance.pass,vehicle:t.vehicleClearance.pass,performance:t.performance})),sections:sections.map(({rows,...s})=>s)},null,2));
}finally{terrain.removeFromParent();geometry.dispose();material.dispose();f.dispose();}
