import {chromium} from '../../../tools/shot/node_modules/playwright/index.mjs';
import {writeFile} from 'node:fs/promises';
const b=await chromium.launch({channel:'chrome',headless:true,args:['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
try{const p=await b.newPage();await p.addInitScript(()=>{const raf=requestAnimationFrame.bind(window);window.requestAnimationFrame=cb=>cb.name==='animate'?0:raf(cb);});await p.goto('http://localhost:8931/TigerMessenger/',{waitUntil:'domcontentloaded'});await p.waitForFunction(()=>!!window.__tm?.messenger,null,{timeout:180000});
 const r=await p.evaluate(async()=>{
 const {scene,THREE:T}=window.__tm;
 const {createWarshipWaterRoutes}=await import('/TigerMessenger/src/world/warshipWaterRoutes.js');
 const {createFisherBoat,updateWarshipOars}=await import('/TigerMessenger/src/assets/harbor.js');
 const {placeWarshipOnSphere}=await import('/TigerMessenger/src/world/warshipNavigation.js');
 const nav=createWarshipWaterRoutes(scene,160),hub=scene.getObjectByName('leviathanGroup').position.clone().normalize(),east=new T.Vector3(0,1,0).cross(hub).normalize();
 const land=hub.clone().addScaledVector(east,.11).normalize(),n=land.clone().cross(east).normalize();
 const rings=[0,24,40,64].map(radius=>{const samples=Array.from({length:radius?32:1},(_,i)=>{const d=land.clone().multiplyScalar(160).addScaledVector(east,radius*Math.cos(i*Math.PI/16)).addScaledVector(n,radius*Math.sin(i*Math.PI/16)).normalize(),s=nav.surface(d);return {bearing:i*360/32,direction:d.toArray(),...s,bedDepth:s?.water-s?.seabed,effectiveDepth:s?.water-Math.max(s?.ground,s?.seabed)};});return {radius,samples,minBedDepth:Math.min(...samples.map(s=>s.bedDepth)),maxBedDepth:Math.max(...samples.map(s=>s.bedDepth)),sufficientCenterDepth:samples.filter(s=>s.effectiveDepth>=1.5).length};});
 const boat=createFisherBoat();boat.scale.setScalar(1.7);const junction=scene.getObjectByName('canal-junction-box').userData.up.clone().normalize();placeWarshipOnSphere(boat,land,160.18,land.clone().sub(junction));updateWarshipOars(boat,1/60,true);boat.updateMatrixWorld(true);
 const minima=[];let vertices=0;boat.traverse(o=>{if(!o.isMesh||!o.geometry.attributes.position||o.userData.isOutline)return;let visible=true;for(let a=o;a;a=a.parent)if(!a.visible)visible=false;if(!visible)return;const attr=o.geometry.attributes.position,v=new T.Vector3();let min=Infinity,point=null;let instanceIndex=null;for(let inst=0;inst<(o.isInstancedMesh?o.count:1);inst++){const matrix=o.matrixWorld.clone();if(o.isInstancedMesh){const local=new T.Matrix4();o.getMatrixAt(inst,local);if(Math.abs(local.determinant())<1e-12)continue;matrix.multiply(local);}for(let i=0;i<attr.count;i++){v.fromBufferAttribute(attr,i).applyMatrix4(matrix);vertices++;if(v.length()<min){min=v.length();point=v.clone();instanceIndex=inst;}}}if(point){const s=nav.surface(point);minima.push({name:o.name,isInstancedMesh:!!o.isInstancedMesh,instanceIndex,parent:o.parent?.name,minimumRadius:min,point:point.toArray(),water:s.water,seabed:s.seabed,ground:s.ground,groundObject:s.object,belowBed:s.seabed-min,belowWater:s.water-min});}});minima.sort((a,b)=>a.minimumRadius-b.minimumRadius);
 const planet=scene.getObjectByName('planet-surface');return {scope:'Read-only authored scene. 32 bearings per radius; not exhaustive harbor search. Boat is detached production V11 model using exact legacy landing placement (radius160.18, scale1.7, last-leg heading), no live actor or vessel moved. Per-instance transforms and one production rowing update applied; minimum vertices of each visible batch sampled against actual bed; no collision tolerance weakened.',rings,ship:{vertices,poseSource:'production legacy landDir endpoint',position:boat.position.toArray(),quaternion:boat.quaternion.toArray(),lowestComponents:minima.slice(0,12),componentsBelowBed:minima.filter(m=>m.belowBed>0).length},bed:{name:planet.name,visible:planet.visible,worldMatrix:planet.matrixWorld.toArray()},stats:nav.stats};
 });await writeFile('TigerMessenger/artifacts/pipeline/saihoji-evacuation-boarding/depth-audit.json',JSON.stringify(r,null,2));console.log(JSON.stringify({rings:r.rings.map(({samples,...v})=>v),ship:r.ship}));
}finally{await b.close();}
