// Pick objects under given pixels from the old-town "side" camera (1400x900).
import {chromium} from '../../../tools/shot/node_modules/playwright/index.mjs';
const pts=JSON.parse(process.argv[2]||'[[405,445]]');
const b=await chromium.launch({channel:'chrome',headless:true,args:['--use-angle=metal']});
try{const p=await b.newPage({viewport:{width:1400,height:900}});await p.goto('http://localhost:8931/TigerMessenger/?autostart=1',{waitUntil:'domcontentloaded'});
await p.waitForFunction(()=>window.__tm?.scene.getObjectByName('highland-west-city'),null,{timeout:240000});await p.waitForTimeout(2000);
const r=await p.evaluate(([pts,process_cam])=>{const t=window.__tm,T=t.THREE;let c;t.scene.traverse(o=>{if(o.userData.highlandAssaultAnchors)c=o;});t.cameraRig.update=()=>{};
const L=v=>c.localToWorld(new T.Vector3(...v));t.camera.aspect=1400/900;const cam=(process_cam==='roofs')?[[-38,14,26],[-52,9,2]]:[[-5,24,40],[-50,8,4]];t.camera.position.copy(L(cam[0]));t.camera.up.set(0,1,0).transformDirection(c.matrixWorld);t.camera.lookAt(L(cam[1]));t.camera.fov=50;t.camera.updateProjectionMatrix();t.camera.updateMatrixWorld(true);
const ray=new T.Raycaster();ray.layers.enableAll();return pts.map(([x,y])=>{ray.setFromCamera(new T.Vector2(x/1400*2-1,-(y/900*2-1)),t.camera);const vis=o=>{while(o){if(!o.visible)return false;o=o.parent;}return true;};const h=ray.intersectObjects(t.scene.children,true).filter(h=>vis(h.object))[0];if(!h)return null;const o=h.object;const m=Array.isArray(o.material)?o.material[h.face?.materialIndex||0]:o.material;
const vc=o.geometry.attributes.color;let vcol=null;if(vc&&h.face){vcol=[vc.getX(h.face.a),vc.getY(h.face.a),vc.getZ(h.face.a)].map(v=>+v.toFixed(2));}
const chain=[];let a=o;while(a&&chain.length<5){chain.push(a.name||'('+a.type+')');a=a.parent;}
const mp=m?.map;let mapURL=null;try{const im=mp?.image;if(im){const cv=document.createElement('canvas');cv.width=im.width;cv.height=im.height;cv.getContext('2d').drawImage(im,0,0);mapURL=cv.toDataURL();}}catch(e){mapURL='ERR '+e.message;}const uvA=h.uv?[+h.uv.x.toFixed(3),+h.uv.y.toFixed(3)]:null;const ud=m?.userData||{};return {mapURL,uvA,matUuid:m?.uuid,sem:ud.semanticToken,obc:!!m?.onBeforeCompile&&m.onBeforeCompile.toString().slice(0,160),mapType:mp?.constructor?.name,img:mp?.image?.constructor?.name,imgW:mp?.image?.width,src:(mp?.image?.src||mp?.image?.currentSrc||"").slice(-60),isCanvasTex:!!mp?.isCanvasTexture,chain,type:m?.type,color:m?.color?'#'+m.color.getHexString():null,map:!!m?.map,vcol,outline:!!o.userData.isOutline,holy:!!o.geometry.userData.holyOldTown};});},[pts,process.argv[3]||'side']);
const fs=await import('node:fs');r.forEach((x,i)=>{if(x?.mapURL&&x.mapURL.startsWith('data:'))fs.writeFileSync(`TigerMessenger/artifacts/pipeline/old-town-platform/textures/pick-${i}.png`,Buffer.from(x.mapURL.split(',')[1],'base64'));if(x)delete x.mapURL;});console.log(JSON.stringify(r,null,1));}finally{await b.close();}
