import * as T from 'three';import {readFileSync,writeFileSync} from 'node:fs';import {buildHighlandCitadelContinuousTerrain} from '../../src/world/highlandCitadelDesign.js';import {bayWeight,bayRotation} from '../../src/world/citadel/bayLayoutMath.js';
const folder=new URL('../../artifacts/pipeline/citadel-five-hour-20261005/',import.meta.url),trace=JSON.parse(readFileSync(new URL('r15-overview-day-cloud-plants-rock-trace.json',folder))),frame=new T.Matrix4().fromArray(trace.castleMatrix),inv=frame.clone().invert(),g=buildHighlandCitadelContinuousTerrain().children[0].geometry,p=g.attributes.position;
const map=v=>{v=v.clone();v.x-=52;const w=bayWeight(v.x,v.z);v.applyMatrix4(frame).applyQuaternion(bayRotation(frame,160,w)).applyMatrix4(inv);if(w>0&&w<1){v.applyMatrix4(frame);v.setLength(Math.min(v.length(),157+90*Math.pow(Math.abs(2*w-1),3)));v.applyMatrix4(inv);}return v;};
const results=[];
for(const n of [1,2,4,8,16,32]){const tris=[];for(const f of [4536,4317,4097]){const [a,b,c]=[0,1,2].map(j=>new T.Vector3().fromBufferAttribute(p,g.index.getX(f*3+j)));const point=(u,v)=>map(a.clone().multiplyScalar(1-u-v).addScaledVector(b,u).addScaledVector(c,v));for(let r=0;r<n;r++)for(let q=0;q<n-r;q++){tris.push([point(q/n,r/n),point((q+1)/n,r/n),point(q/n,(r+1)/n)]);if(q+r<n-1)tris.push([point((q+1)/n,r/n),point((q+1)/n,(r+1)/n),point(q/n,(r+1)/n)]);}}
 const probeLayers=[];for(let x=-1;x<=3;x+=.25)for(let z=-18;z<=-13;z+=.25){const pr=new T.Ray(new T.Vector3(x,100,z),new T.Vector3(0,-1,0)),ph=new T.Vector3(),hs=[];for(const [a,b,c]of tris)if(pr.intersectTriangle(a,b,c,false,ph)&&!hs.some(y=>Math.abs(y-ph.y)<1e-5))hs.push(ph.y);if(hs.length>1)probeLayers.push({x,z,heights:hs.sort((a,b)=>b-a)});}
 const ray=new T.Ray(new T.Vector3(1.24673,100,-15.21581),new T.Vector3(0,-1,0)),hit=new T.Vector3(),heights=[];let positive=0,negative=0,minArea=Infinity;for(const [a,b,c]of tris){const normal=b.clone().sub(a).cross(c.clone().sub(a));if(normal.y>0)positive++;else negative++;minArea=Math.min(minArea,normal.length()/2);if(ray.intersectTriangle(a,b,c,false,hit))heights.push(hit.y);}
 results.push({n,multiLayerProbeCount:probeLayers.length,multiExamples:probeLayers.slice(0,4),triangles:tris.length,positiveXZ:positive,negativeXZ:negative,minArea,heights:heights.sort((a,b)=>b-a)});
}
writeFileSync(new URL('r15-bay-subdivision-probe.json',folder),JSON.stringify(results,null,2));console.log(JSON.stringify(results,null,2));
