"""Refine actual Web portal geometry in an isolated Blender process."""
import bpy, bmesh, json, math
from pathlib import Path
from mathutils import Vector
ROOT=Path(__file__).resolve().parents[2]
OUT=ROOT/'artifacts/citadel-reference-pass'
rows=json.loads((OUT/'portal-original.json').read_text())
bpy.ops.object.select_all(action='SELECT')
bpy.ops.object.delete(use_global=False)
result={}
for row in rows:
    values=row['positions']
    vertices=[(values[i],-values[i+2],values[i+1]) for i in range(0,len(values),3)]
    ids=row['indices'] or list(range(len(vertices)))
    faces=[ids[i:i+3] for i in range(0,len(ids),3)]
    data=bpy.data.meshes.new(row['name']);data.from_pydata(vertices,[],faces);data.update()
    bm=bmesh.new();bm.from_mesh(data)
    bmesh.ops.remove_doubles(bm,verts=list(bm.verts),dist=.00001)
    bmesh.ops.recalc_face_normals(bm,faces=list(bm.faces));bm.to_mesh(data);bm.free()
    ob=bpy.data.objects.new(row['name'],data);bpy.context.collection.objects.link(ob)
    x,y,z=row['position'];ob.location=(x,-z,y)
    material=bpy.data.materials.new(row['name']+' limestone');material.diffuse_color=(*row['color'],1)
    material.use_nodes=True;bsdf=material.node_tree.nodes.get('Principled BSDF');bsdf.inputs['Base Color'].default_value=(*row['color'],1);bsdf.inputs['Roughness'].default_value=.86;data.materials.append(material)
    bevel=ob.modifiers.new('Hand cut stone edge','BEVEL');bevel.width=.055 if 'wall' in row['name'] else .028;bevel.segments=2;bevel.limit_method='ANGLE'
    bpy.context.view_layer.objects.active=ob;ob.select_set(True);bpy.ops.object.modifier_apply(modifier=bevel.name);ob.select_set(False)
    data=ob.data;data.calc_loop_triangles()
    positions=[];normals=[]
    for tri in data.loop_triangles:
        for vi in tri.vertices:
            p=data.vertices[vi].co;n=tri.normal
            positions.extend([round(p.x,6),round(p.z,6),round(-p.y,6)])
            normals.extend([round(n.x,6),round(n.z,6),round(-n.y,6)])
    result[row['name']]={'positions':positions,'normals':normals,'triangles':len(data.loop_triangles)}
sc=bpy.context.scene;sc.render.engine='CYCLES';sc.cycles.samples=24
world=bpy.data.worlds.new('Blue hour') if not sc.world else sc.world;sc.world=world;world.use_nodes=True;world.node_tree.nodes['Background'].inputs[0].default_value=(.12,.22,.42,1);world.node_tree.nodes['Background'].inputs[1].default_value=.35
for name,loc,power,color,size in [('Warm portal',(0,-4,5),750,(1,.38,.08),5),('Cool fill',(-7,-8,14),1800,(.35,.55,1),8)]:
    d=bpy.data.lights.new(name,'AREA');d.energy=power;d.color=color;d.shape='DISK';d.size=size;o=bpy.data.objects.new(name,d);sc.collection.objects.link(o);o.location=loc;o.rotation_euler=(Vector((0,0,6))-o.location).to_track_quat('-Z','Y').to_euler()
d=bpy.data.cameras.new('Portal review');o=bpy.data.objects.new('Portal review',d);sc.collection.objects.link(o);o.location=(15,-28,16);o.rotation_euler=(Vector((0,0,6))-o.location).to_track_quat('-Z','Y').to_euler();sc.camera=o;d.lens=48
sc.render.resolution_x=1000;sc.render.resolution_y=1000;sc.render.resolution_percentage=100
sc['source']='Actual game portal-original.json';sc['scope']='Beveled stone portal; gameplay opening and coordinates preserved'
bpy.ops.wm.save_as_mainfile(filepath=str(OUT/'citadel-portal-refined.blend'))
target=ROOT/'src/assets/citadelPortalBlenderData.js'
target.write_text('// Generated by Blender from actual Web portal geometry.\nexport default '+json.dumps(result,separators=(',',':'))+';\n')
(OUT/'portal-blender-report.json').write_text(json.dumps({k:{'triangles':v['triangles']} for k,v in result.items()},indent=2))
sc.render.filepath=str(OUT/'portal-blender.png');bpy.ops.render.render(write_still=True)
print('PORTAL_REFINED',json.dumps({k:v['triangles'] for k,v in result.items()}))
