import fs from'node:fs';import * as T from'three';import{buildTargetCliffShoreBezier}from'../../src/world/citadel/targetCliffShoreRoute.js';import{createTargetNewCityRetreatField}from'../../src/world/citadel/targetNewCityRetreatField.js';import{createTargetRailCliffField}from'../../src/world/citadel/targetRailCliffField.js';import{targetTerrainHeight,TARGET_CITY_PLATFORMS}from'../../src/world/citadel/targetTerrainCandidate.js';import{createCastleOceanSampler}from'../../src/world/citadel/newCityRidgeCandidate.js';import{officialOceanLevelAt}from'../../src/world/waterV8/officialOcean.js';
const root=new URL('../../',import.meta.url),read=p=>JSON.parse(fs.readFileSync(new URL(p,root))),live=read('artifacts/pipeline/citadel-live-tram-clearance-20261006/global-tram-samples.json'),plan=read('artifacts/pipeline/citadel-cliff-transit-plan-20261006/sections.json').trials.at(-1),matrix=new T.Matrix4().fromArray(live.castleMatrix),sea=createCastleOceanSampler(matrix,160),retreat=createTargetNewCityRetreatField({platforms:TARGET_CITY_PLATFORMS}),rail=createTargetRailCliffField({...live,platforms:TARGET_CITY_PLATFORMS}),terrain=(x,z)=>{if(x< -143||x>143||z< -72||z>107)return null;const s=sea(x,z);return s===null?null:retreat.height(x,z,rail.height(x,z,targetTerrainHeight(x,z,s,{aprons:true,saddle:true,valleyBenches:true}),s),s);};

const summaries=[],best={};const start=live.lanes.red.samples[1684],end=live.lanes.red.samples[1991];
let seed=445;const rng=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;};
let current=read('artifacts/pipeline/citadel-cliff-shore-route-20261006/whole-route-refined-search.json').best.route.key;current.joins.pop();current.joins[2].local=[-30,45];
for(let trial=0;trial<1600;trial++){
 const key0=JSON.parse(JSON.stringify(current));const index=Math.floor(rng()*4),delta=(rng()-.5)*(trial<900?10:4);
 if(index===3)key0.handle=Math.max(8,key0.handle+delta);else {const j=key0.joins[index],choice=Math.floor(rng()*4);if(choice===0)j.local[0]+=delta;else if(choice===1)j.local[1]+=delta;else if(choice===2)j.direction[1]+=delta*.05;else j.handle=Math.max(8,j.handle+delta);}
 const {handle,joins}=key0,midZ=joins[2].local[1],westZ=0,frontZ=joins[0].local[1];
 const p=buildTargetCliffShoreBezier({castleMatrix:matrix,startWorld:start.world,endWorld:end.world,startTangent:start.tangent,endTangent:end.tangent,joins,handleLength:handle,sampleTerrain:terrain,sampleSea:sea,seaRadiusAt:p=>160+officialOceanLevelAt(p.normalize()),platforms:TARGET_CITY_PLATFORMS,bridgePath:[[30,0,frontZ-10],[-20,0,midZ]],bridgeHalfWidth:8,forbiddenPolygon:[[45,76],[49,69],[65,64],[81,67],[88,76],[83,87],[64,91],[49,87]]});const r=p.report;if(!r.samples)continue;
 const key={trial,handle,midZ,westZ,frontZ,joins};summaries.push({...key,R:r.minimumRadius,grade:r.maximumGrade,protected:r.protectedHits,cut:r.cuts.length,wet:r.wet,plaza:r.plaza,far:r.far});const score=(r.protectedHits+r.plaza)*1000+r.wet*1000+Math.max(0,28-r.minimumRadius)*100+r.far+r.cuts.length*.01;if(!best.route||score<best.route.score){best.route={key,score,report:r};current=key;}}
fs.writeFileSync(new URL('artifacts/pipeline/citadel-cliff-shore-route-20261006/whole-route-three-join-search.json',root),JSON.stringify({summaries,best},null,2));const r=best.route.report;console.log(JSON.stringify({...best.route.key,R:r.minimumRadius,grade:r.maximumGrade,protected:r.protectedHits,cut:r.cuts.length,wet:r.wet,plaza:r.plaza,far:r.far}));
