import{createTargetCoastalCliffCutField}from'../../src/world/citadel/targetCoastalCliffCutField.js';
import{buildTargetTerrainHeightfield}from'../../src/world/citadel/targetTerrainHeightfield.js';
import{buildMountainSurfaceIndex}from'../../src/world/citadel/mountainSurfaceIndex.js';
import{replayTargetCliffShoreCurve,createTargetCliffOffsetCurve}from'../../src/world/citadel/targetCliffShoreRoute.js';
import fs from'node:fs';import * as T from'three';import{buildTargetCliffShoreBezier}from'../../src/world/citadel/targetCliffShoreRoute.js';import{createTargetNewCityRetreatField}from'../../src/world/citadel/targetNewCityRetreatField.js';import{createTargetRailCliffField}from'../../src/world/citadel/targetRailCliffField.js';import{targetTerrainHeight,TARGET_CITY_PLATFORMS}from'../../src/world/citadel/targetTerrainCandidate.js';import{createCastleOceanSampler}from'../../src/world/citadel/newCityRidgeCandidate.js';import{officialOceanLevelAt}from'../../src/world/waterV8/officialOcean.js';
const root=new URL('../../',import.meta.url),read=p=>JSON.parse(fs.readFileSync(new URL(p,root))),live=read('artifacts/pipeline/citadel-live-tram-clearance-20261006/global-tram-samples.json'),plan=read('artifacts/pipeline/citadel-cliff-transit-plan-20261006/sections.json').trials.at(-1),matrix=new T.Matrix4().fromArray(live.castleMatrix),sea=createCastleOceanSampler(matrix,160),retreat=createTargetNewCityRetreatField({platforms:TARGET_CITY_PLATFORMS}),rail=createTargetRailCliffField({...live,platforms:TARGET_CITY_PLATFORMS}),terrain=(x,z)=>{if(x< -143||x>143||z< -72||z>107)return null;const s=sea(x,z);return s===null?null:retreat.height(x,z,rail.height(x,z,targetTerrainHeight(x,z,s,{aprons:true,saddle:true,valleyBenches:true}),s),s);};

globalThis.document={getElementById:()=>null};globalThis.window={addEventListener(){}};const{createChristchurchTramSourceCurves}=await import('../../src/world/tramSystem.js'),sources=createChristchurchTramSourceCurves(160),best=read('artifacts/pipeline/citadel-cliff-shore-route-20261006/whole-route-inner31-search.json').best.route,base=replayTargetCliffShoreCurve(best.report.serialization),sU=live.lanes.red.samples[1684].u,eU=live.lanes.red.samples[1991].u;
function nearest(curve,point,lo,hi){for(let i=0;i<55;i++){const a=lo+(hi-lo)/3,b=hi-(hi-lo)/3;if(curve.getPointAt(a).distanceToSquared(point)<curve.getPointAt(b).distanceToSquared(point))hi=b;else lo=a;}return(lo+hi)/2;}
const right=base.getPoint(0).normalize().cross(base.getTangent(0)).normalize(),blueStart=live.lanes.blue.samples[1730].world,sign=Math.sign(new T.Vector3(...blueStart).sub(base.getPoint(0)).dot(right)),report={status:'diagnostic-only',accepted:false,base:best,lanes:{},direction:'source increasing u east to west',castleMatrix:matrix.elements};
const curves={red:base};for(const[name,offset]of[['red',0],['blue',sign*4.1],['center',sign*2.05]]){const source=sources[name],startTarget=base.getPoint(0).addScaledVector(right,offset),endP=base.getPoint(1),endRight=endP.clone().normalize().cross(base.getTangent(1)).normalize(),endTarget=endP.addScaledVector(endRight,offset),startU=name==='red'?sU:nearest(source,startTarget,.63,.68),endU=name==='red'?eU:nearest(source,endTarget,.75,.79),startWorld=source.getPointAt(startU).toArray(),endWorld=source.getPointAt(endU).toArray(),startTangent=source.getTangentAt(startU).toArray(),endTangent=source.getTangentAt(endU).toArray(),c=name==='red'?{curve:base,report:{offset:0}}:createTargetCliffOffsetCurve({base,offset,startWorld,endWorld,startTangent,endTangent});curves[name]=c.curve;
 const count=Math.ceil(c.curve.getLength()*2),samples=[];let minimumRadius=Infinity,maximumGrade=0;for(let i=0;i<=count;i++){const p=c.curve.getPointAt(i/count),t=c.curve.getTangentAt(i/count),v=Math.abs(t.dot(p.clone().normalize()));maximumGrade=Math.max(maximumGrade,v/Math.sqrt(1-v*v));samples.push({world:p.toArray(),local:p.clone().applyMatrix4(matrix.clone().invert()).toArray()});}for(let i=1;i<samples.length-1;i++){const[a,b,d]=samples.slice(i-1,i+2).map(s=>new T.Vector3(...s.world)),cross=b.clone().sub(a).cross(d.clone().sub(a)).length();if(cross>1e-9)minimumRadius=Math.min(minimumRadius,a.distanceTo(b)*b.distanceTo(d)*d.distanceTo(a)/(2*cross));}
 report.lanes[name]={startU,endU,startWorld,endWorld,startTangent,endTangent,offsetReport:c.report,minimumRadius,maximumGrade,startError:c.curve.getPoint(0).distanceTo(new T.Vector3(...startWorld)),endError:c.curve.getPoint(1).distanceTo(new T.Vector3(...endWorld)),startAngle:c.curve.getTangent(0).angleTo(new T.Vector3(...startTangent)),endAngle:c.curve.getTangent(1).angleTo(new T.Vector3(...endTangent)),samples};}

const cutSpec=read('artifacts/pipeline/citadel-cliff-shore-route-20261006/old-retained-cliff-cut.json'),cut=createTargetCoastalCliffCutField({cuts:cutSpec.cuts,platforms:TARGET_CITY_PLATFORMS}),built=buildTargetTerrainHeightfield({bounds:{minX:-143,maxX:143,minZ:-72,maxZ:107},step:1.7,heightAt:(x,z)=>{const h=terrain(x,z),s=sea(x,z);return h===null||s===null?null:cut.height(x,z,h,s);},floorAt:(x,z)=>{const s=sea(x,z);return s===null?null:s-12;}}),mesh=new T.Mesh(built.geometry,new T.MeshBasicMaterial({side:T.DoubleSide}));mesh.updateMatrixWorld();const index=buildMountainSurfaceIndex([mesh]),inv=matrix.clone().invert();report.meshAudit=built.audit;report.cutField=cut.report;
for(const name of ['red','blue']){const c=curves[name],n=Math.ceil(c.getLength()*2),a={probes:0,terrainHits:0,missingSurface:0,waterHits:0,failures:[]};for(let i=0;i<=n;i++){const w=c.getPointAt(i/n),t=c.getTangentAt(i/n),rad=w.clone().normalize(),right=rad.clone().cross(t).normalize(),up=t.clone().cross(right).normalize();for(const dx of[-2.32,0,2.32])for(const dz of[-3.49,0,3.49]){const p=w.clone().addScaledVector(right,dx).addScaledVector(t,dz).addScaledVector(up,-.6),q=p.clone().applyMatrix4(inv),hit=index.sample(new T.Ray(new T.Vector3(q.x,100,q.z),new T.Vector3(0,-1,0)),0,500);a.probes++;if(!hit)a.missingSurface++;else if(hit.point.y>q.y-.08){a.terrainHits++;if(a.failures.length<30)a.failures.push({i,point:q.toArray(),surface:hit.point.y});}if(p.length()<160+officialOceanLevelAt(p.clone().normalize()))a.waterHits++;}}report.lanes[name].actualTriangleUnderbody=a;}
report.retainedTerrainBoundaryLimit='Missing target mesh means outside this explicitly bounded mesh only; other scene geometry is not included.';
fs.writeFileSync(new URL('artifacts/pipeline/citadel-cliff-shore-route-20261006/inner-three-lines.json',root),JSON.stringify(report,null,2));console.log(JSON.stringify(Object.fromEntries(Object.entries(report.lanes).map(([k,v])=>[k,{startU:v.startU,endU:v.endU,R:v.minimumRadius,grade:v.maximumGrade,errors:[v.startError,v.endError],angles:[v.startAngle,v.endAngle],body:v.actualTriangleUnderbody}])),null,2));
