import * as T from 'three';import fs from 'node:fs';
import {createTargetUserMarkedProductionRelease} from '../../src/world/citadel/targetUserMarkedProductionRelease.js';
import {createTargetEastCliffProductionRelease} from '../../src/world/citadel/targetEastCliffProductionRelease.js';
import {buildMountainSurfaceIndex} from '../../src/world/citadel/mountainSurfaceIndex.js';
const ROOT=new URL('../../',import.meta.url),read=p=>JSON.parse(fs.readFileSync(new URL(p,ROOT)));
const pd=globalThis.document,pw=globalThis.window;globalThis.document??={getElementById:()=>null};globalThis.window??={addEventListener(){}};const{createChristchurchTramSourceCurves}=await import('../../src/world/tramSystem.js');if(pd===undefined)delete globalThis.document;else globalThis.document=pd;if(pw===undefined)delete globalThis.window;else globalThis.window=pw;
const sourceCurves=createChristchurchTramSourceCurves(),retainedRelease=createTargetUserMarkedProductionRelease({sourceCurves}),data=read('artifacts/pipeline/citadel-east-shore-route-20261006/remesh-expanded-shift-audit.json'),artifact=read('artifacts/pipeline/citadel-east-shore-route-20261006/remesh-expanded-geometry.json'),p=createTargetEastCliffProductionRelease({enabled:true,sourceCurves,retainedRelease,candidateInput:data.candidateInput,terrainArtifact:artifact});
const matrix=retainedRelease.castleMatrix,inverse=matrix.clone().invert(),up=new T.Vector3(0,1,0).transformDirection(matrix),down=up.clone().negate(),geo=new T.BufferGeometryLoader().parse(artifact.geometry),mesh=new T.Mesh(geo,new T.MeshBasicMaterial({side:T.DoubleSide}));mesh.matrixAutoUpdate=false;mesh.matrix.copy(matrix).multiply(new T.Matrix4().makeTranslation(...artifact.origin));mesh.updateMatrixWorld(true);const index=buildMountainSurfaceIndex([mesh]),curve=p.release.segments.center.newShore,length=curve.getLength(),n=Math.ceil(length/.5),rows=[];
for(let i=0;i<=n;i++){const s=length*i/n,u=i/n,world=curve.getPointAt(u),local=world.clone().applyMatrix4(inverse),front=world.clone().normalize().dot(up),hit=index.sample(new T.Ray(new T.Vector3(local.x,250,local.z).applyMatrix4(matrix),down),0,900),terrainY=hit?hit.point.clone().applyMatrix4(inverse).y:null;rows.push({s,u,world:world.toArray(),local:local.toArray(),radialDotChartUp:front,frontHemisphere:front>0,chartRect:local.x>=-143&&local.x<=143&&local.z>=-72&&local.z<=107,actualArtifactColumn:terrainY!==null,terrainY,nearCoastColumn:front>0&&terrainY!==null&&Math.abs(terrainY-local.y)<30});}
function runs(key){const out=[];for(let i=0;i<rows.length;){const start=i,value=rows[i][key];while(i+1<rows.length&&rows[i+1][key]===value)i++;out.push({value,start:rows[start],end:rows[i],length:rows[i].s-rows[start].s});i++;}return out;}
const oldHead=retainedRelease.curves.center.getPointAt(0);let nearest=rows[0];for(const r of rows)if(new T.Vector3(...r.world).distanceTo(oldHead)<new T.Vector3(...nearest.world).distanceTo(oldHead))nearest=r;
const descriptors=[];for(const x of[143,130,120,110,105,100,95]){let selected=null;for(const r of rows){if(r.radialDotChartUp>.15&&r.local[0]<=x&&r.actualArtifactColumn){selected=r;break;}}descriptors.push({kind:'first-front-actual-column-at-or-west-of-x',x,selected});}
let lo=0,hi=1;for(let i=0;i<48;i++){const u=(lo+hi)/2,q=curve.getPointAt(u).applyMatrix4(inverse);if(q.x>120)lo=u;else hi=u;}const cutU=(lo+hi)/2,cutWorld=curve.getPointAt(cutU),cutLocal=cutWorld.clone().applyMatrix4(inverse),laneBoundaries={};
for(const lane of ['center','red','blue']){const c=p.release.curves[lane];let at=0,best=Infinity;for(let i=0;i<=4096;i++){const u=i/4096,d=c.getPointAt(u).distanceToSquared(cutWorld);if(d<best){best=d;at=u;}}let a=Math.max(0,at-1/4096),b=Math.min(1,at+1/4096);for(let i=0;i<44;i++){const x=a+(b-a)/3,y=b-(b-a)/3;if(c.getPointAt(x).distanceToSquared(cutWorld)<c.getPointAt(y).distanceToSquared(cutWorld))b=y;else a=x;}const u=(a+b)/2;laneBoundaries[lane]={replacementU:u,fromSourceHeadMetres:u*c.getLength(),world:c.getPointAt(u).toArray(),local:c.getPointAt(u).applyMatrix4(inverse).toArray(),distanceToCenter:c.getPointAt(u).distanceTo(cutWorld),remainingCityNewShoreMetres:(p.release.ranges[lane].newShore[1]-u)*c.getLength()};}
const proposal={notInstalled:true,notFoundationAccepted:true,criterion:'Existing city east head X≈120, front hemisphere and full-width chart margin; a scope proposal, not route modification.',newShoreU:cutU,fromSourceHeadMetres:cutU*length,world:cutWorld.toArray(),local:cutLocal.toArray(),laneBoundaries};
const result={version:'east-release-extent-cpu-1',accepted:false,installed:false,finalTerrainEpochVerified:false,proposal,length,sampleStep:length/n,sourceStart:rows[0],centralStart:rows.at(-1),oldHead:{world:oldHead.toArray(),local:oldHead.clone().applyMatrix4(inverse).toArray(),nearestNew:nearest,distance:new T.Vector3(...nearest.world).distanceTo(oldHead)},runs:Object.fromEntries(['frontHemisphere','chartRect','actualArtifactColumn','nearCoastColumn'].map(k=>[k,runs(k)])),descriptors,rows,meaning:{frontHemisphere:'world radial dot castle +Y >0; false means chart-highest-Y surface is the other side.',chartRect:'Authored XZ rectangle only; does not prove local Y is the relevant shell.',actualArtifactColumn:'A vertical ray intersects the existing pre-refinement artifact at this XZ. Not a loaded-body/footing pass.',nearCoastColumn:'Diagnostic only: front side, artifact exists, |railY-terrainY|<30m. Not an install threshold.'}};
fs.writeFileSync(new URL('artifacts/pipeline/citadel-east-structure-audit-20261006/extent.json',ROOT),JSON.stringify(result,null,2));console.log(JSON.stringify({proposal,length,oldHead:result.oldHead,runs:Object.fromEntries(Object.entries(result.runs).map(([k,rs])=>[k,rs.map(r=>({value:r.value,s:[r.start.s,r.end.s],start:r.start.local,end:r.end.local}))])),descriptors},null,2));geo.dispose();mesh.material.dispose();
