import fs from'node:fs';import * as T from'three';import{buildTargetCliffShoreBezier}from'../../src/world/citadel/targetCliffShoreRoute.js';import{createTargetNewCityRetreatField}from'../../src/world/citadel/targetNewCityRetreatField.js';import{createTargetRailCliffField}from'../../src/world/citadel/targetRailCliffField.js';import{targetTerrainHeight,TARGET_CITY_PLATFORMS}from'../../src/world/citadel/targetTerrainCandidate.js';import{createCastleOceanSampler}from'../../src/world/citadel/newCityRidgeCandidate.js';import{officialOceanLevelAt}from'../../src/world/waterV8/officialOcean.js';
const root=new URL('../../',import.meta.url),read=p=>JSON.parse(fs.readFileSync(new URL(p,root))),live=read('artifacts/pipeline/citadel-live-tram-clearance-20261006/global-tram-samples.json'),plan=read('artifacts/pipeline/citadel-cliff-transit-plan-20261006/sections.json').trials.at(-1),matrix=new T.Matrix4().fromArray(live.castleMatrix),sea=createCastleOceanSampler(matrix,160),retreat=createTargetNewCityRetreatField({platforms:TARGET_CITY_PLATFORMS}),rail=createTargetRailCliffField({...live,platforms:TARGET_CITY_PLATFORMS}),terrain=(x,z)=>{if(x< -143||x>143||z< -72||z>107)return null;const s=sea(x,z);return s===null?null:retreat.height(x,z,rail.height(x,z,targetTerrainHeight(x,z,s,{aprons:true,saddle:true,valleyBenches:true}),s),s);};

const summaries=[],best={};
for(const oldXZ of [[-30,40]])for(const newXZ of [[35,74]])for(const radius of [170,172]){
 const shell=createCastleOceanSampler(matrix,radius),a=new T.Vector3(oldXZ[0],shell(...oldXZ),oldXZ[1]).applyMatrix4(matrix),b=new T.Vector3(newXZ[0],shell(...newXZ),newXZ[1]).applyMatrix4(matrix),normal=a.clone().cross(b).normalize(),ta=normal.clone().cross(a).normalize(),tb=normal.clone().cross(b).normalize();
 for(const side of ['old','new'])for(const dir of(side==='old'?[[-1,0],[-1,.5],[-1,1]]:[[0,1],[.3,1],[.6,1]]))for(const handle of [20,35,50])for(const jh of [20,35,50])for(const join of(side==='old'?[[-58,65],[-65,72],[-55,80]]:[[65,107],[75,111],[64,116]])){
 const anchor=live.lanes.red.samples[side==='old'?1991:1684],start=side==='old'?a:b,direction=(()=>{const local=side==='old'?oldXZ:newXZ,p=new T.Vector3(local[0]+dir[0]*.001,shell(local[0]+dir[0]*.001,local[1]+dir[1]*.001),local[1]+dir[1]*.001).applyMatrix4(matrix);return p.sub(start).normalize().toArray();})(),endTangent=anchor.tangent.map(v=>v*(side==='old'?1:-1));
 const p=buildTargetCliffShoreBezier({castleMatrix:matrix,startWorld:start.toArray(),endWorld:anchor.world,startTangent:direction,endTangent,joins:[{local:join,direction:side==='old'?[-1,0]:[1,0],handleIn:jh,handleOut:30}],handleLength:handle,sampleTerrain:terrain,sampleSea:sea,seaRadiusAt:p=>160+officialOceanLevelAt(p.normalize()),platforms:TARGET_CITY_PLATFORMS,forbiddenPolygon:side==='new'?[[45,76],[49,69],[65,64],[81,67],[88,76],[83,87],[64,91],[49,87]]:null});const r=p.report;if(!r.samples)continue;
 const key={side,dir,oldXZ,newXZ,radius,handle,jh,join,anchorIndex:anchor.i,anchorU:anchor.u};summaries.push({...key,status:r.status,R:r.minimumRadius,grade:r.maximumGrade,protected:r.protectedHits,cut:r.cuts.length,wet:r.wet,plaza:r.plaza,far:r.far});const score=(r.protectedHits+r.plaza)*1000+r.wet*1000+Math.max(0,25-r.minimumRadius)*100+Math.max(0,r.maximumGrade-.04)*10000+r.far+r.cuts.length*.01;
 if(!best[side]||score<best[side].score)best[side]={key,score,report:r};}}
const dir=new URL('artifacts/pipeline/citadel-cliff-shore-route-20261006/',root);fs.writeFileSync(new URL('moved-tangent-search.json',dir),JSON.stringify({summaries,best},null,2));console.log(JSON.stringify(Object.fromEntries(Object.entries(best).map(([k,v])=>[k,{...v.key,status:v.report.status,R:v.report.minimumRadius,grade:v.report.maximumGrade,protected:v.report.protectedHits,plaza:v.report.plaza,cut:v.report.cuts.length,wet:v.report.wet,far:v.report.far}])),null,2));
