import fs from'node:fs';import*as T from'three';import{eastCliffFinalSurfaceFixture}from'./east_cliff_final_surface_fixture.mjs';import{createMountainCanopyCandidate}from'../../src/world/citadel/mountainCanopyCandidate.js';import{buildMountainSurfaceIndex}from'../../src/world/citadel/mountainSurfaceIndex.js';import{officialOceanLevelAt}from'../../src/world/waterV8/officialOcean.js';import{createTargetCityDetailCandidate}from'../../src/world/citadel/targetCityDetailCandidate.js';import{createEastCliffAlignmentCandidate}from'../../src/world/citadel/targetEastCliffAlignmentCandidate.js';import{createEastCliffVegetationRefresh}from'../../src/world/citadel/targetEastCliffVegetationRefresh.js';
const dir=new URL('../../artifacts/pipeline/citadel-east-shore-route-20261006/',import.meta.url),artifact=JSON.parse(fs.readFileSync(new URL('remesh-final-surface-geometry.json',dir))),audit=JSON.parse(fs.readFileSync(new URL('remesh-final-surface-audit.json',dir))),f=eastCliffFinalSurfaceFixture(),rail=[];for(const c of Object.values(f.curves))for(let i=0;i<1000;i++)rail.push(c.getPointAt(i/1000));
const canopy=createMountainCanopyCandidate(f.castle,{enabled:true,surfaceIndex:buildMountainSurfaceIndex([f.terrain]),rail,radius:160,waterHeight:officialOceanLevelAt});f.castle.add(canopy.group);f.scene.updateMatrixWorld(true);
const detail=createTargetCityDetailCandidate({castle:f.castle,sceneRoot:f.scene,terrainMeshes:[f.terrain],oceanMesh:f.ocean,fitSunShadow:false,includeFrontRail:false,cliffTransitRelease:f.release});f.castle.add(detail.group);f.scene.updateMatrixWorld(true);
const publicMeshes=[];detail.group.traverse(m=>{if(m.isMesh&&!m.userData.skipColliders&&!/waterfall|water-sheet|foam/.test(m.name))publicMeshes.push(m);});
const alignment=createEastCliffAlignmentCandidate({enabled:true,input:audit.candidateInput,sourceCurves:f.sourceCurves,retainedRelease:f.release,castleMatrix:f.castle.matrixWorld});
const replacement=new T.Mesh(new T.BufferGeometryLoader().parse(artifact.geometry),f.terrain.material);replacement.position.fromArray(artifact.origin);replacement.name='east-remesh-final-survey';f.castle.add(replacement);f.scene.updateMatrixWorld(true);
const seaIndex=buildMountainSurfaceIndex([f.ocean]),matrix=f.castle.matrixWorld,inv=matrix.clone().invert(),down=new T.Vector3(0,-1,0).transformDirection(matrix),sampleSea=(x,z)=>{const hit=seaIndex.sample(new T.Ray(new T.Vector3(x,250,z).applyMatrix4(matrix),down),0,700);return hit?hit.point.clone().applyMatrix4(inv).y:null;};
const handle=createEastCliffVegetationRefresh({enabled:true,castle:f.castle,surfaces:[replacement],previousSurfaces:[f.terrain],maxDistance:24,spacing:1,protectedMeshes:publicMeshes,railCurves:Object.values(alignment.curves),sampleSea});
const transaction={applied:false,rootFailures:[],restored:false};const snapshots=handle.instanceBackups;
if(handle.report.ready){transaction.applied=handle.apply();const finalIndex=handle.surfaceIndex;for(const move of handle.report.moves){const part=move.parts.find(p=>p.name==='citadel-canopy-root-trunks'),mesh=f.castle.getObjectByProperty('uuid',part.uuid),remap=handle.report.instanceRemap.find(r=>r.uuid===part.uuid),m=new T.Matrix4();mesh.getMatrixAt(remap.oldToNew[part.index],m);const world=mesh.matrixWorld.clone().multiply(m);for(let j=0;j<6;j++){const foot=new T.Vector3(Math.sin(j*Math.PI/3)*.12,0,Math.cos(j*Math.PI/3)*.12).applyMatrix4(world).applyMatrix4(inv),hit=finalIndex.sample(new T.Ray(new T.Vector3(foot.x,250,foot.z).applyMatrix4(matrix),down),0,700),gap=hit?foot.y-hit.point.clone().applyMatrix4(inv).y:Infinity;if(gap>.002||gap<-.3)transaction.rootFailures.push({key:move.key,j,gap});}}}
handle.dispose();transaction.restored=snapshots.every(s=>{const m=f.castle.getObjectByProperty('uuid',s.uuid);return m.count===s.count&&m.instanceMatrix.array.every((v,i)=>v===s.matrices[i])&&(!s.colors||m.instanceColor.array.every((v,i)=>v===s.colors[i]));});
fs.writeFileSync(new URL('vegetation-refresh-fixture-survey.json',dir),JSON.stringify({report:handle.report,transaction,fixtureCanopy:canopy.report.accepted,scope:'Production canopy factory and final baseline terrain, but production placement hiding/appearance changes and actual actors are NOT reproduced. CPU-only transaction applied, checked, and rolled back.'},null,2));console.log(JSON.stringify({trees:handle.report.treeCountBefore,after:handle.report.treeCountAfter,moves:handle.report.moves.length,retired:handle.report.retired.length,unchanged:handle.report.unchanged,failures:handle.report.failures.length,unsupported:handle.report.unsupported.length,ready:handle.report.ready,transaction}));detail.dispose();canopy.dispose();replacement.geometry.dispose();f.dispose();
