import{createTargetCoastalCliffCutField}from'../../src/world/citadel/targetCoastalCliffCutField.js';
import fs from'node:fs';import * as T from'three';import{buildTargetCliffShoreBezier}from'../../src/world/citadel/targetCliffShoreRoute.js';import{createTargetNewCityRetreatField}from'../../src/world/citadel/targetNewCityRetreatField.js';import{createTargetRailCliffField}from'../../src/world/citadel/targetRailCliffField.js';import{targetTerrainHeight,TARGET_CITY_PLATFORMS}from'../../src/world/citadel/targetTerrainCandidate.js';import{createCastleOceanSampler}from'../../src/world/citadel/newCityRidgeCandidate.js';import{officialOceanLevelAt}from'../../src/world/waterV8/officialOcean.js';
const root=new URL('../../',import.meta.url),read=p=>JSON.parse(fs.readFileSync(new URL(p,root))),live=read('artifacts/pipeline/citadel-live-tram-clearance-20261006/global-tram-samples.json'),plan=read('artifacts/pipeline/citadel-cliff-transit-plan-20261006/sections.json').trials.at(-1),matrix=new T.Matrix4().fromArray(live.castleMatrix),sea=createCastleOceanSampler(matrix,160),retreat=createTargetNewCityRetreatField({platforms:TARGET_CITY_PLATFORMS}),rail=createTargetRailCliffField({...live,platforms:TARGET_CITY_PLATFORMS}),terrain=(x,z)=>{if(x< -143||x>143||z< -72||z>107)return null;const s=sea(x,z);return s===null?null:retreat.height(x,z,rail.height(x,z,targetTerrainHeight(x,z,s,{aprons:true,saddle:true,valleyBenches:true}),s),s);};

const source=live.lanes.red.samples.slice(1986,2241).filter((_,i)=>i%4===0),edge=[],outer=[];for(let i=0;i<source.length;i++){const p=source[i].local,a=source[Math.max(0,i-1)].local,b=source[Math.min(source.length-1,i+1)].local,dx=b[0]-a[0],dz=b[2]-a[2],l=Math.hypot(dx,dz),ix=-dz/l,iz=dx/l;edge.push([p[0]+ix*8,p[2]+iz*8]);outer.push([p[0]-ix*65,p[2]-iz*65]);}
const cuts=[{id:'old-global-exterior-toe',edge,polygon:[...edge,...outer.reverse()],seaSide:-1,transitionWidth:2}],cut=createTargetCoastalCliffCutField({cuts,platforms:TARGET_CITY_PLATFORMS});const audit={before:0,after:0,missing:0,probes:0,maxDrop:0,failed:[]};
const inv=matrix.clone().invert();for(const lane of ['red','blue'])for(const p of live.lanes[lane].samples){if(p.u<.7675||p.u>.8668)continue;const w=new T.Vector3(...p.world),t=new T.Vector3(...p.tangent),rad=w.clone().normalize(),right=rad.clone().cross(t).normalize(),up=t.clone().cross(right).normalize();for(const dx of[-2.32,0,2.32])for(const dz of[-3.49,0,3.49]){const q=w.clone().addScaledVector(right,dx).addScaledVector(t,dz).addScaledVector(up,-.6).applyMatrix4(inv),h=terrain(q.x,q.z),s=sea(q.x,q.z);audit.probes++;if(h===null||s===null){audit.missing++;continue;}const after=cut.height(q.x,q.z,h,s);if(h>q.y-.08)audit.before++;if(after>q.y-.08){audit.after++;if(audit.failed.length<50)audit.failed.push({lane,i:p.i,local:q.toArray(),before:h,after});}audit.maxDrop=Math.max(audit.maxDrop,h-after);}}

const footprint={platformPoints:0,platformChanged:0,highTerrainChanged:0,changedBounds:{minX:Infinity,maxX:-Infinity,minZ:Infinity,maxZ:-Infinity},mainPeak:null,maxDropPoint:null};
for(let x=-143;x<=143;x++)for(let z=-72;z<=107;z++){const h=terrain(x,z),s=sea(x,z);if(h===null||s===null)continue;const after=cut.height(x,z,h,s),protectedFull=TARGET_CITY_PLATFORMS.some(p=>Math.hypot((x-p.center[0])/p.radii[0],(z-p.center[1])/p.radii[1])<=1);if(protectedFull){footprint.platformPoints++;if(Math.abs(after-h)>1e-8)footprint.platformChanged++;}if(after<h-1e-8){if(h>25)footprint.highTerrainChanged++;const b=footprint.changedBounds;b.minX=Math.min(b.minX,x);b.maxX=Math.max(b.maxX,x);b.minZ=Math.min(b.minZ,z);b.maxZ=Math.max(b.maxZ,z);if(!footprint.maxDropPoint||h-after>footprint.maxDropPoint.drop)footprint.maxDropPoint={x,z,before:h,after,sea:s,drop:h-after};}}
for(const[x,z]of[[-71,-41]]){const before=terrain(x,z);footprint.mainPeak={x,z,before,after:cut.height(x,z,before,sea(x,z))};}
fs.writeFileSync(new URL('artifacts/pipeline/citadel-cliff-shore-route-20261006/old-retained-cliff-cut.json',root),JSON.stringify({cuts,audit,footprint,field:cut.report,note:'Finite procedural heightfield checks, not actual remesh triangles. Outside source domain is reported missing, never clear.'},null,2));console.log(JSON.stringify({audit,footprint,field:cut.report},null,2));
