import {chromium} from '../../../tools/shot/node_modules/playwright/index.mjs';
import {writeFile} from 'node:fs/promises';
const out='TigerMessenger/artifacts/pipeline/citadel-coastal-tram-target/';
const candidate=process.argv.includes('--rail');
const west=process.argv.includes('--west');
const b=await chromium.launch({channel:'chrome',headless:true,args:['--use-angle=metal']});
try{const p=await b.newPage({viewport:{width:1500,height:1000}});await p.goto('http://localhost:8931/TigerMessenger/?autostart=1'+(candidate?'&citadelCoastalTram=1':''),{waitUntil:'domcontentloaded'});await p.waitForFunction(()=>window.__tm?.scene.getObjectByName('highland-west-city'),null,{timeout:180000});
const report=await p.evaluate((west)=>{const t=window.__tm,T=t.THREE;let castle;t.scene.traverse(o=>{if(o.userData.highlandAssaultAnchors)castle=o;});t.cameraRig.update=()=>{};t.P.daySpeed=0;t.P.timeOfDay=.4;t.scene.updateMatrixWorld(true);
const local=p=>castle.localToWorld(new T.Vector3(...p));t.camera.position.copy(local(west?[-180,65,95]:[30,170,220]));t.camera.up.set(0,1,0).transformDirection(castle.matrixWorld);t.camera.lookAt(local(west?[-105,-15,50]:[25,15,30]));t.camera.fov=55;t.camera.far=3000;t.camera.updateProjectionMatrix();t.camera.updateMatrixWorld(true);t.distanceCulling?.update(3);
const selected=[];t.scene.traverse(o=>{if(/^(highland-west-city|old-harbor-scene|citadel-new-city-backdrop-range)$/.test(o.name)||/plaza-statue|front.*berth/.test(o.name)){const box=new T.Box3().setFromObject(o);selected.push({name:o.name,world:o.getWorldPosition(new T.Vector3()).toArray(),castleLocal:castle.worldToLocal(box.getCenter(new T.Vector3())).toArray(),size:box.getSize(new T.Vector3()).toArray()});}});
const peaks=[];const root=t.scene.getObjectByName('citadel-new-city-backdrop-range');root.traverse(o=>{if(!o.isMesh||o.isInstancedMesh)return;const a=o.geometry.attributes.position;let max=-Infinity;for(let i=0;i<a.count;i++)max=Math.max(max,new T.Vector3().fromBufferAttribute(a,i).applyMatrix4(o.matrixWorld).length()-160);peaks.push({name:o.name,maxAltitude:max});});const curve=t.messenger.landmarks.tramSystem.curve;const samples=Array.from({length:720},(_,i)=>{const w=curve.getPointAt(i/720),v=castle.worldToLocal(w.clone());return {t:i/720,local:v.toArray(),world:w.toArray()};}).filter(p=>Math.hypot(p.local[0],p.local[2])<150);return {peaks,trackSamples:samples,selected,landmarkKeys:Object.keys(t.messenger.landmarks),camera:t.camera.position.toArray()};},west);await p.waitForTimeout(1200);
const data=await p.evaluate(()=>{const t=window.__tm;t.distanceCulling?.update(3);t.renderer.render(t.scene,t.camera);return t.renderer.domElement.toDataURL();});await writeFile(out+(west?'rail-west-open.png':candidate?'rail-candidate.png':'actual-birdseye.png'),Buffer.from(data.split(',')[1],'base64'));await writeFile(out+(west?'rail-west-open.json':candidate?'rail-candidate.json':'actual-layout.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({peaks:report.peaks,trackSampleCount:report.trackSamples.length}));}finally{await b.close();}
