import fs from 'node:fs';
import * as THREE from 'three';
import {applyTargetTerrainCandidate} from '../../src/world/citadel/targetTerrainCandidate.js';
import {createTargetStairSurfaceSampler} from '../../src/world/citadel/targetNewCityStairRoute.js';
import {createTargetOldCity} from '../../src/world/citadel/targetOldCity.js';
import {createTargetNewCityMain} from '../../src/world/citadel/targetNewCityMain.js';
import {createTargetNewCityStairs} from '../../src/world/citadel/targetNewCityStairs.js';
const castle=new THREE.Group();castle.matrixAutoUpdate=false;castle.matrix.fromArray([-.5771265090244172,.12463062405961449,.807088718870361,0,.6354855835814281,.689249750214348,.3479839865419536,0,-.5129162364767383,.7137240288626759,-.4769852670498,0,124.43456408079132,72.61606956254715,90.15650671642375,1]);
const source=new THREE.Mesh(new THREE.BoxGeometry(),new THREE.MeshBasicMaterial({side:THREE.DoubleSide}));source.name='citadel-oskar-grid-mountain-surface';castle.add(source);
const previous=globalThis.location;globalThis.location={search:'?citadelTerrainFirst=1&citadelTargetRemesh=1&citadelTerraceAprons=1&citadelRecessedSaddle=1&citadelValleyBenches=1'};try{applyTargetTerrainCandidate(castle);}finally{if(previous===undefined)delete globalThis.location;else globalThis.location=previous;}
const sample=createTargetStairSurfaceSampler(castle,[source]);const before=[...source.geometry.attributes.position.array];
const old=createTargetOldCity(),main=createTargetNewCityMain(),yaw=-55*Math.PI/180,frame=(origin,yaw)=>new THREE.Matrix4().makeRotationY(yaw).setPosition(...origin),oldM=frame([-55,17,9],Math.PI/4),mainM=frame([74,12,33],yaw),P=(p,m)=>new THREE.Vector3(...p).applyMatrix4(m).toArray();
const houses=createTargetNewCityStairs({houseOffsets:{'new-city-stair-house-1--1':[6.5*Math.cos(yaw),6.5*Math.sin(yaw)]},surfaceHeightAt:(x,z)=>{const p=P([x,0,z],mainM);return sample(p[0],p[2])?.height-12;}});
function overlap(a,b){for(const p of[a,b])for(let i=0;i<p.length;i++){const q=p[(i+1)%p.length],nx=q[1]-p[i][1],nz=p[i][0]-q[0],aa=a.map(v=>v[0]*nx+v[1]*nz),bb=b.map(v=>v[0]*nx+v[1]*nz);if(Math.max(...aa)<=Math.min(...bb)+1e-6||Math.max(...bb)<=Math.min(...aa)+1e-6)return false;}return true;}
function audit(model,matrix,sxz,sy,pivotY){const foots=model.report.footprints.filter(f=>f.support||(!f.supportedBy&&!f.elevated&&f.floorY<=.01)),points=[],failures=[];for(const f of foots){const xs=f.polygon.map(p=>p[0]),zs=f.polygon.map(p=>p[1]),xmin=Math.min(...xs),xmax=Math.max(...xs),zmin=Math.min(...zs),zmax=Math.max(...zs);for(let i=0;i<=8;i++)for(let j=0;j<=8;j++){const x=THREE.MathUtils.lerp(xmin,xmax,i/8)*sxz,z=THREE.MathUtils.lerp(zmin,zmax,j/8)*sxz,p=P([x,f.floorY,z],matrix),hit=sample(p[0],p[2]),gap=hit?p[1]-hit.height:null;const q={footprint:f.id,point:p,height:hit?.height??null,gap};points.push(q);if(gap===null||gap>.3||gap<-.35)failures.push(q);}}
const transform=p=>P([p[0]*sxz,p[1]<=pivotY?p[1]:pivotY+(p[1]-pivotY)*sy,p[2]*sxz],matrix),localBounds=model.report.bounds||null;return{sxz,sy,pivotY,supportPoints:points.length,missing:points.filter(p=>p.gap===null).length,maxGap:Math.max(...points.filter(p=>p.gap!==null).map(p=>p.gap)),minGap:Math.min(...points.filter(p=>p.gap!==null).map(p=>p.gap)),unsupported:failures.length,examples:failures.slice(0,6),transform};}
const oldRows=[];for(const sxz of[1,1.05,1.1,1.15,1.2])for(const sy of[1.05,1.1,1.15]){const r=audit(old,oldM,sxz,sy,.3);r.interfaces=Object.fromEntries(Object.entries(old.report.exits).map(([key,p])=>{const before=P(p,oldM),after=r.transform(p);return[key,{before,after,shift:new THREE.Vector3(...before).distanceTo(new THREE.Vector3(...after))}];}));delete r.transform;oldRows.push(r);}
const mainRows=[];for(const sxz of[1,1.05,1.1,1.15])for(const sy of[1.15,1.2,1.3]){const r=audit(main,mainM,sxz,sy,1.2);r.interfaces={entry:r.transform(main.report.entry.position),approach:r.transform(main.report.stairs.bottom),originalEntry:P(main.report.entry.position,mainM),originalApproach:P(main.report.stairs.bottom,mainM)};r.houseIntersections=[];for(const f of main.report.footprints.filter(f=>!f.elevated)){const polygon=f.polygon.map(p=>[p[0]*sxz,p[1]*sxz]);for(const h of houses.report.footprints.filter(h=>h.role==='stair-flank-house'))if(overlap(polygon,h.polygon))r.houseIntersections.push({main:f.id,house:h.id});}delete r.transform;mainRows.push(r);}
const result={fixture:'actual r17 asymmetric shoulder final triangles; 9x9 samples per structural footprint, not full triangle containment',sourceUnchanged:before.every((v,i)=>v===source.geometry.attributes.position.array[i]),old:oldRows,newMain:mainRows,limits:['House intersections are XZ footprint overlaps, not proof of 3D solid collision.','Footprint samples cannot guarantee every point remains supported.','Bridge, water channel and stair route endpoints require explicit rebuild whenever reported shifts are nonzero.','No runtime geometry modified; no GPU visual acceptance.']};
const out=new URL('../../artifacts/pipeline/citadel-city-detail-20261006/city-scale-survey.json',import.meta.url);fs.writeFileSync(out,JSON.stringify(result,null,2));console.log(JSON.stringify({old:oldRows.filter(r=>r.sy===1.1).map(({sxz,unsupported,maxGap,minGap,interfaces})=>({sxz,unsupported,maxGap,minGap,interfaces})),newMain:mainRows.filter(r=>r.sy===1.2).map(({sxz,unsupported,maxGap,minGap,houseIntersections,interfaces})=>({sxz,unsupported,maxGap,minGap,houseIntersections,interfaces}))},null,2));old.dispose();main.dispose();houses.dispose();source.geometry.dispose();source.material.dispose();
