import {chromium} from '../../../tools/shot/node_modules/playwright/index.mjs';import {readFile,writeFile,mkdir} from 'node:fs/promises';import assert from 'node:assert/strict';
const out=new URL('../../artifacts/pipeline/citadel-middle-terraces/',import.meta.url);await mkdir(out,{recursive:true});const b=await chromium.launch({channel:'chrome',headless:true,args:['--use-angle=metal']});const reports={};
try{for(const version of ['before','after']){const p=await b.newPage({viewport:{width:1440,height:1000}}),errors=[];p.on('pageerror',e=>errors.push(String(e)));if(version==='before')for(const file of ['westCity.js','claudeHouses.js','citadelGarden.js']){const body=await readFile(new URL('before-sources/'+file,out),'utf8');await p.route('**/src/world/citadel/'+file+'*',r=>r.fulfill({contentType:'text/javascript',body}));}
await p.goto('http://localhost:8931/TigerMessenger/?autostart=1',{timeout:180000});await p.waitForFunction(()=>window.__tm?.scene.getObjectByName('citadel-target-castle-silhouette'),null,{timeout:180000});
const result=await p.evaluate(async()=>{const t=window.__tm,T=t.THREE,c=t.scene.getObjectByName('castleContainer'),city=c.getObjectByName('highland-west-city'),root=city.getObjectByName('citadel-target-castle-silhouette');t.cameraRig.update=()=>{};t.P.daySpeed=0;t.P.timeOfDay=.85;c.updateWorldMatrix(true,true);
const pictures={};for(const [name,eye,look,fov]of [['terraces',[100,35,99],[61,13,33],48],['overall',[110,44,136],[37,19,40],54]]){t.camera.position.copy(city.localToWorld(new T.Vector3(...eye)));t.camera.up.set(0,1,0).transformDirection(city.matrixWorld);t.camera.lookAt(city.localToWorld(new T.Vector3(...look)));t.camera.fov=fov;t.camera.updateProjectionMatrix();await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));t.renderer.render(t.scene,t.camera);pictures[name]=t.renderer.domElement.toDataURL('image/png');}
const ray=new T.Raycaster();ray.layers.enableAll();ray.far=1;
const tests=[];for(const [x,y,z]of [[48.2,21.3,-.1],[72,21.3,.8],[63.8,21.3,-10.1]])for(const dx of [0,1]){ray.set(city.localToWorld(new T.Vector3(x+dx,y,z+.6)),new T.Vector3(0,0,-1).transformDirection(city.matrixWorld));const hit=ray.intersectObject(root,true)[0];tests.push({x:x+dx,y,z,hit:hit?city.worldToLocal(hit.point.clone()).toArray():null,material:hit?.object.material.emissive?.getHexString()});}
const houses=city.getObjectByName('west-city-middle'),support=[];const floors=[];city.traverse(o=>{if(o.isMesh&&o.userData.westCityWalkable)floors.push(o);});
for(const [x,y,z,w,d]of houses.userData.lots)for(const [dx,dz]of [[0,0],[-w/2+.1,-d/2+.1],[w/2-.1,-d/2+.1],[-w/2+.1,d/2-.1],[w/2-.1,d/2-.1]]){ray.set(city.localToWorld(new T.Vector3(x+dx,y+.1,z+dz)),new T.Vector3(0,-1,0).transformDirection(city.matrixWorld));ray.far=.25;support.push({x:x+dx,y,z:z+dz,ok:ray.intersectObjects(floors,false).length>0});}
return {houses:houses.userData.lots,support,terraces:city.getObjectByName('citadel-middle-terraces')?.userData,shape:city.userData.targetCastleSilhouette,wfc:root.userData.facadeWfc,source:root.userData.sourceId,windowRays:tests,pictures};});
for(const [name,data]of Object.entries(result.pictures))await writeFile(new URL(version+'-'+name+'.png',out),Buffer.from(data.split(',')[1],'base64'));delete result.pictures;result.errors=errors;assert.equal(errors.length,0);reports[version]=result;await p.close();}
assert.equal(reports.before.houses.length,12);assert.equal(reports.after.houses.length,4);assert.ok(reports.after.support.every(s=>s.ok));assert.ok(reports.after.terraces.sourceBlender);
await writeFile(new URL('report.json',out),JSON.stringify(reports,null,2));console.log(JSON.stringify({shape:reports.after.shape,facades:reports.after.wfc.towers.length,houses:reports.after.houses.length,supported:reports.after.support.length,passed:true}));
}finally{await b.close();}
