import {chromium} from '../../../tools/shot/node_modules/playwright/index.mjs';import {writeFile,mkdir} from 'node:fs/promises';import assert from 'node:assert/strict';
const out=new URL('../../artifacts/pipeline/citadel-old-harbor-grade/',import.meta.url);await mkdir(out,{recursive:true});
const browser=await chromium.launch({channel:'chrome',headless:true,args:['--use-angle=metal']});
try{const page=await browser.newPage({viewport:{width:1440,height:900}}),errors=[];page.on('pageerror',e=>errors.push(String(e)));
await page.goto('http://localhost:8931/TigerMessenger/?autostart=1&citadelCommonFrame=1&citadelOldHarbor=1'+(process.argv.includes('--compact-ascent')?'&citadelCompact=1':''),{timeout:180000});await page.waitForFunction(()=>window.__tm?.messenger?.landmarks?.boat,null,{timeout:180000});
const report=await page.evaluate(async()=>{const t=window.__tm,T=t.THREE,c=t.scene.getObjectByName('castleContainer'),h=t.scene.getObjectByName('old-harbor-scene'),boat=t.messenger.landmarks.boat;const {officialOceanLevelAt}=await import('/TigerMessenger/src/world/waterV8/officialOcean.js');
t.P.daySpeed=0;t.P.timeOfDay=.85;t.cameraRig.update=()=>{};await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));t.scene.updateMatrixWorld(true);
const v=boat.getWorldPosition(new T.Vector3()),deck=h.getObjectByName('pier-deck').getWorldPosition(new T.Vector3());
t.camera.position.copy(c.localToWorld(new T.Vector3(0,34,170)));t.camera.up.set(0,1,0).transformDirection(c.matrixWorld);t.camera.lookAt(c.localToWorld(new T.Vector3(-6,14,42)));t.camera.fov=52;t.camera.updateProjectionMatrix();t.renderer.render(t.scene,t.camera);
const meshes=[];t.scene.traverseVisible(o=>{if(o.isMesh&&o.material?.visible!==false&&!o.userData.isOutline&&!o.userData.backlitHighlight)meshes.push(o);});const ray=new T.Raycaster();ray.layers.enableAll();const occlusion={};for(const [key,target]of [['deck',deck],['boat',v]]){const d=target.clone().sub(t.camera.position);ray.set(t.camera.position,d.clone().normalize());ray.far=d.length();occlusion[key]=ray.intersectObjects(meshes,false).slice(0,8).map(hit=>({name:hit.object.name,parent:hit.object.parent?.name,distance:hit.distance}));}
return {mountainForest:c.userData.mountainForest,arcades:c.userData.oldShoreArcades,planting:c.userData.shorePlanting,shore:c.userData.oldShoreApproach,occlusion,harborMatrix:h.matrixWorld.toArray(),castleMatrix:c.matrixWorld.toArray(),grade:h.userData.oldHarborOceanGrade,boat:{name:boat.name,parent:boat.parent.name,altitude:v.length()-160-officialOceanLevelAt(v),deckDistance:v.distanceTo(deck),position:v.toArray()},logistics:!!t.messenger.landmarks.harborLogistics,porters:h.children.filter(o=>o.name==='porter-squad').length,image:t.renderer.domElement.toDataURL('image/png')};});
assert.ok(report.grade);assert.ok(report.grade.deckClearances.every(n=>Math.abs(n-.7)<.001));assert.equal(report.porters,2);assert.ok(report.boat.deckDistance<12);assert.ok(Math.abs(report.boat.altitude-.1)<.002);
await writeFile(new URL('candidate-current.png',out),Buffer.from(report.image.split(',')[1],'base64'));delete report.image;
const bytes=await page.evaluate(async()=>{const t=window.__tm,T=t.THREE,h=t.scene.getObjectByName('old-harbor-scene');const {exportWorldGLB}=await import('/TigerMessenger/tools/world/export_world_glb.js');const scene=new T.Scene(),copy=h.clone(true);copy.position.set(0,0,0);copy.quaternion.identity();copy.scale.set(1,1,1);scene.add(copy);const inverse=h.matrixWorld.clone().invert();for(const name of ['citadel-old-shore-approach','citadel-coastal-cliff-seal','citadel-oskar-grid-mountain-surface','citadel-shore-cypress-groves','highland-canopy-groves','citadel-mountain-cypress-groves']){const source=t.scene.getObjectByName(name);if(!source)throw new Error('Missing integration mesh '+name);const part=source.clone(true);part.matrix.copy(inverse.clone().multiply(source.matrixWorld));part.matrix.decompose(part.position,part.quaternion,part.scale);scene.add(part);}return Array.from(exportWorldGLB(scene,T,{}).bytes);});
await writeFile(new URL('../../godot/assets/art-pilots/old-harbor-ocean-grade.glb',import.meta.url),new Uint8Array(bytes));await writeFile(new URL('../../godot/data/old-harbor-ocean-grade.json',import.meta.url),JSON.stringify(report));
await page.evaluate(()=>{const t=window.__tm,T=t.THREE,b=t.messenger.landmarks.boat,v=b.getWorldPosition(new T.Vector3());t.player.riding=false;t.player.position.copy(v).addScaledVector(v.clone().normalize(),.72);t.player.velocity.set(0,0,0);});
await page.keyboard.press('f');const mounted=await page.evaluate(()=>{const t=window.__tm,b=t.messenger.landmarks.boat;return {piloted:b.userData.piloted,playerRiding:t.player.riding,parentIsScene:b.parent===t.scene};});report.mounted=mounted;
await page.keyboard.press('f');report.dismounted=await page.evaluate(()=>{const t=window.__tm,b=t.messenger.landmarks.boat;return {piloted:b.userData.piloted,playerRiding:t.player.riding,boatRetained:t.scene.getObjectById(b.id)===b};});
report.errors=errors;await writeFile(new URL('candidate-runtime.json',out),JSON.stringify(report,null,2));console.log(JSON.stringify({trees:report.planting?.placed.length,shorePoints:report.shore?.route.length,boat:report.boat,mounted:report.mounted,dismounted:report.dismounted,errors}));assert.equal(errors.length,0);assert.equal(mounted.piloted,true);assert.equal(report.dismounted.piloted,false);
}finally{await browser.close();}
