import {chromium} from '../../../tools/shot/node_modules/playwright/index.mjs';import {writeFile} from 'node:fs/promises';import assert from 'node:assert/strict';
const candidate=process.argv.includes("--placement-r02");
const b=await chromium.launch({channel:'chrome',headless:true,args:['--use-angle=metal']});try {const p=await b.newPage(),errors=[];p.on('pageerror',e=>errors.push(String(e)));await p.addInitScript(()=>{const raf=requestAnimationFrame.bind(window);window.requestAnimationFrame=cb=>cb.name==='animate'?0:raf(cb);});await p.goto('http://localhost:8931/TigerMessenger/?autostart=1'+(candidate?'&citadelMasterTerrain=9&citadelWater=2&citadelFrontGate=1&citadelPlacement=1&citadelMassing=2':''));await p.waitForFunction(()=>window.__tm?.scene.getObjectByName('citadel-target-castle-silhouette'),null,{timeout:180000});
const r=await p.evaluate(()=>{const t=window.__tm,T=t.THREE,c=t.scene.getObjectByName('highland-west-city'),root=c.getObjectByName('citadel-target-castle-silhouette');root.updateWorldMatrix(true,true);const ray=new T.Raycaster();ray.layers.enableAll();ray.far=1;const windows=[];
for(const probe of root.userData.facadeWfc.openingProbes){
 const normal=new T.Vector3(...probe.normal),cast=point=>{ray.set(root.localToWorld(new T.Vector3(...point).addScaledVector(normal,.6)),normal.clone().negate().transformDirection(root.matrixWorld));const h=ray.intersectObject(root,true)[0];return h?{depth:h.distance,emissive:h.object.material.emissive?.getHex(),name:h.object.name}:null;};
 windows.push({id:probe.id,tile:probe.tile,opening:cast(probe.center),wall:cast(probe.wall)});
}
let vertices=0,meshes=0,outlineVertices=0,outlineMeshes=0;root.traverseVisible(o=>{if(o.isMesh){if(o.userData.isOutline){outlineVertices+=o.geometry.attributes.position.count;outlineMeshes++;}else{vertices+=o.geometry.attributes.position.count;meshes++;}}});

return {massing:root.userData.towerMassing,wfc:root.userData.facadeWfc,windows,geometry:{vertices,meshes,outlineVertices,outlineMeshes,scope:'Physical surfaces separate from Web ink shells; GLB exporter omits ink shells'}};});r.errors=errors;await writeFile(new URL('../../artifacts/pipeline/citadel-master-terrain/keep-side-facades.json',import.meta.url),JSON.stringify(r,null,2));assert.equal(errors.length,0);assert.equal(r.wfc.towers.length,17);assert.equal(r.massing.filter(t=>t.cap).length,3);assert.ok(r.windows.length>0);assert.ok(r.windows.every(w=>w.opening&&w.wall&&w.opening.emissive===0xffb767&&w.opening.depth>w.wall.depth+.2),JSON.stringify(r.windows.filter(w=>!w.opening||!w.wall||w.opening.depth<=w.wall.depth+.2)));/* Slenderness is recorded for visual review, not capped to the older broad-tower design. */r.passed=true;await writeFile(new URL(candidate?'../../artifacts/pipeline/citadel-master-terrain/placement-r02-windows.json':'../../artifacts/pipeline/citadel-master-terrain/keep-side-facades.json',import.meta.url),JSON.stringify(r,null,2));console.log(JSON.stringify({passed:true,windows:r.windows.length,towers:r.massing.filter(t=>t.cap)}));}finally{await b.close();}
