import {chromium} from '../../../tools/shot/node_modules/playwright/index.mjs';
import {mkdir,writeFile} from 'node:fs/promises';
const out='artifacts/pipeline/warship-boarding-v11';await mkdir(out,{recursive:true});const errors=[],checks=[];
const browser=await chromium.launch({channel:'chrome',headless:true,args:['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
try{const page=await browser.newPage({viewport:{width:1280,height:1000}});page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400)errors.push(r.status()+' '+r.url())});await page.goto('http://127.0.0.1:8765/TigerMessenger/artifacts/pipeline/warship-boarding-v11/index.html');await page.waitForFunction(()=>window.warshipTransferReview,null,{timeout:60000});
for(const seat of [0,6,12]){await page.selectOption('#role',String(seat));for(const stage of ['seated','deck-unarmed','deck-armed','ashore','seated']){await page.locator(`[data-stage="${stage}"]`).click();const result=await page.evaluate(()=>{const r=window.warshipTransferReview,s=r.seat,stage=r.stage,api=r.boat.userData.warshipV6,row=api.crewStatus()[s],a=r.actors[s];return{stage,uid:a.userData.uid,seatVisible:api.nodes.get(`n220:i${s}`).visible,actorVisible:a.visible,stored:row.weaponStored,otherActorsHidden:r.actors.every((n,i)=>i===s||!n.visible),shipkeeper:api.nodes.get('n220:i25').visible,finite:a.position.toArray().every(Number.isFinite),weapons:Object.entries(a.userData.equipment).filter(([k])=>['spear','gladius','shield','bow'].includes(k)).map(([key,n])=>({key,visible:n.visible}))};});const stored=['seated','deck-unarmed'].includes(stage);checks.push({seat,stage,passed:result.uid===100+seat&&result.seatVisible===(stage==='seated')&&result.actorVisible===(stage!=='seated')&&result.stored===stored&&result.otherActorsHidden&&result.shipkeeper&&result.finite&&result.weapons.every(({key,visible})=>visible===(!stored&&(seat===0?['spear','shield']:seat===6?['gladius','shield']:['bow']).includes(key))),result});}}
await page.selectOption('#role','0');await page.locator('[data-stage="deck-armed"]').click();await page.locator('#top').click();await page.screenshot({path:out+'/stages-top.png',fullPage:true});
} catch(e){errors.push(String(e));} finally{await browser.close();}
const report={passed:!errors.length&&checks.length===15&&checks.every(c=>c.passed),checks,errors,scope:'Public factories, per-person ownership stages and interactive position samples; not natural movement, picking animation or shoreline validation.'};await writeFile(out+'/web-stage-report.json',JSON.stringify(report,null,2));console.log(JSON.stringify({passed:report.passed,checks:checks.length,failures:checks.filter(c=>!c.passed),errors}));if(!report.passed)process.exitCode=1;
