import {chromium} from '../../../tools/shot/node_modules/playwright/index.mjs';import {writeFile,mkdir} from 'node:fs/promises';import assert from 'node:assert/strict';
const out=new URL('../../artifacts/pipeline/citadel-tier-lighting/',import.meta.url);await mkdir(out,{recursive:true});const browser=await chromium.launch({channel:'chrome',headless:true,args:['--use-angle=metal']});const reports={};
try{for(const variant of ['before','after']){const page=await browser.newPage({viewport:{width:1440,height:900}}),errors=[];page.on('pageerror',e=>errors.push(String(e)));
if(variant==='before')await page.route('**/src/world/citadel/tierLighting.js*',r=>r.fulfill({contentType:'text/javascript',body:'export function applyCitadelTierLighting(){}'}));
await page.goto('http://localhost:8931/TigerMessenger/?autostart=1&citadelCommonFrame=1&citadelOldHarbor=1',{timeout:180000});await page.waitForFunction(()=>window.__tm?.scene?.getObjectByName('old-shore-blender-rock-support'),null,{timeout:180000});
reports[variant]={};for(const [label,phase]of [['day',.5],['night',.85]]){const row=await page.evaluate(async(phase)=>{const t=window.__tm,T=t.THREE,c=t.scene.getObjectByName('castleContainer');t.P.daySpeed=0;t.P.timeOfDay=phase;t.cameraRig.update=()=>{};await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));t.camera.position.copy(c.localToWorld(new T.Vector3(0,34,170)));t.camera.up.set(0,1,0).transformDirection(c.matrixWorld);t.camera.lookAt(c.localToWorld(new T.Vector3(-6,14,42)));t.camera.fov=52;t.camera.updateProjectionMatrix();t.renderer.render(t.scene,t.camera);
let frames=null;if(phase===.85){const times=[];for(let i=0;i<65;i++)times.push(await new Promise(r=>requestAnimationFrame(r)));const intervals=times.slice(21).map((v,i)=>v-times[i+20]).sort((a,b)=>a-b);frames={samples:intervals.length,medianMs:intervals[Math.floor(intervals.length/2)],p95Ms:intervals[Math.floor(intervals.length*.95)],scope:'headless rAF intervals including entire game workload; not an isolated GPU timer'};}const old=c.getObjectByName('highland-light-volumes'),fresh=c.getObjectByName('citadel-new-city-lighting'),lights=[];for(const [side,root]of [['old',old],['new',fresh]])root.traverse(o=>{if(o.isPointLight)lights.push({side,name:o.name,position:o.position.toArray(),world:o.getWorldPosition(new T.Vector3()).toArray(),energy:o.intensity,color:o.color.getHex(),radius:o.distance});});const geometry={meshes:0,vertices:0,indices:0};c.traverse(o=>{if(o.isMesh){geometry.meshes++;geometry.vertices+=o.geometry.attributes.position.count;geometry.indices+=o.geometry.index?.count||0;}});return {phase,frames,geometry,lights,profile:c.userData.tierLighting||null,drawCalls:t.renderer.info.render.calls,triangles:t.renderer.info.render.triangles,image:t.renderer.domElement.toDataURL('image/png')};},phase);
await writeFile(new URL(variant+'-'+label+'.png',out),Buffer.from(row.image.split(',')[1],'base64'));delete row.image;reports[variant][label]=row;}
reports[variant].errors=errors;assert.equal(errors.length,0);await page.close();}
await writeFile(new URL('report.json',out),JSON.stringify(reports,null,2));assert.equal(reports.after.night.lights.length,6);assert.ok(reports.after.day.lights.every(l=>l.energy===0));assert.ok(reports.after.night.lights.every(l=>l.energy>0));assert.deepEqual(reports.before.night.geometry,reports.after.night.geometry);
await writeFile(new URL('report.json',out),JSON.stringify(reports,null,2));const profile=reports.after.night.profile;profile.expectedWorld=reports.after.night.lights;await writeFile(new URL('../../godot/data/citadel-tier-lighting.json',import.meta.url),JSON.stringify(profile,null,2));console.log(JSON.stringify({before:reports.before.night.lights.length,after:reports.after.night.lights.length,drawCalls:reports.after.night.drawCalls,triangles:reports.after.night.triangles,passed:true}));
}finally{await browser.close();}
