const {chromium}=require('../../../tools/e2e/node_modules/playwright-core');const fs=require('fs');
(async()=>{const b=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--use-angle=metal']});try{const p=await b.newPage();await p.goto('http://localhost:8931/TigerMessenger/?autostart=1');await p.waitForFunction(()=>window.__tm?.scene.getObjectByName('highland-west-city'),null,{timeout:180000});const report=await p.evaluate(async()=>{
 const T=await import('three'),{createFisherBoat}=await import('/TigerMessenger/src/assets/harbor.js'),{createWarshipWaterRoutes}=await import('/TigerMessenger/src/world/warshipWaterRoutes.js'),{createWarshipClearance}=await import('/TigerMessenger/src/world/warshipClearance.js'),{joinWaterPaths,reverseWaterPath}=await import('/TigerMessenger/src/world/warshipRouteComposition.js');
 const data=await fetch('/TigerMessenger/godot/data/citadel-harbor-approach.json').then(r=>r.json());if(!data.verified)throw Error('Unverified source');
 const points=data.poses.map(p=>new T.Vector3(...p.position).normalize()),path={poses:data.poses,points,length:points.slice(1).reduce((n,p,i)=>n+p.angleTo(points[i])*160,0)};
 const boat=createFisherBoat();boat.scale.setScalar(data.scale);const solver=createWarshipWaterRoutes(window.__tm.scene,160),guard=createWarshipClearance(boat,solver.obstacles),combined=joinWaterPaths(path,reverseWaterPath(path));let checks=0;
 for(let i=0;i<=200;i++){solver.place(boat,combined,i/200);const hit=guard.clear(boat.position,boat.quaternion,boat.scale);if(!hit.clear)throw Error('Composed playback collision '+JSON.stringify({i,...hit}));checks++;}
 const before=new T.Group(),after=new T.Group();solver.place(before,combined,.5-1e-8);solver.place(after,combined,.5+1e-8);
 const positionJump=before.position.distanceTo(after.position),rotationJump=before.quaternion.angleTo(after.quaternion);
 const passed=positionJump<.00001&&rotationJump<.00001&&boat.position.distanceTo(new T.Vector3(...data.poses[0].position))<.00001;
 return {passed,checks,positionJump,rotationJump,segments:combined.segments.length,posesRetained:combined.segments.map(s=>s.poses.length),scope:'Original vessel on joined dock-in / reverse-out path; no global ocean leg, crew boarding or scene trigger verification'};
 });fs.writeFileSync('TigerMessenger/artifacts/pipeline/citadel-plaza-horse/harbor-composition.json',JSON.stringify(report,null,2));console.log(report);if(!report.passed)throw Error('Composition failed');}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1});
