import {chromium} from '../../../tools/shot/node_modules/playwright/index.mjs';
import {writeFile} from 'node:fs/promises';
const b=await chromium.launch({channel:'chrome',headless:true,args:['--use-angle=metal']});
try{const page=await b.newPage();await page.addInitScript(()=>{const raf=requestAnimationFrame.bind(window);window.requestAnimationFrame=cb=>cb.name==='animate'?0:raf(cb);});await page.goto('http://localhost:8931/TigerMessenger/?autostart=1&highlandReview=1');await page.waitForFunction(()=>window.__tm?.scene.getObjectByName('highland-gate'),null,{timeout:240000});
const result=await page.evaluate(async()=>{const t=window.__tm,T=t.THREE,g=t.scene.getObjectByName('highland-gate'),{resolveCollisions}=await import('/TigerMessenger/src/world/collision.js');g.updateMatrixWorld(true);const sample=g.userData.sampleGroundRadius,wall=g.userData.resolveWalls,point=g.userData.toRailWorld;const routes={passage:[],stairs:[]};for(let z=-32;z<=32;z+=2)routes.passage.push(point(-3.15,.05,z));for(let i=0;i<=20;i++){const v=i/20;routes.stairs.push(point(-3.15-14.85*v,.05+2.42*v,-32+10*v));}const results={};
for(const [name,waypoints]of Object.entries(routes)){const pos=waypoints[0].clone(),velocity=new T.Vector3(),prev=new T.Vector3(),up=new T.Vector3(),actor={onGround:true};const h=sample(pos);if(h!=null)pos.normalize().multiplyScalar(h);let seconds=0,stalledAt=null;
 for(const [i,target]of waypoints.slice(1).entries()){let ticks=0;while(pos.distanceTo(target)>.48&&ticks++<900){prev.copy(pos);up.copy(pos).normalize();velocity.copy(target).sub(pos);velocity.addScaledVector(up,-velocity.dot(up)).normalize().multiplyScalar(2);velocity.addScaledVector(up,-.18);resolveCollisions(pos,velocity,1/60,[],actor,()=>{},null,sample);wall(prev,pos,velocity);seconds+=1/60;}if(ticks>=900){stalledAt=i+1;break;}}
 results[name]={stalledAt,seconds,endpoint:g.worldToLocal(pos.clone()).toArray(),supported:sample(pos)!=null};}
return {results,passed:Object.values(results).every(r=>r.stalledAt===null&&r.supported),scope:'Actual movement/ground/wall solver driven by synthetic waypoints; not manual keyboard playthrough'};});await writeFile('TigerMessenger/artifacts/pipeline/highland-gate-thirty-rounds/r30-walk-solver.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result));if(!result.passed)process.exitCode=1;}finally{await b.close();}
