import {chromium} from '../../../tools/shot/node_modules/playwright/index.mjs';import {readFile,writeFile,mkdir} from 'node:fs/promises';import assert from 'node:assert/strict';
const out=new URL('../../artifacts/pipeline/citadel-faceted-towers/',import.meta.url);await mkdir(out,{recursive:true});const b=await chromium.launch({channel:'chrome',headless:true,args:['--use-angle=metal']});const reports={};
try{for(const version of ['before','after']){const p=await b.newPage({viewport:{width:1440,height:1000}}),errors=[];p.on('pageerror',e=>errors.push(String(e)));if(version==='before'){const body=await readFile(new URL('before-source.js',out),'utf8');await p.route('**/targetCastleSilhouette.js*',r=>r.fulfill({contentType:'text/javascript',body}));}
await p.goto('http://localhost:8931/TigerMessenger/?autostart=1',{timeout:180000});await p.waitForFunction(()=>window.__tm?.scene.getObjectByName('citadel-target-castle-silhouette'),null,{timeout:180000});
const result=await p.evaluate(async()=>{const t=window.__tm,T=t.THREE,c=t.scene.getObjectByName('castleContainer'),city=c.getObjectByName('highland-west-city'),root=city.getObjectByName('citadel-target-castle-silhouette');t.cameraRig.update=()=>{};t.P.daySpeed=0;t.P.timeOfDay=.85;c.updateWorldMatrix(true,true);
const pictures={};for(const [name,eye,look,fov]of [['castle',[99,49,69],[61,32,-1],43],['overall',[110,44,136],[37,19,40],54]]){t.camera.position.copy(city.localToWorld(new T.Vector3(...eye)));t.camera.up.set(0,1,0).transformDirection(city.matrixWorld);t.camera.lookAt(city.localToWorld(new T.Vector3(...look)));t.camera.fov=fov;t.camera.updateProjectionMatrix();await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));t.renderer.render(t.scene,t.camera);pictures[name]=t.renderer.domElement.toDataURL('image/png');}
const ray=new T.Raycaster();ray.layers.enableAll();ray.far=1;
const tests=[];for(const [x,y,z]of [[48.2,21.3,-.1],[72,21.3,.8],[63.8,21.3,-10.1]])for(const dx of [0,1]){ray.set(city.localToWorld(new T.Vector3(x+dx,y,z+.6)),new T.Vector3(0,0,-1).transformDirection(city.matrixWorld));const hit=ray.intersectObject(root,true)[0];tests.push({x:x+dx,y,z,hit:hit?city.worldToLocal(hit.point.clone()).toArray():null,material:hit?.object.material.emissive?.getHexString()});}
return {shape:city.userData.targetCastleSilhouette,wfc:root.userData.facadeWfc,source:root.userData.sourceId,windowRays:tests,pictures};});
for(const [name,data]of Object.entries(result.pictures))await writeFile(new URL(version+'-'+name+'.png',out),Buffer.from(data.split(',')[1],'base64'));delete result.pictures;result.errors=errors;assert.equal(errors.length,0);reports[version]=result;await p.close();}
assert.equal(reports.after.shape.facetedTowers,3);assert.equal(reports.after.wfc.towers.length,7);assert.ok(reports.after.wfc.towers.every(t=>t.openings>0));for(let i=0;i<6;i+=2){assert.ok(reports.after.windowRays[i].hit);assert.ok(reports.after.windowRays[i+1].hit);assert.ok(reports.after.windowRays[i].hit[2]<reports.after.windowRays[i+1].hit[2]-.2);}
await writeFile(new URL('report.json',out),JSON.stringify(reports,null,2));console.log(JSON.stringify({shape:reports.after.shape,facades:reports.after.wfc.towers.length,windowRays:reports.after.windowRays,passed:true}));
}finally{await b.close();}
