import {chromium} from '../../../tools/shot/node_modules/playwright/index.mjs';
import {mkdir,writeFile,readFile} from 'node:fs/promises';import assert from 'node:assert/strict';
const out=new URL('../../artifacts/pipeline/citadel-warm-light-target/',import.meta.url);await mkdir(out,{recursive:true});
const b=await chromium.launch({channel:'chrome',headless:true,args:['--use-angle=metal']});const reports={};
try{for(const version of ['before','after']){const p=await b.newPage({viewport:{width:1440,height:1000}}),errors=[];p.on('pageerror',e=>errors.push(String(e)));
if(version==='before')for(const file of ['tierLighting.js','newCityLighting.js','claudeHouses.js','targetCastleSilhouette.js']){const body=await readFile(new URL('before-sources/'+file,out),'utf8');await p.route('**/src/world/citadel/'+file+'*',r=>r.fulfill({contentType:'text/javascript',body}));}
await p.goto('http://localhost:8931/TigerMessenger/?autostart=1',{timeout:180000});await p.waitForFunction(()=>window.__tm?.scene.getObjectByName('citadel-retaining-planting'),null,{timeout:180000});reports[version]={};
for(const [label,phase]of [['night',.85],['day',.5]]){
const report=await p.evaluate(async({phase})=>{const t=window.__tm,T=t.THREE,c=t.scene.getObjectByName('castleContainer');t.P.daySpeed=0;t.P.timeOfDay=phase;t.cameraRig.update=()=>{};await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));c.updateWorldMatrix(true,true);
const mats=new Map(),lights=[],geometry={meshes:0,vertices:0,indices:0};c.traverse(o=>{if(o.isMesh){geometry.meshes++;geometry.vertices+=o.geometry.attributes.position.count;geometry.indices+=o.geometry.index?.count||0;for(const m of Array.isArray(o.material)?o.material:[o.material])if(m.name?.startsWith('claude-house-win_'))mats.set(m.name,{name:m.name,color:m.color.getHexString(),emissive:m.emissive.getHexString(),energy:m.emissiveIntensity});}});
for(const [side,name]of [['old','highland-light-volumes'],['new','citadel-new-city-lighting']])c.getObjectByName(name).traverse(o=>{if(o.isPointLight)lights.push({side,name:o.name,position:o.position.toArray(),world:o.getWorldPosition(new T.Vector3()).toArray(),energy:o.intensity,color:o.color.getHex(),radius:o.distance});});
const pictures={};for(const [name,eye,look,fov]of [['harbor',[-24,29,124],[-12,2,81],43],['cities',[0,34,170],[-6,14,42],52]]){t.camera.position.copy(c.localToWorld(new T.Vector3(...eye)));t.camera.up.set(0,1,0).transformDirection(c.matrixWorld);t.camera.lookAt(c.localToWorld(new T.Vector3(...look)));t.camera.fov=fov;t.camera.updateProjectionMatrix();await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));t.renderer.render(t.scene,t.camera);pictures[name]=t.renderer.domElement.toDataURL('image/png');}
return {phase,materials:[...mats.values()],lights,geometry,pictures,profile:c.userData.tierLighting,drawCalls:t.renderer.info.render.calls};},{phase});
for(const [name,data]of Object.entries(report.pictures))await writeFile(new URL(version+'-'+label+'-'+name+'.png',out),Buffer.from(data.split(',')[1],'base64'));delete report.pictures;reports[version][label]=report;
}assert.equal(errors.length,0);reports[version].errors=errors;await p.close();}
assert.deepEqual(reports.before.night.geometry,reports.after.night.geometry);assert.equal(reports.after.night.lights.length,6);assert.ok(reports.after.day.lights.every(l=>l.energy===0));assert.ok(reports.after.night.materials.length>0);assert.ok(reports.after.night.materials.every(m=>m.emissive!=='ff7084'));
const profile=reports.after.night.profile;profile.expectedWorld=reports.after.night.lights;await writeFile(new URL('../../godot/data/citadel-tier-lighting.json',import.meta.url),JSON.stringify(profile,null,2));await writeFile(new URL('report.json',out),JSON.stringify(reports,null,2));console.log(JSON.stringify({geometryUnchanged:true,materials:reports.after.night.materials,lights:reports.after.night.lights.map(l=>({side:l.side,energy:l.energy})),passed:true}));
}finally{await b.close();}
