import {chromium} from '../../../tools/shot/node_modules/playwright/index.mjs';
import {writeFile} from 'node:fs/promises';import assert from 'node:assert/strict';
const out=new URL('../../artifacts/pipeline/citadel-front-port-berth/',import.meta.url);
const browser=await chromium.launch({channel:'chrome',headless:true,args:['--use-angle=metal']});
try{const p=await browser.newPage();const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://localhost:8931/TigerMessenger/?autostart=1',{timeout:180000});await p.waitForFunction(()=>window.__tm?.messenger?.landmarks?.canalBoats?.boats[0]?.userData.frontHarborBerth,null,{timeout:180000});
 const before=await p.evaluate(()=>{const t=window.__tm,b=t.messenger.landmarks.canalBoats.boats[0];t.player.position.copy(b.userData.frontHarborBerth.exit).addScaledVector(b.userData.frontHarborBerth.exit.clone().normalize(),.08);t.player.velocity.set(0,0,0);return {uuid:b.uuid,old:t.messenger.landmarks.boat.uuid,position:b.position.toArray(),count:t.messenger.landmarks.canalBoats.boats.length};});
 await p.keyboard.press('KeyF');await p.waitForFunction(()=>window.__tm.player.riding);await p.keyboard.press('KeyF');await p.waitForFunction(()=>!window.__tm.player.riding);
 const ashore=await p.evaluate(()=>{const t=window.__tm,b=t.messenger.landmarks.canalBoats.boats[0];return {distance:t.player.position.distanceTo(b.userData.frontHarborBerth.exit),snap:b.userData.needsSnap};});assert.ok(ashore.distance<.6);assert.equal(ashore.snap,false);
 await p.keyboard.press('KeyF');await p.waitForFunction(()=>window.__tm.player.riding);await p.keyboard.down('KeyW');await p.waitForTimeout(500);await p.keyboard.up('KeyW');await p.keyboard.press('KeyF');await p.waitForFunction(()=>!window.__tm.player.riding);
 const after=await p.evaluate(()=>{const t=window.__tm,b=t.messenger.landmarks.canalBoats.boats[0],pos=b.position.clone();t.messenger.landmarks.canalBoats.update(2);return {uuid:b.uuid,old:t.messenger.landmarks.boat.uuid,position:b.position.toArray(),drift:b.position.distanceTo(pos),moored:b.userData.harborDocked,snap:b.userData.needsSnap,count:t.messenger.landmarks.canalBoats.boats.length};});assert.equal(before.uuid,after.uuid);assert.equal(before.old,after.old);assert.equal(after.count,3);assert.equal(after.drift,0);assert.equal(after.snap,false);assert.equal(errors.length,0);
 const report={before,ashore,after,errors,passed:true,scope:'Default Web entry; real F mount/dismount at berth and brief WASD drive. No soldier unloading or full navigation certification.'};await writeFile(new URL('web-resident-test.json',out),JSON.stringify(report,null,2));console.log(JSON.stringify(report));
}finally{await browser.close();}
