import {chromium} from '../../../tools/shot/node_modules/playwright/index.mjs';import {mkdir,writeFile} from 'node:fs/promises';import assert from 'node:assert/strict';
const out=new URL('../../artifacts/pipeline/citadel-old-city-slope/',import.meta.url);await mkdir(out,{recursive:true});const b=await chromium.launch({channel:'chrome',headless:true,args:['--use-angle=metal']});
try{const reports={};for(const version of ['before','after']){const p=await b.newPage({viewport:{width:1440,height:1000}}),errors=[];p.on('pageerror',e=>{errors.push(e.message);console.log(e.message);});if(version==='before')await p.route('**/src/world/citadel/oldCityCoastalSlope.js*',r=>r.fulfill({contentType:'text/javascript',body:'export function applyOldCityCoastalSlope(){}'}));
 await p.goto('http://localhost:8931/TigerMessenger/?autostart=1',{timeout:180000});await p.waitForFunction(()=>window.__tm?.messenger,null,{timeout:180000});
 const report=await p.evaluate(async()=>{const t=window.__tm,T=t.THREE,c=t.scene.getObjectByName('castleContainer'),front=c.getObjectByName('citadel-front-harbor'),f=c.getObjectByName('highland-town-foundation-platform'),mesh=c.getObjectByName('citadel-coastal-cliff-seal');t.cameraRig.update=()=>{};t.P.daySpeed=0;t.P.timeOfDay=.85;const images={};
 for(const [name,frame,eye,look,fov]of [['port',front,[65,16,124],[35,1,91],48],['old-city',f,[48,24,64],[0,-2,13],48]]){t.camera.position.copy(frame.localToWorld(new T.Vector3(...eye)));t.camera.up.set(0,1,0).transformDirection(frame.matrixWorld);t.camera.lookAt(frame.localToWorld(new T.Vector3(...look)));t.camera.fov=fov;t.camera.updateProjectionMatrix();await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));t.renderer.render(t.scene,t.camera);images[name]=t.renderer.domElement.toDataURL('image/png');}
 const ray=new T.Raycaster();ray.layers.enableAll();const objects=[];c.traverse(o=>{let v=true;for(let q=o;q;q=q.parent)v&&=q.visible;if(o.isMesh&&v&&!o.userData.isOutline&&!o.userData.backlitHighlight&&!/highlight|outline|shadow/i.test(o.name))objects.push(o);});const picks=[];
 for(const [x,y]of [[.45,.50],[.39,.50],[.50,.58],[.37,.65],[.45,.35],[.6,.56]]){ray.setFromCamera(new T.Vector2(x*2-1,1-y*2),t.camera);const hit=ray.intersectObjects(objects,false)[0];picks.push({x,y,name:hit?.object.name,local:hit?f.worldToLocal(hit.point.clone()).toArray():null});}
 return {triangles:(mesh.geometry.index?.count||mesh.geometry.attributes.position.count)/3,slope:mesh.userData.oldCityCoastalSlope,route:c.userData.oldShoreApproach.route,images,picks};});
 for(const [name,image]of Object.entries(report.images))await writeFile(new URL(version+'-'+name+'.png',out),Buffer.from(image.split(',')[1],'base64'));delete report.images;reports[version]={...report,errors};assert.equal(errors.length,0);await p.close();}
 assert.deepEqual(reports.before.route,reports.after.route);assert.ok(reports.after.slope);await writeFile(new URL('comparison.json',out),JSON.stringify(reports,null,2));console.log(JSON.stringify({before:reports.before.triangles,after:reports.after.triangles,slope:reports.after.slope,routePreserved:true,picks:reports.after.picks}));
}finally{await b.close();}
