import {chromium} from '../../../tools/shot/node_modules/playwright/index.mjs';import {mkdir,writeFile} from 'node:fs/promises';import assert from 'node:assert/strict';
const out=new URL('../../artifacts/pipeline/citadel-default-entry/',import.meta.url);await mkdir(out,{recursive:true});
const browser=await chromium.launch({channel:'chrome',headless:true,args:['--use-angle=metal']});const report={};
try{for(const [label,query]of [['default',''],['explicit','?citadelCommonFrame=1&citadelOldHarbor=1'],['legacy','?citadelCommonFrame=0&citadelOldHarbor=0']]){
 const page=await browser.newPage({viewport:{width:1440,height:900}}),errors=[];page.on('pageerror',e=>errors.push(String(e)));await page.goto('http://localhost:8931/TigerMessenger/'+query,{timeout:180000});await page.waitForFunction(()=>window.__tm?.messenger,null,{timeout:180000});
 const row=await page.evaluate(async()=>{const t=window.__tm,T=t.THREE,m=t.messenger,c=t.scene.getObjectByName('castleContainer'),city=c.getObjectByName('highland-west-city'),horse=t.scene.getObjectByName('citadel-trojan-horse'),h=t.scene.getObjectByName('old-harbor-scene'),raid=m.landmarks.citadelRange.nightInfiltration;t.P.daySpeed=0;t.P.timeOfDay=.85;t.cameraRig.update=()=>{};await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));t.scene.updateMatrixWorld(true);
 const names=['old-shore-blender-rock-support','citadel-old-city-support-spur','citadel-shore-cypress-groves','citadel-old-shore-arcades'];const geometry={};for(const name of names){const node=c.getObjectByName(name);if(!node){geometry[name]=null;continue;}let meshes=0,triangles=0;node.traverse(o=>{if(o.isMesh){meshes++;triangles+=(o.geometry.index?.count||o.geometry.attributes.position.count)/3;}});geometry[name]={meshes,triangles,matrix:node.matrixWorld.toArray()};}
 const refs={landmarks:Object.keys(m.landmarks).sort(),citadel:Object.keys(m.landmarks.citadelRange).sort(),raidAttached:horse.userData.nightInfiltration===raid.root,raidActors:raid.root.userData.groups.reduce((n,g)=>n+g.userData.records.length,0),boatRetained:m.landmarks.boat===h.getObjectByName('fisher-boat')};
 t.camera.position.copy(c.localToWorld(new T.Vector3(0,34,170)));t.camera.up.set(0,1,0).transformDirection(c.matrixWorld);t.camera.lookAt(c.localToWorld(new T.Vector3(-6,14,42)));t.camera.fov=52;t.camera.updateProjectionMatrix();t.renderer.render(t.scene,t.camera);
 return {frame:!!c.userData.commonSurfaceFrame,harborGrade:!!h.userData.oldHarborOceanGrade,geometry,refs,horseError:horse.getWorldPosition(new T.Vector3()).distanceTo(c.localToWorld(new T.Vector3(...city.userData.horseReservation))),image:t.renderer.domElement.toDataURL('image/png')};});await writeFile(new URL(label+'.png',out),Buffer.from(row.image.split(',')[1],'base64'));delete row.image;row.errors=errors;report[label]=row;assert.equal(errors.length,0);await page.close();}
 await writeFile(new URL('report.json',out),JSON.stringify(report,null,2));
 assert.equal(report.default.frame,true);assert.equal(report.default.harborGrade,true);assert.deepEqual(report.default.geometry,report.explicit.geometry);assert.ok(Object.values(report.default.geometry).every(Boolean));assert.equal(report.legacy.frame,false);assert.equal(report.legacy.harborGrade,false);assert.ok(Object.values(report.legacy.geometry).every(v=>v===null));assert.deepEqual(report.default.refs.landmarks,report.legacy.refs.landmarks);assert.deepEqual(report.default.refs.citadel,report.legacy.refs.citadel);assert.equal(report.default.refs.raidActors,8);assert.equal(report.default.refs.raidAttached,true);assert.equal(report.default.refs.boatRetained,true);assert.ok(report.default.horseError<.001);
 report.passed=true;await writeFile(new URL('report.json',out),JSON.stringify(report,null,2));console.log(JSON.stringify({passed:true,defaultFrame:report.default.frame,raidActors:report.default.refs.raidActors,refs:report.default.refs}));
}finally{await browser.close();}
