import assert from 'node:assert/strict';
import {createBoardingGate} from '../../src/world/citadel/boardingGate.js';
const poses=[];const gate=createBoardingGate(p=>poses.push(p));
assert.equal(gate.deploy({stopped:false}),false);
assert.equal(gate.enter('soldier-21'),false);
assert.equal(gate.deploy({stopped:true}),true);
gate.tick(.75);assert.equal(gate.snapshot().progress,.5);
assert.equal(gate.enter('soldier-21'),false);
assert.equal(gate.retract(),false);
gate.tick(.75);assert.equal(gate.enter('soldier-21'),true);
assert.equal(gate.enter('soldier-21'),false);
assert.equal(gate.enter('messenger'),true);
assert.equal(gate.retract(),false);
assert.equal(gate.snapshot().canSail,false);
assert.equal(gate.leave('unknown'),false);
gate.leave('soldier-21');assert.equal(gate.retract(),false);
gate.leave('messenger');assert.equal(gate.retract(),true);
assert.equal(gate.enter('late-arrival'),false);
assert.equal(gate.deploy({stopped:true}),false);
gate.tick(1.5);assert.equal(gate.snapshot().canSail,true);
assert.equal(poses.at(-1),0);
assert.throws(()=>gate.tick(NaN));
console.log('PASS: moving-ship rejection, mid-motion entry/reversal guards, identity occupancy, multi-actor release, retract/sail interlock');
