import fs from 'node:fs';
import {createTargetEastCliffProductionRelease} from '../../../src/world/citadel/targetEastCliffProductionRelease.js';
import {createTargetUserMarkedProductionRelease} from '../../../src/world/citadel/targetUserMarkedProductionRelease.js';
import {prepareCitadelRailStartup} from '../../../src/world/citadel/citadelRailStartup.js';
import {factoryFreightStops,freightTrainingDepot} from '../../../src/world/bookshopLoadingYards.js';
import {createFreightInterlocking} from '../../../src/gameplay/robotOps/freightInterlocking.js';
import {FREIGHT_PITCH} from '../../../src/assets/freightTrain.js';
const pd=globalThis.document,pw=globalThis.window;globalThis.document??={getElementById:()=>null};globalThis.window??={addEventListener(){}};
let createChristchurchTramSourceCurves;try{({createChristchurchTramSourceCurves}=await import('../../../src/world/tramSystem.js'));}finally{if(pd===undefined)delete globalThis.document;else globalThis.document=pd;if(pw===undefined)delete globalThis.window;else globalThis.window=pw;}
const base=new URL('../citadel-east-shore-route-20261006/',import.meta.url),audit=JSON.parse(fs.readFileSync(new URL('remesh-expanded-shift-audit.json',base))),terrainArtifact=JSON.parse(fs.readFileSync(new URL('remesh-expanded-geometry.json',base)));
const sourceCurves=createChristchurchTramSourceCurves(),retainedRelease=createTargetUserMarkedProductionRelease({sourceCurves}),result=createTargetEastCliffProductionRelease({enabled:true,sourceCurves,retainedRelease,candidateInput:audit.candidateInput,terrainArtifact,seaRadiusAt:()=>160.5});
const old=prepareCitadelRailStartup(sourceCurves,retainedRelease.specs),services=['red','blue'].map((l,i)=>({curve:result.startupPreview.curves[l],trackLen:result.startupPreview.curves[l].getLength(),direction:i?-1:1,progress:0,wagons:[],tram:{userData:{variant:l}}}));
const nearest=(curve,point)=>{let best=Infinity,u=0;for(let i=0;i<4096;i++){const d=curve.getPointAt(i/4096).distanceTo(point);if(d<best){best=d;u=i/4096;}}return{u,distance:best,world:curve.getPointAt(u).toArray()};};
const stations=[];for(const lane of['red','blue'])for(const stop of[...factoryFreightStops(160),freightTrainingDepot(160)]){const a=nearest(old.curves[lane],stop.center),b=nearest(result.startupPreview.curves[lane],stop.center),original=old.splice.lanes[lane].mapSplicedProgress(a.u),mapped=result.startupPreview.splice.lanes[lane].mapOriginalProgress(original.progress);stations.push({lane,stop:stop.name,oldProjection:a,newProjection:b,preservedWorldError:result.startupPreview.curves[lane].getPointAt(mapped.progress).distanceTo(old.curves[lane].getPointAt(a.u))});}
const out={...result.report,ranges:result.release.ranges,mapping:result.mapping,startup:result.startupPreview.report,stationProjection:{method:'Same 4096 finite samples as actual tramSystem; retained old world point also migrated exactly. Not a dwell/door gameplay test.',stations},interlocking:{method:'Actual findFreightJunctions on prepared global center and same new service curve references, empty services at u0; not a traffic stress test.',zones:createFreightInterlocking(result.startupPreview.curves.center,services,FREIGHT_PITCH).zones},seaRadiusSource:'Explicit diagnostic sphere radius160.5; center guide only. Actual vehicle/wave reserve is not certified.'};
fs.writeFileSync(new URL('adapter-audit.json',import.meta.url),JSON.stringify(out,null,2));
console.log(JSON.stringify({version:out.version,shape:out.laneAudit,impact:out.sourceImpact,center:out.centerAnchor,sea:out.seaGuide,stationMaxPreservedWorldError:Math.max(...stations.map(s=>s.preservedWorldError)),zones:out.interlocking.zones.length},null,2));
