import * as THREE from 'three';
import {finishFactoryMaterial} from './factoryMaterials.js';
export function factoryKit(root){
 const material=(color,metalness=0,roughness=.75)=>new THREE.MeshStandardMaterial({color,metalness,roughness});
 const M={stone:material(0xb5b2a3),trim:material(0xd2cbb6),slate:material(0x4c626d,.25),iron:material(0x293b42,.6),brass:material(0xa88954,.6),copper:material(0x996b49,.65),wood:material(0x79624a),dark:material(0x1b252a),glass:material(0x77929a,.3),amber:new THREE.MeshStandardMaterial({color:0xe9be79,emissive:0xc4883e,emissiveIntensity:.35,roughness:.5})};
 M.glass=new THREE.MeshPhysicalMaterial({color:0x7898a1,metalness:.15,roughness:.24,clearcoat:.8,clearcoatRoughness:.16,transparent:true,opacity:.65,depthWrite:false,side:THREE.DoubleSide});
 for(const key of['stone','slate','iron','brass','copper'])finishFactoryMaterial(M[key],key);
 function mesh(g,m,x=0,y=0,z=0,p=root){const o=new THREE.Mesh(g,m);o.position.set(x,y,z);o.castShadow=o.receiveShadow=true;p.add(o);return o;}
 const box=(w,h,d,x,y,z,m=M.stone,p=root)=>mesh(new THREE.BoxGeometry(w,h,d),m,x,y,z,p);
 const cyl=(r,h,x,y,z,m=M.iron,p=root)=>mesh(new THREE.CylinderGeometry(r,r,h,20),m,x,y,z,p);
 function beam(a,b,r=.035,m=M.iron,p=root){const v=new THREE.Vector3(...b).sub(new THREE.Vector3(...a));if(v.lengthSq()<1e-12)return new THREE.Group();const o=cyl(r,v.length(),...new THREE.Vector3(...a).addScaledVector(v,.5).toArray(),m,p);o.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),v.normalize());return o;}
 function pipe(points,r=.08,m=M.copper,p=root){return mesh(new THREE.TubeGeometry(new THREE.CatmullRomCurve3(points.map(p=>new THREE.Vector3(...p))),Math.max(12,points.length*2),r,r<.04?5:8,false),m,0,0,0,p);}
 const torus=(r,t,x,y,z,m=M.brass,p=root)=>mesh(new THREE.TorusGeometry(r,t,8,32),m,x,y,z,p);
 function sign(text,w,h,x,y,z,p=root){const c=document.createElement('canvas');c.width=1024;c.height=192;const ctx=c.getContext('2d');ctx.fillStyle='#d8d0b9';ctx.fillRect(0,0,c.width,c.height);ctx.strokeStyle='#564d3e';ctx.lineWidth=9;ctx.strokeRect(7,7,1010,178);ctx.fillStyle='#262a29';ctx.textAlign='center';ctx.textBaseline='middle';ctx.font='bold 94px serif';ctx.fillText(text,512,103,960);const tex=new THREE.CanvasTexture(c);tex.colorSpace=THREE.SRGBColorSpace;return mesh(new THREE.PlaneGeometry(w,h),new THREE.MeshBasicMaterial({map:tex}),x,y,z,p);}
 function arch(x,y,z,w,h,p=root,filled=true){const r=w/2,H=h-r,s=new THREE.Shape();s.moveTo(-r,0);s.lineTo(r,0);s.lineTo(r,H);s.absarc(0,H,r,0,Math.PI,false);s.closePath();if(filled)mesh(new THREE.ShapeGeometry(s,24),M.dark,x,y,z,p);const pts=[[x-r,y,z+.04],[x-r,y+H,z+.04]];for(let i=0;i<=24;i++){const a=Math.PI-i*Math.PI/24;pts.push([x+Math.cos(a)*r,y+H+Math.sin(a)*r,z+.04]);}pts.push([x+r,y,z+.04]);for(let i=1;i<pts.length;i++)beam(pts[i-1],pts[i],.075,M.trim,p);return {r,H};}
 function dome(x,y,z,r,h,p=root){mesh(new THREE.SphereGeometry(r,32,16,0,Math.PI*2,0,Math.PI/2),M.glass,x,y,z,p).scale.y=h/r;for(let k=0;k<16;k++){const a=k*Math.PI/8,pts=[];for(let j=0;j<=16;j++){const b=j*Math.PI/32;pts.push([x+Math.cos(a)*r*Math.sin(b),y+h*Math.cos(b),z+Math.sin(a)*r*Math.sin(b)]);}pipe(pts,.026,M.brass,p);}for(let j=0;j<4;j++){const b=j*Math.PI/10,t=torus(Math.cos(b)*r,.028,x,y+Math.sin(b)*h,z,M.brass,p);t.rotation.x=Math.PI/2;}cyl(.065,.5,x,y+h+.25,z,M.brass,p);mesh(new THREE.SphereGeometry(.14,12,8),M.brass,x,y+h+.55,z,p);}
 function roof(x,y,z,w,d,h,p=root,closed=true){for(const s of[-1,1]){const o=box(Math.hypot(w/2,h),.13,d,s*w/4+x,y+h/2,z,M.slate,p);o.rotation.z=-s*Math.atan2(h,w/2);const endZ=z+s*(d/2-.06),g=new THREE.BufferGeometry(),points=s>0?[x-w/2,y,endZ,x+w/2,y,endZ,x,y+h,endZ]:[x+w/2,y,endZ,x-w/2,y,endZ,x,y+h,endZ];g.setAttribute('position',new THREE.Float32BufferAttribute(points,3));g.computeVertexNormals();if(closed)mesh(g,M.stone,0,0,0,p);beam([x-w/2,y,endZ+s*.04],[x,y+h,endZ+s*.04],.055,M.iron,p);beam([x+w/2,y,endZ+s*.04],[x,y+h,endZ+s*.04],.055,M.iron,p);}beam([x,y+h,z-d/2],[x,y+h,z+d/2],.07,M.iron,p);}
 function gear(x,y,z,r,p=root){torus(r,.05,x,y,z,M.brass,p);cyl(.08,.12,x,y,z,M.iron,p).rotation.x=Math.PI/2;for(let i=0;i<12;i++){const a=i*Math.PI/6,o=box(.11,.16,.12,x+Math.sin(a)*r,y+Math.cos(a)*r,z,M.brass,p);o.rotation.z=-a;if(i%2===0)beam([x,y,z],[x+Math.sin(a)*r,y+Math.cos(a)*r,z],.025,M.brass,p);}}
 function crate(x,y,z,s=1,p=root){box(s,s,s,x,y+s/2,z,M.wood,p);for(const d of[-1,1])for(const k of[-.35,.35])box(.065,s+.03,.045,x+s*k,y+s/2,z+d*(s/2+.025),M.iron,p);}
 function wheel(x,y,z,r=.5,p=root){torus(r,.13,x,y,z,M.iron,p);torus(r*.64,.04,x,y,z,M.brass,p);for(let k=0;k<8;k++){const a=k*Math.PI/4;beam([x,y,z],[x+r*.8*Math.sin(a),y+r*.8*Math.cos(a),z],.035,M.iron,p);}mesh(new THREE.SphereGeometry(.12,10,8),M.brass,x,y,z,p);}
 return{M,mesh,box,cyl,beam,pipe,torus,sign,arch,dome,roof,gear,crate,wheel};
}
