import{chromium}from'/Users/panglaohu/Downloads/TigerInBamboo/tools/shot/node_modules/playwright/index.mjs';import{writeFileSync}from'node:fs';
const dir='/Users/panglaohu/Downloads/TigerInBamboo/TigerMessenger/artifacts/pipeline/robot-combat-audio';
const browser=await chromium.launch({channel:'chrome',headless:true,args:['--use-angle=metal']});const p=await browser.newPage();const errors=[];p.on('pageerror',e=>errors.push(e.message));
await p.addInitScript(()=>{const AC=window.AudioContext;window.AudioContext=class extends AC{constructor(...args){super(...args);window.testContext=this;window.testMeter=this.createAnalyser();window.testStream=this.createMediaStreamDestination();const old=AudioNode.prototype.connect;AudioNode.prototype.connect=function(to,...rest){if(to===this.context.destination){old.call(this,window.testMeter);old.call(this,window.testStream);}return old.call(this,to,...rest);};}};});
await p.goto('http://localhost:8931/TigerMessenger/artifacts/pipeline/robot-combat-audio/review.html');await p.click('[data-kind=locust]');await p.waitForTimeout(700);
await p.evaluate(()=>{window.parts=[];window.rec=new MediaRecorder(testStream.stream);rec.ondataavailable=e=>parts.push(e.data);rec.start();window.maxPeak=0;window.meterTimer=setInterval(()=>{const a=new Float32Array(testMeter.fftSize);testMeter.getFloatTimeDomainData(a);for(const v of a)maxPeak=Math.max(maxPeak,Math.abs(v));},5);});
const stages=[];for(const kind of ['locust','ant','beetle']){await p.click(`[data-kind=${kind}]`);await p.waitForTimeout(1800);stages.push(await p.evaluate(async()=>{const m=await import('/TigerMessenger/src/audio/worldSfx.js');return{stats:m.getRobotAudioSnapshot(),budget:m.getWorldSfxSnapshot()};}));}
await p.selectOption('#room','0.9');await p.click('[data-kind=ant]');await p.waitForTimeout(1500);await p.click('#crack');await p.waitForTimeout(600);await p.click('#hit');await p.waitForTimeout(400);await p.click('#kill');await p.waitForTimeout(700);
const result=await p.evaluate(async()=>{const m=await import('/TigerMessenger/src/audio/worldSfx.js');const before=m.getRobotAudioSnapshot();m.sfxRobotShot('locust',{x:500,y:0,z:0},{x:600,y:0,z:0});const far=m.getRobotAudioSnapshot().shots===before.shots;window.dispatchEvent(new KeyboardEvent('keydown',{code:'KeyM'}));m.sfxRobotShot('ant',{x:0,y:0,z:2},{x:0,y:0,z:20});const mute=m.getRobotAudioSnapshot().shots===before.shots;const pcmPeak=window.maxPeak;clearInterval(meterTimer);return{stats:m.getRobotAudioSnapshot(),far,mute,pcmPeak,context:testContext.state};});
const recording=await p.evaluate(async()=>{await new Promise(resolve=>{rec.onstop=resolve;rec.stop();});const blob=new Blob(parts,{type:'audio/webm'});return Array.from(new Uint8Array(await blob.arrayBuffer()));});writeFileSync(dir+'/preview.webm',Buffer.from(recording));writeFileSync(dir+'/check.json',JSON.stringify({stages,result,errors},null,2));console.log({result,errors});await browser.close();
