import {chromium} from '/Users/panglaohu/Downloads/TigerInBamboo/tools/shot/node_modules/playwright/index.mjs';import {writeFile} from 'node:fs/promises';
const out='TigerMessenger/artifacts/pipeline/crystal-core-live',b=await chromium.launch({channel:'chrome',headless:true,args:['--use-angle=metal']});
try{const p=await b.newPage({viewport:{width:1200,height:800}}),errors=[];p.on('console',m=>{if(m.type()==='error')console.log('ERROR',m.text())});p.on('pageerror',e=>{errors.push(e.message);console.log('PAGEERROR',e.message)});await p.goto('http://localhost:8931/TigerMessenger/?autostart=1',{waitUntil:'domcontentloaded'});await p.waitForFunction(()=>window.__tm?.messenger?.landmarks?.tramSystem,null,{timeout:180000});await p.waitForTimeout(2000);
const info=await p.evaluate(async()=>{const t=window.__tm,T=t.THREE,l=t.messenger.landmarks,{getCityFrame,dirToCityLocal}=await import('/TigerMessenger/src/world/crystalCityLayout.js'),f=getCityFrame();t.cameraRig.update=()=>{};t.P.daySpeed=0;t.P.timeOfDay=.38;t.scene.updateMatrixWorld(true);
const core=[...l.moebius.crystals.slice(0,3).map(r=>r.group),l.moebiusSwamp];if(l.crystalMotherPort?.root)core.push(l.crystalMotherPort.root);
for(const o of l.moebius.v7Shores.children)if(!o.name||/swamp|garden-connector/.test(o.name)||/^v7-bank-rock-[012]$/.test(o.name))core.push(o);
const unique=core.filter((o,i)=>core.indexOf(o)===i&&!core.some(parent=>parent!==o&&(()=>{for(let q=o.parent;q;q=q.parent)if(q===parent)return true;return false;})()));
const originals=unique.map(o=>({o,m:o.matrixWorld.clone()})),lake0=l.moebiusSwamp.position.clone(),cv=l.tramSystem.curves.blue;
window.rotatePreview=deg=>{const q=new T.Quaternion().setFromAxisAngle(f.center,-deg*Math.PI/180),rotation=new T.Matrix4().makeRotationFromQuaternion(q);for(const {o,m}of originals){const matrix=o.parent.matrixWorld.clone().invert().multiply(rotation).multiply(m);matrix.decompose(o.position,o.quaternion,o.scale);o.updateMatrix();}t.scene.updateMatrixWorld(true);const dir=lake0.clone().normalize().applyQuaternion(q);let nearest={distance:Infinity};for(let i=0;i<4000;i++){const u=i/4000,w=cv.getPointAt(u),dist=w.clone().normalize().angleTo(dir)*160;if(dist<nearest.distance)nearest={u,distance:dist};}return {deg,local:dirToCityLocal(dir),nearest};};
window.rotateView=(kind)=>{if(kind==='map'){const center=f.center.clone().multiplyScalar(150).addScaledVector(f.east,35);t.camera.position.copy(center).addScaledVector(f.center,180);t.camera.up.copy(f.north).negate();t.camera.lookAt(center);}else{const cv=l.tramSystem.curves[kind],eye=cv.getPointAt(.30),up=eye.clone().normalize();t.camera.position.copy(eye).addScaledVector(up,2.5);t.camera.up.copy(up);const s=l.moebiusSwamp.userData.inner||l.moebiusSwamp;t.camera.lookAt(s.localToWorld(new T.Vector3(0,40,0)));}t.camera.fov=65;t.camera.updateProjectionMatrix();t.distanceCulling.recollect();t.distanceCulling.update(3);};return {objects:unique.map(o=>o.name),scope:'Default live gameplay, no preview transformations applied'};});
info.runtime=await p.evaluate(()=>{const l=window.__tm.messenger.landmarks,p=l.crystalMotherPort;return {placement:l.moebius.corePlacement,port:!!p,boardingRoute:p?.boardingRoute.map(v=>v.toArray()),records:p?.records.map(r=>({center:r.center.toArray(),finite:r.center.toArray().every(Number.isFinite)}))}});for(const deg of['live']){for(const v of['map','red','blue']){await p.evaluate(v=>window.rotateView(v),v);await p.waitForTimeout(250);const im=await p.evaluate(()=>{const t=window.__tm;t.renderer.render(t.scene,t.camera);return t.renderer.domElement.toDataURL()});await writeFile(`${out}/ccw${deg}-${v}.png`,Buffer.from(im.split(',')[1],'base64'));}}
info.checks=await p.evaluate(()=>{const t=window.__tm,T=t.THREE,l=t.messenger.landmarks,p=l.crystalMotherPort,nav=p.boat.userData.portNavigation,origin=p.boat.position.clone();nav.step(1,-1);const moved=origin.distanceTo(p.boat.position);nav.step(9999,1);const endpointError=origin.distanceTo(p.boat.position);p.update(8);const finite=p.records.every(r=>r.center.toArray().every(Number.isFinite));const lake=t.scene.getObjectByName('crystal-v10-lake');return {navigationMoves:moved>.01,berthReturnError:endpointError,portPlatformFinite:finite,waterMask:lake.material.uniforms.swamp.value.toArray(),towerCount:l.moebius.crystals.length,placement:l.moebius.corePlacement};});await p.evaluate(()=>window.rotateView('map'));info.hits=await p.evaluate(()=>{const t=window.__tm,T=t.THREE,r=new T.Raycaster();return [[.72,.49],[.62,.78]].map(([x,y])=>{r.setFromCamera(new T.Vector2(x*2-1,1-y*2),t.camera);return r.intersectObjects(t.scene.children,true).filter(h=>{for(let p=h.object;p;p=p.parent)if(!p.visible)return false;return true}).slice(0,5).map(h=>({name:h.object.name,parent:h.object.parent.name,point:h.point.toArray()}))})});info.gate=await p.evaluate(()=>{const g=window.__tm.messenger.landmarks.abandonedGate,s=g.userData.seatRoot;return {anchor:g.userData.meetingAnchor.position.toArray(),meshes:s.getObjectByName('gate-target-blender-v1').children.map(o=>({name:o.name,walk:o.userData.gateWalkable})),v10:s.userData.moebiusV10.children.filter(o=>/meeting/.test(o.name)).map(o=>({name:o.name,position:o.position.toArray()}))}});info.errors=errors;await writeFile(out+'/preview.json',JSON.stringify(info,null,2));console.log(JSON.stringify({hits:info.hits,gate:info.gate}));}finally{await b.close();}
