import * as T from 'three';
import {installCrystalLakeV10} from '../../../src/world/crystalLakeV10.js';
import {alignReleasedLighting} from '../../../src/world/citadel/releasedLighting.js';
const result={timestamp:new Date().toISOString()},out=document.querySelector('#result'),status=document.querySelector('#status');const emit=()=>out.textContent=JSON.stringify(result,null,2);
function lightingFixture(withCandidate){
 const castle=new T.Group(),old=new T.Group(),city=new T.Group(),fresh=new T.Group();old.name='highland-light-volumes';city.name='highland-west-city';fresh.name='citadel-new-city-lighting';castle.add(old,city);city.add(fresh);old.update=()=>{};fresh.userData.update=()=>{};
 const terrain=new T.Mesh(new T.PlaneGeometry(100,100),new T.MeshBasicMaterial());terrain.name='citadel-oskar-grid-mountain-surface';castle.add(terrain);
 for(let i=0;i<3;i++){const a=new T.PointLight(),b=new T.PointLight();a.position.set(i,9,i);old.add(a);fresh.add(b);}
 for(const i of [4,7]){const g=new T.Group();g.name='new-city-lantern-'+i;fresh.add(g);}
 if(withCandidate){const parcels=new T.Group();parcels.name='old-city-staggered-parcels';castle.add(parcels);castle.userData.oldCityParcelCandidate={supports:Array.from({length:7},(_,i)=>({placed:[i,2,i]}))};}
 const before=old.children.filter(x=>x.isPointLight).map(x=>x.position.toArray());const report=alignReleasedLighting(castle);const after=old.children.filter(x=>x.isPointLight).map(x=>x.position.toArray());
 return {withCandidate,mode:report.oldCityAnchors,oldPositionsPreserved:JSON.stringify(before)===JSON.stringify(after),oldPositions:after,newPointCount:report.points.filter(x=>x.side==='new').length,hasNaN:report.points.some(x=>x.castlePosition.some(n=>!Number.isFinite(n)))};
}
document.querySelector('#fixture').onclick=()=>{try{
 const renderer=new T.WebGLRenderer({antialias:false,preserveDrawingBuffer:true});renderer.setSize(300,180);document.querySelector('#canvas').replaceChildren(renderer.domElement);const gl=renderer.getContext(),camera=new T.PerspectiveCamera(60,300/180,.1,1000);camera.position.z=5;
 const scene=new T.Scene(),geometry=new T.PlaneGeometry(2,2),legacyMaterial=new T.ShaderMaterial({vertexShader:'void main(){gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:'void main(){discard;}'}),mesh=new T.Mesh(geometry,legacyMaterial);scene.add(mesh);
 while(gl.getError()!==gl.NO_ERROR){};renderer.render(scene,camera);const legacyError=gl.getError();mesh.removeFromParent();legacyMaterial.dispose();geometry.dispose();
 installCrystalLakeV10({scene,city:{crystals:[]},swamp:{position:new T.Vector3(0,160,0)}});const lake=scene.getObjectByName('crystal-v10-lake');let callbacks=0;const oldCallback=lake.onBeforeRender;lake.onBeforeRender=function(...args){callbacks++;return oldCallback.apply(this,args)};
 const ocean=new T.Mesh(new T.SphereGeometry(1,8,4),new T.ShaderMaterial({uniforms:{uNight:{value:1}},vertexShader:'varying vec3 vRadial;void main(){vRadial=position;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:'uniform float uNight;varying vec3 vRadial;void main(){vec3 color=vec3(.1,.4,.6);float alpha=1.;gl_FragColor = vec4(color, alpha);}'}));ocean.name='planet-v8-curved-ocean';scene.add(ocean);
 const errors=[];for(let i=0;i<6;i++){renderer.render(scene,camera);const error=gl.getError();if(error!==gl.NO_ERROR)errors.push(error);}
 result.fixture={threeRevision:T.REVISION,legacyError,expectedInvalidOperation:gl.INVALID_OPERATION,fixedErrors:errors,callbacks,drawRange:lake.geometry.drawRange,colorWrite:lake.material.colorWrite,depthWrite:lake.material.depthWrite,oceanStyleInstalled:ocean.material.userData.crystalLake===true,uniformUpdates:lake.material.uniforms.time.value>0,lightingWithoutCandidate:lightingFixture(false),lightingWithCandidate:lightingFixture(true)};status.textContent='独立回归完成';emit();renderer.dispose();
 }catch(error){result.fixtureError=error.stack;emit();}};
let t,frames=0,glErrors=[],messages=[],attached=false,started;
const frame=document.querySelector('#stage');function finish(){result.game={frames,glErrors,consoleMessages:messages.slice(-30),elapsedMs:Math.round(performance.now()-started),lake:{drawRange:t.scene.getObjectByName('crystal-v10-lake')?.geometry.drawRange,oceanStyle:t.scene.getObjectByName('planet-v8-curved-ocean')?.material.userData.crystalLake},lighting:[]};t.scene.traverse(o=>{if(o.userData.releasedLighting)result.game.lighting.push(o.userData.releasedLighting)});status.textContent='实际游戏采样完成';emit();}
function sample(){frames=0;glErrors=[];const gl=t.renderer.getContext(),scene=t.scene,prior=scene.onAfterRender;scene.onAfterRender=function(...args){prior?.apply(this,args);const error=gl.getError();if(error!==gl.NO_ERROR)glErrors.push({frame:frames,error});if(++frames>=120){scene.onAfterRender=prior;finish();}};status.textContent='实际游戏渲染采样 120 次…';}
document.querySelector('#game').onclick=()=>{started=performance.now();attached=false;status.textContent='加载完整游戏，保留雾、天气与默认灯光';frame.src='../../../?local=1&autostart=1';const poll=setInterval(()=>{try{const w=frame.contentWindow;if(!attached&&w.document.querySelector('canvas')){attached=true;for(const kind of ['error','warn']){const original=w.console[kind].bind(w.console);w.console[kind]=(...args)=>{messages.push({kind,text:args.map(String).join(' ')});original(...args)};}w.addEventListener('error',e=>messages.push({kind:'uncaught',text:e.message}));}if(w.__tm){t=w.__tm;clearInterval(poll);sample();}}catch{}if(performance.now()-started>360000){clearInterval(poll);status.textContent='加载超过6分钟';}},500)};
document.querySelector('#night').onclick=()=>{if(!t)return;t.P.daySpeed=0;t.P.timeOfDay=.8;t.dayNight.update(.001);sample();};
