import {writeFileSync,readFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {actualUserMarkedStructureFixture} from '../../../tests/world/targetUserMarkedStructure.fixture.mjs';
import {createTargetCityDetailCandidate} from '../../../src/world/citadel/targetCityDetailCandidate.js';
const sourcePaths=['targetOldCity','targetNewCityMain','targetNewCityStairs','targetCityDetailCandidate','targetCliffTransitStructure','targetCliffRailGallery','targetDoubleDeckBridge','targetCityEntityEditor','targetCityPlayerSupport'].map(s=>'src/world/citadel/'+s+'.js');
const hashes=()=>Object.fromEntries(sourcePaths.map(p=>[p,createHash('sha256').update(readFileSync(p)).digest('hex')]));const before=hashes();
const f=actualUserMarkedStructureFixture();f.release.walkingConnection={kind:'stacked-connected'};f.release.structureOptions={galleryPierWidths:{oldShore:.9},newCityTransitLinks:true};
const c=createTargetCityDetailCandidate({castle:f.castle,cliffTransitRelease:f.release,fitSunShadow:false,includeFrontRail:false,newCityStreetInfill:true,newCityFoundationRefinement:true});f.castle.add(c.root);f.scene.updateMatrixWorld(true);
const roots=Object.fromEntries(['old-city','new-city-main','new-city-stairs','cliff-transit-structure'].map(n=>[n,c.root.getObjectByName('citadel-target-'+n)]));
function list(root){const items=[];root.traverse(o=>{if(o.isMesh)items.push(o);});return items;}
function materialList(o){return Array.isArray(o.material)?o.material:[o.material];}
function visible(o){for(let p=o;p;p=p.parent)if(!p.visible)return false;return true;}
function entity(o){for(let p=o;p;p=p.parent)if(p.userData.targetEditableHouse)return p.name;return null;}
function attributes(o){return Object.entries(o.geometry.attributes).map(([n,a])=>[n,a.itemSize,a.normalized,a.array.constructor.name]).sort();}
function key(o){return JSON.stringify([materialList(o).map(m=>m.uuid),entity(o),o.userData.targetWall===true,o.userData.targetWalkable===true,o.castShadow,o.receiveShadow,o.renderOrder,o.layers.mask,o.frustumCulled,o.customDepthMaterial?.uuid,o.customDistanceMaterial?.uuid,o.geometry.drawRange,attributes(o)]);}
function stats(items){const mats=new Set(),geoms=new Set(),names=new Map(),buckets=new Map(),instances=[],batchedNames=[];let triangles=0,baseTriangles=0,visibleCount=0,groups=0,submissions=0;
 for(const o of items){const ts=(o.geometry.index?.count??o.geometry.attributes.position.count)/3;triangles+=ts*(o.isInstancedMesh?o.count:1);baseTriangles+=ts;geoms.add(o.geometry);if(visible(o))visibleCount++;groups+=o.geometry.groups.length;submissions+=Array.isArray(o.material)?o.geometry.groups.length:1;
  for(const m of materialList(o)){mats.add(m);if(!names.has(m.name))names.set(m.name,{name:m.name,objects:new Set(),meshes:0,triangles:0});const row=names.get(m.name);row.objects.add(m);row.meshes++;row.triangles+=ts*(o.isInstancedMesh?o.count:1);}
  if(o.isInstancedMesh)instances.push({name:o.name,count:o.count,baseTriangles:ts});else if(!o.isSkinnedMesh&&!o.morphTargetInfluences?.length&&o.geometry.drawRange.start===0&&o.geometry.drawRange.count===Infinity){const k=key(o);if(!buckets.has(k))buckets.set(k,[]);buckets.get(k).push(o);}
  if(/batch|infill|refined-foundation|continuous-walk-deck|track-protective-ceiling|handrails|rail-posts|edge-curbs|city-link|through-arcade|windows-(glass|trim)/.test(o.name))batchedNames.push(o.name);
 }
 const compat=[...buckets.values()].filter(b=>b.length>1).map(b=>({material:b[0].material.name,entity:entity(b[0]),targetWall:b[0].userData.targetWall===true,explicitWalkable:b[0].userData.targetWalkable===true,meshes:b.length,triangles:b.reduce((n,o)=>n+(o.geometry.index?.count??o.geometry.attributes.position.count)/3,0),names:b.map(o=>o.name)}));
 return{meshObjects:items.length,ancestorVisibleObjects:visibleCount,usedMaterialObjects:mats.size,usedGeometryObjects:geoms.size,geometryGroupCount:groups,unculledSingleColourPassSubmissionUnits:submissions,baseGeometryTriangles:baseTriangles,instanceExpandedTriangles:triangles,instancedMeshes:instances,knownBatchNameMeshCount:batchedNames.length,knownBatchNames:batchedNames,materials:[...names.values()].map(r=>({...r,objects:r.objects.size})).sort((a,b)=>b.meshes-a.meshes),compatiblePartitionUpperBound:{before:compat.reduce((n,b)=>n+b.meshes,0),after:compat.length,saving:compat.reduce((n,b)=>n+b.meshes-1,0),notApprovedBecauseSemanticAndSpatialPartitionStillRequired:true,buckets:compat}};
}
try{
 const all=Object.fromEntries(Object.entries(roots).map(([n,r])=>[n,stats(list(r))]));
 const main=roots['new-city-main'];const windowGroups=[];main.traverse(o=>{if(o.isGroup&&o.children.filter(x=>x.isMesh).length===6&&o.children.every(x=>x.isMesh)&&o.children.some(x=>x.name.endsWith('-recess'))&&o.children.some(x=>x.name.endsWith('-mullion')))windowGroups.push(o);});
 const windows=windowGroups.flatMap(g=>g.children),windowStats=stats(windows),windowMaterials=[...new Set(windows.map(o=>o.material))];
 const windowZones=Object.fromEntries(['drum','left','right'].map(zone=>{const groups=windowGroups.filter(g=>(g.name.startsWith('drum-window-')?'drum':g.name.includes('--1')?'left':'right')===zone);return[zone,{groups:groups.length,meshes:groups.length*6,triangles:stats(groups.flatMap(g=>g.children)).instanceExpandedTriangles,proposedMeshes:2}];}));
 const eligibleWindows=windows.every(o=>!o.isInstancedMesh&&!o.isSkinnedMesh&&!o.morphTargetInfluences?.length&&!Array.isArray(o.material)&&visible(o)&&o.material.visible&&o.material.opacity===1&&!o.material.transparent&&!o.onBeforeRender.toString().includes('=>'));
 const galleryBreakdown=Object.fromEntries(['oldShore','central','newShore'].map(key=>[key,stats(list(roots['cliff-transit-structure'].getObjectByName('cliff-transit-'+key)))]));
 const perHouse=Object.fromEntries(list(roots['old-city']).filter(o=>entity(o)).map(o=>[entity(o),null]));for(const id of Object.keys(perHouse))perHouse[id]=stats(list(roots['old-city'].getObjectByName(id)));
 const report={kind:'read-only-candidate-construction-statistics',gpuMeasurement:false,sourceHashBefore:before,sourceHashAfter:hashes(),sameSourceDuringRun:JSON.stringify(before)===JSON.stringify(hashes()),options:{includeFrontRail:false,newCityStreetInfill:true,newCityFoundationRefinement:true,cliffTransit:'user-marked stacked-connected',oldShorePierWidth:.9,newCityTransitLinks:true,fitSunShadow:false},versions:{oldCity:c.report.oldCity?.geometry?.version,main:c.report.newCity?.geometry?.version,stairs:c.report.newCityStairs.authored.revision,cliffTransit:c.report.cliffTransit?.version},assets:all,galleryBreakdown,oldCityPerHouse:perHouse,mainWindowCandidate:{conservativeSpatialZones:windowZones,threeZonePrediction:{before:windows.length,after:6,saving:windows.length-6},windowGroups:windowGroups.length,groupNames:windowGroups.map(g=>g.name),meshes:windows.length,allMeshesHaveExpectedStaticShape:eligibleWindows,materialObjects:windowMaterials.map(m=>({name:m.name,type:m.type,side:m.side,transparent:m.transparent,opacity:m.opacity})),triangles:windowStats.instanceExpandedTriangles,rawTwoBatchPrediction:{before:windows.length,after:windowMaterials.length,saving:windows.length-windowMaterials.length},compatibleBuckets:windowStats.compatiblePartitionUpperBound,bounds:windowGroups.map(g=>({name:g.name,position:g.position.toArray()}))},limitations:['No renderer, camera frustum, occlusion, shadows, render.info or timing measurement.','Submission units are scene topology only, not actual draw calls.','Explicit walkable is not the complete provider rule; name/report-derived semantics require review.','No source geometry was merged, no materials were changed, and no live browser was used.']};
 writeFileSync(new URL('./statistics.json',import.meta.url),JSON.stringify(report,null,2));console.log(JSON.stringify({sourcesStable:report.sameSourceDuringRun,assets:Object.fromEntries(Object.entries(all).map(([k,v])=>[k,{meshes:v.meshObjects,materials:v.usedMaterialObjects,triangles:v.instanceExpandedTriangles,instances:v.instancedMeshes.map(x=>[x.name,x.count]),naiveCompatibleSaving:v.compatiblePartitionUpperBound.saving}])),windows:report.mainWindowCandidate.rawTwoBatchPrediction,windowGroups:windowGroups.length,gallery:Object.fromEntries(Object.entries(galleryBreakdown).map(([k,v])=>[k,{meshes:v.meshObjects,materials:v.usedMaterialObjects,compatibleSaving:v.compatiblePartitionUpperBound.saving}]))},null,2));
}finally{c.dispose();f.dispose();}
