import {actualUserMarkedStructureFixture}from'../../../tests/world/targetUserMarkedStructure.fixture.mjs';import{createTargetCityDetailCandidate}from'../../../src/world/citadel/targetCityDetailCandidate.js';import{createTargetStairSurfaceSampler}from'../../../src/world/citadel/targetNewCityStairRoute.js';import{writeFileSync}from'node:fs';
const f=actualUserMarkedStructureFixture();f.release.walkingConnection={kind:'stacked-connected'};f.release.structureOptions={galleryPierWidths:{oldShore:.9},newCityTransitLinks:true};const c=createTargetCityDetailCandidate({castle:f.castle,cliffTransitRelease:f.release,fitSunShadow:false,newCityStreetInfill:true,newCityFoundationRefinement:true}),source=c.report.newCityStairs.authored,sample=createTargetStairSurfaceSampler(f.castle,[f.terrain]),yaw=-55*Math.PI/180,cs=Math.cos(yaw),sn=Math.sin(yaw),tol=([x,z])=>[(x-74)*cs-(z-33)*sn,(x-74)*sn+(z-33)*cs],surfaces=[...c.report.newCityStairs.surveyed.selected.treads,...c.report.bridgeConnector.walkSurfaces,...Object.values(c.report.cliffTransit.galleries).flatMap(g=>g.walkSurfaces),...c.report.cliffTransit.connections.flatMap(l=>l.walkSurfaces.map(s=>({polygon:s.corners.map(p=>[p[0],p[2]])}))),...c.report.cliffTransit.newCityTransitLinks.links.flatMap(l=>l.walkSurfaces)].filter(p=>p.polygon).map(p=>({id:p.id,polygon:p.polygon.map(tol)}));
const sep=(A,B)=>[A,B].some(poly=>poly.some((p,i)=>{const q=poly[(i+1)%poly.length],nx=-(q[1]-p[1]),nz=q[0]-p[0],a=A.map(v=>v[0]*nx+v[1]*nz),b=B.map(v=>v[0]*nx+v[1]*nz);return Math.max(...a)<=Math.min(...b)+1e-8||Math.max(...b)<=Math.min(...a)+1e-8;})),rows=[];
for(const h of source.houses)for(const [edge,n,half,span]of[['back',[0,-1],h.size[2]/2,h.size[0]],['east',[1,0],h.size[0]/2,h.size[2]],['west',[-1,0],h.size[0]/2,h.size[2]]])for(const shift of[0,-.65,.65]){
 const w=2.9,d=2.2,tx=n[1],tz=-n[0],x=h.position[0]+n[0]*(half+d/2-.12)+tx*shift,z=h.position[2]+n[1]*(half+d/2-.12)+tz*shift,at=(u,v)=>[x+tx*u+n[0]*v,z+tz*u+n[1]*v],poly=[[-w/2-.12,-d/2-.12],[w/2+.12,-d/2-.12],[w/2+.12,d/2+.12],[-w/2-.12,d/2+.12]].map(p=>at(...p));
 let reason=null;if(poly.some(p=>p[1]<13.6))reason='main-margin';else if(surfaces.some(p=>!sep(poly,p.polygon)))reason='public';else if(source.footprints.some(p=>p.role==='stair-flank-house'&&p.id!==h.id&&!sep(poly,p.polygon)))reason='otherhouse';else if(source.streetInfill.modules.some(p=>!sep(poly,p.polygon)))reason='infill';
 const ys=[];for(const u of[-.5,-.25,0,.25,.5])for(const v of[-.5,-.25,0,.25,.5]){const p=at(w*u,d*v),hit=sample(74+cs*p[0]+sn*p[1],33-sn*p[0]+cs*p[1]);ys.push(hit?hit.height-12:null);}const high=Math.max(...ys),low=Math.min(...ys),fp=source.footprints.find(p=>p.id===h.id);if(!reason&&high-low>1.85)reason='steep';if(!reason&&high+.08+2.5+.6>fp.roofY-.4)reason='subordinate';rows.push({id:h.id,edge,shift,x,z,spread:high-low,floor:high+.08,reason,poly});
}
writeFileSync(new URL('./survey.json',import.meta.url),JSON.stringify(rows,null,2));console.log(JSON.stringify(rows.filter(r=>!r.reason),null,2));c.dispose();f.dispose();
