import test from 'node:test';import assert from 'node:assert/strict';import * as T from 'three';
globalThis.window={addEventListener(){},location:{search:""}};

globalThis.document={getElementById:()=>null};
const {createCitadelNightInfiltration}=await import('../../src/world/citadelInfiltration.js');
function fixture(){const scene=new T.Group(),horse=new T.Group(),squad=new T.Group();scene.add(horse);horse.add(squad);horse.userData.baseQuat=horse.quaternion.clone();const actor=createCitadelNightInfiltration({scene,horse,staticSquad:squad,siteUp:new T.Vector3(0,1,0),siteRight:new T.Vector3(1,0,0),horseGround:new T.Vector3(),waterfallRoute:[],stairRoute:[new T.Vector3(0,0,10)],topAssaultMode:true,captureTarget:new T.Vector3(0,0,10)});return{horse,actor,next:{worldPosition:new T.Vector3(20,3,4),worldQuaternion:new T.Quaternion().setFromAxisAngle(new T.Vector3(0,1,0),.5),horseGround:new T.Vector3(20,3,4),stairRoute:[new T.Vector3(20,3,12),new T.Vector3(0,0,10)],waterfallRoute:[]}};}
test('idle relocation preserves actor, updates anchors and atomically rolls back',()=>{const{horse,actor,next}=fixture(),before=actor.getPlacementState(),id=horse.uuid;const result=actor.relocateGround(next);assert.equal(result.ok,true);assert.equal(horse.uuid,id);assert.deepEqual(horse.position.toArray(),[20,3,4]);assert.deepEqual(actor.getPlacementState().baseGround,[20,3.08,4]);assert.notDeepEqual(actor.getPlacementState().anchors,before.anchors);assert.equal(result.rollback().ok,true);assert.deepEqual(horse.position.toArray(),[0,0,0]);assert.deepEqual(actor.getPlacementState().anchors,before.anchors);assert.deepEqual(actor.getPlacementState().drops,before.drops);assert.equal(result.rollback().ok,false);});
test('invalid input does not partially move actor or anchors; new routes stale rollback',()=>{const{horse,actor,next}=fixture(),before=actor.getPlacementState();assert.equal(actor.relocateGround({...next,horseGround:new T.Vector3(NaN,0,0)}).ok,false);assert.deepEqual(actor.getPlacementState(),before);assert.deepEqual(horse.position.toArray(),[0,0,0]);const r=actor.relocateGround(next);actor.setRoutes({stairRoute:next.stairRoute});assert.equal(r.rollback().ok,false);});
test('active night rejects migration without touching actor or closure anchors',()=>{const{horse,actor,next}=fixture();actor.update(0,0,.9);const before=actor.getPlacementState(),position=horse.position.clone();assert.equal(actor.relocateGround(next).reason,'not-idle-daytime');assert.deepEqual(actor.getPlacementState(),before);assert.ok(horse.position.equals(position));});
test('exception during transaction restores actor, routes and anchor state',()=>{const{horse,actor,next}=fixture(),before=actor.getPlacementState();const broken=new T.Vector3(1,2,3);broken.clone=()=>{throw new Error('fixture clone failure');};const r=actor.relocateGround({...next,stairRoute:[broken]});assert.equal(r.ok,false);assert.equal(r.reason,'rebuild-failed');assert.deepEqual(actor.getPlacementState(),before);assert.deepEqual(horse.position.toArray(),[0,0,0]);});
test('explicit new capture target participates in relocation and rollback',()=>{const{actor,next}=fixture(),before=actor.getPlacementState();const target=new T.Vector3(22,14,6),r=actor.relocateGround({...next,captureTarget:target});assert.equal(r.ok,true);assert.deepEqual(actor.getPlacementState().captureTarget,target.toArray());assert.equal(r.rollback().ok,true);assert.deepEqual(actor.getPlacementState().captureTarget,before.captureTarget);assert.equal(actor.relocateGround({...next,captureTarget:new T.Vector3(NaN,0,0)}).ok,false);assert.deepEqual(actor.getPlacementState().captureTarget,before.captureTarget);});
