import test from 'node:test';
import assert from 'node:assert/strict';
import * as T from 'three';
import {createTerraceBenchGeometry,buildMountainTerraceBenches} from '../../src/world/citadel/mountainTerraceBenches.js';
const options={center:[0,0],radii:[12,10],levels:[{scale:1,y:4},{scale:.65,y:8},{scale:.3,y:12}],bottomY:-2};
test('closed stepped solid has matched directed edges, positive volume and three real horizontal tops',()=>{const g=createTerraceBenchGeometry(options),p=g.attributes.position,ix=g.index,edges=new Map(),tops=new Map();let volume=0;for(let i=0;i<ix.count;i+=3){const ids=[0,1,2].map(j=>ix.getX(i+j)),[a,b,c]=ids.map(j=>new T.Vector3().fromBufferAttribute(p,j)),n=b.clone().sub(a).cross(c.clone().sub(a));assert.ok(n.length()>1e-6);volume+=a.dot(b.clone().cross(c))/6;if(n.y>0&&Math.abs(n.x)+Math.abs(n.z)<1e-6)tops.set(a.y,(tops.get(a.y)||0)+n.length()/2);for(let j=0;j<3;j++){const a=ids[j],b=ids[(j+1)%3],k=a<b?`${a},${b}`:`${b},${a}`;const v=edges.get(k)||{n:0,d:0};v.n++;v.d+=a<b?1:-1;edges.set(k,v);}}for(const e of edges.values()){assert.equal(e.n,2);assert.equal(e.d,0);}assert.ok(volume>0);assert.deepEqual([...tops.keys()],[4,8,12]);assert.ok([...tops.values()].every(a=>a>20));assert.deepEqual(g.attributes.position.array,createTerraceBenchGeometry(options).attributes.position.array);});
function fixture(){const castle=new T.Group();castle.position.set(20,30,10);castle.rotation.set(.3,.2,-.1);const g=new T.PlaneGeometry(100,100);g.rotateX(-Math.PI/2);const mesh=new T.Mesh(g,new T.MeshBasicMaterial({side:T.DoubleSide}));castle.add(mesh);castle.updateWorldMatrix(true,true);return {castle,mesh};}
test('builder defaults off and samples final transformed source without mutating it',()=>{const {castle,mesh}=fixture(),before=mesh.geometry.attributes.position.array.slice();assert.equal(buildMountainTerraceBenches().audit.applied,false);const result=buildMountainTerraceBenches({...options,castle,surfaces:[mesh],enabled:true,railClearance:2});assert.equal(result.audit.applied,true);assert.equal(result.audit.sourceMisses,0);assert.ok(Math.abs(result.audit.sourceMin)<1e-5);assert.equal(result.group.parent,null);assert.deepEqual(mesh.geometry.attributes.position.array,before);assert.equal(result.audit.requiresSourceClipping,true);});
test('reject whole candidate for protected interior, crossing rail segment, and unsupported source',()=>{const {castle,mesh}=fixture(),common={...options,castle,surfaces:[mesh],enabled:true,railClearance:2};assert.equal(buildMountainTerraceBenches({...common,protectedBoxes:[new T.Box3(new T.Vector3(-1,1,-1),new T.Vector3(1,2,1))]}).audit.applied,false);assert.equal(buildMountainTerraceBenches({...common,railPoints:[[-100,6,0],[100,6,0]]}).audit.applied,false);assert.equal(buildMountainTerraceBenches({...common,center:[200,200]}).audit.reason,'source support sample miss');});
test('eccentric retreating levels remain closed and positive-volume; crossing offsets reject',()=>{const levels=[{scale:1,y:4},{scale:.65,y:8,centerOffset:[0,-1.5]},{scale:.3,y:12,centerOffset:[.3,-3]}];const g=createTerraceBenchGeometry({...options,levels}),p=g.attributes.position,idx=g.index,edges=new Map();let volume=0;for(let f=0;f<idx.count;f+=3){const ids=[0,1,2].map(j=>idx.getX(f+j)),[a,b,c]=ids.map(i=>new T.Vector3().fromBufferAttribute(p,i));volume+=a.dot(b.clone().cross(c))/6;assert.ok(b.clone().sub(a).cross(c.clone().sub(a)).length()>1e-5);for(let j=0;j<3;j++){const a=ids[j],b=ids[(j+1)%3],key=a<b?`${a},${b}`:`${b},${a}`,entry=edges.get(key)||[0,0];entry[0]++;entry[1]+=a<b?1:-1;edges.set(key,entry);}}for(const e of edges.values())assert.deepEqual(e,[2,0]);assert.ok(volume>100);assert.deepEqual(g.userData.terraceBenches.levels[2].centerOffset,[.3,-3]);assert.throws(()=>createTerraceBenchGeometry({...options,levels:[levels[0],{...levels[1],centerOffset:[100,0]}]}),/cross/);});
