import test from 'node:test';import assert from 'node:assert/strict';import * as T from 'three';
import {createTargetGlobalRailApproachSupport} from '../../src/world/citadel/targetGlobalRailApproachSupport.js';
import {measureGlobalApproachVehicles} from '../../tools/pipeline/measure_global_approach_vehicles.mjs';
class Arc extends T.Curve{getLength(){return 40;}getPointAt(u,out=new T.Vector3()){return out.set(165*Math.sin(u*40/165),0,165*Math.cos(u*40/165));}getTangentAt(u,out=new T.Vector3()){return out.set(Math.cos(u*40/165),0,-Math.sin(u*40/165));}}
const curve=new Arc(),curves={center:curve,red:curve,blue:curve};
const input=()=>({enabled:true,curves,sampleGround:p=>({point:p.clone().normalize().multiplyScalar(160),objectName:'test-exact-sphere'}),sampleSea:()=>({radius:160.5,upperRadius:160.567,officialUpperRadius:160.567}),vehicleBox:new T.Box3(new T.Vector3(-1.742,-.036,-3.49),new T.Vector3(1.742,5.352,3.49)),vehicleProvenance:'test known production bounds'});
test('off creates no geometry and never evaluates input getters',()=>{const a=createTargetGlobalRailApproachSupport({get curves(){throw Error('read');}});assert.equal(a.report.built,false);assert.equal(a.group.children.length,0);a.dispose();a.dispose();});
test('finite radial pillars, dry top and actual lowered vehicle envelope produce bounded candidate',()=>{const a=createTargetGlobalRailApproachSupport(input());assert.equal(a.report.built,true,JSON.stringify(a.report.issues));assert.equal(a.report.accepted,false);assert.ok(a.report.foundations.every(f=>f.seated&&f.footingSamples.length===4));assert.equal(a.report.vehicleClearance.pass,true);assert.ok(a.report.performance.meshes<=8);assert.ok(a.report.performance.triangles<9000);for(const m of a.group.children){assert.equal(m.userData.targetWalkable,false);assert.ok([...m.geometry.attributes.position.array].every(Number.isFinite));}assert.equal(a.report.supportScope.sourceEndRequiresExistingDeckTransition,true);let n=0;for(const m of a.group.children)m.geometry.addEventListener('dispose',()=>n++);const expected=a.group.children.length;a.dispose();a.dispose();assert.equal(n,expected);});
test('unknown foundations and excessive depth never produce blind pillars',()=>{for(const sampleGround of[()=>null,p=>({point:p.clone().normalize().multiplyScalar(130)})]){const a=createTargetGlobalRailApproachSupport({...input(),sampleGround});assert.equal(a.report.built,false);assert.equal(a.group.children.length,0);assert.ok(a.report.issues.includes('GROUND_UNKNOWN')||a.report.issues.includes('PIER_TOO_LONG'));a.dispose();}});
test('actual triangle contact blocks a physically lower vehicle; no wheel exemption',()=>{const o=input();o.vehicleBox.min.y=-2;const a=createTargetGlobalRailApproachSupport(o);assert.equal(a.report.built,false);assert.ok(a.report.vehicleClearance.collisions.length>0);assert.deepEqual(a.report.vehicle.wheelExceptions,[]);a.dispose();});
test('wet running top rejects before any GPU resource, submerged body is a separate count',()=>{const a=createTargetGlobalRailApproachSupport({...input(),sampleSea:()=>({radius:165,upperRadius:165.067,officialUpperRadius:165.067})});assert.equal(a.report.built,false);assert.ok(a.report.issues.includes('DECK_WATER_RESERVE'));assert.ok(a.report.water.submergedBridgeBodySamples>0);assert.equal(a.group.children.length,0);});
test('actual production running gear and all cargo retain measured wheel minimum, without filtering wheels',async()=>{const v=await measureGlobalApproachVehicles();assert.ok(Math.abs(v.box.min.y+.036)<1e-6);assert.ok(v.box.max.y<=5.36);assert.ok(v.box.max.x<=1.75&&v.box.min.x>=-1.75);assert.ok(v.report.records.length===7);assert.deepEqual(v.report.wheelExceptions,[]);assert.ok(v.report.records[0].dynamicBox.min[1]>v.box.min.y);});
test('explicit underpass keeps seated bearings and adds real longitudinal girders',()=>{const a=createTargetGlobalRailApproachSupport({...input(),supportGaps:[{id:'test-underpass',start:10,end:27,maxSpan:28}]});assert.equal(a.report.built,true,JSON.stringify(a.report.issues));assert.equal(a.report.omittedStations.length,2);assert.equal(a.report.structuralOpenings.length,1);assert.equal(a.report.structuralOpenings[0].upperEdgeGirders,2);assert.equal(a.report.structuralOpenings[0].span,24);assert.equal(a.report.structuralOpenings[0].engineeringCapacityVerified,false);a.dispose();const b=createTargetGlobalRailApproachSupport({...input(),supportGaps:[{start:10,end:27,maxSpan:20}]});assert.equal(b.report.built,false);assert.ok(b.report.issues.includes('UNDERPASS_BEARING_SPAN'));b.dispose();});
test('source collar copies actual supplied underside sections and rejects remote invention',()=>{const bottomSections=[-.8,-.3].map(s=>{const p=curve.getPointAt(s/40),t=curve.getTangentAt(s/40),right=p.clone().normalize().cross(t).normalize(),up=t.clone().cross(right).normalize();return[-4.075,4.075].map(x=>p.clone().addScaledVector(right,x).addScaledVector(up,-.24).toArray());});const a=createTargetGlobalRailApproachSupport({...input(),sourceDeckInterface:{bottomSections,globalInterval:[.1,.1002]}});assert.equal(a.report.built,true,JSON.stringify(a.report.issues));assert.equal(a.report.sourceConnection.verified,true);assert.deepEqual(a.report.sourceConnection.bottomSections,bottomSections);assert.equal(a.report.supportScope.sourceEndRequiresExistingDeckTransition,false);a.dispose();const bad=bottomSections.map(s=>s.map(p=>[p[0]+50,p[1],p[2]]));const b=createTargetGlobalRailApproachSupport({...input(),sourceDeckInterface:{bottomSections:bad}});assert.equal(b.report.built,false);assert.ok(b.report.issues.includes('SOURCE_INTERFACE_TOO_FAR'));b.dispose();});
