import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import * as T from 'three';import{createTargetRailCliffField}from '../../src/world/citadel/targetRailCliffField.js';import{targetTerrainHeight,TARGET_CITY_PLATFORMS}from '../../src/world/citadel/targetTerrainCandidate.js';import{createCastleOceanSampler}from '../../src/world/citadel/newCityRidgeCandidate.js';
const data=JSON.parse(fs.readFileSync(new URL('../../artifacts/pipeline/citadel-live-tram-clearance-20261006/global-tram-samples.json',import.meta.url))),sea=createCastleOceanSampler(new T.Matrix4().fromArray(data.castleMatrix),160),base=(x,z,s)=>targetTerrainHeight(x,z,s,{aprons:true,saddle:true,valleyBenches:true});
test('measured upper south-east rail branch retreats toe only, plateaus and other terrain unchanged',()=>{const a=createTargetRailCliffField({...data,platforms:TARGET_CITY_PLATFORMS}),b=createTargetRailCliffField({...data,platforms:TARGET_CITY_PLATFORMS});assert.ok(a.report.samples>30);let changed=0,protectedN=0;for(let x=-140;x<=140;x++)for(let z=-70;z<=106;z++){const s=sea(x,z);if(s===null)continue;const old=base(x,z,s),next=a.height(x,z,old,s);assert.equal(next,b.height(x,z,old,s));assert.ok(next<=old+1e-9);assert.ok(next>=s-11.5-1e-9);if(x<80||x>143||z<70||z>102)assert.equal(next,old);if(TARGET_CITY_PLATFORMS.some(p=>Math.hypot((x-p.center[0])/p.radii[0],(z-p.center[1])/p.radii[1])<=.78)){assert.equal(next,old);protectedN++;}if(next<old-1e-6)changed++;}assert.ok(changed>100);assert.ok(protectedN>1000);console.log(JSON.stringify({changed,protectedN,...a.report}));});
test('actual rail centre near plaza front-right clears height cap where branch is fully covered',()=>{const f=createTargetRailCliffField({...data,platforms:TARGET_CITY_PLATFORMS});let before=0,after=0,total=0;for(const lane of Object.values(data.lanes))for(const p of lane.samples){const[x,y,z]=p.local;if(x<80||x>110||z<75||z>97||y< -45||y> -15)continue;const s=sea(x,z);if(s===null)continue;const original=base(x,z,s),next=f.height(x,z,original,s);total++;if(original>y-.5)before++;if(next>y-.5)after++;}console.log({total,before,after});assert.ok(total>25);assert.ok(before>10);assert.equal(after,0);});

import{buildTargetTerrainHeightfield}from '../../src/world/citadel/targetTerrainHeightfield.js';
test('remeshed cliff is closed and measured vehicle envelope clears central edited segment',()=>{
 const f=createTargetRailCliffField({...data,platforms:TARGET_CITY_PLATFORMS}),{geometry,audit}=buildTargetTerrainHeightfield({bounds:{minX:-143,maxX:143,minZ:-72,maxZ:107},step:1.7,floorAt:(x,z)=>{const s=sea(x,z);return s===null?null:s-12;},heightAt:(x,z)=>{const s=sea(x,z);return s===null?null:f.height(x,z,base(x,z,s),s);}});assert.ok(audit.closed&&audit.minArea>0);
 const matrix=new T.Matrix4().fromArray(data.castleMatrix),a=geometry.attributes.position,idx=geometry.index,tris=[];for(let i=0;i<idx.count;i+=3){const local=[0,1,2].map(j=>new T.Vector3().fromBufferAttribute(a,idx.getX(i+j)));if(local.every(p=>p.x<75)||local.every(p=>p.z<68))continue;const points=local.map(p=>p.applyMatrix4(matrix));tris.push({points,box:new T.Box3().setFromPoints(points)});}
 const contacts=[];let probes=0;for(const[lane,l]of Object.entries(data.lanes)){const body=new T.Box3();for(const b of data.bodyBounds[lane]){body.expandByPoint(new T.Vector3(...b.min));body.expandByPoint(new T.Vector3(...b.max));}for(const s of l.samples){const[x,y,z]=s.local;if(x<80||x>110||z<77||z>95||y< -45||y> -15)continue;const p=new T.Vector3(...s.world),forward=new T.Vector3(...s.tangent).multiplyScalar(data.vehiclePlacement.directions[lane]),up=p.clone().normalize(),right=new T.Vector3().crossVectors(up,forward).normalize();up.crossVectors(forward,right).normalize();const m=new T.Matrix4().makeBasis(right,up,forward).multiply(new T.Matrix4().makeRotationY(-Math.PI/2));m.setPosition(p.clone().addScaledVector(up,.12));const inverse=m.clone().invert(),bbox=body.clone().applyMatrix4(m);probes++;for(const tri of tris){if(bbox.intersectsBox(tri.box)&&body.intersectsTriangle(new T.Triangle(...tri.points.map(p=>p.clone().applyMatrix4(inverse))))){contacts.push({lane,i:s.i,local:s.local});break;}}}}
 console.log({probes,contacts});assert.ok(probes>25);assert.equal(contacts.length,0);geometry.dispose();
});
