import test from 'node:test';import assert from 'node:assert/strict';import * as T from 'three';import{writeFileSync,readFileSync}from'node:fs';
import{actualUserMarkedStructureFixture}from'./targetUserMarkedStructure.fixture.mjs';
import{createTargetCityDetailCandidate}from'../../src/world/citadel/targetCityDetailCandidate.js';
import{createTargetNewCityStairs}from'../../src/world/citadel/targetNewCityStairs.js';
import{createTargetStairSurfaceSampler}from'../../src/world/citadel/targetNewCityStairRoute.js';
const y=-55*Math.PI/180,cs=Math.cos(y),sn=Math.sin(y),toLocal=([x,z])=>[(x-74)*cs-(z-33)*sn,(x-74)*sn+(z-33)*cs];

test('foundation refinement is default off, cannot claim unsampled support, and rejects malformed option',()=>{
 const a=createTargetNewCityStairs(),b=createTargetNewCityStairs({facadeFoundationRefinement:false}),c=createTargetNewCityStairs({facadeFoundationRefinement:true});
 assert.deepEqual(a.report,b.report);assert.equal(a.report.facadeFoundationRefinement.enabled,false);assert.equal(c.report.facadeFoundationRefinement.refined.length,0);assert.throws(()=>createTargetNewCityStairs({facadeFoundationRefinement:'on'}),/must be boolean/);a.dispose();b.dispose();c.dispose();
});

test('default-off is byte-equivalent to stairs6; refinement resources release exactly once',async()=>{
 let source=readFileSync(new URL('../../artifacts/pipeline/citadel-new-foundation-refinement-20261006/targetNewCityStairs.before.js',import.meta.url),'utf8');source=source.replace("from 'three'",`from '${import.meta.resolve('three')}'`).replace("from './targetNewCityMain.js?revision=entry-r39-colour-1'",`from '${new URL('../../src/world/citadel/targetNewCityMain.js',import.meta.url).href}'`).replace("from './targetArchitecturePalette.js'",`from '${new URL('../../src/world/citadel/targetArchitecturePalette.js',import.meta.url).href}'`);
 const oldFactory=(await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'))).createTargetNewCityStairs,opts={surfaceHeightAt:(x,z)=>-Math.abs(x)*.3-1,streetInfill:{publicFootprints:[]}},a=oldFactory(opts),b=createTargetNewCityStairs(opts),geometry=h=>{const rows=[];h.group.traverse(o=>{if(o.isMesh){o.updateMatrix();rows.push([o.name,[...o.geometry.attributes.position.array],[...o.matrix.elements],o.material.color.getHexString()]);}});return rows;};assert.deepEqual(geometry(a),geometry(b));assert.deepEqual(a.report.footprints,b.report.footprints);assert.deepEqual(a.report.walkSurfaces,b.report.walkSurfaces);a.dispose();b.dispose();
 const c=createTargetNewCityStairs({...opts,facadeFoundationRefinement:true}),geometries=new Set(),materials=new Set();let ng=0,nm=0;c.group.traverse(o=>{if(o.isMesh){geometries.add(o.geometry);materials.add(o.material);}});for(const g of geometries)g.addEventListener('dispose',()=>ng++);for(const m of materials)m.addEventListener('dispose',()=>nm++);c.dispose();c.dispose();assert.equal(ng,geometries.size);assert.equal(nm,materials.size);
});

test('actual refinement seats pink foundation and reshapes tall blue base without public or loaded-rail collision',()=>{
 const f=actualUserMarkedStructureFixture();f.release.walkingConnection={kind:'stacked-connected'};f.release.structureOptions={galleryPierWidths:{oldShore:.9},newCityTransitLinks:true};const c=createTargetCityDetailCandidate({castle:f.castle,cliffTransitRelease:f.release,fitSunShadow:false,newCityStreetInfill:true});f.castle.add(c.root);f.scene.updateMatrixWorld(true);const old=c.root.getObjectByName('citadel-target-new-city-stairs'),source=c.report.newCityStairs.authored,sample=createTargetStairSurfaceSampler(f.castle,[f.terrain]);
 const publicSurfaces=[...c.report.newCityStairs.surveyed.selected.treads.map(t=>({id:'surveyed-tread',polygon:t.polygon})),...c.report.bridgeConnector.walkSurfaces,...Object.values(c.report.cliffTransit.galleries).flatMap(g=>g.walkSurfaces),...c.report.cliffTransit.connections.flatMap(l=>l.walkSurfaces.map(s=>({id:l.id,polygon:s.corners.map(p=>[p[0],p[2]])}))),...c.report.cliffTransit.newCityTransitLinks.links.flatMap(l=>l.walkSurfaces)];
 const a=createTargetNewCityStairs({seed:source.seed,palette:source.palette,houseOffsets:source.houseOffsets,facadeFoundationRefinement:true,surfaceHeightAt:(x,z)=>{const v=sample(74+cs*x+sn*z,33-sn*x+cs*z);return v?v.height-12:null;}});a.completeStreetInfill({publicFootprints:publicSurfaces.filter(p=>p.polygon).map(p=>({id:p.id,polygon:p.polygon.map(toLocal)}))});
 for(const child of [...a.group.children])if(!/^new-city-stair-house-/.test(child.name))a.group.remove(child);a.group.position.copy(old.position);a.group.rotation.copy(old.rotation);old.removeFromParent();c.root.add(a.group);f.scene.updateMatrixWorld(true);
 const r=a.report.facadeFoundationRefinement,targets=r.refined.map(h=>a.group.getObjectByName(h.id+'-refined-foundation')),failures=[],paths=[c.report.newCityStairs.surveyed.selected.walkPath,...c.report.cliffTransit.connections.map(l=>l.walkPath),...c.report.cliffTransit.newCityTransitLinks.links.map(l=>l.walkPath),[c.report.bridgeConnector.dock,c.report.bridgeConnector.endpoint],[[72,3,78],[72,3,68],[62,3,68]]];let rays=0,contactRays=0,interpolationRays=0,nicheRays=0;const interpolationFailures=[],contactFailures=[],publicTriangleFailures=[];
 try{
  assert.equal(a.report.revision,'target-new-city-stairs-7-foundation-refinement');assert.equal(r.refined.length,3);assert.deepEqual(r.rejected,[]);assert.equal(a.report.streetInfill.modules.length,3);assert.deepEqual(a.report.houses,source.houses);assert.deepEqual(a.report.walkSurfaces,source.walkSurfaces);assert.deepEqual(a.report.houseOffsets,source.houseOffsets);assert.deepEqual(a.report.footprints.map(p=>[p.id,p.polygon,p.roofY]),source.footprints.map(p=>[p.id,p.polygon,p.roofY]));
  const pink=r.refined.find(h=>h.id==='new-city-stair-house-1--1'),blue=r.refined.find(h=>h.id==='new-city-stair-house-2-1');assert.ok(pink.actualBottom<source.houseFoundations.find(h=>h.id===pink.id).height*-1-.5,'dense slope sample must detect missing side support');assert.equal(blue.lowerSetback,.18);assert.ok(blue.windows.length>=4);assert.ok(blue.arcades.every(p=>p.kind==='raised-blind-retaining-arch'&&!p.throughPassage));assert.ok(r.refined.every(h=>h.arcades.every(x=>x.minimumGroundClearance>=.4799)));
  const inverse=a.group.matrixWorld.clone().invert(),up=new T.Vector3(0,1,0).transformDirection(f.castle.matrixWorld);for(const target of targets)target.traverse(o=>{if(o.isMesh)o.material.side=T.DoubleSide;});
  for(const h of r.refined){const house=a.report.houses.find(v=>v.id===h.id),target=a.group.getObjectByName(h.id+'-refined-foundation'),foot=a.report.footprints.find(p=>p.id===h.id),minX=Math.min(...foot.polygon.map(p=>p[0])),maxX=Math.max(...foot.polygon.map(p=>p[0])),minZ=Math.min(...foot.polygon.map(p=>p[1])),maxZ=Math.max(...foot.polygon.map(p=>p[1]));
   target.traverse(o=>{if(!o.isMesh)return;assert.equal(o.userData.targetWalkable,false);const p=o.geometry.attributes.position;for(let i=0;i<p.count;i++){const v=new T.Vector3().fromBufferAttribute(p,i).applyMatrix4(o.matrixWorld).applyMatrix4(inverse);assert.ok(v.toArray().every(Number.isFinite));assert.ok(v.x>=minX-1e-5&&v.x<=maxX+1e-5&&v.z>=minZ-1e-5&&v.z<=maxZ+1e-5,'footprint expanded');assert.ok(v.y<=house.position[1]+1e-5,'upper house moved');}}
   );
   // Contact band is a real masonry volume straddling both face and inset rock
   // samples. Dense downward probes hit the generated triangles, not metadata.
   for(const face of h.contacts)for(const row of face.profile.slice(1,-1)){for(const p of row.probes){assert.ok(row.bandBottomY<=p.y+.0001);assert.ok(row.bandTopY>p.y);}
    const p=row.probes[0],n={front:[0,1],back:[0,-1],right:[1,0],left:[-1,0]}[face.side],origin=new T.Vector3(p.x-n[0]*.035,row.bandTopY+.08,p.z-n[1]*.035).applyMatrix4(a.group.matrixWorld),hits=new T.Raycaster(origin,up.clone().negate(),0,row.bandTopY-row.bandBottomY+.2).intersectObject(target,true);contactRays++;if(!hits.length)contactFailures.push({id:h.id,side:face.side,u:row.u});
   }
   for(const face of h.contacts){const n={front:[0,1],back:[0,-1],right:[1,0],left:[-1,0]}[face.side];for(let i=1;i<face.profile.length;i++)for(const t of[.25,.5,.75]){
    const L=face.profile[i-1],R=face.profile[i],x=L.probes[0].x*(1-t)+R.probes[0].x*t-n[0]*.035,z=L.probes[0].z*(1-t)+R.probes[0].z*t-n[1]*.035,top=L.bandTopY*(1-t)+R.bandTopY*t,bottom=L.bandBottomY*(1-t)+R.bandBottomY*t,ground=sample(74+cs*x+sn*z,33-sn*x+cs*z)?.height-12;
    const origin=new T.Vector3(x,top+.08,z).applyMatrix4(a.group.matrixWorld),hit=new T.Raycaster(origin,up.clone().negate(),0,top-bottom+.2).intersectObject(target,true)[0],hitY=hit?.point.clone().applyMatrix4(inverse).y;interpolationRays++;
    if(!Number.isFinite(ground)||bottom>ground+.04||!hit||hitY<ground-.04)interpolationFailures.push({id:h.id,side:face.side,x,z,ground,bottom,top,hitY});
   }}
   for(const niche of h.arcades){const outward=new T.Vector3(...niche.outwardLocal).transformDirection(a.group.matrixWorld),origin=new T.Vector3(...niche.centreLocal).applyMatrix4(a.group.matrixWorld).addScaledVector(outward,.08),direction=outward.clone().negate();assert.equal(new T.Raycaster(origin,direction,0,.55).intersectObject(target,true).length,0,h.id+' blind arch filled');assert.ok(new T.Raycaster(origin,direction,0,1).intersectObject(target,true).length,h.id+' retained back missing');nicheRays+=2;}
  }
  for(const path of paths)for(let j=1;j<path.length;j++){const A=new T.Vector3(...path[j-1]),B=new T.Vector3(...path[j]),d=B.clone().sub(A),len=Math.hypot(d.x,d.z),side=new T.Vector3(-d.z,0,d.x).normalize();if(len<1e-7)continue;const n=Math.max(1,Math.ceil(A.distanceTo(B)/.5));for(let i=1;i<=n;i++)for(const lateral of[-.4,0,.4])for(const h of[.05,.55,1.2,1.8]){const start=A.clone().lerp(B,(i-1)/n).addScaledVector(side,lateral).applyMatrix4(f.castle.matrixWorld).addScaledVector(up,h),end=A.clone().lerp(B,i/n).addScaledVector(side,lateral).applyMatrix4(f.castle.matrixWorld).addScaledVector(up,h),delta=end.clone().sub(start);rays++;const hit=new T.Raycaster(start,delta.normalize(),0,start.distanceTo(end)).intersectObjects(targets,true)[0];if(hit)failures.push({path:paths.indexOf(path),name:hit.object.name,point:hit.point.toArray()});}}
  const publicMeshes=[];c.root.traverse(o=>{if(o.isMesh&&(o.userData.targetWalkable||/surveyed.*parapet|bridge.*curb|bridge.*rail/.test(o.name)))publicMeshes.push(o);});
  // Actual public triangles against the complete unchanged plot envelope below
  // the fixed house floor. This conservative test also covers the new deep foot.
  for(const h of r.refined){const house=a.report.houses.find(v=>v.id===h.id),fp=a.report.footprints.find(p=>p.id===h.id),box=new T.Box3(new T.Vector3(Math.min(...fp.polygon.map(p=>p[0])),h.actualBottom,Math.min(...fp.polygon.map(p=>p[1]))),new T.Vector3(Math.max(...fp.polygon.map(p=>p[0])),house.position[1],Math.max(...fp.polygon.map(p=>p[1]))));for(const mesh of publicMeshes){const matrix=new T.Matrix4().multiplyMatrices(inverse,mesh.matrixWorld);mesh.geometry.computeBoundingBox();if(!box.intersectsBox(mesh.geometry.boundingBox.clone().applyMatrix4(matrix)))continue;const p=mesh.geometry.attributes.position,ix=mesh.geometry.index;for(let i=0;i<(ix?.count??p.count);i+=3){const tri=new T.Triangle(...[0,1,2].map(j=>new T.Vector3().fromBufferAttribute(p,ix?ix.getX(i+j):i+j).applyMatrix4(matrix)));if(box.intersectsTriangle(tri)){publicTriangleFailures.push({id:h.id,mesh:mesh.name,face:i/3});break;}}}}
  const records=[];for(const target of targets)target.traverse(o=>{if(!o.isMesh)return;const p=o.geometry.attributes.position,triangles=[];for(let i=0;i<p.count;i+=3){const tri=new T.Triangle(...[0,1,2].map(j=>new T.Vector3().fromBufferAttribute(p,i+j).applyMatrix4(o.matrixWorld)));triangles.push({tri,box:new T.Box3().setFromPoints([tri.a,tri.b,tri.c])});}records.push({name:o.name,box:new T.Box3().setFromObject(o),triangles});});
  const trainBox=new T.Box3(new T.Vector3(-2.32,-.6,-3.49),new T.Vector3(2.32,5.71,3.49)),trainHits=[];let trainPoses=0;for(const lane of['red','blue']){const curve=f.release.curves[lane],count=Math.ceil(curve.getLength()/.75);for(let i=0;i<=count;i++){const p=curve.getPointAt(i/count),t=curve.getTangentAt(i/count).normalize(),right=p.clone().normalize().cross(t).normalize(),up=t.clone().cross(right).normalize(),world=new T.Matrix4().makeBasis(right,up,t).setPosition(p),inv=world.clone().invert(),b=trainBox.clone().applyMatrix4(world);trainPoses++;for(const mesh of records){if(!b.intersectsBox(mesh.box))continue;for(const row of mesh.triangles){if(!b.intersectsBox(row.box))continue;const tri=row.tri.clone();tri.a.applyMatrix4(inv);tri.b.applyMatrix4(inv);tri.c.applyMatrix4(inv);if(trainBox.intersectsTriangle(tri)){trainHits.push({lane,i,mesh:mesh.name});break;}}}}}
  const stats=root=>{let meshes=0,triangles=0;root.traverse(o=>{if(o.isMesh){meshes++;triangles+=(o.geometry.index?.count??o.geometry.attributes.position.count)/3;}});return{meshes,triangles};};
  const evidence={report:r,beforeActualGeometry:stats(old),afterActualGeometry:stats(a.group),housePositionsUnchanged:true,footprintXZUnchanged:true,contactRays,contactFailures,interpolationRays,interpolationFailures,nicheRays,publicTriangleFailures,bodyRays:rays,bodyFailures:failures,trainPoses,trainHits,geometry:a.report.performance,gpuVerified:false};if(process.env.CITADEL_FOUNDATION_REPORT){writeFileSync(process.env.CITADEL_FOUNDATION_REPORT,JSON.stringify(evidence,null,2));writeFileSync(process.env.CITADEL_FOUNDATION_REPORT.replace(/\.json$/,'-geometry.json'),JSON.stringify(a.group.toJSON()));}
  assert.deepEqual(interpolationFailures,[]);assert.deepEqual(contactFailures,[]);assert.deepEqual(publicTriangleFailures,[]);assert.deepEqual(failures,[]);assert.deepEqual(trainHits,[]);assert.ok(rays>2000);assert.ok(contactRays>200);
 }finally{a.dispose();c.dispose();f.dispose();}
});
