import test from 'node:test';import assert from 'node:assert/strict';import * as T from 'three';
import{createTargetCliffTransitRelease}from'../../src/world/citadel/targetCliffTransitRelease.js';
import{prepareCitadelRailStartup}from'../../src/world/citadel/citadelRailStartup.js';
globalThis.document={getElementById:()=>null};globalThis.window={addEventListener(){}};
const{createChristchurchTramSourceCurves}=await import('../../src/world/tramSystem.js');
const sources=createChristchurchTramSourceCurves(160);
test('release composes exact production source three lanes without partial fallback',()=>{const r=createTargetCliffTransitRelease({sourceCurves:sources}),a=prepareCitadelRailStartup(sources,r.specs);assert.equal(a.report.status,'composed-before-construction',JSON.stringify(a.report));assert.equal(r.report.accepted,false);for(const lane of['red','blue','center']){const s=r.specs[lane];assert.ok(s.replacementCurve.getPoint(0).distanceTo(sources[lane].getPointAt(s.startU))<1e-8);assert.ok(s.replacementCurve.getPoint(1).distanceTo(sources[lane].getPointAt(s.endU))<1e-8);assert.ok(r.segments[lane].retainedOld);}});
test('three lanes retain 25m curvature and 4 percent grade in finite half-meter audit',()=>{const r=createTargetCliffTransitRelease();for(const [name,c]of Object.entries(r.curves)){const n=Math.ceil(c.getLength()*2),p=[];let min=Infinity,max=0;for(let i=0;i<=n;i++){const v=c.getPointAt(i/n),t=c.getTangentAt(i/n),s=Math.abs(t.dot(v.clone().normalize()));max=Math.max(max,s/Math.sqrt(1-s*s));p.push(v);}for(let i=1;i<n;i++){const[a,b,d]=p.slice(i-1,i+2),cross=b.clone().sub(a).cross(d.clone().sub(a)).length();if(cross>1e-9)min=Math.min(min,a.distanceTo(b)*b.distanceTo(d)*d.distanceTo(a)/(2*cross));}assert.ok(min>=25,name+':'+min);assert.ok(max<=.04,name+':'+max);}});
test('section interfaces match exact parent curve and cut polygons stay in bounded terrain domain',()=>{const r=createTargetCliffTransitRelease();for(const lane of['red','blue','center'])for(const[k,v]of Object.entries(r.ranges[lane])){assert.ok(v[0]>=0&&v[1]<=1&&v[1]>v[0]);assert.ok(r.segments[lane][k].getPoint(0).distanceTo(r.curves[lane].getPointAt(v[0]))<1e-9);}for(const cut of r.coastalCliffCuts.cuts)for(const[x,z]of cut.polygon){assert.ok(x>=-143-1e-8&&x<=143+1e-8);assert.ok(z>=-72-1e-8&&z<=107+1e-8);}r.coastalCliffCuts.cuts[0].polygon[0][0]=999;assert.notEqual(createTargetCliffTransitRelease().coastalCliffCuts.cuts[0].polygon[0][0],999);});
