import test from 'node:test';
import assert from 'node:assert/strict';
import * as T from 'three';
import {createTargetForestCompanions} from '../../src/world/citadel/targetForestCompanions.js';
function fixture(){const castle=new T.Group(),candidateRoot=new T.Group();castle.add(candidateRoot);castle.rotation.set(.13,.2,-.09);const geometry=new T.SphereGeometry(1.2,8,8);geometry.translate(0,2,0);const material=new T.MeshStandardMaterial(),trees=new T.InstancedMesh(geometry,material,60);trees.name='citadel-canopy-broadleaf-0';for(let i=0;i<60;i++)trees.setMatrixAt(i,new T.Matrix4().makeTranslation((i%10)*8-40,5,Math.floor(i/10)*9-50));castle.add(trees);return{castle,candidateRoot,trees,sampleTerrain:()=>5,sampleSea:()=>0,dispose(){geometry.dispose();material.dispose();}};}
test('finite deterministic companions keep source matrices and bounded draw count',()=>{const f=fixture(),before=[...f.trees.instanceMatrix.array],a=createTargetForestCompanions(f),b=createTargetForestCompanions(f);console.log(a.report.counts,a.report.rejected);assert.ok(a.report.counts.cypress>=16);assert.ok(a.report.counts.shrub>=50);assert.ok(a.report.drawCalls<=4);assert.equal(a.report.accepted,false);assert.deepEqual(a.report,b.report);assert.deepEqual([...f.trees.instanceMatrix.array],before);for(const p of a.report.placements){assert.ok(p.matrix.every(Number.isFinite));assert.ok(p.slope>=.8);assert.ok(p.position[1]>p.seaHeight+1.6);}let released=0;for(const m of a.group.children)m.geometry.addEventListener('dispose',()=>released++);f.castle.add(a.group);a.dispose();a.dispose();assert.equal(released,3);assert.equal(a.group.parent,null);b.dispose();f.dispose();});
test('missing sea/surface and steep slopes cannot be filled by nominal fallback',()=>{for(const options of[{sampleSea:()=>null},{sampleTerrain:()=>null},{sampleTerrain:x=>x*5+100}]){const f=fixture(),a=createTargetForestCompanions({...f,...options});assert.equal(a.report.built,false);a.dispose();f.dispose();}});
test('full building/route envelope and cloud swept envelope reject companions',()=>{const f=fixture(),wall=new T.Mesh(new T.BoxGeometry(200,100,200),new T.MeshBasicMaterial());wall.name='surveyed-route-headroom';f.candidateRoot.add(wall);const a=createTargetForestCompanions(f);assert.equal(a.report.built,false);assert.ok(a.report.rejected.structure>0);a.dispose();wall.visible=false;const cloud=new T.Group();cloud.userData.cloudBankStudy={banks:[{localSweptBounds:{min:[-100,-5,-100],max:[100,100,100]}}]};f.castle.add(cloud);const b=createTargetForestCompanions(f);assert.equal(b.report.built,false);b.dispose();wall.geometry.dispose();wall.material.dispose();f.dispose();});
test('existing crown boxes and new companion boxes stay separate',()=>{const f=fixture(),a=createTargetForestCompanions(f),boxes=a.report.placements.map(p=>new T.Box3(new T.Vector3(...p.bounds.min),new T.Vector3(...p.bounds.max)));f.trees.geometry.computeBoundingBox();for(const box of boxes){for(let i=0;i<f.trees.count;i++){const matrix=new T.Matrix4();f.trees.getMatrixAt(i,matrix);assert.equal(box.intersectsBox(f.trees.geometry.boundingBox.clone().applyMatrix4(matrix)),false);}}for(let i=0;i<boxes.length;i++)for(let j=i+1;j<boxes.length;j++)assert.equal(boxes[i].intersectsBox(boxes[j]),false);a.dispose();f.dispose();});
