import test from'node:test';import assert from'node:assert/strict';import * as T from'three';import{searchTargetCliffShoreRoute,buildTargetCliffShoreBezier,replayTargetCliffShoreCurve,createTargetCliffOffsetCurve}from'../../src/world/citadel/targetCliffShoreRoute.js';
const fixture=()=>({castleMatrix:new T.Matrix4().makeTranslation(0,160,0),startWorld:[-24,168,0],endWorld:[24,168,0],startTangent:new T.Vector3(168,24,0).normalize().toArray(),endTangent:new T.Vector3(168,-24,0).normalize().toArray(),sampleSea:()=>-2,sampleTerrain:(x,z)=>z>=8?10:-5,bounds:{minX:-32,maxX:32,minZ:-16,maxZ:20},gridStep:4,maxCliffDistance:24});
test('multi-node coastal search yields finite constant-radius unobstructed fixture without installing',()=>{const a=searchTargetCliffShoreRoute(fixture());assert.ok(a.report.trials[0].gridPath.length>5);assert.ok(a.candidate);assert.equal(a.report.installed,false);assert.ok(a.candidate.audit.minimumRadius>=25);assert.ok(a.candidate.audit.maximumGrade<=.04);assert.equal(a.candidate.audit.soil,0);});
test('mandatory multiple sea-side waypoints survive graph stage; plaza chord is never accepted',()=>{const o=fixture(),a=searchTargetCliffShoreRoute({...o,waypoints:[[-12,-8],[12,-8]],forbiddenPolygon:[[-6,-3],[6,-3],[6,5],[-6,5]]});assert.ok(a.report.trials.every(t=>t.snapped.length===4));for(const t of a.report.trials)for(const v of t.variants)if(v.clear)assert.equal(v.plaza,0);});
test('missing sea and all-solid terrain reject; absent endpoint tangent cannot silently pass',()=>{for(const options of[{sampleSea:()=>null},{sampleTerrain:()=>100},{startTangent:null}]){const a=searchTargetCliffShoreRoute({...fixture(),...options});assert.equal(a.candidate,null);assert.equal(a.report.status,'failed');}});

test('Bezier explicit tangents preserve low-grade clear arc and serialize without installation',()=>{const r=buildTargetCliffShoreBezier({...fixture(),handleLength:16}).report;assert.equal(r.shapePass,true);assert.ok(r.minimumRadius>=25);assert.ok(r.startAngle<Math.PI/360);assert.ok(r.endAngle<Math.PI/360);assert.equal(r.installed,false);assert.equal(r.serialization.segments.length,1);});
test('Bezier rejects nonfinite input and cannot classify distant offshore cut as valid coast',()=>{assert.throws(()=>buildTargetCliffShoreBezier({...fixture(),handleLength:NaN}),TypeError);const r=buildTargetCliffShoreBezier({...fixture(),sampleTerrain:()=>-5,handleLength:16}).report;assert.ok(r.far>0);assert.equal(r.status,'failed');});

test('serialized curve replays identically and companion has exact source endpoint/tangent corrections',()=>{const built=buildTargetCliffShoreBezier({...fixture(),handleLength:16}),base=replayTargetCliffShoreCurve(built.report.serialization);for(let i=0;i<=100;i++)assert.ok(base.getPoint(i/100).distanceTo(built.curve.getPoint(i/100))<1e-9);const start=base.getPoint(0).add(new T.Vector3(0,0,4.1)),end=base.getPoint(1).add(new T.Vector3(0,0,4.1)),a=createTargetCliffOffsetCurve({base,offset:4.1,startWorld:start.toArray(),endWorld:end.toArray(),startTangent:base.getTangent(0).toArray(),endTangent:base.getTangent(1).toArray()});assert.ok(a.curve.getPoint(0).distanceTo(start)<1e-10);assert.ok(a.curve.getPoint(1).distanceTo(end)<1e-10);assert.ok(a.curve.getTangent(0).angleTo(base.getTangent(0))<Math.PI/360);assert.ok(a.curve.getTangent(1).angleTo(base.getTangent(1))<Math.PI/360);assert.equal(a.report.clearanceVerified,false);});
