import test from 'node:test';
import assert from 'node:assert/strict';
import * as T from 'three';
import {surveyTargetGlobalRailApproach} from '../../src/world/citadel/targetGlobalRailApproachSurvey.js';
class Arc extends T.Curve{constructor(radius=161.15){super();this.radius=radius;}getLength(){return 2;}getPointAt(u,out=new T.Vector3()){return out.set(Math.sin(u*2/this.radius)*this.radius,0,Math.cos(u*2/this.radius)*this.radius);}getTangentAt(u,out=new T.Vector3()){return out.set(Math.cos(u*2/this.radius),0,-Math.sin(u*2/this.radius));}}
const curves=Object.fromEntries(['center','red','blue'].map(k=>[k,new Arc()]));
const water=()=>({terrainRadius:160,seaRadius:160.5,seaUpperRadius:160.567,seaOfficialUpperRadius:160.567});
test('default off does not inspect curves or touch any scene',()=>{assert.equal(surveyTargetGlobalRailApproach({get curves(){throw Error('read');}}).enabled,false);});
test('source-height -.75 deck rejects water before geometry construction; rails/sleepers still clear',()=>{const r=surveyTargetGlobalRailApproach({enabled:true,curves,sampleSurface:water});assert.equal(r.built,false);assert.equal(r.waterPreflightPass,false);assert.equal(r.failures[0].code,'GLOBAL_APPROACH_DECK_WET');assert.ok(r.summary.deckTop.minOceanWaveGap<-.16);assert.ok(r.summary.sleeperBottom.minOceanWaveGap>.55);assert.ok(r.summary.railLowerEnvelope.minOceanWaveGap>.60);assert.equal(r.summary.deckTop.land,0);});
test('land cover is not counted as ocean; a buried deck remains a hard failure',()=>{const r=surveyTargetGlobalRailApproach({enabled:true,curves,sampleSurface:()=>({...water(),terrainRadius:160.8})});assert.equal(r.summary.deckTop.ocean,0);assert.equal(r.failures.some(f=>f.code==='GLOBAL_APPROACH_DECK_WET'),false);assert.equal(r.failures.some(f=>f.code==='GLOBAL_APPROACH_DECK_INSIDE_LAND'),true);});
test('unknown actual sea envelope does not borrow the analytic radius',()=>{const r=surveyTargetGlobalRailApproach({enabled:true,curves,sampleSurface:()=>({terrainRadius:160,seaRadius:160.5,seaOfficialUpperRadius:160.567})});assert.equal(r.waterPreflightPass,false);assert.ok(r.failures.some(f=>f.code==='GLOBAL_APPROACH_SURFACE_UNKNOWN'));});
test('dry raised test curves pass water only and never claim overall acceptance',()=>{const high=Object.fromEntries(['center','red','blue'].map(k=>[k,new Arc(163)]));const r=surveyTargetGlobalRailApproach({enabled:true,curves:high,sampleSurface:water});assert.equal(r.waterPreflightPass,true);assert.equal(r.accepted,false);assert.equal(r.built,false);});
test('invalid dimensions and over-coarse sampling are rejected',()=>{for(const p of[{sampleStep:1},{deckBottom:0},{deckWidth:-1}])assert.throws(()=>surveyTargetGlobalRailApproach({enabled:true,curves,sampleSurface:water,...p}),/DIMENSIONS/);});
