import test from 'node:test';import assert from 'node:assert/strict';import * as T from 'three';import {applyTargetRockAppearance,rockPaletteCoordinates}from '../../src/world/citadel/targetRockAppearance.js';
function fixture(){const scene=new T.Group(),castle=new T.Group();scene.add(castle);const material=new T.MeshStandardMaterial(),base=new T.Color('red');material.onBeforeCompile=s=>{s.uniforms.mtBase={value:base};s.uniforms.mtDetailGain={value:1};s.vertexShader='';s.fragmentShader='varying vec3 vMtShade;\nvec3 mtColor=mix(mtShade,mtBase,.65+.35*mtWash);\nmtColor=mix(mtColor,mtChalk,smoothstep(.57,.86,mtMacro.g)*.13);\ndiffuseColor.rgb=mtColor;';};const mesh=new T.Mesh(new T.BoxGeometry(),material);mesh.name='citadel-oskar-grid-mountain-surface';castle.add(mesh);return{scene,castle,mesh,material,base};}
test('broad rock palette is continuous, directional and nonconstant without vertex mutation',()=>{const a=rockPaletteCoordinates([0,0,0],[1,0,0],[1,0,0]),b=rockPaletteCoordinates([0,0,0],[-1,0,0],[1,0,0]);assert.ok(a.exposure-b.exposure>.8);assert.notEqual(a.layer,rockPaletteCoordinates([0,15,0],[1,0,0],[1,0,0]).layer);for(let x=-40;x<40;x++){const a=rockPaletteCoordinates([x,12,6],[1,0,0]),b=rockPaletteCoordinates([x+.001,12,6],[1,0,0]);assert.ok(Math.abs(a.region-b.region)<.0001);assert.ok(Math.abs(a.layer-b.layer)<.0001);}});
test('shader replaces flattening wash, owns uniforms and follows actual scene sun in castle chart',()=>{const f=fixture(),sun=new T.DirectionalLight(0xffffff,1);sun.position.set(5,0,0);f.scene.add(sun,sun.target);f.castle.rotation.y=Math.PI/2;const positions=[...f.mesh.geometry.attributes.position.array],api=applyTargetRockAppearance(f.castle),shader={uniforms:{},fragmentShader:'',vertexShader:''};f.mesh.material.onBeforeCompile(shader);assert.ok(shader.fragmentShader.includes('float trLayer'));assert.ok(!shader.fragmentShader.includes('.65+.35*mtWash'));assert.equal((shader.fragmentShader.match(/vec3 mtColor=/g)||[]).length,1);assert.notEqual(shader.uniforms.mtBase.value,f.base);f.mesh.onBeforeRender();assert.ok(shader.uniforms.trSunDirection.value.distanceTo(new T.Vector3(0,0,1))<1e-6);sun.position.set(0,5,0);f.mesh.onBeforeRender();assert.ok(shader.uniforms.trSunDirection.value.distanceTo(new T.Vector3(0,1,0))<1e-6);assert.equal(api.report.sunBound,true);assert.deepEqual([...f.mesh.geometry.attributes.position.array],positions);let disposed=0;f.mesh.material.addEventListener('dispose',()=>disposed++);api.dispose();api.dispose();assert.equal(f.mesh.material,f.material);assert.equal(disposed,1);f.mesh.geometry.dispose();f.material.dispose();});
test('missing sun yields neutral palette exposure, no invented directional source',()=>{const f=fixture(),api=applyTargetRockAppearance(f.castle),s={uniforms:{}};f.mesh.material.onBeforeCompile(s);f.mesh.onBeforeRender();assert.equal(api.report.sunBound,false);assert.equal(s.uniforms.trSunDirection.value.length(),0);api.dispose();f.mesh.geometry.dispose();f.material.dispose();});

test('hidden parent and camera-excluded lights never drive mineral shading; director toggles rebind',()=>{
 const f=fixture(),live=new T.DirectionalLight('white',1),hidden=new T.Group(),wrong=new T.DirectionalLight('red',20),layered=new T.DirectionalLight('blue',30),camera=new T.PerspectiveCamera();
 live.position.set(5,0,0);wrong.position.set(0,5,0);layered.position.set(0,0,5);layered.layers.set(2);hidden.visible=false;hidden.add(wrong);f.scene.add(live,hidden,layered);
 const api=applyTargetRockAppearance(f.castle),s={uniforms:{}};f.mesh.material.onBeforeCompile(s);
 f.mesh.onBeforeRender(null,null,camera);assert.ok(s.uniforms.trSunDirection.value.distanceTo(new T.Vector3(1,0,0))<1e-6);
 hidden.visible=true;f.mesh.onBeforeRender(null,null,camera);assert.ok(s.uniforms.trSunDirection.value.distanceTo(new T.Vector3(0,1,0))<1e-6);
 hidden.visible=false;live.intensity=0;f.mesh.onBeforeRender(null,null,camera);assert.equal(api.report.sunBound,false);assert.equal(s.uniforms.trSunDirection.value.length(),0);api.dispose();f.mesh.geometry.dispose();f.material.dispose();
});
