import test from'node:test';import assert from'node:assert/strict';import * as T from'three';import{createTargetCliffTransitPlan}from'../../src/world/citadel/targetCliffTransitPlan.js';
const matrix=new T.Matrix4().makeTranslation(0,160,0),path=[[-12,10,0],[12,10,0]];
function options(){const g=new T.Group();g.matrixAutoUpdate=false;g.matrix.copy(matrix);g.updateMatrixWorld(true);return{castleMatrix:matrix,bridgeReport:{path,width:4.4},bridgeRoot:g,sampleTerrain:()=>-20,sampleSea:()=>-10};}
test('diagnostic produces finite world-space lower lanes, never autoaccepts or installs',()=>{const o=options(),a=createTargetCliffTransitPlan(o);assert.equal(a.report.accepted,false);assert.equal(a.report.installed,false);assert.equal(a.report.issues.length,0);assert.ok(Math.abs(a.report.dimensions.requiredWidth-8.74)<1e-10);for(const s of a.report.sections){assert.ok(s.world.every(Number.isFinite));assert.ok(Math.abs(new T.Vector3(...s.lanes[0].world).distanceTo(new T.Vector3(...s.lanes[1].world))-4.1)<1e-8);}assert.deepEqual(o.bridgeReport.path,path);});
test('actual bridge pier triangles reject envelope and missing sea cannot pass',()=>{const o=options(),pier=new T.Mesh(new T.BoxGeometry(3,15,12));pier.name='actual-pier';pier.position.y=3;o.bridgeRoot.add(pier);o.bridgeRoot.updateMatrixWorld(true);const a=createTargetCliffTransitPlan(o);assert.ok(a.report.issues.some(x=>x.bridgeHits.includes('actual-pier')));const b=createTargetCliffTransitPlan({...options(),sampleSea:()=>null});assert.ok(b.report.issues.every(x=>x.missing===9));pier.geometry.dispose();pier.material.dispose();});
test('terrain intrusion, sharp corner and steep grade remain explicit failures',()=>{const o=options();const a=createTargetCliffTransitPlan({...o,sampleTerrain:()=>5,bridgeReport:{path:[[-10,10,0],[0,10,0],[10,17,10]],width:4.4}});assert.ok(a.report.issues.some(x=>x.soil));assert.ok(a.report.turns.length);assert.equal(a.report.gradePass,false);assert.equal(a.report.status,'failed-diagnostic');});
test('radial lower deck is near-zero world grade and solves real upper/sea bounds without moving bridge',()=>{const o=options(),before=JSON.stringify(o.bridgeReport.path),p=createTargetCliffTransitPlan({...o,mode:'radial'});assert.equal(JSON.stringify(o.bridgeReport.path),before);assert.ok(p.report.maximumGrade<.001);assert.ok(p.report.radialSolve.verticalFeasible);assert.ok(p.report.radialSolve.radius>=p.report.radialSolve.minRequired);const radii=p.report.sections.map(s=>new T.Vector3(...s.world).length());assert.ok(Math.max(...radii)-Math.min(...radii)<1e-8);assert.equal(p.report.accepted,false);});
test('real-rail default grade and curve radius gates reject tight radial bends',()=>{const o=options(),p=createTargetCliffTransitPlan({...o,mode:'radial',bridgeReport:{path:[[-8,10,0],[0,10,0],[0,10,8]],width:4.4}});assert.equal(p.report.maxGrade,.04);assert.equal(p.report.minCurveRadius,25);assert.equal(p.report.curveRadiusPass,false);assert.equal(p.report.status,'failed-diagnostic');assert.equal(p.report.bodyProjectionCovered,false);});
test('nonfinite water/matrix/path and zero sampling step reject before generating a plan',()=>{for(const delta of[{waterClearance:NaN},{step:0},{castleMatrix:Array(16).fill(NaN)},{castleMatrix:Array(16).fill(0)},{bridgeReport:{path:[[0,0,0],[NaN,2,3]],width:4.4}},{bridgeReport:{path:[[0,0,0],[0,0,0]],width:4.4}}])assert.throws(()=>createTargetCliffTransitPlan({...options(),...delta}));});
import{findTargetCliffBankCandidates}from'../../src/world/citadel/targetCliffTransitPlan.js';
test('shore search returns finite uninstalled candidates and rejects obstructed approaches',()=>{const o=options(),plan=createTargetCliffTransitPlan({...o,mode:'radial'}),a=findTargetCliffBankCandidates({plan,...o});assert.ok(a.banks.old.candidates.length>0);assert.equal(a.installed,false);for(const bank of Object.values(a.banks))for(const c of bank.candidates){assert.ok(c.minimumTerrainGap>.05);assert.ok(c.anchorLocal.every(Number.isFinite));assert.equal(c.globalConnected,false);}const b=findTargetCliffBankCandidates({plan,...o,sampleTerrain:()=>100});assert.equal(b.banks.old.candidates.length,0);assert.equal(b.banks.new.candidates.length,0);});
test('explicit lower radius respects the measured upper/lower corridor bounds',()=>{const o=options(),a=createTargetCliffTransitPlan({...o,mode:'radial',lowerRadius:164});assert.equal(a.report.radialSolve.radius,164);assert.equal(a.report.radialSolve.verticalFeasible,true);const b=createTargetCliffTransitPlan({...o,mode:'radial',lowerRadius:200});assert.equal(b.report.radialSolve.verticalFeasible,false);assert.equal(b.report.status,'failed-diagnostic');});
