import test from 'node:test';
import assert from 'node:assert/strict';
import * as T from 'three';
import {createTargetForestCompanions} from '../../src/world/citadel/targetForestCompanions.js';
import {prepareEastCliffCompanionRefresh} from '../../src/world/citadel/targetEastCliffCompanionRefresh.js';
function fixture(){const castle=new T.Group(),candidateRoot=new T.Group();castle.add(candidateRoot);castle.rotation.set(.13,.2,-.09);const g=new T.SphereGeometry(1.2,8,8);g.translate(0,2,0);const trees=new T.InstancedMesh(g,new T.MeshStandardMaterial(),60);trees.name='citadel-canopy-broadleaf-0';for(let i=0;i<60;i++)trees.setMatrixAt(i,new T.Matrix4().makeTranslation(i%10*8-40,5,Math.floor(i/10)*9-50));castle.add(trees);const args={castle,candidateRoot,sampleTerrain:()=>5,sampleSea:()=>0},original=createTargetForestCompanions(args);candidateRoot.add(original.group);candidateRoot.userData.detailCandidateReport={forestCompanions:original.report};const remap=Array.from({length:60},(_,i)=>i===0?null:i-1);trees.instanceMatrix.array.copyWithin(0,16);trees.count=59;trees.instanceMatrix.needsUpdate=true;const vegetationReport={applied:true,instanceRemap:[{uuid:trees.uuid,name:trees.name,before:60,after:59,oldToNew:remap}]};return{...args,trees,original,vegetationReport,enabled:true,clean(){original.dispose();g.dispose();trees.material.dispose();}};}
test('default off and preparation do not mutate live companion resources or report',()=>{const f=fixture(),old=f.original.report,a=prepareEastCliffCompanionRefresh({...f,enabled:false});assert.equal(a.report.ready,false);const b=prepareEastCliffCompanionRefresh(f);assert.equal(b.report.ready,true,JSON.stringify(b.report));assert.equal(f.original.group.userData.forestCompanionsReport,old);b.dispose();assert.equal(f.original.group.userData.forestCompanionsReport,old);f.clean();});
test('actual remap rebuilt companions stay supported and preserve mesh/material identity; exact rollback',()=>{const f=fixture(),meshes=f.original.group.children.slice(),attrs=meshes.map(m=>m.instanceMatrix),materials=meshes.map(m=>m.material),old=f.original.report,b=prepareEastCliffCompanionRefresh(f);assert.ok(b.report.ready);assert.ok(b.commit());assert.deepEqual(f.original.group.children,meshes);meshes.forEach((m,i)=>assert.equal(m.material,materials[i]));const r=f.original.group.userData.forestCompanionsReport;assert.equal(f.candidateRoot.userData.detailCandidateReport.forestCompanions,r);assert.notEqual(r,old);assert.ok(r.placements.length>10);for(const p of r.placements){assert.ok(p.anchor.index<59);assert.ok(Math.abs(p.position[1]-4.988)<1e-8);assert.ok(p.rootGap.every(g=>g<=.002&&g>=-.20));}assert.ok(b.report.remappedAnchors.some(a=>a.from.index!==a.to.index));b.rollback();assert.equal(f.candidateRoot.userData.detailCandidateReport.forestCompanions,old);meshes.forEach((m,i)=>assert.equal(m.instanceMatrix,attrs[i]));b.dispose();f.clean();});
test('hidden group and zero-scale paired companions are not resurrected',()=>{const f=fixture(),m=f.original.group.getObjectByName('target-companion-cypress'),tr=f.original.group.getObjectByName('target-companion-trunks');m.setMatrixAt(0,new T.Matrix4().makeScale(0,0,0));tr.setMatrixAt(0,new T.Matrix4().makeScale(0,0,0));f.original.group.visible=false;const b=prepareEastCliffCompanionRefresh(f);assert.ok(b.report.ready,JSON.stringify(b.report));assert.ok(b.commit());assert.equal(f.original.group.visible,false);assert.equal(b.report.hiddenSlots,1);for(const mesh of[m,tr]){const a=new T.Matrix4();mesh.getMatrixAt(mesh.count-1,a);assert.equal(a.determinant(),0);}b.rollback();f.clean();});
test('moving public obstacle or changed tree buffer rejects commit atomically',()=>{for(const type of['obstacle','tree']){const f=fixture(),ob=new T.Mesh(new T.BoxGeometry(1,1,1),new T.MeshBasicMaterial());ob.position.set(150,20,100);f.candidateRoot.add(ob);const b=prepareEastCliffCompanionRefresh(f),old=f.original.report;assert.ok(b.report.ready);if(type==='obstacle')ob.position.x+=1;else f.trees.setMatrixAt(0,new T.Matrix4().makeTranslation(10,5,10));assert.equal(b.commit(),false);assert.equal(f.original.group.userData.forestCompanionsReport,old);b.dispose();ob.geometry.dispose();ob.material.dispose();f.clean();}});
test('missing final sea rejects instead of publishing an empty rebuilt forest',()=>{const f=fixture(),old=f.original.report,b=prepareEastCliffCompanionRefresh({...f,sampleSea:()=>null});assert.equal(b.report.ready,false);assert.equal(b.commit(),false);assert.equal(f.original.group.userData.forestCompanionsReport,old);f.clean();});
test('castle-local rebuild matrices account for existing companion mesh transforms',()=>{const f=fixture();f.original.group.position.set(2,0,-3);f.original.group.rotation.y=.3;f.castle.updateWorldMatrix(true,true);const b=prepareEastCliffCompanionRefresh(f);assert.ok(b.commit());const mesh=f.original.group.getObjectByName('target-companion-cypress'),p=f.original.group.userData.forestCompanionsReport.placements.find(p=>p.kind==='cypress'),m=new T.Matrix4();mesh.getMatrixAt(0,m);const world=new T.Vector3().setFromMatrixPosition(mesh.matrixWorld.clone().multiply(m)),expected=new T.Vector3(...p.position).applyMatrix4(f.castle.matrixWorld);assert.ok(world.distanceTo(expected)<1e-5);b.dispose();f.clean();});

test('live cyclic candidate handle does not serialize or mutate when preparing structural view',()=>{const f=fixture(),handle={root:f.candidateRoot};f.candidateRoot.userData.candidateHandle=handle;const b=prepareEastCliffCompanionRefresh(f);assert.ok(b.report.ready,JSON.stringify(b.report));assert.equal(f.candidateRoot.userData.candidateHandle,handle);assert.ok(b.commit());b.rollback();f.clean();});
