import test from 'node:test';import assert from 'node:assert/strict';import * as T from 'three';import{readFileSync,writeFileSync}from'node:fs';
import{createTargetNewCityMain}from'../../src/world/citadel/targetNewCityMain.js';
import{createTargetOldCity}from'../../src/world/citadel/targetOldCity.js';
import{createTargetCityEntityEditor}from'../../src/world/citadel/targetCityEntityEditor.js';
import{createTargetCityPlayerSupport}from'../../src/world/citadel/targetCityPlayerSupport.js';
const near=(a,b,t=2e-5)=>assert.ok(Math.abs(a-b)<=t,`${a} differs from ${b}`);
const batches=a=>{const out=[];a.group.traverse(o=>{if(o.userData.targetWindowBatch)out.push(o);});return out;};
const snapshot=a=>{const out=[];a.group.traverse(o=>{if(o.isMesh){o.updateMatrix();out.push([o.name,[...o.matrix.elements],Object.fromEntries(Object.entries(o.geometry.attributes).map(([k,v])=>[k,[...v.array]])),o.geometry.index?[...o.geometry.index.array]:null,o.material.color.getHexString()]);}});return out;};

test('window batching is opt-in and default matches the saved main factory byte for byte',async()=>{
 let source=readFileSync(new URL('../../artifacts/pipeline/citadel-main-window-batching-20261006/targetNewCityMain.before.js',import.meta.url),'utf8');source=source.replace("from 'three'",`from '${import.meta.resolve('three')}'`).replace("from './targetArchitecturePalette.js'",`from '${new URL('../../src/world/citadel/targetArchitecturePalette.js',import.meta.url).href}'`);const before=(await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'))).createTargetNewCityMain;
 for(const proportion of['original','expanded-1']){const a=before({proportion}),b=createTargetNewCityMain({proportion});assert.deepEqual(snapshot(a),snapshot(b));assert.deepEqual(a.report.footprints,b.report.footprints);assert.equal(b.report.windowBatching.enabled,false);a.dispose();b.dispose();}assert.throws(()=>createTargetNewCityMain({batchWindowDetails:'yes'}),/must be boolean/);
});

for(const proportion of['original','expanded-1'])test(proportion+' batches preserve every world vertex, normal, UV, material colour and window ray',()=>{
 const a=createTargetNewCityMain({proportion}),b=createTargetNewCityMain({proportion,batchWindowDetails:true}),scene=new T.Group();scene.position.set(19,163,-37);scene.rotation.set(.13,-.41,.07);scene.add(a.group,b.group);for(const asset of[a,b]){asset.group.position.set(74,12,33);asset.group.rotation.y=-55*Math.PI/180;}scene.updateMatrixWorld(true);
 try{
  assert.equal(b.report.version,'target-new-city-main-v4-window-batches');assert.equal(b.report.windowBatching.windowCount,34);assert.equal(b.report.windowBatching.beforeMeshes,204);assert.equal(b.report.windowBatching.afterMeshes,6);assert.equal(b.report.performance.meshes,a.report.performance.meshes-198);assert.equal(b.report.performance.triangles,a.report.performance.triangles);assert.equal(b.report.performance.materials,a.report.performance.materials);assert.deepEqual(b.report.footprints,a.report.footprints);assert.deepEqual(b.report.entry,a.report.entry);assert.deepEqual(b.report.passage,a.report.passage);assert.deepEqual(b.report.stairs,a.report.stairs);
  const ba=new T.Box3().setFromObject(a.group,true),bb=new T.Box3().setFromObject(b.group,true);for(const k of['min','max','size'])for(let i=0;i<3;i++)near(a.report.bounds[k][i],b.report.bounds[k][i]);for(const k of['min','max'])for(const axis of['x','y','z'])near(ba[k][axis],bb[k][axis]);const allSources=[],rows=[];let vertices=0,rays=0,maxPositionError=0,maxNormalError=0;
  for(const batch of batches(b)){
   assert.equal(batch.visible,true);assert.equal(batch.userData.targetWalkable,false);assert.equal(batch.userData.preserveCitadelMaterials,true);assert.equal(batch.material.transparent,false);const normalB=new T.Matrix3().getNormalMatrix(batch.matrixWorld),p=batch.geometry.attributes.position,n=batch.geometry.attributes.normal,uv=batch.geometry.attributes.uv;
   for(const row of batch.userData.targetWindowBatch.sourceFaces){const source=a.group.getObjectByName(row.sourceName);assert.ok(source?.isMesh);assert.equal(b.group.getObjectByName(row.sourceName),undefined,'original mesh should be removed, not hidden');assert.equal(b.group.getObjectByName(row.windowName).children.length,0);assert.equal(source.material.name,batch.material.name);assert.equal(source.material.color.getHexString(),batch.material.color.getHexString());assert.equal(source.material.roughness,batch.material.roughness);assert.equal(source.castShadow,batch.castShadow);assert.equal(source.receiveShadow,batch.receiveShadow);assert.equal(source.layers.mask,batch.layers.mask);const g=source.geometry,ix=g.index,normalA=new T.Matrix3().getNormalMatrix(source.matrixWorld);allSources.push(source);
    for(let j=0;j<row.vertexCount;j++){const i=ix?ix.getX(j):j,oldPoint=new T.Vector3().fromBufferAttribute(g.attributes.position,i).applyMatrix4(source.matrixWorld),newPoint=new T.Vector3().fromBufferAttribute(p,row.firstVertex+j).applyMatrix4(batch.matrixWorld),oldNormal=new T.Vector3().fromBufferAttribute(g.attributes.normal,i).applyMatrix3(normalA).normalize(),newNormal=new T.Vector3().fromBufferAttribute(n,row.firstVertex+j).applyMatrix3(normalB).normalize();const pe=oldPoint.distanceTo(newPoint),ne=oldNormal.distanceTo(newNormal);assert.ok(pe<2e-5);assert.ok(ne<2e-6);maxPositionError=Math.max(maxPositionError,pe);maxNormalError=Math.max(maxNormalError,ne);assert.equal(!!g.attributes.uv,!!uv);if(uv){near(g.attributes.uv.getX(i),uv.getX(row.firstVertex+j),0);near(g.attributes.uv.getY(i),uv.getY(row.firstVertex+j),0);}vertices++;}
    assert.equal(row.triangleCount,row.vertexCount/3);assert.equal(row.semantic,'protected-main-window-detail');rows.push({batch,source,row});
   }
  }
  assert.equal(new Set(allSources).size,204);assert.equal(vertices/3,b.report.windowBatching.triangles);
  for(const {source}of rows){source.geometry.computeBoundingBox();const point=source.geometry.boundingBox.getCenter(new T.Vector3());point.z=source.geometry.boundingBox.max.z;point.applyMatrix4(source.matrixWorld);const outward=new T.Vector3(0,0,1).transformDirection(source.matrixWorld),ray=new T.Raycaster(point.clone().addScaledVector(outward,.35),outward.clone().negate(),0,1),x=ray.intersectObjects(allSources,false)[0],y=ray.intersectObjects(batches(b),false)[0];assert.ok(x&&y,source.name);near(x.distance,y.distance);assert.ok(x.point.distanceTo(y.point)<2e-5);const semantic=y.object.userData.targetWindowBatch.sourceFaces.find(r=>y.faceIndex>=r.firstTriangle&&y.faceIndex<r.firstTriangle+r.triangleCount);assert.ok(semantic);assert.equal(semantic.sourceName,x.object.name);rays++;}
  // All non-window geometry remains byte-identical, including public entrance.
  const oldNonWindow=snapshot(a).filter(r=>!allSources.some(o=>o.name===r[0])),newNonWindow=snapshot(b).filter(r=>!r[0].startsWith('main-window-batch-'));assert.deepEqual(oldNonWindow,newNonWindow);
  const evidence={proportion,before:a.report.performance,after:b.report.performance,windowBatching:b.report.windowBatching,worldVerticesCompared:vertices,windowRays:rays,maxPositionError,maxNormalError,gpuMeasured:false};if(process.env.CITADEL_MAIN_WINDOW_REPORT){const suffix=proportion==='original'?'original':'expanded';writeFileSync(process.env.CITADEL_MAIN_WINDOW_REPORT.replace(/\.json$/,'-'+suffix+'.json'),JSON.stringify(evidence,null,2));}
 }finally{a.dispose();b.dispose();}
});

test('real batch is a protected nearest face and cannot pick through to editable old-city housing',()=>{
 const a=createTargetNewCityMain({batchWindowDetails:true}),old=createTargetOldCity(),root=new T.Group();root.add(a.group,old.group);const window=a.group.getObjectByName('blue-front-1-4.2'),house=old.report.houses[0];old.group.position.set(window.position.x-house.position[0],window.position.y-house.position[1]-2,window.position.z-house.position[2]-2.35-4);root.updateMatrixWorld(true);
 const editor=createTargetCityEntityEditor({root,targetId:'batch-check',terrainVersion:'fixed',factoryVersion:old.report.version});try{assert.equal(editor.size,15);const origin=window.getWorldPosition(new T.Vector3()).add(new T.Vector3(.15,0,.5)),ray=new T.Raycaster(origin,new T.Vector3(0,0,-1),0,30);assert.ok(ray.intersectObject(old.group,true).length,'actual editable city must exist behind pane');const picked=editor.intersectClosestVisible(ray,root);assert.equal(picked.kind,'protected');assert.ok(picked.object.userData.targetWindowBatch);const id=editor.list()[0].id;assert.equal(editor.edit({id,wallColor:'#aabbcc',occupied:false}).ok,true);assert.equal(editor.undo().ok,true);assert.equal(editor.intersectClosestVisible(ray,root).kind,'protected');}finally{editor.dispose();a.dispose();old.dispose();}
});

test('player provider refresh uses replacement triangles, preserves open nave and solid jamb, and never treats windows as floors',()=>{
 const castle=new T.Group();castle.position.set(0,10000,0);const root=new T.Group(),terrain=new T.Mesh(new T.BoxGeometry(250,1,250),new T.MeshBasicMaterial());terrain.position.y=-1;castle.add(root,terrain);const a=createTargetNewCityMain(),b=createTargetNewCityMain({batchWindowDetails:true});root.add(a.group);const provider=createTargetCityPlayerSupport({castle,candidateRoot:root,finalTerrain:terrain}),point=(x,y,z)=>new T.Vector3(x,y,z).applyMatrix4(castle.matrixWorld);
 const audit=()=>{const rows=[];for(const x of[-1.8,0,1.8,3.6]){const previous=point(x,1.2,7.2),next=point(x,1.2,4.8),velocity=next.clone().sub(previous).normalize(),blocked=provider.walls(previous,next,velocity);rows.push({x,blocked,position:next.toArray(),ground:provider.ground(point(x,1.3,6))});}return rows;};
 try{const before=audit();a.group.removeFromParent();root.add(b.group);provider.refresh();const after=audit();assert.deepEqual(after,before);assert.deepEqual(after.map(r=>r.blocked),[false,false,false,true]);assert.equal(provider.ground(point(8.05,14.3,.5)),null);assert.equal(provider.ground(point(0,23.3,-1.4)),null);for(const batch of batches(b)){assert.equal(batch.userData.targetWalkable,false);assert.equal(batch.visible,true);}}
 finally{provider.dispose();a.dispose();b.dispose();terrain.geometry.dispose();terrain.material.dispose();}
});

test('batched geometry and shared materials release once; independent factory remains usable',()=>{
 const a=createTargetNewCityMain({batchWindowDetails:true}),b=createTargetNewCityMain(),geometries=new Set(),materials=new Set();let ng=0,nm=0;a.group.traverse(o=>{if(o.isMesh){geometries.add(o.geometry);materials.add(o.material);}});for(const g of geometries)g.addEventListener('dispose',()=>ng++);for(const m of materials)m.addEventListener('dispose',()=>nm++);assert.equal(geometries.size,a.report.performance.geometries);a.dispose();a.dispose();assert.equal(ng,geometries.size);assert.equal(nm,materials.size);assert.ok(b.group.getObjectByName('blue-front-1-4.2-recess').isMesh);b.dispose();
});
