import test from 'node:test';import assert from 'node:assert/strict';import * as T from 'three';import {createTargetBenchTurf,smoothBenchSlope} from '../../src/world/citadel/targetBenchTurf.js';
function fixture(){const castle=new T.Group(),g=new T.PlaneGeometry(20,20,4,4);g.rotateX(-Math.PI/2);g.translate(0,10,0);const m=new T.Mesh(g,new T.MeshBasicMaterial({side:T.DoubleSide}));castle.add(m);return{castle,surfaces:[m],sampleSea:()=>0};}
test('flat final bench covered on source and legacy grass restored',()=>{const o=fixture(),old=new T.Group();old.name='citadel-study-groundcover';o.castle.add(old);const before=o.surfaces[0].geometry.attributes.position.array.slice(),r=createTargetBenchTurf(o);assert.equal(r.report.built,true);assert.equal(r.report.drawCalls,1);assert.ok(r.report.triangles>0);assert.equal(old.visible,false);const p=r.group.children[0].geometry.attributes.position;for(let i=0;i<p.count;i++)assert.equal(p.getY(i),10);assert.deepEqual(o.surfaces[0].geometry.attributes.position.array,before);r.dispose();assert.equal(old.visible,true);});
test('vertical cliff and missing sea never become turf',()=>{const o=fixture();o.surfaces[0].rotation.z=Math.PI/2;let r=createTargetBenchTurf(o);assert.equal(r.report.triangles,0);r.dispose();const f=fixture(),old=new T.Group();old.name='citadel-study-meadow-grass';f.castle.add(old);r=createTargetBenchTurf({...f,sampleSea:()=>null});assert.equal(r.report.triangles,0);assert.equal(old.visible,true);r.dispose();});
test('first-hit rejects lower overlapping sheet without changing upper source',()=>{const o=fixture(),lower=o.surfaces[0].clone();lower.geometry=lower.geometry.clone();lower.position.y=-1;o.castle.add(lower);o.surfaces.push(lower);const r=createTargetBenchTurf(o),p=r.group.children[0].geometry.attributes.position;assert.ok(r.report.hiddenFaceRejects>0);for(let i=0;i<p.count;i++)assert.equal(p.getY(i),10);r.dispose();});
test('clipped/refined outputs stay barycentric on parent face; shared coordinates agree',()=>{const o=fixture(),g=o.surfaces[0].geometry,p=g.attributes.position;for(let i=0;i<p.count;i++){const x=p.getX(i);p.setY(i,10+(x>0?x*2:0));}g.computeVertexNormals();const r=createTargetBenchTurf(o),out=r.group.children[0].geometry,a=out.attributes.position,ids=out.attributes.sourceFace,ix=g.index,tri=new T.Triangle(),bary=new T.Vector3();assert.ok(r.report.triangles>0&&r.report.splitEdges>0);for(let i=0;i<a.count;i++){const f=ids.getX(i)*3;tri.set(...[0,1,2].map(k=>new T.Vector3().fromBufferAttribute(p,ix.getX(f+k))));const point=new T.Vector3().fromBufferAttribute(a,i);tri.getBarycoord(point,bary);assert.ok(Math.min(bary.x,bary.y,bary.z)>-1e-5);assert.ok(new T.Plane().setFromCoplanarPoints(tri.a,tri.b,tri.c).distanceToPoint(point)<1e-5);}assert.ok(r.report.triangles<=120000);r.dispose();});
test('two adjacent source faces produce identical subdivided clipped common-edge coordinates',()=>{const o=fixture(),g=new T.PlaneGeometry(20,20,1,1);g.rotateX(-Math.PI/2);g.translate(0,10,0);g.attributes.position.setY(0,18);g.computeVertexNormals();o.surfaces[0].geometry=g;const r=createTargetBenchTurf({...o,sampleSea:x=>8.4+x*.2}),ix=g.index,p=g.attributes.position;const common=[ix.getX(0),ix.getX(1),ix.getX(2)].filter(v=>[ix.getX(3),ix.getX(4),ix.getX(5)].includes(v));const a=new T.Vector3().fromBufferAttribute(p,common[0]),b=new T.Vector3().fromBufferAttribute(p,common[1]),edge=new T.Line3(a,b),out=r.group.children[0].geometry,sets=[new Set(),new Set()];for(let i=0;i<out.attributes.position.count;i++){const q=new T.Vector3().fromBufferAttribute(out.attributes.position,i);if(edge.closestPointToPoint(q,true,new T.Vector3()).distanceTo(q)<1e-5)sets[out.attributes.sourceFace.getX(i)].add(q.toArray().map(n=>String(Math.round(n*1e5))).join(','));}assert.ok(sets[0].size>=2);assert.deepEqual([...sets[0]].sort(),[...sets[1]].sort());r.dispose();});

test('paving prism wholly inside a large source face cuts a true hole without lifting grass',()=>{
 const castle=new T.Group(),g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute([-10,10,-10,0,10,12,10,10,-10],3));const m=new T.Mesh(g,new T.MeshBasicMaterial({side:T.DoubleSide}));castle.add(m);const r=createTargetBenchTurf({castle,surfaces:[m],sampleSea:()=>0,exclusions:[{polygon:[[-1,-1],[1,-1],[1,1],[-1,1]],minY:9,maxY:11}]});castle.add(r.group);castle.updateMatrixWorld(true);const ray=new T.Raycaster(new T.Vector3(0,20,0),new T.Vector3(0,-1,0));assert.equal(ray.intersectObject(r.group,true).length,0);ray.set(new T.Vector3(3,20,0),new T.Vector3(0,-1,0));assert.ok(ray.intersectObject(r.group,true).length>0);const p=r.group.children[0].geometry.attributes.position;let area=0;for(let i=0;i<p.count;i+=3){const tri=new T.Triangle(...[0,1,2].map(k=>new T.Vector3().fromBufferAttribute(p,i+k)));area+=tri.getArea();for(const v of[tri.a,tri.b,tri.c])assert.equal(v.y,10);}assert.ok(Math.abs(area-216)<1e-4,area);assert.equal(r.report.accepted,false);r.dispose();g.dispose();m.material.dispose();
});

import {compileOfficialOcean} from '../../src/world/waterV8/officialOcean.js';
import {applyTargetTerrainCandidate} from '../../src/world/citadel/targetTerrainCandidate.js';
import {createTargetStairSurfaceSampler} from '../../src/world/citadel/targetNewCityStairRoute.js';
function frozenScene() {
  const scene = new T.Group(), castle = new T.Group(); scene.add(castle);
  castle.matrixAutoUpdate = false;
  castle.matrix.fromArray([-.5771265090244172,.12463062405961449,.807088718870361,0,.6354855835814281,.689249750214348,.3479839865419536,0,-.5129162364767383,.7137240288626759,-.4769852670498,0,124.43456408079132,72.61606956254715,90.15650671642375,1]);
  const source = new T.Mesh(new T.BoxGeometry(), new T.MeshBasicMaterial({side: T.DoubleSide}));
  source.name = 'citadel-oskar-grid-mountain-surface'; castle.add(source);
  const previous = globalThis.location;
  globalThis.location = {search: '?citadelTerrainFirst=1&citadelTargetRemesh=1&citadelTerraceAprons=1&citadelRecessedSaddle=1&citadelValleyBenches=1'};
  try {const obsolete = source.geometry; applyTargetTerrainCandidate(castle); obsolete.dispose();}
  finally {if (previous === undefined) delete globalThis.location; else globalThis.location = previous;}
  const compiled = compileOfficialOcean().ocean, geometry = new T.BufferGeometry();
  geometry.setAttribute('position', new T.BufferAttribute(compiled.positions, 3));
  geometry.setIndex(new T.BufferAttribute(compiled.indices, 1)); geometry.computeVertexNormals();
  const ocean = new T.Mesh(geometry, new T.MeshBasicMaterial({side: T.DoubleSide})); ocean.name = 'planet-v8-curved-ocean'; scene.add(ocean);
  const originalBuilding = new T.Group(); originalBuilding.name = 'old-city-preserved'; castle.add(originalBuilding);
  scene.updateMatrixWorld(true);
  return {scene, castle, source, ocean, originalBuilding, dispose() {for (const m of [source, ocean]) {m.geometry.dispose(); m.material.dispose();}}};
}

test('bounded two-round scalar smoothing reduces alternating edge slope without touching input',()=>{const values=Array.from({length:30},(_,i)=>i%2?.86:.54),before=[...values],adj=values.map((_,i)=>[i-1,i+1].filter(j=>j>=0&&j<values.length)),smooth=smoothBenchSlope(values,adj),variation=a=>a.slice(1).reduce((sum,x,i)=>sum+Math.abs(x-a[i]),0);assert.ok(variation(smooth)<variation(values)*.4);assert.ok(smooth.every((v,i)=>Math.abs(v-values[i])<=.12000001));assert.deepEqual(values,before);console.log({alternatingBefore:variation(values),alternatingAfter:variation(smooth)});});
test('actual r17 final triangles remain unchanged and smoothed turf builds within 120k',()=>{const f=frozenScene(),sampleSea=createTargetStairSurfaceSampler(f.castle,[f.ocean]),before=f.source.geometry.attributes.position.array.slice(),r=createTargetBenchTurf({castle:f.castle,surfaces:[f.source],sampleSea,exclusions:[{polygon:[[51,71],[78,71],[78,85],[51,85]],minY:2.2,maxY:3.5}]});console.log({actual:r.report.built,triangles:r.report.triangles,slopeSmoothing:r.report.slopeSmoothing,buildMs:r.report.buildMs});assert.equal(r.report.built,true);assert.ok(r.report.triangles>1000&&r.report.triangles<=120000);assert.ok(r.report.slopeSmoothing.after.meanAbsoluteDifference<r.report.slopeSmoothing.before.meanAbsoluteDifference);assert.deepEqual(f.source.geometry.attributes.position.array,before);r.dispose();f.dispose();});
