import test from 'node:test';import assert from 'node:assert/strict';import * as T from 'three';import{writeFileSync}from'node:fs';
import{actualUserMarkedStructureFixture}from'./targetUserMarkedStructure.fixture.mjs';
import{createTargetCityDetailCandidate}from'../../src/world/citadel/targetCityDetailCandidate.js';
import{createTargetNewCityStairs}from'../../src/world/citadel/targetNewCityStairs.js';
import{createTargetStairSurfaceSampler}from'../../src/world/citadel/targetNewCityStairRoute.js';
const y=-55*Math.PI/180,cs=Math.cos(y),sn=Math.sin(y),toLocal=([x,z])=>[(x-74)*cs-(z-33)*sn,(x-74)*sn+(z-33)*cs];

test('secondary streets stay off without explicit post-construction enable and require real primary/public inputs',()=>{
 const a=createTargetNewCityStairs();assert.equal(a.report.secondaryStreetClusters.enabled,false);assert.equal(a.completeSecondaryStreetClusters().enabled,false);assert.equal(a.group.getObjectByName('new-city-stair-house-secondary-clusters'),undefined);assert.throws(()=>a.completeSecondaryStreetClusters({enabled:true}),/primary street infill first/);assert.throws(()=>a.completeSecondaryStreetClusters({enabled:'yes'}),/boolean/);a.dispose();assert.throws(()=>a.completeSecondaryStreetClusters(),/disposed/);
 const b=createTargetNewCityStairs({surfaceHeightAt:()=>0,streetInfill:{publicFootprints:[]}});assert.throws(()=>b.completeSecondaryStreetClusters({enabled:true}),/actual local XZ polygons/);assert.equal(b.report.secondaryStreetClusters.enabled,false);b.dispose();
});

test('default off retains all stairs7 geometry and primary infill; sample exceptions publish nothing',async()=>{
 const {readFile}=await import('node:fs/promises');let source=await readFile(new URL('../../artifacts/pipeline/citadel-secondary-street-clusters-20261006/targetNewCityStairs.before.js',import.meta.url),'utf8');source=source.replace("from 'three'",`from '${import.meta.resolve('three')}'`).replace("from './targetNewCityMain.js?revision=entry-r39-colour-1'",`from '${new URL('../../src/world/citadel/targetNewCityMain.js',import.meta.url).href}'`).replace("from './targetArchitecturePalette.js'",`from '${new URL('../../src/world/citadel/targetArchitecturePalette.js',import.meta.url).href}'`);
 const before=(await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'))).createTargetNewCityStairs,opts={surfaceHeightAt:()=>0,facadeFoundationRefinement:true,streetInfill:{publicFootprints:[]}},a=before(opts),b=createTargetNewCityStairs(opts),geometry=h=>{const rows=[];h.group.traverse(o=>{if(o.isMesh){o.updateMatrix();rows.push([o.name,[...o.geometry.attributes.position.array],[...o.matrix.elements],o.material.color.getHexString()]);}});return rows;};assert.deepEqual(geometry(a),geometry(b));assert.deepEqual(a.report.footprints,b.report.footprints);assert.deepEqual(a.report.streetInfill,b.report.streetInfill);a.dispose();b.dispose();
 let invalid=false;const c=createTargetNewCityStairs({surfaceHeightAt:()=>invalid?NaN:0,streetInfill:{publicFootprints:[]}}),snapshot=geometry(c),report=JSON.stringify(c.report.secondaryStreetClusters),far=[{polygon:[[100,100],[101,100],[101,101],[100,101]]}];invalid=true;assert.throws(()=>c.completeSecondaryStreetClusters({enabled:true,publicFootprints:far,protectedFootprints:far}),/nonfinite/);assert.deepEqual(geometry(c),snapshot);assert.equal(JSON.stringify(c.report.secondaryStreetClusters),report);c.dispose();
});

test('secondary support rejection never invents a foundation; successful meshes and materials dispose once',()=>{
 let sampled=true;const a=createTargetNewCityStairs({surfaceHeightAt:()=>sampled?0:null,streetInfill:{publicFootprints:[]}});sampled=false;const far=[{id:'actual-far-public',polygon:[[100,100],[101,100],[101,101],[100,101]]}];const r=a.completeSecondaryStreetClusters({enabled:true,publicFootprints:far,protectedFootprints:far});assert.equal(r.modules.length,0);assert.equal(r.extraMeshes,0);assert.equal(r.finitePass,false);assert.ok(r.rejected.some(x=>x.reason==='actual-terrain-missing'));a.dispose();
 const b=createTargetNewCityStairs({surfaceHeightAt:()=>0,streetInfill:{publicFootprints:[]}});b.completeSecondaryStreetClusters({enabled:true,publicFootprints:far,protectedFootprints:far});const gs=new Set(),ms=new Set();b.group.traverse(o=>{if(o.isMesh){gs.add(o.geometry);ms.add(o.material);}});let ng=0,nm=0;for(const g of gs)g.addEventListener('dispose',()=>ng++);for(const m of ms)m.addEventListener('dispose',()=>nm++);b.dispose();b.dispose();assert.equal(ng,gs.size);assert.equal(nm,ms.size);
});

test('secondary clusters attach to real masonry, retain primary wings and clear actual public/rail geometry',()=>{
 const f=actualUserMarkedStructureFixture();f.release.walkingConnection={kind:'stacked-connected'};f.release.structureOptions={galleryPierWidths:{oldShore:.9},newCityTransitLinks:true};const c=createTargetCityDetailCandidate({castle:f.castle,cliffTransitRelease:f.release,fitSunShadow:false,newCityStreetInfill:true,newCityFoundationRefinement:true});f.castle.add(c.root);f.scene.updateMatrixWorld(true);const old=c.root.getObjectByName('citadel-target-new-city-stairs'),source=c.report.newCityStairs.authored,sample=createTargetStairSurfaceSampler(f.castle,[f.terrain]);
 const publicSurfaces=[...c.report.newCityStairs.surveyed.selected.treads.map(t=>({id:'surveyed-tread',polygon:t.polygon})),...c.report.bridgeConnector.walkSurfaces,...Object.values(c.report.cliffTransit.galleries).flatMap(g=>g.walkSurfaces),...c.report.cliffTransit.connections.flatMap(l=>l.walkSurfaces.map(s=>({id:l.id,polygon:s.corners.map(p=>[p[0],p[2]])}))),...c.report.cliffTransit.newCityTransitLinks.links.flatMap(l=>l.walkSurfaces)];
 const a=createTargetNewCityStairs({seed:source.seed,palette:source.palette,houseOffsets:source.houseOffsets,facadeFoundationRefinement:true,surfaceHeightAt:(x,z)=>{const v=sample(74+cs*x+sn*z,33-sn*x+cs*z);return v?v.height-12:null;}});a.completeStreetInfill({publicFootprints:publicSurfaces.filter(p=>p.polygon).map(p=>({id:p.id,polygon:p.polygon.map(toLocal)}))});assert.throws(()=>a.completeStreetInfill(),/already constructed/);const primary=JSON.parse(JSON.stringify(a.report.streetInfill));a.completeSecondaryStreetClusters({enabled:true,publicFootprints:publicSurfaces.filter(p=>p.polygon).map(p=>({id:p.id,polygon:p.polygon.map(toLocal)})),protectedFootprints:c.report.newCity.geometry.footprints});assert.deepEqual(a.report.streetInfill,primary);assert.throws(()=>a.completeSecondaryStreetClusters({enabled:true}),/already constructed/);
 for(const child of [...a.group.children])if(!/^new-city-stair-house-/.test(child.name))a.group.remove(child);a.group.position.copy(old.position);a.group.rotation.copy(old.rotation);old.removeFromParent();c.root.add(a.group);f.scene.updateMatrixWorld(true);const r=a.report.secondaryStreetClusters,failures=[],infill=a.group.getObjectByName('new-city-stair-house-secondary-clusters'),provider=c.getPlayerSupport(),paths=[c.report.newCityStairs.surveyed.selected.walkPath,...c.report.cliffTransit.connections.map(l=>l.walkPath),...c.report.cliffTransit.newCityTransitLinks.links.map(l=>l.walkPath),[c.report.bridgeConnector.dock,c.report.bridgeConnector.endpoint],[[72,3,78],[72,3,68],[62,3,68]]];let rays=0;
 try{
  assert.deepEqual(a.report.footprints,source.footprints);assert.deepEqual(a.report.houseOffsets,source.houseOffsets);assert.equal(a.report.houses.length,6);assert.ok(r.extraMeshes<=12);assert.ok(r.modules.length>=4,JSON.stringify(r));assert.equal(r.finitePass,true,JSON.stringify(r.rejected));assert.equal(r.supportSamples.length,r.modules.reduce((n,p)=>n+p.terrainSampleCount,0));assert.ok(r.supportSamples.every(p=>p.gap===0&&p.buriedBody===0));
  const geometryFailures=[],publicMeshes=[];c.root.traverse(o=>{if(o.isMesh&&!o.userData.targetSecondaryStreetCluster&&!o.name.startsWith('new-city-street-infill-')&&!o.name.startsWith('new-city-stair-house-')&&!o.name.startsWith('target-bench-')&&!/canopy|grass|water|cloud|turf/.test(o.name))publicMeshes.push(o);});
  // Public mesh triangles must stay outside every room envelope. Attachment
  // overlaps are only permitted with the explicitly named parent houses.
  for(const part of r.modules){const transform=new T.Matrix4().compose(new T.Vector3(...part.position),new T.Quaternion().setFromAxisAngle(new T.Vector3(0,1,0),part.yaw),new T.Vector3(1,1,1)),world=new T.Matrix4().multiplyMatrices(a.group.matrixWorld,transform),inverse=world.clone().invert(),envelope=new T.Box3(new T.Vector3(-part.width/2-.10,part.bottomY-part.position[1],-part.depth/2-.18),new T.Vector3(part.width/2+.10,part.height+.61,part.depth/2+.18));
   for(const mesh of publicMeshes){const mat=new T.Matrix4().multiplyMatrices(inverse,mesh.matrixWorld);mesh.geometry.computeBoundingBox();if(!envelope.intersectsBox(mesh.geometry.boundingBox.clone().applyMatrix4(mat)))continue;const p=mesh.geometry.attributes.position,ix=mesh.geometry.index;for(let i=0;i<(ix?.count??p.count);i+=3){const tri=new T.Triangle(...[0,1,2].map(j=>new T.Vector3().fromBufferAttribute(p,ix?ix.getX(i+j):i+j).applyMatrix4(mat)));if(envelope.intersectsTriangle(tri)){geometryFailures.push({id:part.id,mesh:mesh.name,face:i/3});break;}}}
  }
  const up=new T.Vector3(0,1,0).transformDirection(f.castle.matrixWorld);for(const path of paths)for(let j=1;j<path.length;j++){const A=new T.Vector3(...path[j-1]),B=new T.Vector3(...path[j]),d=B.clone().sub(A),len=Math.hypot(d.x,d.z),side=new T.Vector3(-d.z,0,d.x).normalize();if(len<1e-7)continue;const n=Math.max(1,Math.ceil(A.distanceTo(B)/.5));for(let i=1;i<=n;i++)for(const lateral of[-.4,0,.4])for(const h of[.05,.55,1.2,1.8]){const a=A.clone().lerp(B,(i-1)/n).addScaledVector(side,lateral).applyMatrix4(f.castle.matrixWorld).addScaledVector(up,h),b=A.clone().lerp(B,i/n).addScaledVector(side,lateral).applyMatrix4(f.castle.matrixWorld).addScaledVector(up,h),delta=b.clone().sub(a);rays++;const hit=new T.Raycaster(a,delta.normalize(),0,a.distanceTo(b)).intersectObject(infill,true)[0];if(hit)failures.push({path:paths.indexOf(path),name:hit.object.name,point:hit.point.toArray()});}}
  // Probe actual top faces over all foundations, and the real recessed door
  // void before reaching its retained back wall; not report-only support.
  infill.traverse(o=>{if(o.isMesh)o.material.side=T.DoubleSide;});let foundationRays=0,doorRays=0;
  for(const part of r.modules){const transform=new T.Matrix4().compose(new T.Vector3(...part.position),new T.Quaternion().setFromAxisAngle(new T.Vector3(0,1,0),part.yaw),new T.Vector3(1,1,1)),world=a.group.matrixWorld.clone().multiply(transform),upLocal=new T.Vector3(0,1,0).transformDirection(world),inward=new T.Vector3(0,0,-1).transformDirection(world);
   for(const u of[-.45,0,.45])for(const v of[-.45,0,.45]){const origin=new T.Vector3(u*part.width,.02,v*part.depth).applyMatrix4(world),hits=new T.Raycaster(origin,upLocal.clone().negate(),0,.05).intersectObject(infill,true);assert.ok(hits.length,part.id+' actual foundation top missing');foundationRays++;}
   if(part.door){const origin=new T.Vector3(0,.7,part.depth/2+.1).applyMatrix4(world);assert.equal(new T.Raycaster(origin,inward,0,.4).intersectObject(infill,true).length,0,part.id+' door recess is filled');assert.ok(new T.Raycaster(origin,inward,0,.8).intersectObject(infill,true).length,part.id+' retained back wall missing');doorRays+=2;}
  }
  const records=[];infill.traverse(o=>{if(!o.isMesh)return;const p=o.geometry.attributes.position,triangles=[];for(let i=0;i<p.count;i+=3){const tri=new T.Triangle(...[0,1,2].map(j=>new T.Vector3().fromBufferAttribute(p,i+j).applyMatrix4(o.matrixWorld)));triangles.push({tri,box:new T.Box3().setFromPoints([tri.a,tri.b,tri.c])});}records.push({name:o.name,box:new T.Box3().setFromObject(o),triangles});});
  const trainBox=new T.Box3(new T.Vector3(-2.32,-.6,-3.49),new T.Vector3(2.32,5.71,3.49)),trainHits=[];let trainPoses=0;
  for(const lane of['red','blue']){const curve=f.release.curves[lane],count=Math.ceil(curve.getLength()/.75);for(let i=0;i<=count;i++){const p=curve.getPointAt(i/count),t=curve.getTangentAt(i/count).normalize(),right=p.clone().normalize().cross(t).normalize(),up=t.clone().cross(right).normalize(),world=new T.Matrix4().makeBasis(right,up,t).setPosition(p),inverse=world.clone().invert(),b=trainBox.clone().applyMatrix4(world);trainPoses++;for(const mesh of records){if(!b.intersectsBox(mesh.box))continue;for(const row of mesh.triangles){if(!b.intersectsBox(row.box))continue;const tri=row.tri.clone();tri.a.applyMatrix4(inverse);tri.b.applyMatrix4(inverse);tri.c.applyMatrix4(inverse);if(trainBox.intersectsTriangle(tri)){trainHits.push({lane,i,mesh:mesh.name});break;}}}}}
  const stats=root=>{let meshes=0,triangles=0;root.traverse(o=>{if(o.isMesh){meshes++;triangles+=(o.geometry.index?.count??o.geometry.attributes.position.count)/3;}});return{meshes,triangles};};const evidence={report:r,beforeActualGeometry:stats(old),afterActualGeometry:stats(a.group),foundationRays,doorRays,trainPoses,trainHits,existingFootprintsUnchanged:true,publicTriangleFailures:geometryFailures,bodyRays:rays,bodyFailures:failures,geometry:a.report.performance,gpuVerified:false};if(process.env.CITADEL_SECONDARY_STREET_REPORT){writeFileSync(process.env.CITADEL_SECONDARY_STREET_REPORT,JSON.stringify(evidence,null,2));writeFileSync(process.env.CITADEL_SECONDARY_STREET_REPORT.replace(/\.json$/,'-geometry.json'),JSON.stringify(infill.toJSON()));}
  assert.deepEqual(trainHits,[]);assert.deepEqual(geometryFailures,[]);assert.deepEqual(failures,[]);assert.ok(rays>2000);assert.ok(r.modules.every(m=>m.sharedMasonryContacts.length>=3&&m.foundationHeight<=2.05));
  // Only the existing terrain/stair surfaces can provide feet, never these roofs.
  infill.traverse(o=>{if(o.isMesh){assert.equal(o.userData.targetWalkable,false);for(const v of o.geometry.attributes.position.array)assert.ok(Number.isFinite(v));}});
 }finally{a.dispose();c.dispose();f.dispose();}
});

