import test from 'node:test';import assert from 'node:assert/strict';import * as T from 'three';
globalThis.window={addEventListener(){},location:{search:''}};globalThis.document={getElementById:()=>null};
const {integrateTargetCityLandmarks}=await import('../../src/world/citadel/targetCityLandmarkIntegration.js');
const {createCitadelNightInfiltration}=await import('../../src/world/citadelInfiltration.js');
function fixture(){const sceneRoot=new T.Group(),castle=new T.Group();sceneRoot.add(castle);const terrain=new T.Mesh(new T.PlaneGeometry(240,240),new T.MeshBasicMaterial());terrain.name='citadel-oskar-grid-mountain-surface';terrain.rotation.x=-Math.PI/2;terrain.position.y=3;castle.add(terrain);const statue=new T.Group();statue.name='citadel-plaza-hero-statue';castle.add(statue);const horse=new T.Group(),squad=new T.Group();horse.scale.setScalar(.72);horse.add(squad);horse.userData.rangeLocal={lx:1,lz:2};horse.userData.placement={test:'original'};sceneRoot.add(horse);const controller=createCitadelNightInfiltration({scene:sceneRoot,horse,staticSquad:squad,siteUp:new T.Vector3(0,1,0),siteRight:new T.Vector3(1,0,0),horseGround:new T.Vector3(),stairRoute:[new T.Vector3(0,0,10)],waterfallRoute:[],topAssaultMode:true,captureTarget:new T.Vector3(0,0,10)});const root=new T.Group();castle.add(root);const detailCandidate={root,report:{sourceSurfaces:{terrain:[{name:terrain.name}]},newCityStairs:{surveyed:{start:[62,3,60],end:[62,3,64],selected:{treads:[{x:62,z:61,top:3},{x:62,z:63,top:3}]}}},newCity:{position:[62,3,59],yawDegrees:0,geometry:{entry:{position:[0,0,0]}}}}};return{sceneRoot,castle,range:{trojanHorse:horse,nightInfiltration:controller},detailCandidate,worldToRange:p=>({x:p.x,z:p.z}),terrain};}
test('validated finite corridor commits original actors, clears only matched forest and restores',()=>{const o=fixture(),canopy=new T.Group();canopy.name='citadel-mountain-canopy-candidate';o.castle.add(canopy);const m=new T.InstancedMesh(new T.BoxGeometry(1,4,1),new T.MeshBasicMaterial(),2);canopy.add(m);m.setMatrixAt(0,new T.Matrix4().makeTranslation(72,5,75));m.setMatrixAt(1,new T.Matrix4().makeTranslation(-50,5,-50));const old=Array.from(m.instanceMatrix.array),id=o.range.trojanHorse.uuid;const result=integrateTargetCityLandmarks(o);assert.equal(result.ok,true,JSON.stringify(result.report.failures));assert.equal(o.range.trojanHorse.uuid,id);assert.ok(Math.abs(result.report.route[0].position[1]-o.range.trojanHorse.position.y)<1e-5);assert.deepEqual(o.range.nightInfiltration.getPlacementState().captureTarget,[62,3,59]);assert.equal(result.report.forestRemoved.length,1);assert.equal(o.range.trojanHorse.userData.rangeLocal.lx,72);assert.equal(result.rollback().ok,true);assert.deepEqual(Array.from(m.instanceMatrix.array),old);assert.deepEqual(o.range.trojanHorse.userData.rangeLocal,{lx:1,lz:2});assert.deepEqual(o.range.trojanHorse.userData.placement,{test:'original'});});
test('real blocking wall rejects before any actor or tree mutation',()=>{const o=fixture(),wall=new T.Mesh(new T.BoxGeometry(8,4,1),new T.MeshBasicMaterial());wall.position.set(72,5,72);wall.name='test-route-wall';o.detailCandidate.root.add(wall);const result=integrateTargetCityLandmarks(o);assert.equal(result.ok,false);assert.ok(result.report.failures.some(f=>f.kind==='head-or-body-obstacle'));assert.deepEqual(o.range.trojanHorse.position.toArray(),[0,0,0]);});
test('missing terrain supports fail without actor migration',()=>{const o=fixture();o.terrain.position.y=0;const result=integrateTargetCityLandmarks(o);assert.equal(result.ok,false);assert.deepEqual(o.range.trojanHorse.position.toArray(),[0,0,0]);});

test('walkPath supersedes stale tread centres without relaxing support limits',()=>{const o=fixture(),sr=o.detailCandidate.report.newCityStairs.surveyed;sr.selected.walkPath=[[62,3,60],[62,3,62],[62,3,64]];sr.selected.treads=[{x:200,z:200,top:99}];const result=integrateTargetCityLandmarks(o);assert.equal(result.ok,true,JSON.stringify(result.report.failures));assert.equal(result.report.walkPathSource,'selected.walkPath');assert.ok(result.report.route.every(r=>r.position[0]<100));assert.equal(result.rollback().ok,true);});
test('enclosing planet AABB is only broadphase, actual remote shell does not block',()=>{const o=fixture(),planet=new T.Mesh(new T.SphereGeometry(400,24,12),new T.MeshBasicMaterial());planet.name='planet-surface';o.sceneRoot.add(planet);const result=integrateTargetCityLandmarks(o);assert.equal(result.ok,true,JSON.stringify(result.report.failures));assert.ok(result.report.envelopeChecks.some(c=>c.name==='planet-surface'&&c.hitFace===null&&c.trianglesChecked>0));result.rollback();});
test('anonymous actual triangle intersecting landmark body remains rejected and diagnosed',()=>{const o=fixture(),wall=new T.Mesh(new T.BoxGeometry(1,3,1),new T.MeshBasicMaterial());wall.position.set(73,5,79);o.sceneRoot.add(wall);const result=integrateTargetCityLandmarks(o);assert.equal(result.ok,false);const f=result.report.failures.find(f=>f.kind==='landmark-envelope-triangle-obstacle');assert.ok(f&&f.ancestors.length&&f.material[0].type==='MeshBasicMaterial');});
test('forward statue site clears the actual old stair-side z73.5 strip without lowering envelope',()=>{const o=fixture(),parapet=new T.InstancedMesh(new T.BoxGeometry(8,1.2,.3),new T.MeshBasicMaterial(),1);parapet.name='surveyed-route-side-parapets';parapet.setMatrixAt(0,new T.Matrix4().makeTranslation(56,3.6,73.5));o.detailCandidate.root.add(parapet);const result=integrateTargetCityLandmarks(o);assert.equal(result.ok,true,JSON.stringify(result.report.failures));assert.equal(result.report.survey.candidates.statue.selected.position[2],78);assert.equal(result.report.survey.candidates.horse.selected.position[2],78);assert.equal(result.rollback().ok,true);});

test('explicit main four-step walkPath is consumed instead of a direct entry chord',()=>{const o=fixture();o.detailCandidate.report.newCity.geometry.stairs={walkPath:[[0,0,1],[.5,0,.5],[0,0,0]]};const result=integrateTargetCityLandmarks(o);assert.equal(result.ok,true,JSON.stringify(result.report.failures));assert.equal(result.report.mainWalkPathSource,'geometry.stairs.walkPath');assert.ok(result.report.route.some(r=>Math.abs(r.position[0]-62.5)<1e-8&&Math.abs(r.position[2]-59.5)<1e-8));assert.deepEqual(result.report.captureTarget,[62,3,59]);assert.equal(result.rollback().ok,true);});
