import test from'node:test';import assert from'node:assert/strict';import * as T from'three';import{createTargetOldShoreApronField}from'../../src/world/citadel/targetOldShoreApronField.js';
const fixture=()=>({castleMatrix:new T.Matrix4().makeTranslation(0,160,0),worldCurve:new T.LineCurve3(new T.Vector3(-85,170,0),new T.Vector3(-50,170,0)),sampleTerrain:(x,z)=>z<-12?20:-10,sampleSea:()=>-12,landwardTarget:[-60,-30]});
test('narrow landward gap adds a flat cliff apron but leaves seaward ground and high terrain intact',()=>{const f=createTargetOldShoreApronField(fixture());assert.ok(f.report.eligibleStations>0);assert.ok(f.height(-65,-9,-10,-12)>-10);assert.equal(f.height(-65,4,-10,-12),-10);assert.equal(f.height(-65,-15,20,-12),20);assert.equal(f.report.accepted,false);});
test('full platform footprints, bridge exclusion, distant coast and missing surface do not fill',()=>{const f=createTargetOldShoreApronField({...fixture(),platforms:[{center:[-65,-9],radii:[3,3]}]});assert.equal(f.height(-65,-9,-10,-12),-10);assert.equal(f.height(-40,-9,-10,-12),-10);for(const sampleTerrain of[()=>null,(x,z)=>z<-50?20:-10]){const a=createTargetOldShoreApronField({...fixture(),sampleTerrain});assert.equal(a.report.segments,0);assert.equal(a.height(-65,-9,-10,-12),-10);}});
test('field deterministic, does not mutate source curve, finite gap constraint enforced',()=>{const o=fixture(),p=o.worldCurve.getPoint(.5).toArray(),a=createTargetOldShoreApronField(o),b=createTargetOldShoreApronField(o);assert.deepEqual(a.stations,b.stations);assert.deepEqual(o.worldCurve.getPoint(.5).toArray(),p);assert.throws(()=>createTargetOldShoreApronField({...o,maxGap:33}));});

test('loaded freight height controls projected exclusion while original curve remains unchanged',()=>{const low=createTargetOldShoreApronField({...fixture(),vehicleTop:3.242}),high=createTargetOldShoreApronField({...fixture(),vehicleTop:5.71});assert.equal(high.report.walkwayHeight,6.9);assert.equal(high.report.vehicleTop,5.71);for(let i=0;i<low.stations.length;i++)if(low.stations[i].vehicleProjection!==undefined)assert.ok(high.stations[i].vehicleProjection>=low.stations[i].vehicleProjection-1e-9);assert.throws(()=>createTargetOldShoreApronField({...fixture(),vehicleTop:NaN}));});

test('stepped rock link reaches lower existing bench without making entire gap one high plane',()=>{const o={...fixture(),maxGap:32,profile:'stepped-rock-link',sampleSea:()=>-8,sampleTerrain:(x,z)=>z<-24?2:-10},f=createTargetOldShoreApronField(o);assert.ok(f.report.segments>0);const row=f.stations.find(s=>s.enabled&&s.center[0]>-70),x=row.edge[0]+row.inward[0]*1,z=row.edge[1]+row.inward[1]*1,backX=row.edge[0]+row.inward[0]*10,backZ=row.edge[1]+row.inward[1]*10;assert.ok(f.height(x,z,-10,-12)>f.height(backX,backZ,-10,-12)+3);assert.equal(f.height(-65,4,-10,-12),-10);});

test('stepped terminal joins measured dry contact without fading through submerged terrain',()=>{const o={...fixture(),maxGap:32,profile:'stepped-rock-link',sampleSea:()=>-8,sampleTerrain:(x,z)=>z<-24?2:-10},f=createTargetOldShoreApronField(o);for(const row of f.stations.filter(s=>s.enabled).slice(2,-2)){for(let d=row.width-2;d<row.width-.2;d+=.1){const x=row.edge[0]+row.inward[0]*d,z=row.edge[1]+row.inward[1]*d,h=o.sampleTerrain(x,z),v=f.height(x,z,h,-8);assert.ok(v>=2-1e-8,'terminal must not dip below measured 2m rock contact');assert.ok(v>=h);}}});
