import test from 'node:test';import assert from 'node:assert/strict';import * as T from 'three';
import {surveyTargetCityLandmarks,applyTargetCityLandmarksCandidate} from '../../src/world/citadel/targetCityLandmarksCandidate.js';
globalThis.window={addEventListener(){},location:{search:''}};globalThis.document={getElementById:()=>null};
const {createCitadelNightInfiltration}=await import('../../src/world/citadelInfiltration.js');
function fixture(){const scene=new T.Group(),castle=new T.Group();scene.add(castle);castle.position.set(12,9,-3);castle.rotation.y=.3;const terrain=new T.Mesh(new T.PlaneGeometry(240,240),new T.MeshBasicMaterial());terrain.rotation.x=-Math.PI/2;terrain.position.y=3;castle.add(terrain);const statue=new T.Group();statue.name='citadel-plaza-hero-statue';statue.scale.setScalar(1.2);statue.add(new T.Mesh(new T.BoxGeometry(1,3,1),new T.MeshBasicMaterial()));castle.add(statue);const horse=new T.Group(),squad=new T.Group();horse.scale.setScalar(.72);horse.add(squad);scene.add(horse);horse.userData.baseQuat=horse.quaternion.clone();const controller=createCitadelNightInfiltration({scene,horse,staticSquad:squad,siteUp:new T.Vector3(0,1,0),siteRight:new T.Vector3(1,0,0),horseGround:new T.Vector3(),stairRoute:[new T.Vector3(0,0,10)],waterfallRoute:[],topAssaultMode:true,captureTarget:new T.Vector3(0,0,10)});return{castle,sceneRoot:scene,range:{trojanHorse:horse,nightInfiltration:controller},terrainMeshes:[terrain],statue,horse,controller,clearanceVerified:true,routes:{stairRoute:[new T.Vector3(5,3,10)],waterfallRoute:[]}};}
test('readonly survey samples actual triangles and original identities',()=>{const o=fixture(),r=surveyTargetCityLandmarks(o);assert.equal(r.ready,true);assert.equal(r.horse.uuid,o.horse.uuid);assert.deepEqual(o.statue.position.toArray(),[0,0,0]);for(const k of['horse','statue'])assert.ok(r.candidates[k].selected.feet.every(f=>Math.abs(f.surface.height-3)<1e-5));assert.doesNotThrow(()=>JSON.stringify(r));});
test('migration retains original actors and rollback releases only owned paving',()=>{const o=fixture(),id=o.horse.uuid,before=o.controller.getPlacementState();let originalDisposed=0,ownedDisposed=0;o.statue.children[0].geometry.addEventListener('dispose',()=>originalDisposed++);const r=applyTargetCityLandmarksCandidate(o);assert.equal(r.ok,true);assert.equal(o.horse.uuid,id);assert.equal(r.group.children.length,2);for(const m of r.group.children)m.geometry.addEventListener('dispose',()=>ownedDisposed++);assert.ok(r.visibilityExemptions.includes(o.statue.children[0]));assert.ok(o.statue.position.distanceTo(new T.Vector3(56,3.06,78))<1e-5);assert.ok(o.castle.worldToLocal(o.horse.getWorldPosition(new T.Vector3())).distanceTo(new T.Vector3(72,3.06,78))<1e-5);assert.equal(applyTargetCityLandmarksCandidate(o).reason,'already-applied');assert.equal(r.rollback().ok,true);assert.equal(ownedDisposed,2);assert.equal(originalDisposed,0);assert.deepEqual(o.controller.getPlacementState().anchors,before.anchors);assert.deepEqual(o.statue.position.toArray(),[0,0,0]);});
test('invalid clearance, absent support and active controller leave original state',()=>{const o=fixture();assert.equal(applyTargetCityLandmarksCandidate({...o,clearanceVerified:false}).ok,false);assert.equal(applyTargetCityLandmarksCandidate({...o,terrainMeshes:[]}).ok,false);o.controller.update(0,0,.9);assert.equal(applyTargetCityLandmarksCandidate(o).ok,false);assert.deepEqual(o.statue.position.toArray(),[0,0,0]);assert.equal(o.castle.getObjectByName('target-original-landmark-paving'),undefined);});
test('active rollback refuses the whole transaction without removing support',()=>{const o=fixture(),r=applyTargetCityLandmarksCandidate(o);assert.equal(r.ok,true);const position=o.statue.position.clone();o.controller.update(0,0,.9);assert.equal(r.rollback().ok,false);assert.ok(o.statue.position.equals(position));assert.equal(r.group.parent,o.castle);});
