import test from 'node:test';import assert from 'node:assert/strict';import * as T from 'three';
import {createTargetCityPlayerNavigation} from '../../src/world/citadel/targetCityPlayerNavigation.js';
import {createTargetCityPlayerSupport} from '../../src/world/citadel/targetCityPlayerSupport.js';
import {createTargetNewCityMain} from '../../src/world/citadel/targetNewCityMain.js';
import {createTargetOldCity} from '../../src/world/citadel/targetOldCity.js';
globalThis.window??={addEventListener(){},location:{search:''}};globalThis.document??={getElementById:()=>null};
const {resolveCollisions,resolveAssetColliders}=await import('../../src/world/collision.js');
function fixture(){const castle=new T.Group();castle.position.y=160;const root=new T.Group(),terrain=new T.Mesh(new T.BoxGeometry(100,1,100),new T.MeshBasicMaterial());terrain.position.y=-.5;castle.add(root,terrain);const provider=createTargetCityPlayerSupport({castle,candidateRoot:root,finalTerrain:[terrain]}),proxy={position:new T.Vector3(0,160,0),radius:6},bookshop={position:new T.Vector3(0,-160,0),radius:6},runtime={root,report:{installed:true},getPlayerSupport:()=>provider};const nav=createTargetCityPlayerNavigation({runtime,castle,finalTerrain:[terrain],legacyCitadelPosition:proxy.position,legacyColliders:[proxy,bookshop]});const assets=[];return{castle,root,terrain,provider,runtime,nav,proxy,bookshop,p:(x,y,z)=>new T.Vector3(x,160+y,z),add(asset){root.add(asset.group);assets.push(asset);provider.refresh();return asset;},close(){nav.dispose();provider.dispose();assets.forEach(a=>a.dispose());terrain.geometry.dispose();terrain.material.dispose();}};}
const near=(a,b)=>assert.ok(Math.abs(a-b)<1e-5,`${a} vs ${b}`);

test('airborne gap uses actual terrain instead of old analytic terraces and never attracts feet to roofs',()=>{const f=fixture();f.add(createTargetNewCityMain());const feet=f.p(0,8,0);assert.equal(f.provider.ground(feet),null);near(f.nav.ground(feet),160);near(f.nav.ground(f.p(0,1.3,0)),161.2);assert.equal(f.nav.ground(f.p(110,2,0)),null);assert.equal(f.nav.ground(new T.Vector3(0,-168,0)),null);f.close();});

test('real collision keeps upward jump and lands after descending; no hidden platform side or obsolete 6m proxy push',()=>{const f=fixture();const hidden=new T.Mesh(new T.BoxGeometry(4,2,4),new T.MeshBasicMaterial());hidden.visible=false;f.castle.add(hidden);const platform={mesh:hidden,center:f.p(0,2,0),normal:new T.Vector3(0,1,0),right:new T.Vector3(1,0,0),forward:new T.Vector3(0,0,1),half:new T.Vector3(4,1,4),topHeight:162};const platforms=[platform],colliders=[f.proxy,f.bookshop];assert.deepEqual(f.nav.platformsForPhysics(platforms),[]);assert.deepEqual(f.nav.collidersForPhysics(colliders),[f.bookshop]);assert.equal(platforms.length,1);assert.equal(colliders.length,2);
 const player={onGround:true},feet=f.p(0,0,0),velocity=new T.Vector3(0,5,0);resolveCollisions(feet,velocity,.01,f.nav.platformsForPhysics(platforms),player,()=>assert.fail('respawn'),null,f.nav.ground);resolveAssetColliders(feet,f.nav.collidersForPhysics(colliders));near(feet.y,160.05);near(feet.x,0);assert.equal(player.onGround,false);near(velocity.y,5);
 feet.y=160.02;velocity.y=-5;resolveCollisions(feet,velocity,.01,[],player,()=>assert.fail('respawn'),null,f.nav.ground);near(feet.y,160);assert.equal(player.onGround,true);hidden.geometry.dispose();hidden.material.dispose();f.close();});

test('bookshop hemisphere and non-citadel hidden sources preserve original ground/collider physics exactly',()=>{const f=fixture(),bookMesh=new T.Mesh(new T.BoxGeometry(),new T.MeshBasicMaterial());bookMesh.visible=false;const untouched={mesh:bookMesh};assert.equal(f.nav.platformsForPhysics([untouched])[0],untouched);assert.equal(f.nav.collidersForPhysics([f.bookshop])[0],f.bookshop);const baseline=new T.Vector3(0,-160.03,0),adapted=baseline.clone(),vb=new T.Vector3(0,1,0),va=vb.clone(),pb={},pa={};resolveCollisions(baseline,vb,.01,[],pb,()=>{},null,null);resolveCollisions(adapted,va,.01,[],pa,()=>{},null,f.nav.ground);assert.deepEqual(adapted,baseline);assert.deepEqual(va,vb);assert.deepEqual(pa,pb);resolveAssetColliders(baseline,[f.bookshop]);resolveAssetColliders(adapted,f.nav.collidersForPhysics([f.bookshop]));assert.deepEqual(adapted,baseline);bookMesh.geometry.dispose();bookMesh.material.dispose();f.close();});

test('real two-city arch openings remain open while solid jambs block; replacement meshes refresh through borrowed provider',()=>{const f=fixture(),old=f.add(createTargetOldCity());let previous=f.p(0,.3,18),next=f.p(0,.3,14),velocity=new T.Vector3(0,0,-1);assert.equal(f.nav.walls(previous,next,velocity),false);previous=f.p(3,.3,18);next=f.p(3,.3,14);assert.equal(f.nav.walls(previous,next,velocity),true);old.group.removeFromParent();const main=f.add(createTargetNewCityMain());previous=f.p(0,1.2,8);next=f.p(0,1.2,4);assert.equal(f.nav.walls(previous,next,velocity),false);previous=f.p(3.6,1.2,8);next=f.p(3.6,1.2,4);assert.equal(f.nav.walls(previous,next,velocity),true);main.group.visible=false;assert.equal(f.nav.walls(previous,f.p(3.6,1.2,4),velocity),false);f.close();});

test('rollback disables adapter and restores exact collider inputs without disposing candidate-owned provider',()=>{const f=fixture(),colliders=[f.proxy],platforms=[];f.runtime.report.installed=false;assert.equal(f.nav.ground(f.p(0,0,0)),null);assert.equal(f.nav.collidersForPhysics(colliders),colliders);assert.equal(f.nav.platformsForPhysics(platforms),platforms);assert.equal(f.nav.walls(f.p(0,0,0),f.p(1,0,0),new T.Vector3(1,0,0)),false);f.nav.dispose();assert.equal(f.provider.report().disposed,false);assert.equal(f.nav.report.continuousRouteVerified,false);f.close();});

test('frozen r17 terrain replaces analytic fallback during a high jump over the actual city frame',async()=>{
 const {applyTargetTerrainCandidate}=await import('../../src/world/citadel/targetTerrainCandidate.js');
 const castle=new T.Group();castle.matrixAutoUpdate=false;castle.matrix.fromArray([-.5771265090244172,.12463062405961449,.807088718870361,0,.6354855835814281,.689249750214348,.3479839865419536,0,-.5129162364767383,.7137240288626759,-.4769852670498,0,124.43456408079132,72.61606956254715,90.15650671642375,1]);
 const terrain=new T.Mesh(new T.BoxGeometry(),new T.MeshBasicMaterial({side:T.DoubleSide}));terrain.name='citadel-oskar-grid-mountain-surface';castle.add(terrain);const location=globalThis.location;globalThis.location={search:'?citadelTerrainFirst=1&citadelTargetRemesh=1&citadelTerraceAprons=1&citadelRecessedSaddle=1&citadelValleyBenches=1'};
 try{const obsolete=terrain.geometry;applyTargetTerrainCandidate(castle);obsolete.dispose();}finally{if(location===undefined)delete globalThis.location;else globalThis.location=location;}
 const root=new T.Group();castle.add(root);const provider=createTargetCityPlayerSupport({castle,candidateRoot:root,finalTerrain:[terrain]}),runtime={root,report:{installed:true},getPlayerSupport:()=>provider},nav=createTargetCityPlayerNavigation({runtime,castle,finalTerrain:[terrain]});
 try{castle.updateWorldMatrix(true,true);const ray=new T.Raycaster();ray.layers.enableAll();for(const local of[[-55,17,9],[74,12,33],[60,4,75]]){const nominal=new T.Vector3(...local).applyMatrix4(castle.matrixWorld),up=nominal.clone().normalize();ray.set(up.clone().multiplyScalar(260),up.clone().negate());const hits=ray.intersectObject(terrain,false);assert.ok(hits.length);const surface=hits[0].point,air=surface.clone().addScaledVector(up,8);assert.equal(provider.ground(air),null);near(nav.ground(air),surface.length());const velocity=up.clone().multiplyScalar(5),feet=surface.clone(),player={onGround:true};resolveCollisions(feet,velocity,.01,[],player,()=>assert.fail('respawn'),null,nav.ground);assert.ok(feet.length()>surface.length()+.049);assert.equal(player.onGround,false);}}finally{nav.dispose();provider.dispose();terrain.geometry.dispose();terrain.material.dispose();}
});
