import test from 'node:test';import assert from 'node:assert/strict';import{createTargetNewCityPlaza}from'../../src/world/citadel/targetNewCityPlaza.js';
test('paving follows sloping final surface and stays within authored plaza contour',()=>{const sample=(x,z)=>({height:3+(x-65)*.004}),p=createTargetNewCityPlaza({sampleSurface:sample});assert.equal(p.report.accepted,true);let n=0;p.group.traverse(o=>{if(o.isMesh){const a=o.geometry.attributes.position;for(let i=0;i<a.count;i++){const x=a.getX(i),z=a.getZ(i),y=a.getY(i);assert.ok(x>=44.99&&x<=88.01&&z>=63.99&&z<=91.01);assert.ok(Math.abs(y-sample(x,z).height-(o.name.includes('rings')?.040:.035))<1e-5);n++;}}});assert.ok(n>1000);p.dispose();p.dispose();});
test('missing or steep support is left open and reported, never guessed level',()=>{const p=createTargetNewCityPlaza({sampleSurface:(x,z)=>x>80?null:{height:x<50?0:3}});assert.equal(p.report.accepted,false);assert.ok(p.report.missing>0&&p.report.rejectedCells>0);p.dispose();});

import * as T from 'three';
test('foreground vista hides only supported crown/trunk pairs and restores exact instances',()=>{
 const castle=new T.Group(),canopy=new T.Group();canopy.name='citadel-mountain-canopy-candidate';castle.add(canopy);const trees=[[60,3,95],[40,3,95],[85,3,95],[62,12,95],[60,3,102]];
 const geometry=new T.SphereGeometry(2,8,6),material=new T.MeshBasicMaterial(),crowns=new T.InstancedMesh(geometry,material,trees.length),trunks=new T.InstancedMesh(geometry,material,trees.length);crowns.name='citadel-canopy-crowns';trunks.name='citadel-canopy-root-trunks';canopy.add(crowns,trunks);
 for(let i=0;i<trees.length;i++){const m=new T.Matrix4().makeTranslation(...trees[i]);crowns.setMatrixAt(i,m);trunks.setMatrixAt(i,m);}const before=[...crowns.instanceMatrix.array];
 const actor=new T.Group();actor.name='original-statue';castle.add(actor);const uuid=actor.uuid,p=createTargetNewCityPlaza({castle,sampleSurface:()=>3});assert.equal(p.report.forest.vistaTrees,1);assert.equal(p.report.forest.hiddenInstances,2);assert.ok(p.report.forest.nearby.some(r=>r.root[1]===12&&r.reason==='root-gap'));assert.ok(p.report.forest.nearby.some(r=>r.root[2]===102&&r.reason==='outside-vista'));const matrix=new T.Matrix4();for(const mesh of[crowns,trunks]){mesh.getMatrixAt(0,matrix);assert.equal(matrix.determinant(),0);for(let i=1;i<trees.length;i++){mesh.getMatrixAt(i,matrix);assert.deepEqual(new T.Vector3().setFromMatrixPosition(matrix).toArray(),trees[i]);}}
 assert.equal(actor.uuid,uuid);assert.equal(actor.parent,castle);p.dispose();assert.deepEqual([...crowns.instanceMatrix.array],before);assert.deepEqual([...trunks.instanceMatrix.array],before);geometry.dispose();material.dispose();
});
test('outer inlay is clipped to actual paving polygon and never spans missing sampled support',()=>{
 const p=createTargetNewCityPlaza({sampleSurface:(x,z)=>x<49?null:3});const ring=p.group.getObjectByName('target-plaza-statue-inlaid-rings'),a=ring.geometry.attributes.position;assert.ok(a.count>0);assert.equal(p.report.rings.clippedSegments,0,'authored outer ring already fits the plaza polygon');assert.ok(p.report.rings.rejectedSegments>0);let outer=0;
 for(let i=0;i<a.count;i++){const x=a.getX(i),z=a.getZ(i);assert.ok(x>=49-1e-5);for(let j=0;j<p.report.polygon.length;j++){const u=p.report.polygon[j],v=p.report.polygon[(j+1)%p.report.polygon.length];assert.ok((v[0]-u[0])*(z-u[1])-(v[1]-u[1])*(x-u[0])>=-1e-4);}if(Math.hypot(x-56,z-78)>7.59)outer++;}assert.ok(outer>50);assert.equal(p.group.children.filter(o=>o.isLight).length,0);p.dispose();
});
test('r47 west lip screening is narrow and preserves outer lateral woodland',()=>{
 const castle=new T.Group(),g=new T.Group();g.name='citadel-mountain-canopy-candidate';castle.add(g);const geometry=new T.SphereGeometry(2,8,6),material=new T.MeshBasicMaterial(),roots=[[45.1,2.75,77.7],[47.6,1.2,92.3],[40,2.8,80],[43,2.8,75],[45,7,83],[84,-2,87]];const meshes=['crowns','citadel-canopy-root-trunks'].map(name=>{const m=new T.InstancedMesh(geometry,material,roots.length);m.name=name;roots.forEach((p,i)=>m.setMatrixAt(i,new T.Matrix4().makeTranslation(...p)));g.add(m);return m;});const before=meshes.map(m=>[...m.instanceMatrix.array]);const p=createTargetNewCityPlaza({castle,sampleSurface:(x,z)=>z>91?1.3:2.85});assert.equal(p.report.forest.westVistaTrees,2);const m=new T.Matrix4();for(const mesh of meshes)for(let i=0;i<roots.length;i++){mesh.getMatrixAt(i,m);assert.equal(m.determinant()===0,i<2);}
 p.dispose();meshes.forEach((m,i)=>assert.deepEqual([...m.instanceMatrix.array],before[i]));geometry.dispose();material.dispose();
});
