import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import * as T from 'three';
import {createTargetNewCityRetreatField}from '../../src/world/citadel/targetNewCityRetreatField.js';
import {targetTerrainHeight,TARGET_CITY_PLATFORMS}from '../../src/world/citadel/targetTerrainCandidate.js';
import {createCastleOceanSampler}from '../../src/world/citadel/newCityRidgeCandidate.js';
import {buildTargetTerrainHeightfield}from '../../src/world/citadel/targetTerrainHeightfield.js';
const live=JSON.parse(fs.readFileSync(new URL('../../artifacts/pipeline/citadel-live-tram-clearance-20261006/global-tram-samples.json',import.meta.url))),sea=createCastleOceanSampler(new T.Matrix4().fromArray(live.castleMatrix),160),base=(x,z,s)=>targetTerrainHeight(x,z,s,{aprons:true,saddle:true,valleyBenches:true});
test('new city exterior retreats, all old terrain and full construction ellipses remain exactly fixed',()=>{const f=createTargetNewCityRetreatField({platforms:TARGET_CITY_PLATFORMS});let changed=0,protectedPoints=0;for(let x=-140;x<=140;x++)for(let z=-70;z<=107;z++){const s=sea(x,z);if(s===null)continue;const b=base(x,z,s),h=f.height(x,z,b,s);assert.ok(Number.isFinite(h)&&h<=b+1e-8&&h>=s-3-1e-8);if(x<80||z< -58)assert.equal(h,b);if(TARGET_CITY_PLATFORMS.some(p=>Math.hypot((x-p.center[0])/p.radii[0],(z-p.center[1])/p.radii[1])<=1)){assert.equal(h,b);protectedPoints++;}if(h<b-1e-6)changed++;}assert.ok(changed>2000);assert.ok(protectedPoints>6000);console.log({changed,protectedPoints,report:f.report});});
test('outer ridge and toe removed seaward continuously, plaza actors and terrace remain supported',()=>{const f=createTargetNewCityRetreatField({platforms:TARGET_CITY_PLATFORMS});for(const z of[-35,-10,15,40,60,80]){const edge=f.edgeAt(z);for(let x=edge+3.81;x<142;x+=.5){const s=sea(x,z);if(s===null)continue;assert.ok(f.height(x,z,base(x,z,s),s)<=s-2.999);}}
 for(const[cx,cz,r]of[[56,78,8],[72,78,5]])for(let i=0;i<40;i++){const x=cx+r*Math.cos(i*Math.PI/20),z=cz+r*Math.sin(i*Math.PI/20),s=sea(x,z);assert.equal(f.height(x,z,base(x,z,s),s),base(x,z,s));}
 const s=sea(111,20);assert.ok(base(111,20,s)>15);assert.equal(f.height(111,20,base(111,20,s),s),s-3);
});
test('retreated entire mesh stays closed positive-area deterministic with original submerged floor',()=>{const make=()=>{const f=createTargetNewCityRetreatField({platforms:TARGET_CITY_PLATFORMS});return buildTargetTerrainHeightfield({bounds:{minX:-143,maxX:143,minZ:-72,maxZ:107},step:1.7,floorAt:(x,z)=>{const s=sea(x,z);return s===null?null:s-12;},heightAt:(x,z)=>{const s=sea(x,z);return s===null?null:f.height(x,z,base(x,z,s),s);}});};const a=make(),b=make();assert.ok(a.audit.closed&&a.audit.minArea>0);assert.deepEqual(a.geometry.attributes.position.array,b.geometry.attributes.position.array);console.log(a.audit);a.geometry.dispose();b.geometry.dispose();});
