import test from 'node:test';import assert from 'node:assert/strict';import * as T from 'three';import fs from 'node:fs';
// Inert canvas/HUD hooks for CPU-created smoke textures, no browser/rendering.
globalThis.document={getElementById:()=>null,createElement:()=>({getContext:()=>({createRadialGradient:()=>({addColorStop(){}}),fillRect(){}})})};globalThis.window={addEventListener(){}};globalThis.location={search:''};
const {buildChristchurchTramSystem}=await import('../../src/world/tramSystem.js');
const ROOT=new URL('../../',import.meta.url),read=p=>JSON.parse(fs.readFileSync(new URL(p,ROOT))),base='artifacts/pipeline/citadel-east-shore-route-20261006/';
const crossing={enabled:true,candidateInput:read(base+'remesh-expanded-shift-audit.json').candidateInput,terrainArtifact:read(base+'remesh-final-surface-geometry.json')};
test('default-off preserves production user-marked curves and geometry/vehicle sharing',()=>{const scene=new T.Scene(),sys=buildChristchurchTramSystem(scene,160,{citadelCliffTransit:true,citadelEastGlobalCrossing:{enabled:false}});try{assert.equal(sys.crossingBundle,null);assert.equal(sys.bootstrapCurves,null);assert.equal(sys.citadelTransitRelease.version,'user-marked-transit-release-1');assert.equal(sys.group.visible,true);assert.equal(sys.freightServices[0].curve,sys.curves.red);assert.equal(sys.freightServices[1].curve,sys.curves.blue);assert.equal(sys.group.userData.citadelRailStartup.installed,true);assert.ok(sys.group.getObjectByName('moebius-city-viaduct'));}finally{sys.dispose();sys.dispose();}});
test('actual factory stages one new route for tracks, freight stops and interlocking while pending',()=>{const scene=new T.Scene(),sys=buildChristchurchTramSystem(scene,160,{citadelEastGlobalCrossing:crossing});try{assert.ok(sys.crossingBundle);assert.equal(sys.curve,sys.crossingBundle.startupPreview.curves.center);assert.equal(sys.freightServices[0].curve,sys.crossingBundle.startupPreview.curves.red);assert.equal(sys.freightServices[1].curve,sys.crossingBundle.startupPreview.curves.blue);assert.equal(sys.bootstrapRelease,sys.crossingBundle.terrainPreparation.bootstrapRelease);assert.equal(sys.bootstrapCurves,sys.crossingBundle.terrainPreparation.bootstrapStartup.curves);assert.notEqual(sys.bootstrapCurves.red,sys.curves.red);assert.equal(sys.group.visible,false);assert.equal(sys.group.userData.citadelRailStartup.installed,false);const positions=sys.freightServices.map(s=>s.progress);sys.update(1);assert.deepEqual(sys.freightServices.map(s=>s.progress),positions);assert.equal(sys.getNearestBoardable(new T.Vector3()),null);assert.equal(sys.isNearTram(new T.Vector3()),false);assert.ok(sys.group.getObjectByName('tram-crossing-provisional-supports'));for(const s of sys.freightServices){assert.equal(s.trackLen,s.curve.getLength());assert.ok(s.loadingStops.length>0);assert.ok(s.loadingStops.every(v=>Number.isFinite(v.progress)&&v.progress>=0&&v.progress<1));}assert.ok(Array.isArray(sys.group.userData.freightJunctions));assert.throws(()=>sys.prepareCrossingSupport({sampleGround:()=>null,sampleSea:()=>null,cityStructure:new T.Group()}),/CITY_STRUCTURE/);assert.equal(sys.group.visible,false);assert.ok(Object.values(sys.crossingBundle.exclusionPlan).every(r=>!r.active));}finally{sys.dispose();}});
test('malformed candidate rejects before scene attachment rather than silently using original',()=>{const scene=new T.Scene();assert.throws(()=>buildChristchurchTramSystem(scene,160,{citadelEastGlobalCrossing:{enabled:true}}));assert.equal(scene.children.length,0);assert.throws(()=>buildChristchurchTramSystem(scene,160,{citadelEastGlobalCrossing:crossing,citadelRailSplice:{}}),/CONFLICTING_SPLICE/);assert.equal(scene.children.length,0);});
test('actual final-surface stage verifies real source bay, commits support and rolls back atomically',async()=>{
 const {actualCliffTransitFixture}=await import('./targetCliffTransitStructure.fixture.mjs');
 const {createTargetCliffTransitStructure}=await import('../../src/world/citadel/targetCliffTransitStructure.js');
 const {buildMountainSurfaceIndex}=await import('../../src/world/citadel/mountainSurfaceIndex.js');
 const {buildHills,carveHillsForTrack}=await import('../../src/world/hills.js');
 const {officialOceanLevelAt}=await import('../../src/world/waterV8/officialOcean.js');
 const f=actualCliffTransitFixture(),sys=buildChristchurchTramSystem(f.scene,160,{citadelEastGlobalCrossing:crossing}),artifact=crossing.terrainArtifact,g=new T.BufferGeometryLoader().parse(artifact.geometry),mat=new T.MeshBasicMaterial({side:T.DoubleSide}),terrain=new T.Mesh(g,mat),waveG=f.ocean.geometry.clone(),wave=new T.Mesh(waveG,mat),hills=buildHills(f.scene,160);let city;
 terrain.name='final-artifact-cpu';terrain.position.fromArray(artifact.origin);f.castle.add(terrain);carveHillsForTrack(hills.mesh,sys.crossingBundle.startupPreview.curves?Object.values(sys.crossingBundle.startupPreview.curves):[],160);
 const p=waveG.attributes.position;for(let i=0;i<p.count;i++){const q=new T.Vector3().fromBufferAttribute(p,i);q.addScaledVector(q.clone().normalize(),.067);p.setXYZ(i,...q.toArray());}f.scene.add(wave);f.scene.updateMatrixWorld(true);
 const matrix=f.castle.matrixWorld.clone(),inverse=matrix.clone().invert(),terrainIndex=buildMountainSurfaceIndex([terrain]),ground=buildMountainSurfaceIndex([terrain,f.scene.getObjectByName('planet-surface'),hills.mesh,hills.skirt]),sea=buildMountainSurfaceIndex([f.ocean]),upper=buildMountainSurfaceIndex([wave]),down=new T.Vector3(0,-1,0).transformDirection(matrix);
 const local=index=>(x,z)=>{const h=index.sample(new T.Ray(new T.Vector3(x,250,z).applyMatrix4(matrix),down),0,900);return h?h.point.clone().applyMatrix4(inverse).y:null;},radial=(index,q)=>{const d=q.clone().normalize();return index.sample(new T.Ray(d.clone().multiplyScalar(500),d.clone().negate()),0,500);};
 const callbacks={sampleGround:q=>{const h=radial(ground,q);return h?{point:h.point,objectName:h.object.name}:null;},sampleSea:q=>({radius:radial(sea,q)?.point.length(),upperRadius:radial(upper,q)?.point.length(),officialUpperRadius:160+officialOceanLevelAt(q)+.067})};
 try{
  const frozen=read('artifacts/pipeline/citadel-global-approach-support-20261006/crossing-50-city-structure.json');
  city=createTargetCliffTransitStructure({...sys.crossingBundle.structureOptions,release:sys.citadelTransitRelease,castleMatrix:matrix,sampleTerrain:local(terrainIndex),sampleSea:local(sea),sampleRailTerrain:local(ground),connectionTargets:frozen.connectionTargets});f.castle.add(city.group);f.scene.updateMatrixWorld(true);assert.equal(city.report.finitePass,true,JSON.stringify(city.report.issues));
  const provisional=sys.group.getObjectByName('tram-crossing-provisional-supports'),beforeChildren=sys.group.children.length;
  assert.throws(()=>sys.prepareCrossingSupport({...callbacks,sampleGround:()=>null,cityStructure:city.group}),/APPROACH_REJECTED/);assert.equal(sys.group.children.length,beforeChildren);assert.equal(provisional.parent,sys.group);assert.equal(sys.crossingState.active,false);
  const expected=sys.crossingBundle.expectedSourceDeckInterface.bottomSections;sys.crossingBundle.expectedSourceDeckInterface.bottomSections=expected.map(s=>s.map(p=>[p[0]+25,p[1],p[2]]));assert.throws(()=>sys.prepareCrossingSupport({...callbacks,cityStructure:city.group}),/SOURCE_DECK_MISSING/);sys.crossingBundle.expectedSourceDeckInterface.bottomSections=expected;
  const tx=sys.prepareCrossingSupport({...callbacks,cityStructure:city.group});assert.equal(tx.report.sourceDeck.pass,true);assert.ok(tx.report.sourceDeck.maxDistance<.00005);assert.ok(tx.report.sourceDeck.meshUuid);assert.equal(tx.report.cityStructure.walkableSamples.length,9);assert.equal(tx.report.approach.vehicleClearance.collisions.length,0);assert.equal(sys.group.visible,false);assert.equal(provisional.parent,sys.group);assert.ok(Object.values(sys.crossingBundle.exclusionPlan).every(p=>!p.active));tx.commit();assert.equal(sys.group.visible,true);assert.equal(sys.crossingState.active,true);assert.equal(provisional.parent,null);assert.ok(sys.group.getObjectByName('target-global-approach-support'));assert.ok(Object.values(sys.crossingBundle.exclusionPlan).every(p=>p.active));assert.equal(sys.citadelTransitRelease.cityGalleryCoverage.globalApproachSupportBuilt,true);
  const previous=sys.freightServices.map(s=>s.progress);sys.update(.016);assert.ok(sys.freightServices.some((s,i)=>s.progress!==previous[i]));tx.rollback();assert.equal(provisional.parent,sys.group);assert.equal(sys.group.visible,false);assert.equal(sys.crossingState.active,false);assert.equal(sys.group.children.length,beforeChildren);assert.ok(sys.citadelTransitRelease.cityGalleryCoverage.hardFailures.some(x=>x.code==='GLOBAL_APPROACH_SUPPORT_UNBUILT'));tx.rollback();
  const geometries=new Set();provisional.traverse(o=>{if(o.geometry)geometries.add(o.geometry);});let disposed=0;for(const g of geometries)g.addEventListener('dispose',()=>disposed++);
  const installed=sys.installCrossingSupport({...callbacks,cityStructure:city.group});assert.equal(installed.report.status,'committed');installed.finalize();assert.equal(disposed,geometries.size);installed.finalize();assert.equal(disposed,geometries.size);assert.throws(()=>installed.rollback(),/FINALIZED/);assert.equal(sys.group.visible,true);
  fs.mkdirSync(new URL('artifacts/pipeline/citadel-global-crossing-startup-20261006/',ROOT),{recursive:true});fs.writeFileSync(new URL('artifacts/pipeline/citadel-global-crossing-startup-20261006/native-factory-cpu.json',ROOT),JSON.stringify({installedInProduction:false,gpuVerified:false,sourceEpochStartupSequenceVerified:false,sourceDeck:tx.report.sourceDeck,cityStructure:tx.report.cityStructure,approach:tx.report.approach,rollback:{testedBeforeSecondCommit:true,originalProvisionalGroupRestored:true},finalize:{discardedProvisionalGeometries:disposed,idempotent:true},consumerCurvesShared:true,bootstrapSeparated:true},null,2));
 }finally{sys.dispose();city?.dispose();g.dispose();waveG.dispose();mat.dispose();for(const m of[hills.mesh,hills.skirt]){m.geometry.dispose();m.material.dispose();}f.dispose();}
});
test('default user-marked viaduct matches saved pre-change actual factory geometry',async()=>{
 const sourceURL=new URL('../../src/world/tramSystem.js',import.meta.url),snapshot=fs.readFileSync(new URL('../../artifacts/pipeline/citadel-global-crossing-startup-20261006/tramSystem.before-crossing.js',import.meta.url),'utf8'),rewritten=snapshot.replace(/from\s*(["'])(\.\.?\/[^"']+)\1/g,(_m,q,path)=>'from '+q+new URL(path,sourceURL).href+q).replace(/from\s*(["'])three\1/g,(_m,q)=>'from '+q+import.meta.resolve('three')+q),prior=await import('data:text/javascript;base64,'+Buffer.from(rewritten).toString('base64')),scene=new T.Scene(),old=prior.buildChristchurchTramSystem(scene,160,{citadelCliffTransit:true}),current=buildChristchurchTramSystem(scene,160,{citadelCliffTransit:true});
 try{const meshes=root=>{const a=[];root.getObjectByName('moebius-city-viaduct').traverse(o=>{if(o.isMesh&&!o.userData.isOutline)a.push(o);});return a;},a=meshes(old.group),b=meshes(current.group);assert.equal(a.length,b.length);for(let i=0;i<a.length;i++){assert.deepEqual(a[i].geometry.attributes.position.array,b[i].geometry.attributes.position.array);assert.deepEqual(a[i].geometry.index.array,b[i].geometry.index.array);}for(const key of['red','blue'])for(let i=0;i<=100;i++)assert.ok(old.curves[key].getPointAt(i/100).distanceTo(current.curves[key].getPointAt(i/100))<1e-9);}
 finally{current.dispose();const gs=new Set(),ms=new Set();old.group.traverse(o=>{if(o.geometry)gs.add(o.geometry);for(const m of(Array.isArray(o.material)?o.material:[o.material]))if(m&&!m.userData.shared)ms.add(m);});gs.forEach(g=>g.dispose());ms.forEach(m=>m.dispose());old.group.removeFromParent();}
});
