extends SceneTree
const Director = preload("res://scripts/saihoji_battle_director.gd")
var failures: Array[String] = []
var checks := 0
var events: Array[Dictionary] = []
func check(condition: bool, label: String) -> void:
    checks += 1
    if not condition: failures.append(label)
func count(kind: String) -> int:
    return events.filter(func(e): return e.type == kind).size()
func _initialize() -> void:
    var d = Director.new()
    root.add_child(d)
    d.event_emitted.connect(func(e): events.append(e))
    check(not d.configure(["same"], ["same"], []), "reject duplicate entity identity")
    check(d.configure(["fleet1"], ["blue1"], ["heavy1", "heavy2", "heavy3", "heavy4"]), "configure valid identity")
    check(d.start(), "start")
    check(not d.configure(["new"], ["newblue"], []), "identity immutable while running")
    var observation := {"fleet_present": true, "fleet_ground_dir": Vector3.UP, "near": true, "far": false, "drum_active": false, "whale_lift": 0.0}
    d.tick(1.0, observation)
    check(not d.report_landing("saihoji-warship-0"), "cannot land unrequested ship")
    for i in range(40): d.tick(1.0, observation)
    check(count("ship_departure_requested") == 2, "exactly two dispatch intentions")
    check(d.phase == "sail_out", "timers do not fake landing")
    check(count("assault_requested") == 0, "whale rise cannot automatically deploy")
    check(count("bgm_intent") == 2, "prelude/storm music intentions once")
    check(d.report_landing("saihoji-warship-0"), "actual first landing")
    check(not d.report_landing("saihoji-warship-0"), "landing duplicate rejected")
    check(d.report_landing("saihoji-warship-1"), "actual second landing")
    check(d.report_formation_ready(), "formation observation")
    observation.whale_lift = 1.0
    d.tick(1.0, observation)
    check(count("resistance_enabled") == 1, "resistance needs formation and risen whale")
    check(count("assault_requested") == 0, "formed resistance cannot automatically deploy")
    check(not d.report_fleet_hit("bad", "fleet1", "fleet1"), "aircraft cannot be own attacker")
    check(d.report_fleet_hit("hit1", "blue1", "fleet1"), "real typed hit")
    check(not d.report_fleet_hit("hit1", "blue1", "fleet1"), "hit deduplicated")
    check(d.snapshot().hits == 1, "duplicate does not count damage")
    check(d.snapshot().threat_ids == ["blue1"], "threat is actual shooter")
    check(count("assault_requested") == 1, "one qualified attack starts deployment")
    check(not d.report_assault_stage("combat"), "cannot skip actual insertion")
    check(d.report_assault_stage("insert") and d.report_assault_stage("combat"), "observed insertion and combat")
    check(not d.report_whale_swallow("too-many", ["heavy1", "heavy2", "heavy3", "heavy4"]), "swallow capacity")
    check(not d.report_whale_swallow("friend", ["blue1"]), "swallow only registered enemy")
    check(d.report_whale_swallow("sw1", ["heavy1"]), "observed mouth capture")
    check(not d.report_whale_swallow("sw2", ["heavy2"]), "swallow cooldown")
    for i in range(2, 301): d.report_fleet_hit("hit%d" % i, "blue1", "fleet1")
    check(count("assault_requested") == 1, "arrow rain cannot reinsert")
    check(count("suction_changed") == 6 and d.snapshot().sink_step == 6, "six real damage thresholds")
    check(d.phase == "fight", "300 hits cannot fake physical whale landing")
    observation.whale_lift = 0.0
    d.tick(1.0, observation)
    check(count("whale_returned") == 1, "actual whale return")
    d.tick(1.0, observation)
    check(count("whale_returned") == 1, "return signal once")
    check(d.report_assault_stage("withdraw") and d.report_assault_stage("extract") and d.report_assault_stage("done"), "actual extraction sequence")
    d.report_fleet_hit("post", "blue1", "fleet1")
    check(count("assault_requested") == 1, "station cooldown prevents repeated drop")
    observation.near = false; observation.far = true; d.tick(1.0, observation)
    observation.near = true; observation.far = false; d.tick(1.0, observation)
    observation.near = false; observation.far = true; d.tick(1.0, observation)
    check(d.phase == "withdrawal", "route passage cannot fake defender boarding")
    check(d.report_withdrawal_complete(), "actual defenders returned")
    d.tick(1.0, observation)
    check(d.phase == "complete" and count("round_completed") == 1, "complete needs all observations")
    d.reset(); check(d.snapshot().hits == 0 and d.snapshot().landed.is_empty(), "reset clears transient state")
    d.start(); d.stop("test interruption")
    var n := events.size()
    d.tick(200.0, observation)
    check(events.size() == n and not d.report_fleet_hit("late", "blue1", "fleet1"), "stopped rejects late input")
    d.reset(); d.start()
    observation.near = true; observation.far = false
    observation.whale_lift = 0.0
    d.tick(0.1, observation)
    d.report_fleet_hit("moving", "blue1", "fleet1")
    check(d.assault_phase == "idle", "attack before settled cannot deploy")
    d.tick(5.0, observation)
    check(d.assault_phase == "idle", "timer after unqualified hit cannot invent new hit")
    d.report_fleet_hit("settled", "blue1", "fleet1")
    check(d.assault_phase == "approach", "new real hit at settled fleet deploys")
    var report := {"passed": failures.is_empty(), "checks": checks, "failures": failures, "scope": "isolated state/event core; observations supplied by tests, no actual world/physics/audio integration", "events": events}
    var output := OS.get_environment("SAIHOJI_REPORT")
    FileAccess.open(output, FileAccess.WRITE).store_string(JSON.stringify(report, "  "))
    print(JSON.stringify({"passed": failures.is_empty(), "checks": checks, "failures": failures}))
    quit(0 if failures.is_empty() else 1)
