import {chromium} from '/Users/panglaohu/Downloads/TigerInBamboo/tools/shot/node_modules/playwright/index.mjs';import {writeFile} from 'node:fs/promises';
const out='TigerMessenger/artifacts/pipeline/crystal-core-rotation',b=await chromium.launch({channel:'chrome',headless:true,args:['--use-angle=metal']});
try{const p=await b.newPage({viewport:{width:1200,height:800}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://localhost:8931/TigerMessenger/?autostart=1',{waitUntil:'domcontentloaded'});await p.waitForFunction(()=>window.__tm?.messenger?.landmarks?.tramSystem,null,{timeout:180000});await p.waitForTimeout(2000);
const info=await p.evaluate(async()=>{const t=window.__tm,T=t.THREE,l=t.messenger.landmarks,{getCityFrame,dirToCityLocal}=await import('/TigerMessenger/src/world/crystalCityLayout.js'),f=getCityFrame();t.cameraRig.update=()=>{};t.P.daySpeed=0;t.P.timeOfDay=.38;t.scene.updateMatrixWorld(true);
const core=[...l.moebius.crystals.slice(0,3).map(r=>r.group),l.moebiusSwamp];if(l.crystalMotherPort?.root)core.push(l.crystalMotherPort.root);
for(const o of l.moebius.v7Shores.children)if(!o.name||/swamp|garden-connector/.test(o.name)||/^v7-bank-rock-[012]$/.test(o.name))core.push(o);
const unique=core.filter((o,i)=>core.indexOf(o)===i&&!core.some(parent=>parent!==o&&(()=>{for(let q=o.parent;q;q=q.parent)if(q===parent)return true;return false;})()));
const originals=unique.map(o=>({o,m:o.matrixWorld.clone()})),lake0=l.moebiusSwamp.position.clone(),cv=l.tramSystem.curves.blue;
window.rotatePreview=deg=>{const q=new T.Quaternion().setFromAxisAngle(f.center,-deg*Math.PI/180),rotation=new T.Matrix4().makeRotationFromQuaternion(q);for(const {o,m}of originals){const matrix=o.parent.matrixWorld.clone().invert().multiply(rotation).multiply(m);matrix.decompose(o.position,o.quaternion,o.scale);o.updateMatrix();}t.scene.updateMatrixWorld(true);const dir=lake0.clone().normalize().applyQuaternion(q);let nearest={distance:Infinity};for(let i=0;i<4000;i++){const u=i/4000,w=cv.getPointAt(u),dist=w.clone().normalize().angleTo(dir)*160;if(dist<nearest.distance)nearest={u,distance:dist};}return {deg,local:dirToCityLocal(dir),nearest};};
window.rotateView=(kind)=>{if(kind==='map'){const center=f.center.clone().multiplyScalar(150).addScaledVector(f.east,35);t.camera.position.copy(center).addScaledVector(f.center,180);t.camera.up.copy(f.north).negate();t.camera.lookAt(center);}else{const cv=l.tramSystem.curves[kind],eye=cv.getPointAt(.30),up=eye.clone().normalize();t.camera.position.copy(eye).addScaledVector(up,2.5);t.camera.up.copy(up);const s=l.moebiusSwamp.userData.inner||l.moebiusSwamp;t.camera.lookAt(s.localToWorld(new T.Vector3(0,40,0)));}t.camera.fov=65;t.camera.updateProjectionMatrix();t.distanceCulling.recollect();t.distanceCulling.update(3);};return {objects:unique.map(o=>o.name),scope:'Disposable browser rigid spherical rotation of core geometry; not gameplay relocation'};});
info.trials=[];for(const deg of[0,15,30]){info.trials.push(await p.evaluate(d=>window.rotatePreview(d),deg));for(const v of['map','red','blue']){await p.evaluate(v=>window.rotateView(v),v);await p.waitForTimeout(250);const im=await p.evaluate(()=>{const t=window.__tm;t.renderer.render(t.scene,t.camera);return t.renderer.domElement.toDataURL()});await writeFile(`${out}/ccw${deg}-${v}.png`,Buffer.from(im.split(',')[1],'base64'));}}
info.errors=errors;await writeFile(out+'/preview.json',JSON.stringify(info,null,2));console.log(JSON.stringify(info));}finally{await b.close();}
