import * as T from 'three';
import {clipTurfTriangle,turfEdgeKey} from './mountainTurfGeometry.js';
// Same-component Euclidean distance in world metres; no geodesic claim.
export function insetMountainTurf(input,{inset=.25,maxOutput=180000,maxDepth=8}={}){
 const n=input.length,parent=Array.from({length:n},(_,i)=>i),find=i=>parent[i]===i?i:(parent[i]=find(parent[i])),join=(a,b)=>{a=find(a);b=find(b);if(a!==b)parent[b]=a;},edges=new Map();
 input.forEach((tri,i)=>{const v=[tri.a,tri.b,tri.c];for(let k=0;k<3;k++){const key=turfEdgeKey(v[k],v[(k+1)%3]),e=edges.get(key);if(e){e.ids.push(i);join(i,e.ids[0]);}else edges.set(key,{a:v[k],b:v[(k+1)%3],ids:[i]});}});
 const groups=new Map();for(let i=0;i<n;i++){const id=find(i);if(!groups.has(id))groups.set(id,{indices:[],segments:[],beforeArea:0,afterArea:0,sampledMaxWidth:0});const g=groups.get(id);g.indices.push(i);g.beforeArea+=input[i].getArea();}let nonmanifold=0;for(const e of edges.values()){if(e.ids.length===1)groups.get(find(e.ids[0])).segments.push({...e,box:new T.Box3().setFromPoints([e.a,e.b])});if(e.ids.length>2)nonmanifold++;}
 function tree(items){const box=new T.Box3();items.forEach(e=>box.union(e.box));if(items.length<=8)return {box,items};const s=box.getSize(new T.Vector3()),axis=s.x>=s.y&&s.x>=s.z?'x':s.y>=s.z?'y':'z';items.sort((a,b)=>(a.a[axis]+a.b[axis])-(b.a[axis]+b.b[axis]));const mid=items.length>>1;return {box,left:tree(items.slice(0,mid)),right:tree(items.slice(mid))};}
 const tmp=new T.Vector3();function distance(p,node,best=Infinity){if(!node||node.box.distanceToPoint(p)>=best)return best;if(node.items){for(const e of node.items)best=Math.min(best,new T.Line3(e.a,e.b).closestPointToPoint(p,true,tmp).distanceTo(p));return best;}best=distance(p,node.left,best);return distance(p,node.right,best);}
 function segmentDistance(a,b,c,d){const u=b.clone().sub(a),v=d.clone().sub(c),w=a.clone().sub(c),aa=u.dot(u),bb=u.dot(v),cc=v.dot(v),dd=u.dot(w),ee=v.dot(w),den=aa*cc-bb*bb;let s=den>1e-20?T.MathUtils.clamp((bb*ee-cc*dd)/den,0,1):0,t=cc>0?(bb*s+ee)/cc:0;if(t<0){t=0;s=aa?T.MathUtils.clamp(-dd/aa,0,1):0;}else if(t>1){t=1;s=aa?T.MathUtils.clamp((bb-dd)/aa,0,1):0;}return w.addScaledVector(u,s).addScaledVector(v,-t).length();}
 function exactDistance(tri,node,best=Infinity){const tb=new T.Box3().setFromPoints([tri.a,tri.b,tri.c]);function visit(b){if(!b)return;let gap=0;for(const axis of['x','y','z']){const d=Math.max(0,tb.min[axis]-b.box.max[axis],b.box.min[axis]-tb.max[axis]);gap+=d*d;}if(Math.sqrt(gap)>=best)return;if(b.items){for(const e of b.items){const delta=e.b.clone().sub(e.a),len=delta.length(),ray=new T.Ray(e.a,delta.clone().normalize()),hit=ray.intersectTriangle(tri.a,tri.b,tri.c,false,new T.Vector3());if(hit&&hit.distanceTo(e.a)<=len){best=0;return;}best=Math.min(best,tri.closestPointToPoint(e.a,new T.Vector3()).distanceTo(e.a),tri.closestPointToPoint(e.b,new T.Vector3()).distanceTo(e.b),segmentDistance(tri.a,tri.b,e.a,e.b),segmentDistance(tri.b,tri.c,e.a,e.b),segmentDistance(tri.c,tri.a,e.a,e.b));}}else{visit(b.left);visit(b.right);}}visit(node);return best;}
 const output=[];let tinyRejected=0,wholeInsideRejected=0,subdivisions=0;const summaries=[];
 for(const [id,g]of groups){const boundary=g.segments.length?tree(g.segments):null;let minRetained=Infinity;
  function add(triangle,source){if(output.length>=maxOutput)throw Error('Turf inset output budget exceeded; candidate not accepted');output.push({triangle,source});g.afterArea+=triangle.getArea();}
  function process(tri,source,depth){if(!boundary){add(tri,source);return;}const vs=[tri.a,tri.b,tri.c],ds=vs.map(v=>distance(v,boundary)),longest=Math.max(tri.a.distanceTo(tri.b),tri.b.distanceTo(tri.c),tri.c.distanceTo(tri.a));if(Math.max(...ds)+longest<inset){wholeInsideRejected++;return;}const exact=exactDistance(tri,boundary);if(exact>=inset-1e-8){minRetained=Math.min(minRetained,exact);add(tri,source);return;}const clipped=clipTurfTriangle(tri,ds.map(d=>d-inset));if(!clipped.length&&Math.max(...ds)+longest<inset+.01)return;if(clipped.length&&longest<=1){const gaps=clipped.map(p=>exactDistance(p,boundary));if(gaps.every(d=>d>=inset-1e-8)){for(let i=0;i<clipped.length;i++){minRetained=Math.min(minRetained,gaps[i]);add(clipped[i],source);}return;}}
   if(depth>=maxDepth||longest<.10){for(const p of clipped){const gap=exactDistance(p,boundary);if(gap>=inset-1e-8){minRetained=Math.min(minRetained,gap);add(p,source);}else tinyRejected++;}return;}
   // Interior/negative-vertex triangles are subdivided too: a broad interior
   // may exist even when all three original vertices lie on a boundary.
   subdivisions++;const ab=tri.a.clone().add(tri.b).multiplyScalar(.5),bc=tri.b.clone().add(tri.c).multiplyScalar(.5),ca=tri.c.clone().add(tri.a).multiplyScalar(.5);for(const p of[new T.Triangle(tri.a,ab,ca),new T.Triangle(ab,tri.b,bc),new T.Triangle(ca,bc,tri.c),new T.Triangle(ab,bc,ca)])process(p,source,depth+1);
  }
  for(const i of g.indices){const tri=input[i];g.sampledMaxWidth=Math.max(g.sampledMaxWidth,2*distance(tri.getMidpoint(new T.Vector3()),boundary));process(tri,i,0);}
  summaries.push({id,sourceTriangles:g.indices.length,boundarySegments:g.segments.length,beforeArea:g.beforeArea,afterArea:g.afterArea,sampledMaximumInteriorWidth:g.sampledMaxWidth,minRetainedBoundaryDistance:Number.isFinite(minRetained)?minRetained:null});
 }
 return {output,stats:{method:'same-edge-connected-component world 3D boundary distance, exact triangle-to-boundary certification; no terrain displacement',inset,maxOutput,maxDepth,components:groups.size,retainedSourceComponents:summaries.filter(g=>g.afterArea>0).length,removedSourceComponents:summaries.filter(g=>g.afterArea===0).length,nonmanifoldEdges:nonmanifold,beforeTriangles:n,afterTriangles:output.length,beforeArea:summaries.reduce((s,g)=>s+g.beforeArea,0),afterArea:summaries.reduce((s,g)=>s+g.afterArea,0),tinyRejected,wholeInsideRejected,subdivisions,widthMeaning:'twice maximum distance among input triangle centroids, not exact minimum width or geodesic width',items:summaries}};
}
