import * as T from 'three';
import {cliffWallGeometryEpoch} from './targetEastCliffWallSimplification.js';
const pointSegment=(p,a,b)=>{const d=b.clone().sub(a),t=T.MathUtils.clamp(p.clone().sub(a).dot(d)/d.lengthSq(),0,1);return p.distanceTo(a.clone().addScaledVector(d,t));};
/** Default-off inward-only reshaping of one explicitly traced COPLANAR wall.
 * Keeps the complete wall perimeter and stitches new edge points into adjacent
 * raw faces. Interior offsets create three unequal shelves, not shorter cliffs.
 * Caller must audit the final refinement, protected support and loaded routes. */
export function reshapeEastCliffWall({enabled=false,geometry,provenance,cluster,maxInset=.6,horizontalStep=.7}={}){
 const report={version:'east-cliff-wall-reshape-1',enabled,built:false,accepted:false,shortCliffCreated:false,failures:[]};if(!enabled)return{geometry:null,report};
 if(!geometry?.index||geometry.groups.length||!cluster?.sourceFaces?.length||provenance?.kind!=='recorded-builder-new-cliff-faces'||!provenance.builderSourceHash||JSON.stringify(cliffWallGeometryEpoch(geometry))!==JSON.stringify(provenance.geometryEpoch)||!Number.isFinite(maxInset)||maxInset<=0||maxInset>.8||!Number.isFinite(horizontalStep)||horizontalStep<=0){report.failures.push('explicit raw wall provenance and bounded parameters required');return{geometry:null,report};}
 const pos=geometry.attributes.position,ix=Array.from(geometry.index.array),V=i=>new T.Vector3().fromBufferAttribute(pos,i),selected=new Set(cluster.sourceFaces),recorded=new Set(provenance.faces);if([...selected].some(i=>!recorded.has(i))){report.failures.push('unrecorded wall face');return{geometry:null,report};}
 const ring=cluster.boundaryVertices.map(V),first=ix.slice(cluster.sourceFaces[0]*3,cluster.sourceFaces[0]*3+3).map(V),normal=first[1].clone().sub(first[0]).cross(first[2].clone().sub(first[0])).normalize();if(Math.abs(normal.y)>.02){report.failures.push('vertical cliff panel required');return{geometry:null,report};}
 const axis=new T.Vector3(0,1,0).cross(normal).normalize(),base=ring[0],project=p=>[p.clone().sub(base).dot(axis),p.y],unproject=q=>base.clone().addScaledVector(axis,q[0]).setY(q[1]),poly=ring.map(project),uMin=Math.min(...poly.map(p=>p[0])),uMax=Math.max(...poly.map(p=>p[0])),yMin=Math.min(...poly.map(p=>p[1])),yMax=Math.max(...poly.map(p=>p[1]));
 if(ring.some(p=>Math.abs(p.clone().sub(base).dot(normal))>1e-5)||uMax-uMin<.1||yMax-yMin<1){report.failures.push('nonplanar or tiny selected wall');return{geometry:null,report};}
 function clip(poly,dimension,value,sign){const out=[];for(let i=0;i<poly.length;i++){const a=poly[i],b=poly[(i+1)%poly.length],da=(a[dimension]-value)*sign,db=(b[dimension]-value)*sign;if(da>=-1e-9)out.push(a);if(da*db<-1e-18){const t=da/(da-db);out.push(a.map((v,k)=>v+(b[k]-v)*t));}}return out;}
 const us=[uMin,uMax,...poly.map(p=>p[0])];for(let u=uMin+horizontalStep;u<uMax;u+=horizontalStep)us.push(u);const unique=a=>[...new Set(a.map(v=>+v.toFixed(8)))].sort((a,b)=>a-b),uCuts=unique(us),fractions=[0,.13,.135,.40,.405,.68,.685,.94,1],depths=[0,.10,.78,.30,1,.16,.72,.20,0],yCuts=fractions.map(t=>yMin+(yMax-yMin)*t);
 const positions=Array.from(pos.array),map=new Map();for(let i=0;i<pos.count;i++)map.set(V(i).toArray().map(v=>v.toFixed(6)).join(','),i);const extras=[],moves=[],newFaces=[];
 function vertex(q){const original=unproject(q),boundary=ring.some((a,i)=>pointSegment(original,a,ring[(i+1)%ring.length])<2e-6);let point=original.clone();if(!boundary){const t=(q[1]-yMin)/(yMax-yMin);let i=0;while(i<fractions.length-2&&t>fractions[i+1])i++;const h=(t-fractions[i])/(fractions[i+1]-fractions[i]),depth=depths[i]+(depths[i+1]-depths[i])*h,side=Math.sin(Math.PI*(q[0]-uMin)/(uMax-uMin));point.addScaledVector(normal,-maxInset*depth*side);}
  const key=point.toArray().map(v=>v.toFixed(6)).join(',');if(map.has(key))return map.get(key);const id=positions.length/3;positions.push(...point.toArray());map.set(key,id);if(boundary)extras.push({id,p:point});else moves.push({id,before:original.toArray(),after:point.toArray(),inset:original.distanceTo(point)});return id;
 }
 function addTri(a,b,c){const va=new T.Vector3().fromArray(positions,a*3),n=new T.Vector3().fromArray(positions,b*3).sub(va).cross(new T.Vector3().fromArray(positions,c*3).sub(va));if(n.length()<1e-9)return;if(n.dot(normal)<0)[b,c]=[c,b];newFaces.push(a,b,c);}
 for(let i=0;i<uCuts.length-1;i++)for(let j=0;j<yCuts.length-1;j++){let p=clip(clip(clip(clip(poly,0,uCuts[i],1),0,uCuts[i+1],-1),1,yCuts[j],1),1,yCuts[j+1],-1);p=p.filter((q,k)=>!k||Math.hypot(q[0]-p[k-1][0],q[1]-p[k-1][1])>1e-7);if(p.length<3)continue;const c=p.reduce((a,q)=>[a[0]+q[0]/p.length,a[1]+q[1]/p.length],[0,0]),ci=vertex(c),ids=p.map(vertex);for(let k=0;k<ids.length;k++)addTri(ci,ids[k],ids[(k+1)%ids.length]);}
 const indices=[];let stitched=0;
 for(let f=0;f<ix.length/3;f++){if(selected.has(f))continue;const ids=ix.slice(f*3,f*3+3),out=[];for(let j=0;j<3;j++){const a=V(ids[j]),b=V(ids[(j+1)%3]),d=b.clone().sub(a),len=d.lengthSq();out.push(ids[j]);const hits=extras.filter(e=>pointSegment(e.p,a,b)<2e-6).map(e=>({...e,t:e.p.clone().sub(a).dot(d)/len})).filter(e=>e.t>1e-7&&e.t<1-1e-7).sort((a,b)=>a.t-b.t);out.push(...hits.map(e=>e.id));}if(out.length===3){indices.push(...ids);continue;}stitched++;const center=ids.map(V).reduce((a,v)=>a.add(v),new T.Vector3()).multiplyScalar(1/3),ci=positions.length/3;positions.push(...center.toArray());for(let j=0;j<out.length;j++)indices.push(ci,out[j],out[(j+1)%out.length]);}
 indices.push(...newFaces);
 const result=new T.BufferGeometry().setAttribute('position',new T.Float32BufferAttribute(positions,3));result.setIndex(indices);result.computeVertexNormals();result.computeBoundingBox();result.computeBoundingSphere();Object.assign(report,{built:true,sourceEpoch:cliffWallGeometryEpoch(geometry),candidateEpoch:cliffWallGeometryEpoch(result),perimeterFixed:true,normal:normal.toArray(),maxInset:Math.max(0,...moves.map(m=>m.inset)),movedVertices:moves.length,removedFaces:selected.size,newWallFaces:newFaces.length/3,stitchedNeighborFaces:stitched,fullHeight:yMax-yMin,profile:{fractions,depths},limitations:['Raw position/normal mesh only; must regenerate original rock attributes through production refinement.','Top/bottom and all panel perimeter fixed; no claim of globally shorter cliffs or solved structural support.']});return{geometry:result,report,moves};
}
