import * as T from 'three';
const clamp=x=>T.MathUtils.clamp(x,-1,1),angle=(a,b)=>Math.acos(clamp(a.dot(b)));
/** Great-circle legs joined by exact tangent small circles on a unit sphere.
 * No chart-space spline followed by projection; failed overlapping fillets are rejected. */
export function createSphericalShoreArcCandidate({enabled=false,points,startTangent,endTangent,turnRadius=32,minRadius=27.05,maxGrade=.04}={}){
 const report={version:'spherical-shore-arc-1',enabled,accepted:false,installed:false,issues:[],fillets:[]};
 if(!enabled)return{curve:null,report};
 if(!Array.isArray(points)||points.length<3||points.some(p=>p.length!==3||!p.every(Number.isFinite))||![startTangent,endTangent].every(p=>Array.isArray(p)&&p.length===3&&p.every(Number.isFinite)&&Math.hypot(...p)>1e-8)||![turnRadius,minRadius,maxGrade].every(v=>Number.isFinite(v)&&v>0))throw new TypeError('finite world control points and endpoint tangents required');
 const raw=points.map(p=>new T.Vector3(...p)),units=raw.map(p=>p.clone().normalize()),r0=raw[0].length(),r1=raw.at(-1).length(),rho=Math.asin(turnRadius/Math.min(r0,r1)),fillets=[];
 for(let i=1;i<units.length-1;i++){const v=units[i],a=units[i-1].clone().addScaledVector(v,-units[i-1].dot(v)).normalize(),b=units[i+1].clone().addScaledVector(v,-units[i+1].dot(v)).normalize(),beta=angle(a,b),hSin=Math.sin(rho)/Math.sin(beta/2);if(!Number.isFinite(hSin)||hSin>=1){report.issues.push({type:'turn-too-tight',i});return{curve:null,report};}const h=Math.asin(hSin),axis=v.clone().multiplyScalar(Math.cos(h)).addScaledVector(a.clone().add(b).normalize(),Math.sin(h)).normalize(),n0=new T.Vector3().crossVectors(v,units[i-1]).normalize(),n1=new T.Vector3().crossVectors(v,units[i+1]).normalize(),entry=axis.clone().addScaledVector(n0,-axis.dot(n0)).normalize(),exit=axis.clone().addScaledVector(n1,-axis.dot(n1)).normalize();fillets.push({i,axis,entry,exit});report.fillets.push({i,turnRadius,entry:entry.toArray(),exit:exit.toArray(),angularRetreatIn:angle(v,entry),angularRetreatOut:angle(v,exit)});}
 for(let i=0;i<units.length-1;i++){const used=(i>0?angle(units[i],fillets[i-1].exit):0)+(i<units.length-2?angle(units[i+1],fillets[i].entry):0),available=angle(units[i],units[i+1]);if(used>=available-1e-6)report.issues.push({type:'fillets-overlap',leg:i,required:used*Math.min(r0,r1),available:available*Math.min(r0,r1)});}
 if(report.issues.length)return{curve:null,report};
 const segments=[];function great(a,b){const theta=angle(a,b),axis=new T.Vector3().crossVectors(a,b).normalize();if(theta>1e-8)segments.push({length:theta,point:t=>a.clone().applyAxisAngle(axis,theta*t),kind:'great-circle'});}
 let from=units[0];for(const f of fillets){great(from,f.entry);const cosine=f.axis.dot(f.entry),basis=f.entry.clone().addScaledVector(f.axis,-cosine),end=f.exit.clone().addScaledVector(f.axis,-cosine),sine=f.axis.dot(new T.Vector3().crossVectors(basis,end)),theta=Math.atan2(sine,basis.dot(end));segments.push({length:Math.abs(theta)*basis.length(),point:t=>f.axis.clone().multiplyScalar(cosine).add(basis.clone().applyAxisAngle(f.axis,theta*t)),kind:'small-circle'});from=f.exit;}great(from,units.at(-1));
 const total=segments.reduce((s,p)=>s+p.length,0),derivative=(t,u,r)=>{const v=new T.Vector3(...t).normalize(),rad=v.dot(u);return rad/Math.sqrt(1-rad*rad)*total*r;},d0=derivative(startTangent,units[0],r0),d1=derivative(endTangent,units.at(-1),r1);
 const edge=.1,plateau=(r1-r0-.5*edge*(d0+d1))/(1-edge),integral=u=>.5*u-Math.sin(Math.PI*u)/(2*Math.PI),radiusAt=t=>{if(t<edge)return r0+d0*t+(plateau-d0)*edge*integral(t/edge);const first=.5*edge*(d0+plateau);if(t<=1-edge)return r0+first+plateau*(t-edge);const u=(t-1+edge)/edge;return r0+first+plateau*(1-2*edge)+plateau*edge*u+(d1-plateau)*edge*integral(u);};
 class C extends T.Curve{getPoint(t,out=new T.Vector3()){let remaining=T.MathUtils.clamp(t,0,1)*total,s=segments.at(-1),f=1;for(const part of segments){if(remaining<=part.length){s=part;f=remaining/part.length;break;}remaining-=part.length;}const r=radiusAt(t);return out.copy(s.point(f)).multiplyScalar(r);}}
 const curve=new C();curve.arcLengthDivisions=4096;let min=Infinity,grade=0;const n=Math.ceil(curve.getLength()/.5),samples=Array.from({length:n+1},(_,i)=>curve.getPointAt(i/n));for(let i=0;i<=n;i++){const p=samples[i],v=Math.abs(curve.getTangentAt(i/n).dot(p.clone().normalize()));grade=Math.max(grade,v/Math.sqrt(1-v*v));if(i&&i<n){const a=samples[i-1],b=p,c=samples[i+1],cross=b.clone().sub(a).cross(c.clone().sub(a)).length();if(cross>1e-10)min=Math.min(min,a.distanceTo(b)*b.distanceTo(c)*c.distanceTo(a)/(2*cross));}}
 const endpointAngles=[curve.getTangent(0).angleTo(new T.Vector3(...startTangent)),curve.getTangent(1).angleTo(new T.Vector3(...endTangent))];if(min<minRadius)report.issues.push({type:'radius',value:min,limit:minRadius});if(grade>maxGrade)report.issues.push({type:'grade',value:grade,limit:maxGrade});if(endpointAngles.some(a=>a>Math.PI/360))report.issues.push({type:'endpoint-tangent',endpointAngles});Object.assign(report,{status:report.issues.length?'failed':'shape-only-not-clearance',minRadius:min,maxGrade:grade,endpointAngles,length:curve.getLength(),points,turnRadius,radialProfile:{kind:'cosine-eased endpoint grades and constant middle grade',edgeFraction:edge,r0,r1,d0,d1,plateau},segments:segments.map(s=>({kind:s.kind,angularLength:s.length})),limitations:['C1 tangent circle joins have a curvature step, not clothoid/C2 track dynamics.','Only spherical path geometry audited here; loaded body, water, actors, support structures and station mapping required separately.']});return{curve,report};
}
/** Recompute only spherical radius after companion-line endpoint blending.
 * Uses actual normalized endpoint derivative; never changes the directional path. */
export function applySphericalShoreGradeProfile(base,{startTangent,endTangent,edgeFraction=.1}={}){
 if(!base?.getPointAt||![startTangent,endTangent].every(v=>Array.isArray(v)&&v.length===3&&v.every(Number.isFinite))||!(edgeFraction>0&&edgeFraction<.5))throw new TypeError('curve and endpoint grades required');
 const first=base.getPointAt(0),last=base.getPointAt(1),r0=first.length(),r1=last.length(),e=1e-5,derivative=(t,tan,r)=>{const u=base.getPointAt(t).normalize(),a=base.getPointAt(Math.max(0,t-e)).normalize(),b=base.getPointAt(Math.min(1,t+e)).normalize(),speed=a.distanceTo(b)/e,v=new T.Vector3(...tan).normalize().dot(u);return speed*r*v/Math.sqrt(1-v*v);},d0=derivative(0,startTangent,r0),d1=derivative(1,endTangent,r1),edge=edgeFraction,plateau=(r1-r0-.5*edge*(d0+d1))/(1-edge),integral=u=>.5*u-Math.sin(Math.PI*u)/(2*Math.PI);
 class Profile extends T.Curve{getPoint(t,out=new T.Vector3()){let r;const first=.5*edge*(d0+plateau);if(t<edge)r=r0+d0*t+(plateau-d0)*edge*integral(t/edge);else if(t<=1-edge)r=r0+first+plateau*(t-edge);else{const u=(t-1+edge)/edge;r=r0+first+plateau*(1-2*edge)+plateau*edge*u+(d1-plateau)*edge*integral(u);}return out.copy(base.getPointAt(t)).normalize().multiplyScalar(r);}}
 const curve=new Profile();curve.arcLengthDivisions=4096;return curve;
}
