import * as T from 'three';
import {buildMountainSurfaceIndex} from './mountainSurfaceIndex.js';
const signature=m=>m.elements.map(v=>v.toFixed(6)).join(',');
const visible=o=>{for(let p=o;p;p=p.parent)if(!p.visible)return false;return true;};
function overlapOrientedBoxes(a,ma,b,mb){
 const corners=(box,m)=>{const out=[];for(const x of[box.min.x,box.max.x])for(const y of[box.min.y,box.max.y])for(const z of[box.min.z,box.max.z])out.push(new T.Vector3(x,y,z).applyMatrix4(m));return out;};
 const ca=corners(a,ma),cb=corners(b,mb),aa=[0,1,2].map(i=>new T.Vector3().setFromMatrixColumn(ma,i).normalize()),bb=[0,1,2].map(i=>new T.Vector3().setFromMatrixColumn(mb,i).normalize()),axes=[...aa,...bb,...aa.flatMap(x=>bb.map(y=>x.clone().cross(y)))];
 for(const axis of axes){if(axis.lengthSq()<1e-12)continue;axis.normalize();const pa=ca.map(p=>p.dot(axis)),pb=cb.map(p=>p.dot(axis));if(Math.max(...pa)<Math.min(...pb)-1e-6||Math.max(...pb)<Math.min(...pa)-1e-6)return false;}return true;
}
function insideProtectedSolid(point,triangles){let angle=0;for(const t of triangles){const a=t.a.clone().sub(point),b=t.b.clone().sub(point),c=t.c.clone().sub(point),la=a.length(),lb=b.length(),lc=c.length();angle+=2*Math.atan2(a.dot(b.clone().cross(c)),la*lb*lc+a.dot(b)*lc+b.dot(c)*la+c.dot(a)*lb);}return Math.abs(angle/(4*Math.PI))>.5;}
/** Default-off, all-or-nothing candidate canopy transplantation. Never hides trees.
 * Explicit public meshes include actor reserve geometry; curves must be the candidate lanes.
 * All sample coordinates and report positions are castle-local unless marked world. */
export function createEastCliffVegetationRefresh({enabled=false,castle,surfaces=[],previousSurfaces=[],protectedMeshes=[],railCurves=[],sampleSea,maxDistance=12,minimumScale=.8,repairUnsupportedTurf=true,retireUnplaced=true,plantingBounds={x:[25,135],z:[-65,105]},spacing=2,minSlope=.72,railClearance=6.2}={}){
 const started=performance.now();const report={version:'east-cliff-vegetation-refresh-1',enabled,accepted:false,applied:false,moves:[],retired:[],failures:[],unchanged:0,hiddenInstancesUntouched:0,unsupported:[],treeCountBefore:0,treeCountAfter:0,publicBlockers:{},rejections:{surface:0,slopeOrWater:0,feet:0,public:0,rail:0,trees:0}};
 if(!enabled)return{report,apply:()=>false,dispose(){}};
 if(!castle?.isObject3D||!surfaces.length||!protectedMeshes.length||railCurves.length<2||typeof sampleSea!=='function')throw new TypeError('actual castle, final surfaces, public/actor protected meshes, both candidate rail curves and actual sea sampler required');
 if(!plantingBounds?.x?.every(Number.isFinite)||!plantingBounds?.z?.every(Number.isFinite)||plantingBounds.x[0]>=plantingBounds.x[1]||plantingBounds.z[0]>=plantingBounds.z[1])throw new TypeError('finite new-shore planting bounds required');
 if(!Number.isFinite(minimumScale)||minimumScale<.8||minimumScale>1)throw new RangeError('minimumScale must be .8..1');
 if(![maxDistance,spacing,minSlope,railClearance].every(Number.isFinite)||maxDistance<=0||maxDistance>24||spacing<=0||minSlope<.5||minSlope>1)throw new RangeError('finite conservative search limits required');
 castle.updateWorldMatrix(true,true);for(const m of [...surfaces,...protectedMeshes])m.updateWorldMatrix(true,false);
 const previousIndex=previousSurfaces.length?buildMountainSurfaceIndex(previousSurfaces):null,index=buildMountainSurfaceIndex(surfaces),inv=castle.matrixWorld.clone().invert(),up=new T.Vector3(0,1,0).transformDirection(castle.matrixWorld),down=up.clone().negate(),normalMatrix=new T.Matrix3(),forest=castle.getObjectByName('citadel-mountain-canopy-candidate');
 if(!forest){report.failures.push({reason:'candidate-canopy-missing'});return{report,apply:()=>false,dispose(){}};}
 const turfMeshes=[],parts=[],groups=new Map();forest.traverse(m=>{if(!m.isInstancedMesh||!visible(m))return;m.geometry.computeBoundingBox();parts.push(m);for(let i=0;i<m.count;i++){const matrix=new T.Matrix4();m.getMatrixAt(i,matrix);if(Math.abs(matrix.determinant())<1e-12){report.hiddenInstancesUntouched++;continue;}const world=m.matrixWorld.clone().multiply(matrix),key=signature(world);if(!groups.has(key))groups.set(key,[]);groups.get(key).push({mesh:m,index:i,matrix,world});}});
 castle.traverse(o=>{if(o.isMesh&&visible(o)&&o.name==='target-bench-turf-surface'){turfMeshes.push(o);return;}if(o.isMesh&&visible(o)&&/grass|scrub|forest-companion|mountain-tree|mountain-shrub|groundcover|turf/i.test(o.name)&&!parts.includes(o))report.unsupported.push({name:o.name,uuid:o.uuid,count:o.isInstancedMesh?o.count:1});});
 const protections=[];for(const m of protectedMeshes.filter(visible)){const p=m.geometry?.attributes.position;if(!p)throw new TypeError('protectedMeshes must contain actual mesh geometry, not groups');const ix=m.geometry.index;for(let instance=0;instance<(m.isInstancedMesh?m.count:1);instance++){const transform=m.matrixWorld.clone();if(m.isInstancedMesh){const im=new T.Matrix4();m.getMatrixAt(instance,im);if(Math.abs(im.determinant())<1e-12)continue;transform.multiply(im);}const triangles=[];for(let k=0;k<(ix?.count??p.count);k+=3)triangles.push(new T.Triangle(...[0,1,2].map(j=>new T.Vector3().fromBufferAttribute(p,ix?ix.getX(k+j):k+j).applyMatrix4(transform))));protections.push({name:m.name,uuid:m.uuid,instance:m.isInstancedMesh?instance:null,box:new T.Box3().setFromPoints(triangles.flatMap(t=>[t.a,t.b,t.c])),triangles});}}
 const protectionEpochs=[...protectedMeshes,...turfMeshes].map(m=>({mesh:m,world:m.matrixWorld.toArray(),geometry:m.geometry?.uuid,positionVersion:m.geometry?.attributes.position?.version,visible:visible(m),count:m.isInstancedMesh?m.count:null,instances:m.isInstancedMesh?m.instanceMatrix.array.slice():null}));
 const forestEpochs=parts.map(m=>({mesh:m,count:m.count,instances:m.instanceMatrix.array.slice(),colors:m.instanceColor?.array.slice()??null,world:m.matrixWorld.toArray(),geometry:m.geometry.uuid,positionVersion:m.geometry.attributes.position.version}));
 const differs=(a,b)=>a.length!==b.length||a.some((v,i)=>Math.abs(v-b[i])>1e-9);
 const changedEpoch=()=>{castle.updateWorldMatrix(true,true);for(const r of [...protectionEpochs,...forestEpochs]){r.mesh.updateWorldMatrix(true,false);if(differs(r.world,r.mesh.matrixWorld.elements)||r.geometry!==r.mesh.geometry?.uuid||r.positionVersion!==r.mesh.geometry?.attributes.position?.version||(r.visible!==undefined&&r.visible!==visible(r.mesh))||(r.instances&&(r.count!==r.mesh.count||differs(r.instances,r.mesh.instanceMatrix.array))))return r.mesh.name||r.mesh.uuid;}return null;};
 const rail=[];for(const curve of railCurves){const n=Math.ceil(curve.getLength());for(let i=0;i<=n;i++)rail.push(curve.getPointAt(i/n));}
 const sample=(x,z)=>{const hit=index.sample(new T.Ray(new T.Vector3(x,250,z).applyMatrix4(castle.matrixWorld),down),0,700);if(!hit)return null;const point=hit.point.clone().applyMatrix4(inv),normal=hit.face.normal.clone().applyMatrix3(normalMatrix.getNormalMatrix(hit.object.matrixWorld)).normalize();if(normal.dot(up)<0)normal.negate();return{point,normal,slope:Math.abs(normal.dot(up)),object:hit.object.name,face:hit.faceIndex};};
 const sea=(x,z)=>{const s=sampleSea(x,z);return typeof s==='number'?s:s?.height;};
 const check=(rows,local,protect=true,scaleFactor=1)=>{
  if(local.x<plantingBounds.x[0]||local.x>plantingBounds.x[1]||local.z<plantingBounds.z[0]||local.z>plantingBounds.z[1])return null;
  const hit=sample(local.x,local.z),water=sea(local.x,local.z);if(!hit||!Number.isFinite(water)){report.rejections.surface++;return null;}if(hit.point.y<water+1.6||hit.slope<minSlope){report.rejections.slopeOrWater++;return null;}
  const originalWorld=rows[0].world,oldUp=new T.Vector3(0,1,0).transformDirection(originalWorld),rotation=new T.Quaternion().setFromUnitVectors(oldUp,hit.normal),oldWorld=new T.Matrix4().makeRotationFromQuaternion(rotation).multiply(originalWorld).setPosition(new T.Vector3().setFromMatrixPosition(originalWorld)).scale(new T.Vector3(scaleFactor,scaleFactor,scaleFactor)),oldRoot=new T.Vector3().setFromMatrixPosition(oldWorld),target=hit.point.clone().applyMatrix4(castle.matrixWorld),delta=target.sub(oldRoot).addScaledVector(up,-.012),world=oldWorld.clone().setPosition(oldRoot.clone().add(delta)),trunk=rows.find(r=>r.mesh.name==='citadel-canopy-root-trunks');
  const gaps=[];for(let j=0;j<6;j++){const p=new T.Vector3(Math.sin(j*Math.PI/3)*.12,0,Math.cos(j*Math.PI/3)*.12).applyMatrix4(world).applyMatrix4(inv),support=sample(p.x,p.z);if(!support){report.rejections.feet++;return null;}gaps.push(p.y-support.point.y);}const lower=Math.max(0,Math.max(...gaps)+.012);delta.addScaledVector(up,-lower);world.setPosition(oldRoot.clone().add(delta));for(let i=0;i<gaps.length;i++)gaps[i]-=lower;if(gaps.some(g=>g>.002||g<-.3)){report.rejections.feet++;return null;}
  const box=new T.Box3();for(const row of rows)box.union(row.mesh.geometry.boundingBox.clone().applyMatrix4(world));
  const obstacle=protect?protections.find(p=>p.box.intersectsBox(box)&&(p.triangles.some(t=>box.intersectsTriangle(t))||(p.box.containsPoint(box.getCenter(new T.Vector3()))&&insideProtectedSolid(box.getCenter(new T.Vector3()),p.triangles)))):null;if(obstacle){report.rejections.public++;report.publicBlockers[obstacle.name]=(report.publicBlockers[obstacle.name]||0)+1;return null;}if(protect&&rail.some(p=>box.distanceToPoint(p)<railClearance)){report.rejections.rail++;return null;}
  return{delta,scaleFactor,worldMatrix:world.clone(),normal:hit.normal.toArray(),worldRoot:new T.Vector3().setFromMatrixPosition(world),local:new T.Vector3().setFromMatrixPosition(world).applyMatrix4(inv).toArray(),supportPoint:hit.point.toArray(),slope:hit.slope,footGaps:gaps,surface:hit.object,face:hit.face,box};
 };
 const changes=[],fixed=[],pending=[];
 report.surfaceEpochs=surfaces.map(m=>({uuid:m.uuid,name:m.name,geometryUUID:m.geometry.uuid,positionVersion:m.geometry.attributes.position.version,vertices:m.geometry.attributes.position.count,matrixWorld:m.matrixWorld.toArray()}));
 for(const[key,rows]of groups){report.treeCountBefore++;if(rows.length!==2||!rows.some(r=>r.mesh.name==='citadel-canopy-root-trunks')){report.failures.push({key,reason:'unpaired-or-ambiguous-canopy'});continue;}
  const root=new T.Vector3().setFromMatrixPosition(rows[0].world).applyMatrix4(inv),hit=sample(root.x,root.z),beforeGap=hit?root.y-hit.point.y:null;
  const probes=[root.clone(),...Array.from({length:6},(_,j)=>new T.Vector3(Math.sin(j*Math.PI/3)*.12,0,Math.cos(j*Math.PI/3)*.12).applyMatrix4(rows[0].world).applyMatrix4(inv))];
  const unchanged=previousIndex?probes.every(p=>{const ray=new T.Ray(new T.Vector3(p.x,250,p.z).applyMatrix4(castle.matrixWorld),down),old=previousIndex.sample(ray,0,700),now=index.sample(ray,0,700);return old&&now&&old.point.distanceTo(now.point)<.02;}):hit&&hit.slope>=minSlope&&probes.every(p=>{const h=sample(p.x,p.z);return h&&p.y-h.point.y<=.002&&p.y-h.point.y>=-.3;});
  if(unchanged){report.unchanged++;report.unchangedExistingNotRevalidated=(report.unchangedExistingNotRevalidated||0)+1;fixed.push({key,rows,matrix:rows[0].world});continue;}
  if(!Number.isFinite(sea(root.x,root.z))){report.failures.push({key,reason:'actual-sea-missing-at-affected-root'});continue;}pending.push({key,rows,root,beforeGap,candidates:[]});
 }
 const overlapCache=new WeakMap();const overlap=(rows,matrix,otherRows,otherMatrix)=>{let cache=overlapCache.get(matrix);if(!cache){cache=new WeakMap();overlapCache.set(matrix,cache);}if(cache.has(otherMatrix))return cache.get(otherMatrix);const value=rows.some(r=>otherRows.some(o=>overlapOrientedBoxes(r.mesh.geometry.boundingBox,matrix,o.mesh.geometry.boundingBox,otherMatrix)));cache.set(otherMatrix,value);return value;};
 for(const item of pending){const start={...report.rejections};
  for(const scaleFactor of[1,.9,.8].filter(v=>v>=minimumScale)){let kept=0;for(let radius=0;radius<=maxDistance&&kept<24;radius+=spacing){const n=radius?Math.max(8,Math.ceil(2*Math.PI*radius/spacing)):1;for(let a=0;a<n&&kept<24;a++){const point=item.root.clone().add(new T.Vector3(radius*Math.cos(a/n*2*Math.PI),0,radius*Math.sin(a/n*2*Math.PI))),candidate=check(item.rows,point,true,scaleFactor);if(!candidate)continue;if(item.candidates.some(c=>c.scaleFactor===scaleFactor&&Math.hypot(c.local[0]-candidate.local[0],c.local[2]-candidate.local[2])<2.5))continue;if(fixed.some(f=>overlap(item.rows,candidate.worldMatrix,f.rows,f.matrix))){report.rejections.trees++;continue;}candidate.distance=radius;item.candidates.push(candidate);kept++;}}}
  item.rejections=Object.fromEntries(Object.entries(report.rejections).map(([k,v])=>[k,v-start[k]]));
 }
 // Smallest domain first; all movable OLD positions are absent from fixed constraints.
 const order=[...pending].sort((a,b)=>a.candidates.length-b.candidates.length),assigned=new Map();let nodes=0,bestDepth=0,nodeLimit=5000,bestAssignment=new Map();
 const solve=depth=>{if(depth>bestDepth){bestDepth=depth;bestAssignment=new Map(assigned);}if(depth===order.length)return true;if(nodes>=nodeLimit)return false;nodes++;let chosen=null,options=null;for(const item of order){if(assigned.has(item))continue;const valid=item.candidates.filter(c=>![...assigned].some(([other,oc])=>overlap(item.rows,c.worldMatrix,other.rows,oc.worldMatrix)));if(!valid.length)return false;if(!options||valid.length<options.length){chosen=item;options=valid;}}for(const c of options){assigned.set(chosen,c);if(solve(depth+1))return true;assigned.delete(chosen);if(nodes>=nodeLimit)break;}return false;};
 let solved=solve(0);let compactFallback=false;if(!solved&&order.every(p=>p.candidates.length)){compactFallback=true;for(const item of order)item.candidates.sort((a,b)=>a.scaleFactor-b.scaleFactor||a.distance-b.distance);nodeLimit=10000;solved=solve(0);}report.assignment={method:'smallest-domain-first bounded joint backtracking; old movable positions excluded',nodes,budget:nodeLimit,bestDepth,compactFallback,solved,domains:pending.map(p=>({key:p.key,count:p.candidates.length,root:p.root.toArray(),originalScale:new T.Vector3().setFromMatrixScale(p.rows[0].world).toArray(),rejections:p.rejections,nearbyStableSites:p.candidates.slice(0,8).map(c=>({point:c.local,scaleFactor:c.scaleFactor,slope:c.slope}))}))};
 const selected=solved?assigned:bestAssignment;
 for(const item of pending){const found=selected.get(item),{key,rows,root,beforeGap}=item;if(!found){const info={key,root:root.toArray(),beforeGap,originalScale:new T.Vector3().setFromMatrixScale(rows[0].world).toArray(),rejections:item.rejections,candidateCount:item.candidates.length,parts:rows.map(r=>({uuid:r.mesh.uuid,name:r.mesh.name,index:r.index})),reason:item.candidates.length?'changed-cliff-landscape-no-joint-placement-within-budget':'changed-cliff-no-supported-clear-nearby-top'};if(retireUnplaced)report.retired.push(info);else report.failures.push(info);continue;}
  report.moves.push({key,parts:rows.map(r=>({uuid:r.mesh.uuid,name:r.mesh.name,index:r.index})),before:root.toArray(),beforeGap,after:found.local,scaleFactor:found.scaleFactor,normal:found.normal,originalScale:new T.Vector3().setFromMatrixScale(rows[0].world).toArray(),horizontalDisplacement:Math.hypot(found.local[0]-root.x,found.local[2]-root.z),supportPoint:found.supportPoint,slope:found.slope,footGaps:found.footGaps,surface:found.surface,face:found.face});for(const row of rows)changes.push({...row,next:row.mesh.matrixWorld.clone().invert().multiply(found.worldMatrix)});
 }
 const retiredIndices=new Map(parts.map(m=>[m,new Set(report.retired.flatMap(t=>t.parts.filter(p=>p.uuid===m.uuid).map(p=>p.index)))]));
 report.instanceRemap=parts.map(m=>{let next=0;return{uuid:m.uuid,name:m.name,before:m.count,after:m.count-retiredIndices.get(m).size,oldToNew:Array.from({length:m.count},(_,i)=>retiredIndices.get(m).has(i)?null:next++)};});
 const oldCanopyReport=forest.userData.canopyStudy,hadCanopyReport=Object.hasOwn(forest.userData,'canopyStudy'),study=castle.userData.mountainStudy,oldStudyCanopy=study?.canopy;
 const oldBindings=parts.map(mesh=>({mesh,had:Object.hasOwn(mesh.userData,'eastCliffPlacementBindings'),value:mesh.userData.eastCliffPlacementBindings}));
 const metadataSourcePlacements=oldCanopyReport?.placements??[],trunkMesh=parts.find(m=>m.name==='citadel-canopy-root-trunks');
 const canopyMetadataEpoch=JSON.stringify(oldCanopyReport??null);const metadataState={published:null};
 const bucketCounts=[0,0,0,0],authoredBucketIndices=metadataSourcePlacements.map(p=>Number.isInteger(p.variant)&&p.variant>=0&&p.variant<4?bucketCounts[p.variant]++:null);
 const publishMetadata=()=>{
  const rows=[],retiredRows=[],bindings=new Map(parts.map(m=>[m,[]])),usedSource=new Set(),sourceTrunk=forestEpochs.find(e=>e.mesh===trunkMesh),remap=report.instanceRemap.find(r=>r.uuid===trunkMesh?.uuid);
  for(let oldIndex=0;oldIndex<(sourceTrunk?.count??0);oldIndex++){
   const beforeMatrix=new T.Matrix4().fromArray(sourceTrunk.instances,oldIndex*16),beforeWorld=trunkMesh.matrixWorld.clone().multiply(beforeMatrix),hiddenBefore=Math.abs(beforeMatrix.determinant())<1e-12,beforePoint=new T.Vector3().setFromMatrixPosition(beforeWorld);
   let sourceIndex=oldIndex,source=metadataSourcePlacements[sourceIndex];
   const matches=row=>Array.isArray(row?.world)&&new T.Vector3().fromArray(row.world).distanceTo(beforePoint)<.01;
   if(!hiddenBefore&&!matches(source)){sourceIndex=metadataSourcePlacements.findIndex((r,i)=>!usedSource.has(i)&&matches(r));source=metadataSourcePlacements[sourceIndex];}
   if(source)usedSource.add(sourceIndex);
   const original=source?{...source}: {id:`runtime:${trunkMesh.uuid}:${oldIndex}`,kind:'unclassified',metadataOrigin:'actual-instance-without-authored-placement-match'};
   const nextIndex=remap.oldToNew[oldIndex],retired=report.retired.find(r=>r.parts.some(p=>p.uuid===trunkMesh.uuid&&p.index===oldIndex));
   if(nextIndex===null){retiredRows.push({...original,status:'retired-with-cliff',oldRootIndex:oldIndex,reason:retired?.reason});continue;}
   const localMatrix=new T.Matrix4();trunkMesh.getMatrixAt(nextIndex,localMatrix);const worldMatrix=trunkMesh.matrixWorld.clone().multiply(localMatrix),worldPoint=new T.Vector3().setFromMatrixPosition(worldMatrix),scale=new T.Vector3().setFromMatrixScale(worldMatrix),active=Math.abs(localMatrix.determinant())>=1e-12;
   const move=report.moves.find(r=>r.parts.some(p=>p.uuid===trunkMesh.uuid&&p.index===oldIndex)),localPoint=worldPoint.clone().applyMatrix4(inv),support=active?sample(localPoint.x,localPoint.z):null;
   let pair=active?[...groups.values()].find(rs=>rs.some(r=>r.mesh===trunkMesh&&r.index===oldIndex)):null;
   if(!active&&source&&metadataSourcePlacements.length===sourceTrunk.count){const name=source.variant===3?'citadel-canopy-cypress':`citadel-canopy-broadleaf-${source.variant}`,crown=parts.find(m=>m.name===name),oldCrownIndex=authoredBucketIndices[sourceIndex];if(crown&&Number.isInteger(oldCrownIndex)&&forestEpochs.find(e=>e.mesh===crown)?.count===bucketCounts[source.variant]){const cm=new T.Matrix4().fromArray(forestEpochs.find(e=>e.mesh===crown).instances,oldCrownIndex*16);if(Math.abs(cm.determinant())<1e-12)pair=[{mesh:trunkMesh,index:oldIndex},{mesh:crown,index:oldCrownIndex}];}}

   const instanceRefs=[];for(const part of pair??[{mesh:trunkMesh,index:oldIndex}]){const mapped=report.instanceRemap.find(r=>r.uuid===part.mesh.uuid).oldToNew[part.index];if(mapped===null)continue;const matrix=new T.Matrix4();part.mesh.getMatrixAt(mapped,matrix);const ref={meshUUID:part.mesh.uuid,meshName:part.mesh.name,oldIndex:part.index,index:mapped,matrix:matrix.toArray(),worldMatrix:part.mesh.matrixWorld.clone().multiply(matrix).toArray()};instanceRefs.push(ref);bindings.get(part.mesh).push({placementId:original.id,index:mapped,oldIndex:part.index,status:active?'active':'hidden-zero-scale'});}
   const row={...original,status:active?(move?'relocated':'retained'):'hidden-zero-scale',active,oldRootIndex:oldIndex,rootIndex:nextIndex,root:{meshUUID:trunkMesh.uuid,index:nextIndex,matrix:localMatrix.toArray(),worldMatrix:worldMatrix.toArray()},instances:instanceRefs};
   if(active){Object.assign(row,{world:worldPoint.toArray(),castleLocal:localPoint.toArray(),size:scale.x,scale:scale.toArray(),surface:support?.object??null,faceIndex:support?.face??null,sourcePoint:support? support.point.clone().applyMatrix4(castle.matrixWorld).toArray():null,slope:support?.slope??null,surfaceEpochs:report.surfaceEpochs.map(e=>({uuid:e.uuid,geometryUUID:e.geometryUUID,positionVersion:e.positionVersion}))});const footSupports=Array.from({length:6},(_,j)=>{const foot=new T.Vector3(Math.sin(j*Math.PI/3)*.12,0,Math.cos(j*Math.PI/3)*.12).applyMatrix4(worldMatrix).applyMatrix4(inv),h=sample(foot.x,foot.z);return h?{gap:foot.y-h.point.y,radius:h.point.clone().applyMatrix4(castle.matrixWorld).length()}:null;});if(footSupports.every(Boolean))Object.assign(row,{baseRadius:.12*scale.x,baseGapMin:Math.min(...footSupports.map(f=>f.gap)),baseGapMax:Math.max(...footSupports.map(f=>f.gap)),footGapCoordinate:'castle-local-Y',footMin:Math.min(...footSupports.map(f=>f.radius)),footMax:Math.max(...footSupports.map(f=>f.radius))});if(move)Object.assign(row,{baseGapMin:Math.min(...move.footGaps),baseGapMax:Math.max(...move.footGaps),footGapCoordinate:'castle-local-Y',scaleFactor:move.scaleFactor});const box=new T.Box3();for(const ref of instanceRefs){const mesh=parts.find(m=>m.uuid===ref.meshUUID);box.union(mesh.geometry.boundingBox.clone().applyMatrix4(new T.Matrix4().fromArray(ref.worldMatrix)));}row.bounds={min:box.min.toArray(),max:box.max.toArray()};}
   rows.push(row);
  }
  const next={...(oldCanopyReport??{}),placements:rows,accepted:rows.filter(r=>r.active).length,broadleaf:rows.filter(r=>r.active&&r.kind==='broadleaf').length,cypress:rows.filter(r=>r.active&&r.kind==='cypress').length,slotCount:rows.length,hiddenSlotCount:rows.filter(r=>!r.active).length,sourceAccepted:oldCanopyReport?.accepted??null,retiredPlacements:retiredRows,eastCliffRefresh:{version:report.version,sourceReportPreserved:true,instanceRemap:report.instanceRemap,surfaceEpochs:report.surfaceEpochs}};
  forest.userData.canopyStudy=next;if(study&&oldStudyCanopy===oldCanopyReport)study.canopy=next;for(const[mesh,value]of bindings)mesh.userData.eastCliffPlacementBindings=value;metadataState.published=next;report.metadata={placements:rows.length,active:next.accepted,hidden:next.hiddenSlotCount,retired:retiredRows.length,forestAndStudyAliasUpdated:!!study&&oldStudyCanopy===oldCanopyReport};
 };
 const restoreMetadata=()=>{if(hadCanopyReport)forest.userData.canopyStudy=oldCanopyReport;else delete forest.userData.canopyStudy;if(study&&oldStudyCanopy===oldCanopyReport)study.canopy=oldStudyCanopy;for(const r of oldBindings){if(r.had)r.mesh.userData.eastCliffPlacementBindings=r.value;else delete r.mesh.userData.eastCliffPlacementBindings;}};
 report.metadataRefreshRequired=['external forestCompanionsReport anchor indices must consume instanceRemap or rebuild companions','mountainStudy sampling/index, actual player/navigation collision caches remain caller-owned','cloud final-surface field and swept-clearance cache must be rebuilt by caller'];

 report.turfAudit=[];const turfChanges=[];
 for(const mesh of turfMeshes){const p=mesh.geometry.attributes.position,ix=mesh.geometry.index,mat=inv.clone().multiply(mesh.matrixWorld),cache=new Map(),kept=[],row={name:mesh.name,uuid:mesh.uuid,triangles:0,supported:0,unsupported:0,examples:[],maxGap:0};
  const support=point=>{const k=point.toArray().map(n=>n.toFixed(5)).join(',');if(cache.has(k))return cache.get(k);const hit=sample(point.x,point.z),gap=hit?point.y-hit.point.y:null;cache.set(k,gap);return gap;};
  for(let i=0;i<(ix?.count??p.count);i+=3){const pts=[0,1,2].map(j=>new T.Vector3().fromBufferAttribute(p,ix?ix.getX(i+j):i+j).applyMatrix4(mat));pts.push(pts[0].clone().add(pts[1]).add(pts[2]).multiplyScalar(1/3));const gaps=pts.map(support);row.triangles++;for(const gap of gaps)if(gap!==null)row.maxGap=Math.max(row.maxGap,Math.abs(gap));if(gaps.every(g=>g!==null&&Math.abs(g)<.02)){row.supported++;kept.push(...[0,1,2].map(j=>ix?ix.getX(i+j):i+j));}else{row.unsupported++;if(row.examples.length<16)row.examples.push({face:i/3,gaps,center:pts[3].toArray()});}}
  if(row.unsupported&&repairUnsupportedTurf&&kept.length){const geometry=new T.BufferGeometry();for(const[name,attribute]of Object.entries(mesh.geometry.attributes)){const values=new attribute.array.constructor(kept.length*attribute.itemSize);kept.forEach((id,i)=>{for(let j=0;j<attribute.itemSize;j++)values[i*attribute.itemSize+j]=attribute.array[id*attribute.itemSize+j];});geometry.setAttribute(name,new T.BufferAttribute(values,attribute.itemSize,attribute.normalized));}geometry.computeBoundingBox();geometry.computeBoundingSphere();geometry.userData={...mesh.geometry.userData,eastCliffSupportedCrop:true};turfChanges.push({mesh,original:mesh.geometry,geometry});row.rebuilt=true;row.removedUnsupportedTriangles=row.unsupported;row.method='retain exact supported old overlay triangles; remove only final-surface unsupported cliff crop, no movement';}
  report.turfAudit.push(row);if(row.unsupported&&!row.rebuilt)report.unsupported.push({name:mesh.name,uuid:mesh.uuid,reason:'actual-final-support-lost',triangles:row.unsupported,inspected:row.triangles});
 }
 report.treeCountAfter=report.treeCountBefore-report.retired.length;report.ready=report.failures.length===0&&report.unsupported.length===0;report.constraints={maxDistance,minimumScale,plantingBounds,spacing,minSlope,railClearance,protectedMeshes:protections.map(p=>({name:p.name,uuid:p.uuid})),railSamples:rail.length};report.limitations=['Candidate canopy crown/trunk pairs only; unsupported vegetation is explicitly inventoried.','World AABB broadphase, tree-to-tree oriented crown/trunk bounds SAT, and actual protected instance triangles; crown concavities are not exploited for packing.','Caller must handle other planting systems and cache version publication before full installation.'];
 const refresh=()=>{for(const m of new Set([...changes.map(r=>r.mesh),...parts.filter(m=>retiredIndices.get(m).size)])){m.instanceMatrix.needsUpdate=true;m.computeBoundingBox();m.computeBoundingSphere();}};let applied=false,disposed=false;
 report.buildMs=performance.now()-started;return{report,surfaceIndex:index,instanceBackups:forestEpochs.map(r=>({uuid:r.mesh.uuid,count:r.count,matrices:r.instances.slice(),colors:r.colors?.slice()??null})),apply(){if(disposed||!report.ready)return false;if(applied)return true;if(forest.userData.canopyStudy!==oldCanopyReport||JSON.stringify(oldCanopyReport??null)!==canopyMetadataEpoch||(study&&study.canopy!==oldStudyCanopy)){report.failures.push({reason:'canopy-metadata-changed-since-survey'});report.ready=false;return false;}const epochChanged=changedEpoch();if(epochChanged){report.failures.push({reason:'protected-or-forest-epoch-changed',object:epochChanged});report.ready=false;return false;}if(surfaces.some((m,i)=>m.geometry.uuid!==report.surfaceEpochs[i].geometryUUID||m.geometry.attributes.position.version!==report.surfaceEpochs[i].positionVersion||m.matrixWorld.elements.some((v,j)=>Math.abs(v-report.surfaceEpochs[i].matrixWorld[j])>1e-9))){report.failures.push({reason:'surface-changed-since-survey'});report.ready=false;return false;}for(const r of changes){const current=new T.Matrix4();r.mesh.getMatrixAt(r.index,current);if(signature(current)!==signature(r.matrix)){report.failures.push({reason:'instance-changed-since-survey'});report.ready=false;return false;}}for(const r of changes)r.mesh.setMatrixAt(r.index,r.next);for(const m of parts){const removed=retiredIndices.get(m);let out=0;for(let i=0;i<m.count;i++){if(removed.has(i))continue;if(i!==out){m.instanceMatrix.array.copyWithin(out*16,i*16,i*16+16);if(m.instanceColor)m.instanceColor.array.copyWithin(out*3,i*3,i*3+3);}out++;}m.count=out;if(m.instanceColor)m.instanceColor.needsUpdate=true;}for(const r of turfChanges)r.mesh.geometry=r.geometry;refresh();publishMetadata();applied=true;report.applied=true;return true;},dispose(){if(disposed)return;disposed=true;if(applied){for(const r of forestEpochs){r.mesh.instanceMatrix.array.set(r.instances);r.mesh.count=r.count;if(r.colors){r.mesh.instanceColor.array.set(r.colors);r.mesh.instanceColor.needsUpdate=true;}}for(const r of turfChanges)r.mesh.geometry=r.original;refresh();restoreMetadata();}for(const r of turfChanges)r.geometry.dispose();report.applied=false;report.restored=applied;}};
}
