import * as T from 'three';
import {createTargetCliffTransitRelease} from './targetCliffTransitRelease.js';
import {buildTargetCliffShoreBezier,createTargetCliffOffsetCurve} from './targetCliffShoreRoute.js';
/** User-painted chart, 2026-10-06. Approximate hand tracing, NOT measured track.
 * Original SVG calibration: pixelX=650+4*x, pixelY=365+4*z.
 * Attachment is scaled/cropped. Preserve broad intent, not marker kinks. */
export const USER_MARKED_TRANSIT={version:'user-marked-transit-1',uncertaintyMetres:2,svg:{origin:[650,365],pixelsPerMetre:4},railWestToEast:[[-140,32],[-116,55],[-90,64],[-67,45],[-40,40],[-27,29],[7,40],[35,47],[46,57],[35,70],[34,86],[42,96],[64,101],[88,97],[106,91],[131,92]],walkOldToNew:[[-31,11],[-28,20],[-20,27],[-8,31],[16,38],[49,45]]};
export function markedSvgToChart(pixel){if(!Array.isArray(pixel)||pixel.length!==2||!pixel.every(Number.isFinite))throw new TypeError('finite SVG pair required');return[(pixel[0]-650)/4,(pixel[1]-365)/4];}
/** Diagnostic candidate: exact current production endpoints retained. The drawn
 * far-west return is a separate unresolved segment, never silently approved. */
export function createTargetUserMarkedTransitPlan({sourceCurves,sampleTerrain,sampleSea,sampleWalkHeight=null,platforms=[],forbiddenPolygon=null,joins=null,handleLength=30,sourceIntervals=null}={}){
 if(!sourceCurves?.red||!sourceCurves?.blue||!sourceCurves?.center||typeof sampleTerrain!=='function'||typeof sampleSea!=='function')throw new TypeError('production three lanes and actual surface callbacks required');
 const previous=createTargetCliffTransitRelease({sourceCurves}),matrix=previous.castleMatrix;
 const nodes=joins??[{"local":[74,104],"direction":[-1,0],"handleIn":30,"handleOut":22,"handle":26},{"local":[32,87],"direction":[-0.6,-1],"handleIn":24,"handleOut":12,"handle":18},{"local":[22,58],"direction":[-0.5,-1],"handle":18},{"local":[-26,38],"direction":[-1,0.15],"handleIn":21,"handleOut":24,"handle":18},{"local":[-95,59],"direction":[-1,-0.2],"handle":29}];
 sourceIntervals??={red:[previous.specs.red.startU,.798],blue:[previous.specs.blue.startU,.800],center:[previous.specs.center.startU,.799]};
 const endpoints={};for(const lane of['red','blue','center']){const s={...previous.specs[lane]},c=sourceCurves[lane];if(sourceIntervals?.[lane]){[s.startU,s.endU]=sourceIntervals[lane];if(![s.startU,s.endU].every(Number.isFinite)||s.startU<0||s.endU>1||s.startU>=s.endU)throw new TypeError('ordered source interval required');}endpoints[lane]={startU:s.startU,endU:s.endU,startWorld:c.getPointAt(s.startU).toArray(),endWorld:c.getPointAt(s.endU).toArray(),startTangent:c.getTangentAt(s.startU).toArray(),endTangent:c.getTangentAt(s.endU).toArray()};}
 const result=buildTargetCliffShoreBezier({castleMatrix:matrix,...endpoints.red,joins:nodes,handleLength,sampleTerrain,sampleSea,platforms,forbiddenPolygon,minRadius:25,maxGrade:.04,bridgeLocalEndpoints:[[-28,32],[35,47]]});
 const curves={},specs={},laneAudit={};if(result.curve){curves.red=result.curve;for(const lane of['blue','center'])curves[lane]=createTargetCliffOffsetCurve({base:result.curve,offset:lane==='blue'?4.1:2.05,...endpoints[lane],blendLength:30}).curve;
 for(const lane of['red','blue','center']){const c=curves[lane],n=Math.ceil(c.getLength()),pts=Array.from({length:n+1},(_,i)=>c.getPointAt(i/n));let minRadius=Infinity,maxGrade=0;for(let i=0;i<=n;i++){const t=c.getTangentAt(i/n),v=Math.abs(t.dot(pts[i].clone().normalize()));maxGrade=Math.max(maxGrade,v/Math.sqrt(Math.max(1e-12,1-v*v)));if(i&&i<n){const a=pts[i-1],b=pts[i],d=pts[i+1],cross=b.clone().sub(a).cross(d.clone().sub(a)).length();if(cross>1e-9)minRadius=Math.min(minRadius,a.distanceTo(b)*b.distanceTo(d)*d.distanceTo(a)/(2*cross));}}
 laneAudit[lane]={minRadius,maxGrade,pass:minRadius>=25&&maxGrade<=.04};specs[lane]={id:USER_MARKED_TRANSIT.version+'-'+lane,startU:endpoints[lane].startU,endU:endpoints[lane].endU,replacementCurve:c,metadata:{clearanceVerified:false,routeStatus:'diagnostic-not-installed'}};}}
 const walkingConnection={version:USER_MARKED_TRANSIT.version,kind:'independent-short-bridge',pathXZ:USER_MARKED_TRANSIT.walkOldToNew.map(p=>p.slice()),path:[],unmeasured:[]};
 for(const[x,z]of walkingConnection.pathXZ){const raw=sampleWalkHeight?.(x,z),y=Number.isFinite(raw)?raw:Number.isFinite(raw?.height)?raw.height:null;if(y===null)walkingConnection.unmeasured.push([x,z]);else walkingConnection.path.push([x,y,z]);}if(walkingConnection.unmeasured.length)walkingConnection.path=null;
 return{castleMatrix:matrix,curves,specs,walkingConnection,report:{version:USER_MARKED_TRANSIT.version,accepted:false,installed:false,status:'diagnostic-only',marking:USER_MARKED_TRANSIT,joins:nodes,endpoints,laneAudit,rail:result.report,limitations:['Short walking bridge and railway are independent; no automatic vertical stacking.','Western splice extends to source u about .80; attachment leftmost x=-140 is not hit exactly.','Companion lanes receive curvature/grade audit, not full loaded-vehicle or triangle clearance.','No nominal walking heights; caller must supply surveyed public tread heights.','Two-metre tracing uncertainty; marker kinks are not design constraints.']}};
}
