import * as T from 'three';
const read=(f,x,z)=>{const v=f(x,z);return Number.isFinite(v)?v:Number.isFinite(v?.height)?v.height:null;};
/** Small shore-gallery gaps only. Existing final mesh must be sampled by caller.
 * No central segment, no source curve mutation, no automatic scene installation.
 * heights/field queries are castle-chart Y; track frames are WORLD radial. */
export function createTargetTransitLandwardContactField({release,sampleTerrain,sampleSea,platforms=[],step=2,maxGap=6,surveyLimit=36,walkwayHeight=6.9,vehicleTop=5.71,meshBoundaryMargin=2.4,protectedBoxes=[]}={}){
 if(!release?.castleMatrix?.isMatrix4||!release.segments?.center||typeof sampleTerrain!=='function'||typeof sampleSea!=='function'||![step,maxGap,surveyLimit,walkwayHeight,vehicleTop,meshBoundaryMargin].every(v=>Number.isFinite(v)&&v>0)||step>2||maxGap>6||surveyLimit>60||surveyLimit<maxGap)throw new TypeError('actual release, surface callbacks and bounded finite contact survey required');
 const inverse=release.castleMatrix.clone().invert(),rows=[],segments=[];
 const protectedPoint=(x,z)=>platforms.some(p=>Math.hypot((x-p.center[0])/p.radii[0],(z-p.center[1])/p.radii[1])<=1)||protectedBoxes.some(b=>x>=b.min[0]&&x<=b.max[0]&&z>=b.min[2]&&z<=b.max[2]);
 for(const shore of['oldShore','newShore']){
 const curve=release.segments.center[shore],n=Math.ceil(curve.getLength()/step),target=shore==='oldShore'?[-55,9]:[62,76],pier=shore==='oldShore'?.9:1.2,roofHalf=4.37+Math.max(pier,.6)/2+.35+.3,local=[];
 for(let i=0;i<=n;i++){
 const w=curve.getPointAt(i/n),t=curve.getTangentAt(i/n).normalize(),right=w.clone().normalize().cross(t).normalize(),up=t.clone().cross(right).normalize(),p=w.clone().applyMatrix4(inverse),ct=t.clone().transformDirection(inverse),inward=new T.Vector2(-ct.z,ct.x).normalize();if(inward.dot(new T.Vector2(target[0]-p.x,target[1]-p.z))<0)inward.negate();const rightChart=right.clone().transformDirection(inverse),side=Math.sign(inward.dot(new T.Vector2(rightChart.x,rightChart.z)))||1;
 const roof=w.clone().addScaledVector(right,side*roofHalf).addScaledVector(up,walkwayHeight-.18).applyMatrix4(inverse),walk=w.clone().addScaledVector(right,side*2.2).addScaledVector(up,walkwayHeight).applyMatrix4(inverse);
 let safe=-Infinity;for(const dx of[-4.37,4.37])for(const dz of[-3.49,3.49])for(const h of[-.6,vehicleTop]){const q=w.clone().addScaledVector(right,dx).addScaledVector(t,dz).addScaledVector(up,h).applyMatrix4(inverse);safe=Math.max(safe,(q.x-roof.x)*inward.x+(q.z-roof.z)*inward.y+meshBoundaryMargin);}
 const row={shore,i,u:i/n,center:p.toArray(),roofEdge:roof.toArray(),walkEdge:walk.toArray(),inward:inward.toArray(),roofHalfWidth:roofHalf,safeStart:Math.max(0,safe),enabled:false,gap:null,status:'no-contact-within-survey'};local.push(row);rows.push(row);
 for(let d=0;d<=surveyLimit+1e-6;d+=.25){const x=roof.x+inward.x*d,z=roof.z+inward.y*d,h=read(sampleTerrain,x,z),sea=read(sampleSea,x,z);if(h===null||sea===null)continue;if(h>=roof.y-2&&h>sea+1.5){row.gap=d;row.contact=[x,h,z];row.contactSea=sea;break;}}
 if(row.gap===null)continue;if(row.gap<.25){row.status='already-contact';continue;}if(row.gap>maxGap){row.status='gap-too-large';continue;}if(row.safeStart>=row.gap){row.status='loaded-envelope-exclusion';continue;}let blocked=false;for(let d=row.safeStart;d<row.gap;d+=.25)if(protectedPoint(roof.x+inward.x*d,roof.z+inward.y*d))blocked=true;if(blocked){row.status='protected-footprint';continue;}row.status='eligible-small-gap';row.enabled=true;
 }
 for(let i=1;i<local.length;i++){const a=local[i-1],b=local[i];if(!a.enabled||!b.enabled)continue;const dx=b.roofEdge[0]-a.roofEdge[0],dz=b.roofEdge[2]-a.roofEdge[2],len2=dx*dx+dz*dz;if(len2>1e-8)segments.push({a,b,dx,dz,len2});}
 }
 const report={version:'transit-landward-small-contact-1',accepted:false,installed:false,maxGap,step,walkwayHeight,vehicleTop,meshBoundaryMargin,rows,segments:segments.length,counts:{},changedQueries:0,maxRaise:0,limitations:['Contact requires actual final surface within 2m vertically of gallery rear edge, not just a distant seabed.','Gap is measured in castle-chart horizontal metres from structural roof rear edge; not pixel estimation or registered public walk edge.','Only successive eligible shore stations form a field; central bay has no stations.','Finite whole loaded envelope exclusion must be rechecked after remeshing.']};for(const row of rows)report.counts[row.status]=(report.counts[row.status]??0)+1;
 function height(x,z,original,sea){if(![x,z,original,sea].every(Number.isFinite))throw new TypeError('finite field query required');if(protectedPoint(x,z))return original;let out=original;for(const s of segments){const u=((x-s.a.roofEdge[0])*s.dx+(z-s.a.roofEdge[2])*s.dz)/s.len2;if(u<0||u>1)continue;const ix=T.MathUtils.lerp(s.a.inward[0],s.b.inward[0],u),iz=T.MathUtils.lerp(s.a.inward[1],s.b.inward[1],u),d=((x-s.a.roofEdge[0]-u*s.dx)*ix+(z-s.a.roofEdge[2]-u*s.dz)*iz)/Math.hypot(ix,iz),start=T.MathUtils.lerp(s.a.safeStart,s.b.safeStart,u),end=T.MathUtils.lerp(s.a.gap,s.b.gap,u);if(d<start||d>end)continue;const a=T.MathUtils.lerp(s.a.roofEdge[1],s.b.roofEdge[1],u),b=T.MathUtils.lerp(s.a.contact[1],s.b.contact[1],u),h=T.MathUtils.lerp(a,b,T.MathUtils.smoothstep((d-start)/(end-start),0,1));if(h>sea+1.5)out=Math.max(out,h);}
 if(out>original){report.changedQueries++;report.maxRaise=Math.max(report.maxRaise,out-original);}return out;}
 return{height,report,rows};
}
