import * as T from 'three';
import {createCastleOceanSampler} from './newCityRidgeCandidate.js';
const finite=p=>Array.isArray(p)&&p.length===3&&p.every(Number.isFinite);
function polygonGap(x,z,polygon){if(!polygon?.length)return Infinity;let inside=false,d=Infinity;for(let i=0,j=polygon.length-1;i<polygon.length;j=i++){const a=polygon[j],b=polygon[i];if((a[1]>z)!==(b[1]>z)&&x<(b[0]-a[0])*(z-a[1])/(b[1]-a[1])+a[0])inside=!inside;const dx=b[0]-a[0],dz=b[1]-a[1],t=T.MathUtils.clamp(((x-a[0])*dx+(z-a[1])*dz)/(dx*dx+dz*dz),0,1);d=Math.min(d,Math.hypot(x-a[0]-t*dx,z-a[1]-t*dz));}return inside?-d:d;}
function simplifyLine(points,tolerance){if(points.length<=2)return points;const a=points[0],b=points.at(-1),d=b.clone().sub(a),len=d.lengthSq();let best=0,k=-1;for(let i=1;i<points.length-1;i++){const t=T.MathUtils.clamp(points[i].clone().sub(a).dot(d)/len,0,1),distance=points[i].distanceTo(a.clone().addScaledVector(d,t));if(distance>best){best=distance;k=i;}}return best>tolerance?[...simplifyLine(points.slice(0,k+1),tolerance).slice(0,-1),...simplifyLine(points.slice(k),tolerance)]:[a,b];}
/** Finite A* multi-leg shore search, then real curve diagnostics. No installation.
 * Samplers use final castle-local surfaces, not an implicit spherical land fallback.
 * Mandatory sea-side waypoints must be supplied for the full plaza bypass. */
export function searchTargetCliffShoreRoute({castleMatrix,startWorld,endWorld,startTangent=null,endTangent=null,sampleTerrain,sampleSea,waypoints=[],forbiddenPolygon=null,bounds={minX:-140,maxX:130,minZ:-35,maxZ:120},gridStep=4,radii=null,minRadius=25,maxGrade=.04,maxCliffDistance=24,tangentTolerance=Math.PI/360,maxExpanded=22000}={}){
 if(!castleMatrix||!finite(startWorld)||!finite(endWorld)||typeof sampleTerrain!=='function'||typeof sampleSea!=='function')throw new TypeError('matrix, true world endpoints and final samplers required');
 const matrix=castleMatrix.isMatrix4?castleMatrix.clone():new T.Matrix4().fromArray(castleMatrix);if(!matrix.elements.every(Number.isFinite)||Math.abs(matrix.determinant())<1e-12)throw new TypeError('finite invertible matrix required');
 if(![gridStep,minRadius,maxGrade,maxCliffDistance,maxExpanded].every(v=>Number.isFinite(v)&&v>0)||waypoints.some(p=>p.length!==2||!p.every(Number.isFinite)))throw new TypeError('finite positive search settings required');
 const inv=matrix.clone().invert(),start=new T.Vector3(...startWorld),end=new T.Vector3(...endWorld),sl=start.clone().applyMatrix4(inv),el=end.clone().applyMatrix4(inv),halfWidth=4.37,halfLength=3.49;
 const sample=(fn,x,z)=>{const a=fn(x,z),h=typeof a==='number'?a:a?.height;return Number.isFinite(h)?h:null;};
 const trials=[],candidates=[],radiusChoices=radii??[start.length(),(start.length()+end.length())/2,end.length()];
 const nx=Math.ceil((bounds.maxX-bounds.minX)/gridStep),nz=Math.ceil((bounds.maxZ-bounds.minZ)/gridStep),id=(i,j)=>j*(nx+1)+i,coords=k=>[bounds.minX+(k%(nx+1))*gridStep,bounds.minZ+Math.floor(k/(nx+1))*gridStep],nearest=(x,z)=>id(T.MathUtils.clamp(Math.round((x-bounds.minX)/gridStep),0,nx),T.MathUtils.clamp(Math.round((z-bounds.minZ)/gridStep),0,nz));
 const cliffCache=new Map();function cliffDistance(x,z){const key=x+','+z;if(cliffCache.has(key))return cliffCache.get(key);let distance=Infinity;for(let r=0;r<=maxCliffDistance;r+=4){for(let a=0;a<12;a++){const xx=x+r*Math.cos(a*Math.PI/6),zz=z+r*Math.sin(a*Math.PI/6),s=sample(sampleSea,xx,zz),h=sample(sampleTerrain,xx,zz);if(s!==null&&h!==null&&h>s+1.5){distance=r;break;}}if(Number.isFinite(distance))break;}cliffCache.set(key,distance);return distance;}
 for(const radius of [...new Set(radiusChoices)]){
  const shell=createCastleOceanSampler(matrix,radius),cache=new Map(),rejections={terrain:0,sea:0,plaza:0,farFromCliff:0};
  function valid(k){if(cache.has(k))return cache.get(k);const[x,z]=coords(k),y=shell(x,z);let reason=null;if(y===null)reason='sea';else if(polygonGap(x,z,forbiddenPolygon)<halfWidth+.6)reason='plaza';else{const p=new T.Vector3(x,y,z).applyMatrix4(matrix),up=p.clone().normalize();for(let a=0;a<8&&!reason;a++){const xx=x+5.6*Math.cos(a*Math.PI/4),zz=z+5.6*Math.sin(a*Math.PI/4),yy=shell(xx,zz);if(yy===null){reason='sea';break;}const bottom=new T.Vector3(xx,yy,zz).applyMatrix4(matrix).addScaledVector(up,-.6).applyMatrix4(inv),s=sample(sampleSea,bottom.x,bottom.z),h=sample(sampleTerrain,bottom.x,bottom.z);if(s===null||s>bottom.y)reason='sea';else if(h!==null&&h>bottom.y-.08)reason='terrain';}if(!reason&&cliffDistance(x,z)>maxCliffDistance)reason='farFromCliff';}
   if(reason)rejections[reason]++;cache.set(k,!reason);return !reason;
  }
  function nearestValid(x,z){const c=nearest(x,z),ci=c%(nx+1),cj=Math.floor(c/(nx+1)),options=[];for(let j=Math.max(0,cj-4);j<=Math.min(nz,cj+4);j++)for(let i=Math.max(0,ci-4);i<=Math.min(nx,ci+4);i++){const k=id(i,j),p=coords(k);options.push({k,d:Math.hypot(x-p[0],z-p[1])});}options.sort((a,b)=>a.d-b.d);return options.find(p=>valid(p.k))?.k;}
  const anchors=[[sl.x,sl.z],...waypoints,[el.x,el.z]],snapped=anchors.map(p=>nearestValid(...p));let expanded=0,path=[],failure=null;
  if(snapped.some(k=>k===undefined))failure='missing-safe-waypoint';
  function solve(a,b){const open=[a],scores=new Map([[a,0]]),parents=new Map(),closed=new Set(),bp=coords(b);while(open.length&&expanded<maxExpanded){let best=0,bestF=Infinity;for(let i=0;i<open.length;i++){const p=coords(open[i]),f=scores.get(open[i])+Math.hypot(p[0]-bp[0],p[1]-bp[1]);if(f<bestF){bestF=f;best=i;}}const k=open.splice(best,1)[0];if(k===b){const p=[k];while(parents.has(p.at(-1)))p.push(parents.get(p.at(-1)));return p.reverse();}if(closed.has(k))continue;closed.add(k);expanded++;const i=k%(nx+1),j=Math.floor(k/(nx+1));for(let dz=-1;dz<=1;dz++)for(let dx=-1;dx<=1;dx++){if(!dx&&!dz||i+dx<0||i+dx>nx||j+dz<0||j+dz>nz)continue;const n=id(i+dx,j+dz);if(closed.has(n)||!valid(n))continue;if(dx&&dz&&(!valid(id(i+dx,j))||!valid(id(i,j+dz))))continue;const p=coords(n),g=scores.get(k)+gridStep*Math.hypot(dx,dz)+.015*cliffDistance(...p);if(g<(scores.get(n)??Infinity)){scores.set(n,g);parents.set(n,k);open.push(n);}}}return null;}
  if(!failure)for(let i=1;i<snapped.length;i++){const segment=solve(snapped[i-1],snapped[i]);if(!segment){failure='no-safe-multi-leg-path';break;}path.push(...segment.slice(i===1?0:1));}
  const trial={radius,expanded,rejections,failure,snapped:snapped.map(k=>k===undefined?null:coords(k)),gridPath:path.map(coords),variants:[]};trials.push(trial);if(failure)continue;
  for(const stride of[3,5,7,-4,-8]){
   let points=path.filter((_,i)=>i===0||i===path.length-1||(stride<0||i%stride===0)).map(k=>{const[x,z]=coords(k);return new T.Vector3(x,shell(x,z),z).applyMatrix4(matrix);});if(stride<0)points=simplifyLine(points,-stride);if(points[0].distanceTo(start)>1e-6)points.unshift(start.clone());else points[0].copy(start);if(points.at(-1).distanceTo(end)>1e-6)points.push(end.clone());else points.at(-1).copy(end);
   // Remove snapped-node reversals near exact endpoints, then impose actual
   // endpoint tangent handles. These may still collide and are fully audited.
   points=points.filter((p,i)=>i===0||i===points.length-1||(p.distanceTo(start)>18&&p.distanceTo(end)>18));
   if(startTangent)points.splice(1,0,start.clone().addScaledVector(new T.Vector3(...startTangent).normalize(),14));
   if(endTangent)points.splice(points.length-1,0,end.clone().addScaledVector(new T.Vector3(...endTangent).normalize(),-14));
   const spline=new T.CatmullRomCurve3(points,false,'centripetal');const rs=start.length(),re=end.length();
   function radiusDerivative(t,desired,r){if(!desired)return re-rs;const q=spline.getPointAt(t),e=1e-5,d=spline.getPointAt(Math.min(1,t+e)).sub(spline.getPointAt(Math.max(0,t-e))).divideScalar(t===0||t===1?e:2*e),rad=q.clone().normalize(),tangentSpeed=d.addScaledVector(rad,-d.dot(rad)).length()*r/q.length(),v=new T.Vector3(...desired).normalize().dot(rad);return tangentSpeed*v/Math.sqrt(Math.max(1e-12,1-v*v));}
   const d0=radiusDerivative(0,startTangent,rs),d1=radiusDerivative(1,endTangent,re);
   class ShoreCurve extends T.Curve{getPoint(t,target=new T.Vector3()){const h=(2*t*t*t-3*t*t+1)*rs+(t*t*t-2*t*t+t)*d0+(-2*t*t*t+3*t*t)*re+(t*t*t-t*t)*d1;return target.copy(spline.getPointAt(t)).normalize().multiplyScalar(h);}}const curve=new ShoreCurve(),length=curve.getLength(),count=Math.ceil(length),samples=[];let soil=0,wet=0,plaza=0,far=0,grade=0,minimumRadius=Infinity;
   for(let i=0;i<=count;i++){const beforeSoil=soil,beforeWet=wet;const u=i/count,w=curve.getPointAt(u),t=curve.getTangentAt(u),radial=w.clone().normalize(),right=radial.clone().cross(t).normalize(),up=t.clone().cross(right).normalize(),local=w.clone().applyMatrix4(inv);const v=Math.abs(t.dot(radial));grade=Math.max(grade,v/Math.sqrt(Math.max(1e-12,1-v*v)));if(polygonGap(local.x,local.z,forbiddenPolygon)<halfWidth+.6)plaza++;if(cliffDistance(local.x,local.z)>maxCliffDistance)far++;
    for(const dx of[-halfWidth,0,halfWidth])for(const dz of[-halfLength,0,halfLength]){const p=w.clone().addScaledVector(right,dx).addScaledVector(t,dz).addScaledVector(up,-.6).applyMatrix4(inv),s=sample(sampleSea,p.x,p.z),h=sample(sampleTerrain,p.x,p.z);if(s===null||s>p.y)wet++;if(h!==null&&h>p.y-.08)soil++;}samples.push({world:w.toArray(),local:local.toArray(),soil:soil-beforeSoil,wet:wet-beforeWet});}
   for(let i=1;i<samples.length-1;i++){const a=new T.Vector3(...samples[i-1].world),b=new T.Vector3(...samples[i].world),c=new T.Vector3(...samples[i+1].world),cross=b.clone().sub(a).cross(c.clone().sub(a)).length();if(cross>1e-9)minimumRadius=Math.min(minimumRadius,a.distanceTo(b)*b.distanceTo(c)*c.distanceTo(a)/(2*cross));}
   const startAngle=startTangent?curve.getTangent(0).angleTo(new T.Vector3(...startTangent)):null,endAngle=endTangent?curve.getTangent(1).angleTo(new T.Vector3(...endTangent)):null,clear=soil===0&&wet===0&&plaza===0&&far===0&&grade<=maxGrade&&minimumRadius>=minRadius&&startAngle!==null&&endAngle!==null&&startAngle<=tangentTolerance&&endAngle<=tangentTolerance;
   const audit={stride,length,samples,soil,wet,plaza,far,maximumGrade:grade,minimumRadius:Number.isFinite(minimumRadius)?minimumRadius:null,startAngle,endAngle,clear};trial.variants.push(audit);if(clear)candidates.push({curve,audit});
  }
 }
 return {candidate:candidates.sort((a,b)=>a.audit.length-b.audit.length)[0]??null,report:{version:'target-cliff-shore-search-1',accepted:false,installed:false,status:candidates.length?'finite-candidate-needs-bridge-and-runtime-audit':'failed',limits:{minRadius,maxGrade,maxCliffDistance,requiredWidth:8.74,gridStep,tangentTolerance},trials,limitations:['Finite 9-point full-width/length underbody test, not continuous triangle CCD; roof/side overhangs are not represented by height samplers.','Cliff proximity is a finite dry-surface ring search, not exact Euclidean mesh distance.','No main scene, global railway, terrain, actor or bridge mutation.','Endpoint tangents and smoothed full-plaza bypass are mandatory before a candidate can pass.']}};
}

/** Explicit tangent-continuous long Bezier construction. Soil conflicts are
 * exported as possible cliff-cut samples, never silently accepted. */
export function buildTargetCliffShoreBezier({castleMatrix,startWorld,endWorld,startTangent,endTangent,joins=[],handleLength=30,sampleTerrain,sampleSea,seaRadiusAt=null,bridgePath=null,bridgeHalfWidth=2.2,bridgeLocalEndpoints=null,platforms=[],forbiddenPolygon=null,minRadius=25,maxGrade=.04,maxCliffDistance=24}={}){
 if(!castleMatrix||![startWorld,endWorld,startTangent,endTangent].every(finite)||typeof sampleTerrain!=='function'||typeof sampleSea!=='function'||![handleLength,minRadius,maxGrade,maxCliffDistance].every(v=>Number.isFinite(v)&&v>0)||joins.some(j=>!Array.isArray(j.local)||j.local.length!==2||!j.local.every(Number.isFinite)||!Array.isArray(j.direction)||j.direction.length!==2||!j.direction.every(Number.isFinite)||Math.hypot(...j.direction)<1e-8))throw new TypeError('finite curve inputs and actual surface callbacks required');
 const m=castleMatrix.isMatrix4?castleMatrix.clone():new T.Matrix4().fromArray(castleMatrix),inv=m.clone().invert(),start=new T.Vector3(...startWorld),end=new T.Vector3(...endWorld),shell=createCastleOceanSampler(m,(start.length()+end.length())/2),nodes=[{p:start,t:new T.Vector3(...startTangent).normalize(),h:handleLength}];
 if(!m.elements.every(Number.isFinite)||Math.abs(m.determinant())<1e-12||Math.hypot(...startTangent)<1e-8||Math.hypot(...endTangent)<1e-8)throw new TypeError('finite invertible chart and nonzero tangents required');
 for(const j of joins){const y=shell(...j.local);if(y===null)return{curve:null,report:{status:'failed-join-outside-chart',accepted:false,join:j}};const p=new T.Vector3(j.local[0],y,j.local[1]).applyMatrix4(m),nextY=shell(j.local[0]+j.direction[0]*.001,j.local[1]+j.direction[1]*.001),t=new T.Vector3(j.local[0]+j.direction[0]*.001,nextY,j.local[1]+j.direction[1]*.001).applyMatrix4(m).sub(p).normalize();nodes.push({p,t,h:j.handle??handleLength,hIn:j.handleIn,hOut:j.handleOut});}nodes.push({p:end,t:new T.Vector3(...endTangent).normalize(),h:handleLength});
 const raw=new T.CurvePath(),segments=[];for(let i=1;i<nodes.length;i++){const a=nodes[i-1],b=nodes[i],points=[a.p,a.p.clone().addScaledVector(a.t,a.hOut??a.h),b.p.clone().addScaledVector(b.t,-(b.hIn??b.h)),b.p];raw.add(new T.CubicBezierCurve3(...points));segments.push(points.map(p=>p.toArray()));}
 const rs=start.length(),re=end.length(),derivative=(t,d,r)=>{const e=1e-5,p=raw.getPointAt(t),v=raw.getPointAt(Math.min(1,t+e)).sub(raw.getPointAt(Math.max(0,t-e))).divideScalar(e),rad=p.clone().normalize(),along=new T.Vector3(...d).dot(rad),speed=v.addScaledVector(rad,-v.dot(rad)).length()*r/p.length();return speed*along/Math.sqrt(Math.max(1e-12,1-along*along));},d0=derivative(0,startTangent,rs),d1=derivative(1,endTangent,re);
 class Curve extends T.Curve{getPoint(t,target=new T.Vector3()){const r=(2*t*t*t-3*t*t+1)*rs+(t*t*t-2*t*t+t)*d0+(-2*t*t*t+3*t*t)*re+(t*t*t-t*t)*d1;return target.copy(raw.getPointAt(t)).normalize().multiplyScalar(r);}}const curve=new Curve(),length=curve.getLength(),n=Math.ceil(length),samples=[],cuts=[];let minR=Infinity,maxSlope=0,wet=0,plaza=0,far=0,protectedHits=0;
 const bridgeIndices=bridgeLocalEndpoints?.map(e=>{let best=Infinity,index=-1;for(let i=0;i<=n;i++){const p=curve.getPointAt(i/n).applyMatrix4(inv),d=Math.hypot(p.x-e[0],p.z-e[1]);if(d<best){best=d;index=i;}}return index;});
 const read=(f,x,z)=>{const s=f(x,z);return Number.isFinite(s)?s:Number.isFinite(s?.height)?s.height:null;};
 for(let i=0;i<=n;i++){const u=i/n,w=curve.getPointAt(u),t=curve.getTangentAt(u),rad=w.clone().normalize(),right=rad.clone().cross(t).normalize(),up=t.clone().cross(right).normalize(),p=w.clone().applyMatrix4(inv),v=Math.abs(t.dot(rad));maxSlope=Math.max(maxSlope,v/Math.sqrt(Math.max(1e-12,1-v*v)));if(polygonGap(p.x,p.z,forbiddenPolygon)<4.97)plaza++;
  let near=false;for(let r=0;r<=maxCliffDistance&&!near;r+=4)for(let a=0;a<12;a++){const x=p.x+r*Math.cos(a*Math.PI/6),z=p.z+r*Math.sin(a*Math.PI/6),h=read(sampleTerrain,x,z),s=read(sampleSea,x,z);if(h!==null&&s!==null&&h>s+1.5){near=true;break;}}if(!near){let bridgeDistance=Infinity;if(bridgePath)for(let k=1;k<bridgePath.length;k++){const a=bridgePath[k-1],b=bridgePath[k],dx=b[0]-a[0],dz=b[2]-a[2],u=T.MathUtils.clamp(((p.x-a[0])*dx+(p.z-a[2])*dz)/(dx*dx+dz*dz),0,1);bridgeDistance=Math.min(bridgeDistance,Math.hypot(p.x-a[0]-u*dx,p.z-a[2]-u*dz));}if(bridgeDistance>bridgeHalfWidth&&!(bridgeIndices&&i>=Math.min(...bridgeIndices)&&i<=Math.max(...bridgeIndices)))far++;}
  for(const dx of[-4.37,0,4.37])for(const dz of[-3.49,0,3.49]){const qWorld=w.clone().addScaledVector(right,dx).addScaledVector(t,dz).addScaledVector(up,-.6),q=qWorld.clone().applyMatrix4(inv),h=read(sampleTerrain,q.x,q.z),s=read(sampleSea,q.x,q.z);const oceanRadius=seaRadiusAt?.(qWorld.clone());if(oceanRadius!==undefined&&oceanRadius!==null){if(!Number.isFinite(oceanRadius)||qWorld.length()<oceanRadius)wet++;}else if(s===null||s>q.y)wet++;
   if(h!==null&&h>q.y-.08){const protectedCore=platforms.some(b=>Math.hypot((q.x-b.center[0])/b.radii[0],(q.z-b.center[1])/b.radii[1])<=.85)||polygonGap(q.x,q.z,forbiddenPolygon)<2.4;if(protectedCore)protectedHits++;cuts.push({x:q.x,z:q.z,before:h,cap:q.y-.08,drop:h-q.y+.08,protectedCore});}}
  samples.push({world:w.toArray(),local:p.toArray()});
 }
 for(let i=1;i<samples.length-1;i++){const a=new T.Vector3(...samples[i-1].world),b=new T.Vector3(...samples[i].world),c=new T.Vector3(...samples[i+1].world),cross=b.clone().sub(a).cross(c.clone().sub(a)).length();if(cross>1e-9)minR=Math.min(minR,a.distanceTo(b)*b.distanceTo(c)*c.distanceTo(a)/(2*cross));}
 const startAngle=curve.getTangent(0).angleTo(new T.Vector3(...startTangent)),endAngle=curve.getTangent(1).angleTo(new T.Vector3(...endTangent)),shapePass=minR>=minRadius&&maxSlope<=maxGrade&&startAngle<=Math.PI/360&&endAngle<=Math.PI/360&&plaza===0;
 return{curve,report:{version:'target-cliff-shore-bezier-1',accepted:false,installed:false,status:shapePass&&!wet&&!far&&!cuts.length?'finite-candidate-needs-runtime':shapePass&&!wet&&!far&&!protectedHits?'shape-candidate-needs-cliff-cut':'failed',shapePass,length,bridgeIndices,minimumRadius:minR,maximumGrade:maxSlope,startAngle,endAngle,wet,plaza,far,protectedHits,cuts,samples,serialization:{type:'world-bezier-chain-radial-hermite',segments,radius:[rs,re],radiusDerivatives:[d0,d1]},limits:{minRadius,maxGrade,maxCliffDistance,tangentTolerance:Math.PI/360},limitations:['Cut samples are diagnostic envelope points, not an applied cliff polygon or permission to remove protected city support.','Bridge/ships/head-clearance and all future cargo still need actual mesh checks.','World sea radius, when provided, is caller-owned source data; no nominal sea fallback.']}};
}

/** Replay one diagnosed world curve; this does not grant installation approval. */
export function replayTargetCliffShoreCurve(serialization){
 if(serialization?.type!=='world-bezier-chain-radial-hermite'||!serialization.segments?.length||serialization.segments.some(s=>s.length!==4||!s.every(finite))||!serialization.radius?.every(Number.isFinite)||!serialization.radiusDerivatives?.every(Number.isFinite))throw new TypeError('finite serialized shore curve required');
 const raw=new T.CurvePath();for(const points of serialization.segments)raw.add(new T.CubicBezierCurve3(...points.map(p=>new T.Vector3(...p))));const[rs,re]=serialization.radius,[d0,d1]=serialization.radiusDerivatives;
 class Replay extends T.Curve{getPoint(t,target=new T.Vector3()){const r=(2*t*t*t-3*t*t+1)*rs+(t*t*t-2*t*t+t)*d0+(-2*t*t*t+3*t*t)*re+(t*t*t-t*t)*d1;return target.copy(raw.getPointAt(t)).normalize().multiplyScalar(r);}}return new Replay();
}
/** Companion line with explicit end position AND derivative corrections. Actual
 * source-lane endpoints are required. Full clearance/curvature must be rechecked. */
export function createTargetCliffOffsetCurve({base,offset,startWorld,endWorld,startTangent,endTangent,blendLength=30}={}){
 if(!base?.getPointAt||!Number.isFinite(offset)||![startWorld,endWorld,startTangent,endTangent].every(finite)||!Number.isFinite(blendLength)||blendLength<=0)throw new TypeError('base, finite offset and real source-lane endpoints required');
 const length=base.getLength(),blend=Math.min(.25,blendLength/length),raw=t=>{const p=base.getPointAt(t),tan=base.getTangentAt(t),right=p.clone().normalize().cross(tan).normalize();return p.addScaledVector(right,offset);},epsilon=1e-5;
 const corrections=[0,1].map((t,i)=>{const p=raw(t),d=raw(Math.min(1,t+epsilon)).sub(raw(Math.max(0,t-epsilon))).divideScalar(epsilon),desired=new T.Vector3(...(i?endTangent:startTangent)).normalize().multiplyScalar(d.length());return{position:new T.Vector3(...(i?endWorld:startWorld)).sub(p),derivative:desired.sub(d)};});
 class Offset extends T.Curve{getPoint(t,target=new T.Vector3()){target.copy(raw(t));for(let i=0;i<2;i++){const v=i?(1-t)/blend:t/blend;if(v>1)continue;const c=corrections[i],h00=2*v*v*v-3*v*v+1,h10=v*v*v-2*v*v+v;target.addScaledVector(c.position,h00).addScaledVector(c.derivative,h10*blend*(i?-1:1));}return target;}}
 return{curve:new Offset(),report:{offset,blendLength:blend*length,corrections:corrections.map(c=>({position:c.position.toArray(),derivative:c.derivative.toArray()})),accepted:false,clearanceVerified:false}};
}
