import * as T from 'three';
import {createTargetUserMarkedTransitPlan} from './targetUserMarkedTransitPlan.js';
import {createTargetCliffTransitRelease} from './targetCliffTransitRelease.js';
function slice(curve,range){class Part extends T.Curve{getPoint(t,out=new T.Vector3()){return out.copy(curve.getPointAt(range[0]+t*(range[1]-range[0])));}}return new Part();}
function near(curve,point,inverse){let best=Infinity,u=0;for(let i=0;i<=1200;i++){const q=curve.getPointAt(i/1200).applyMatrix4(inverse),d=Math.hypot(q.x-point[0],q.z-point[1]);if(d<best){best=d;u=i/1200;}}return u;}
function clip(poly,axis,value,less){const out=[];for(let i=0;i<poly.length;i++){const a=poly[i],b=poly[(i+1)%poly.length],ia=less?a[axis]<=value:a[axis]>=value,ib=less?b[axis]<=value:b[axis]>=value;if(ia)out.push(a);if(ia!==ib){const t=(value-a[axis])/(b[axis]-a[axis]);out.push(a.map((x,j)=>x+t*(b[j]-x)));}}return out;}
/** Alternative release; never installs itself. Cuts are explicit landward-edge
 * to exterior-sea polygons, not centre-line slots. Requires a regenerated actual
 * terrain mesh and complete loaded-vehicle audit before caller can install. */
export function createTargetUserMarkedTransitRelease(options={}){
 const plan=createTargetUserMarkedTransitPlan(options),old=createTargetCliffTransitRelease({sourceCurves:options.sourceCurves}),matrix=plan.castleMatrix,inv=matrix.clone().invert(),ranges={},segments={},cuts=[],cutStations=[];
 for(const lane of['red','blue','center']){const c=plan.curves[lane];if(!c)throw new Error('marked curve unavailable');const a=near(c,[22,58],inv),b=near(c,[-26,38],inv);ranges[lane]={newShore:[0,a],central:[a,b],oldShore:[b,1]};segments[lane]=Object.fromEntries(Object.entries(ranges[lane]).map(([k,r])=>[k,slice(c,r)]));segments[lane].retainedOld=slice(options.sourceCurves[lane],[plan.specs[lane].endU,old.report.retainedOldSourceIntervals[lane][1]]);}
 for(const name of['newShore','oldShore']){const curve=segments.center[name],target=name==='newShore'?[62,76]:[-55,9],n=Math.ceil(curve.getLength()/2.5),rows=[];
 for(let i=0;i<=n;i++){const w=curve.getPointAt(i/n),t=curve.getTangentAt(i/n).normalize(),right=w.clone().normalize().cross(t).normalize(),up=t.clone().cross(right).normalize(),p=w.clone().applyMatrix4(inv),ct=t.clone().transformDirection(inv),normal=new T.Vector2(-ct.z,ct.x).normalize();if(normal.dot(new T.Vector2(target[0]-p.x,target[1]-p.z))<0)normal.negate();let support=-Infinity;for(const dx of[-4.37,4.37])for(const dz of[-3.49,3.49])for(const h of[-.6,5.71]){const q=w.clone().addScaledVector(right,dx).addScaledVector(t,dz).addScaledVector(up,h).applyMatrix4(inv);support=Math.max(support,(q.x-p.x)*normal.x+(q.z-p.z)*normal.y);}const edge=[p.x+normal.x*(support+2.5),p.z+normal.y*(support+2.5)];rows.push({edge,seaward:[edge[0]-normal.x*80,edge[1]-normal.y*80],center:p.toArray()});}
 cutStations.push({name,rows});for(let i=1;i<rows.length;i++){const a=rows[i-1],b=rows[i];let polygon=[a.edge,b.edge,b.seaward,a.seaward];for(const[axis,value,less]of[[0,-143,false],[0,143,true],[1,-72,false],[1,107,true]])polygon=clip(polygon,axis,value,less);if(polygon.length<3)continue;const dx=b.edge[0]-a.edge[0],dz=b.edge[1]-a.edge[1],seaSide=Math.sign(dx*(a.seaward[1]-a.edge[1])-dz*(a.seaward[0]-a.edge[0]))||1;cuts.push({id:'marked-'+name+'-'+i,edge:[a.edge,b.edge],polygon,seaSide,transitionWidth:1.5});}}
 const protectedPolygons=(options.platforms??[]).map(p=>Array.from({length:96},(_,i)=>[p.center[0]+p.radii[0]*Math.cos(i*Math.PI/48),p.center[1]+p.radii[1]*Math.sin(i*Math.PI/48)]));
 return{...plan,version:'user-marked-transit-release-1',worldCurve:plan.curves.center,ranges,segments,coastalCliffCuts:{cuts:[...old.coastalCliffCuts.cuts,...cuts],protectedPolygons},report:{...plan.report,terrainDomain:old.report.terrainDomain,junctions:{new:[22,58],old:[-26,38]},cutStations,cutCount:cuts.length,sourceIntervals:Object.fromEntries(Object.entries(plan.specs).map(([k,v])=>[k,[v.startU,v.endU]])),accepted:false,installed:false,status:'requires-regenerated-terrain-loaded-audit',loadedEnvelope:{doubleRailHalfWidth:4.37,halfLength:3.49,bottom:-.6,top:5.71},limitations:[...plan.report.limitations,'Exterior polygons are clipped to authored target terrain domain; other world geometry remains separately unverified.','Full platform ellipses receive explicit protection, not merely .78 construction cores.','Cut-to-sea may expose foundation toes; support and rendered coastline still require joint review.']}};
}
