import * as T from 'three';
/** CPU candidate join only. Source geometry is already in castle chart.
 * Removes the patch rectangle from source top/bottom, removes artificial patch
 * boundary walls, splits seam edges, and welds the common 3D boundary. */
export function joinEastCliffPatch({sourceGeometry,patch,bounds,tolerance=1e-5}={}){
 const planes=[[0,bounds.minX,1],[0,bounds.maxX,-1],[2,bounds.minZ,1],[2,bounds.maxZ,-1]],boundary=p=>planes.some(([a,v])=>Math.abs(p[a]-v)<tolerance),source=sourceGeometry.attributes.position,ix=sourceGeometry.index,polys=[],sourceFaces=ix?ix.count/3:source.count/3;
 const area=p=>{let a=0;for(let i=1;i<p.length-1;i++)a+=new T.Vector3().fromArray(p[i]).sub(new T.Vector3().fromArray(p[0])).cross(new T.Vector3().fromArray(p[i+1]).sub(new T.Vector3().fromArray(p[0]))).length();return a;};
 const half=(p,axis,v,sign)=>{const q=[];for(let i=0;i<p.length;i++){const a=p[i],b=p[(i+1)%p.length],u=(a[axis]-v)*sign,w=(b[axis]-v)*sign;if(u>=-1e-9)q.push(a);if((u>1e-9&&w<-1e-9)||(u<-1e-9&&w>1e-9)){const t=u/(u-w);q.push(a.map((x,j)=>x+t*(b[j]-x)));}}return q;};
 let changedSourceFaces=0;for(let i=0;i<sourceFaces;i++){const tri=[0,1,2].map(j=>new T.Vector3().fromBufferAttribute(source,ix?ix.getX(i*3+j):i*3+j).toArray());if(planes.some(([a,v,s])=>tri.every(p=>(p[a]-v)*s<=0))){tri.owner='source';polys.push(tri);continue;}let pending=tri;changedSourceFaces++;for(const[axis,v,sign]of planes){if(pending.length<3)break;const outside=half(pending,axis,v,-sign);if(outside.length>=3&&area(outside)>1e-10){outside.owner='source';polys.push(outside);}pending=half(pending,axis,v,sign);}}
 const pp=patch.geometry.attributes.position,pi=patch.geometry.index;let removedPatchCaps=0;for(let i=0;i<pi.count;i+=3){const tri=[0,1,2].map(j=>new T.Vector3().fromBufferAttribute(pp,pi.getX(i+j)).add(new T.Vector3().fromArray(patch.origin)).toArray());if(planes.some(([a,v])=>tri.every(p=>Math.abs(p[a]-v)<tolerance))){removedPatchCaps++;continue;}tri.owner='patch';polys.push(tri);}
 const bridges=[];for(const[axis,value,insideSign]of planes){const other=axis===0?2:0,edgeSets={source:[],patch:[]};for(const p of polys){if(!p.owner)continue;const n=new T.Vector3().fromArray(p[1]).sub(new T.Vector3().fromArray(p[0])).cross(new T.Vector3().fromArray(p[2]).sub(new T.Vector3().fromArray(p[0])));if(n.y<=1e-9)continue;for(let i=0;i<p.length;i++){const a=p[i],b=p[(i+1)%p.length];if(Math.abs(a[axis]-value)<tolerance&&Math.abs(b[axis]-value)<tolerance&&Math.abs(a[other]-b[other])>1e-7)edgeSets[p.owner].push({a,b});}}
 const cuts=[...new Set([...edgeSets.source,...edgeSets.patch].flatMap(e=>[e.a[other],e.b[other]]).map(x=>+x.toFixed(6)))].sort((a,b)=>a-b),height=(list,t)=>{const e=list.find(e=>t>=Math.min(e.a[other],e.b[other])-1e-5&&t<=Math.max(e.a[other],e.b[other])+1e-5);return e?e.a[1]+(e.b[1]-e.a[1])*(t-e.a[other])/(e.b[other]-e.a[other]):null;};
 for(let i=0;i<cuts.length-1;i++){const a=cuts[i],b=cuts[i+1],mid=(a+b)/2;if(height(edgeSets.source,mid)===null||height(edgeSets.patch,mid)===null)continue;const pick=list=>list.find(e=>mid>=Math.min(e.a[other],e.b[other])-1e-7&&mid<=Math.max(e.a[other],e.b[other])+1e-7),se=pick(edgeSets.source),pe=pick(edgeSets.patch);if(!se||!pe)continue;const y=(e,t)=>e.a[1]+(e.b[1]-e.a[1])*(t-e.a[other])/(e.b[other]-e.a[other]),h=[y(se,a),y(se,b),y(pe,b),y(pe,a)];if(Math.abs(h[0]-h[3])+Math.abs(h[1]-h[2])<1e-5)continue;const p=[a,b,b,a].map((t,i)=>axis===0?[value,h[i],t]:[t,h[i],value]),normal=new T.Vector3().fromArray(p[1]).sub(new T.Vector3().fromArray(p[0])).cross(new T.Vector3().fromArray(p[2]).sub(new T.Vector3().fromArray(p[0]))),desired=insideSign*Math.sign(h[0]+h[1]-h[2]-h[3]);if(normal.getComponent(axis)*desired<0)p.reverse();bridges.push(p);}}
 polys.push(...bridges);
 const seam=new Map();for(const p of polys)for(const q of p)if(boundary(q))seam.set(q.map(v=>v.toFixed(6)).join(','),q);const seamPoints=[...seam.values()],positions=[],indices=[],map=new Map(),origin=patch.origin;
 function vertex(p){const snap=p.map(v=>v);if(boundary(p)){for(const q of seamPoints){if(Math.hypot(...q.map((x,i)=>x-p[i]))<tolerance){for(let j=0;j<3;j++)snap[j]=q[j];break;}}}if(boundary(p))for(let i=0;i<3;i++)snap[i]=Math.round(snap[i]/tolerance)*tolerance;const k=snap.map(v=>Math.round(v/1e-7)).join(',');p=snap;if(!map.has(k)){map.set(k,positions.length/3);positions.push(...p.map((x,i)=>x-origin[i]));}return map.get(k);}
 let degenerateRemoved=0;function tri(a,b,c){if(a===b||b===c||a===c){degenerateRemoved++;return;}const va=new T.Vector3().fromArray(positions,a*3),vb=new T.Vector3().fromArray(positions,b*3),vc=new T.Vector3().fromArray(positions,c*3);if(vb.sub(va).cross(vc.sub(va)).length()<1e-10){degenerateRemoved++;return;}indices.push(a,b,c);}
 for(const poly of polys){let p=[];for(let i=0;i<poly.length;i++){const a=poly[i],b=poly[(i+1)%poly.length],va=new T.Vector3().fromArray(a),delta=new T.Vector3().fromArray(b).sub(va),length=delta.lengthSq();p.push(a);const extra=[];for(const q of seamPoints){const plane=planes.find(([k,v])=>Math.abs(a[k]-v)<tolerance&&Math.abs(b[k]-v)<tolerance&&Math.abs(q[k]-v)<tolerance);if(!plane){const dq=new T.Vector3().fromArray(q).sub(va),t=dq.dot(delta)/length;if(t>1e-7&&t<1-1e-7&&dq.addScaledVector(delta,-t).length()<tolerance)extra.push({q,t});continue;}const other=plane[0]===0?2:0;let t;if(Math.abs(b[other]-a[other])>1e-8)t=(q[other]-a[other])/(b[other]-a[other]);else t=(q[1]-a[1])/(b[1]-a[1]);if(t>1e-7&&t<1-1e-7)extra.push({q:a.map((x,i)=>x+t*(b[i]-x)),t});}extra.sort((a,b)=>a.t-b.t);p.push(...extra.map(q=>q.q));}if(p.length===3)tri(...p.map(vertex));else{const c=[0,0,0];for(const q of p)for(let j=0;j<3;j++)c[j]+=q[j]/p.length;const ci=vertex(c);for(let j=0;j<p.length;j++)tri(ci,vertex(p[j]),vertex(p[(j+1)%p.length]));}}
 const directed=new Map(),adjacency=Array.from({length:indices.length/3},()=>[]);for(let f=0;f<indices.length/3;f++)for(let j=0;j<3;j++){const a=indices[f*3+j],b=indices[f*3+(j+1)%3],k=a<b?a+','+b:b+','+a,dir=a<b?1:-1;if(!directed.has(k))directed.set(k,[]);directed.get(k).push({f,dir});}for(const e of directed.values())if(e.length===2){const same=e[0].dir===e[1].dir;adjacency[e[0].f].push({f:e[1].f,same});adjacency[e[1].f].push({f:e[0].f,same});}const flips=new Array(adjacency.length),queue=[];let windingAdjustedFaces=0,nonOrientableConflicts=0,connectedComponents=0;for(let seed=0;seed<flips.length;seed++){if(flips[seed]!==undefined)continue;connectedComponents++;flips[seed]=false;queue.push(seed);for(let at=0;at<queue.length;at++){const f=queue[at];for(const a of adjacency[f]){const expected=!!(flips[f]^a.same);if(flips[a.f]===undefined){flips[a.f]=expected;queue.push(a.f);}else if(flips[a.f]!==expected)nonOrientableConflicts++;}}queue.length=0;}for(let f=0;f<flips.length;f++)if(flips[f]){[indices[f*3+1],indices[f*3+2]]=[indices[f*3+2],indices[f*3+1]];windingAdjustedFaces++;}
 const geometry=new T.BufferGeometry().setAttribute('position',new T.Float32BufferAttribute(positions,3));geometry.setIndex(indices);geometry.computeVertexNormals();geometry.computeBoundingBox();geometry.computeBoundingSphere();const edges=new Map();let floatCollapsed=0,volume=0,orientationConflicts=0;for(let i=0;i<indices.length;i+=3){const ids=indices.slice(i,i+3),p=ids.map(k=>new T.Vector3().fromBufferAttribute(geometry.attributes.position,k));if(p[1].clone().sub(p[0]).cross(p[2].clone().sub(p[0])).length()<1e-10)floatCollapsed++;volume+=p[0].dot(p[1].clone().cross(p[2]))/6;for(let j=0;j<3;j++){const a=ids[j],b=ids[(j+1)%3],key=a<b?a+','+b:b+','+a;if(!edges.has(key))edges.set(key,{count:0,orientation:0});const e=edges.get(key);e.count++;e.orientation+=a<b?1:-1;}}
 const bad=[...edges.values()].filter(e=>e.count!==2).length;orientationConflicts=[...edges.values()].filter(e=>e.count===2&&e.orientation!==0).length;
 return{geometry,origin,report:{version:'east-cliff-patch-join-1',accepted:false,installed:false,connectedComponents,windingAdjustedFaces,nonOrientableConflicts,changedSourceFaces,removedPatchCaps,transitionSeamWalls:bridges.length,seamPoints:seamPoints.length,triangles:indices.length/3,degenerateRemoved,floatCollapsed,badEdges:[...edges.entries()].filter(([k,e])=>e.count!==2).slice(0,100).map(([k,e])=>({count:e.count,points:k.split(',').map(i=>new T.Vector3().fromBufferAttribute(geometry.attributes.position,+i).add(new T.Vector3().fromArray(origin)).toArray())})),nonManifoldEdges:bad,orientationConflicts,signedVolume:volume,closed:bad===0&&orientationConflicts===0&&floatCollapsed===0&&nonOrientableConflicts===0}};
}
