import * as T from 'three';
import {createWarshipClearance} from '../warshipClearance.js';
import {solveTargetNewCityStairRoute} from './targetNewCityStairRoute.js';
export const TARGET_OLD_CITY_WATERFRONT_STAIRS_VERSION='target-old-city-waterfront-stairs-5-stone-arcades';
const value=v=>typeof v==='number'?v:v?.height;
const finite3=p=>Array.isArray(p)&&p.length===3&&p.every(Number.isFinite);
const polygonOverlap=(A,B)=>![A,B].some(poly=>poly.some((p,i)=>{const q=poly[(i+1)%poly.length],nx=-(q[1]-p[1]),nz=q[0]-p[0],a=A.map(v=>v[0]*nx+v[1]*nz),b=B.map(v=>v[0]*nx+v[1]*nz);return Math.max(...a)<=Math.min(...b)+1e-7||Math.max(...b)<=Math.min(...a)+1e-7;}));
function clipPolygon(subject,clip){let out=subject.map(p=>[...p]);for(let i=0;i<clip.length;i++){const a=clip[i],b=clip[(i+1)%clip.length],cross=p=>(b[0]-a[0])*(p[1]-a[1])-(b[1]-a[1])*(p[0]-a[0]),input=out;out=[];for(let j=0;j<input.length;j++){const p=input[j],q=input[(j+1)%input.length],P=cross(p),Q=cross(q);if(P>=-1e-8)out.push(p);if((P>=0)!==(Q>=0)){const t=P/(P-Q);out.push([p[0]+(q[0]-p[0])*t,p[1]+(q[1]-p[1])*t]);}}}return out;}
// Stone arcade planning is deliberately limited to an already verified short,
// straight descending flight. Invalid bays keep their original sampled posts.
function planStoneArcades({supports,treads,points,sample,obstacles,shipBounds}){
 const plan={arches:[],replacements:new Map(),retired:new Set(),rejected:[],eligible:points.length===3};
 if(!plan.eligible)return plan;
 const candidates=supports.filter(s=>Number.isFinite(s.distance)&&s.top-s.bottom>6),pierWidth=1.25,depth=1.4;
 const ordered=poly=>{const a=poly.reduce((n,p,i)=>{const q=poly[(i+1)%poly.length];return n+p[0]*q[1]-q[0]*p[1];},0);return a<0?poly.reverse():poly;};
 for(let i=0;i+2<candidates.length;i+=2){const [left,middle,right]=candidates.slice(i,i+3),dx=right.x-left.x,dz=right.z-left.z,length=Math.hypot(dx,dz),u=[dx/length,dz/length],n=[-u[1],u[0]],clear=length-pierWidth;
  if(clear<3||length>7.5||Math.abs((middle.x-left.x)*n[0]+(middle.z-left.z)*n[1])>.04){plan.rejected.push({left:left.id,right:right.id,reason:'unsupported-span-or-turn'});continue;}
  const strip=(lo,hi,w)=>ordered([[left.x+u[0]*lo+n[0]*w/2,left.z+u[1]*lo+n[1]*w/2],[left.x+u[0]*hi+n[0]*w/2,left.z+u[1]*hi+n[1]*w/2],[left.x+u[0]*hi-n[0]*w/2,left.z+u[1]*hi-n[1]*w/2],[left.x+u[0]*lo-n[0]*w/2,left.z+u[1]*lo-n[1]*w/2]]),lo=pierWidth/2,hi=length-pierWidth/2,polygon=strip(lo,hi,depth),overlap=treads.filter(t=>polygonOverlap(t.polygon,polygon));
  if(!overlap.length)continue;
  const crown=Math.min(...overlap.map(t=>t.top))-.55,rise=clear/2,spring=crown-rise,soffit=s=>spring+rise*Math.sqrt(Math.max(0,1-((s-length/2)/(clear/2))**2)),footings=[];let failure=null;
  for(const old of[left,right]){const polygon=strip(old===left?-pierWidth/2:length-pierWidth/2,old===left?pierWidth/2:length+pierWidth/2,depth),samples=[];for(const a of[-.5,0,.5])for(const b of[-.5,0,.5]){const x=old.x+u[0]*a*pierWidth+n[0]*b*depth,z=old.z+u[1]*a*pierWidth+n[1]*b*depth;samples.push({x,z,...sample(x,z)});}if(samples.some(p=>p.ground===null||p.sea===null)){failure='missing-expanded-pier-footing';break;}const bottom=Math.min(...samples.map(p=>p.ground))-.15;if(old.top-bottom>26){failure='expanded-pier-too-tall';break;}const conflict=[...obstacles,...shipBounds].find(o=>old.top>o.minY&&bottom<o.maxY&&polygonOverlap(polygon,o.polygon));if(conflict){failure='expanded-pier-conflict:'+conflict.id;break;}footings.push({...old,polygon,samples,bottom,marine:samples.some(p=>p.ground<p.sea-.2),arcadePier:true,pierWidth,depth});}
  const samples=[];for(let j=0;j<=20;j++)for(const across of[-.5,0,.5]){const distance=lo+clear*j/20,x=left.x+u[0]*distance+n[0]*across*depth,z=left.z+u[1]*distance+n[1]*across*depth,y=soffit(distance),surface=sample(x,z);samples.push({x,z,soffit:y,...surface});if(surface.ground===null||surface.sea===null)failure='missing-arch-opening-surface';else if(y-Math.max(surface.ground,surface.sea)<1.5)failure='insufficient-open-arch-headroom';}
  const conflict=[...obstacles,...shipBounds].find(o=>Math.max(...overlap.map(t=>t.top))-.2>o.minY&&spring<o.maxY&&polygonOverlap(polygon,o.polygon));if(conflict)failure='arch-solid-envelope-conflict:'+conflict.id;
  if(failure){plan.rejected.push({left:left.id,right:right.id,reason:failure});continue;}
  const bay={id:'waterfront-stone-arch-'+plan.arches.length,left:left.id,right:right.id,removedPost:middle.id,origin:[left.x,left.z],u,n,length,clearWidth:clear,pierWidth,depth,crown,spring,rise,polygon,segments:24,minY:spring,maxY:Math.max(...overlap.map(t=>t.top))-.2,samples,minimumSurfaceHeadroom:Math.min(...samples.map(p=>p.soffit-Math.max(p.ground,p.sea))),minimumSeaHeadroom:Math.min(...samples.map(p=>p.soffit-p.sea))};
  plan.arches.push(bay);footings.forEach(p=>plan.replacements.set(p.id,p));plan.retired.add(middle.id);
 }
 return plan;
}
function transform(p,position,yaw){return[position[0]+Math.cos(yaw)*p[0]+Math.sin(yaw)*p[2],position[1]+p[1],position[2]-Math.sin(yaw)*p[0]+Math.cos(yaw)*p[2]];}
/** Read-only feasibility first. Report positions are castle-local unless marked
 * world. Callbacks MUST sample final geometry, never nominal sea/terrain height.
 * candidateRoot may be the candidate handle or its Group with detailCandidateReport.
 * `supportStyle: 'posts'` restores the v4 support geometry; default stone-arcade
 * only replaces fully sampled, collision-free bays on a short straight flight.
 * `landingSampleIndices` optionally restricts 1..8 actual rail samples; default
 * searches 0/16/32/48/64/80/96/112, retaining rejected original reports.
 * `shipWorldBoxes` are current world-space bounds; `obstacleGroups` are current
 * vessel groups for finite triangle crossings. `collisionGroups` are actual
 * visible city/rail groups for body rays, including their instance transforms.
 * Samplers return a finite number or {height}; missing ground/sea never defaults.
 * Return Group is castle-local. Attach only when report.built; accepted stays
 * false pending GPU/integrated review. dispose owns only generated G/M objects.
 * No production navigation, terrain mutation, or rail modification is performed. */
export function createTargetOldCityWaterfrontStairs(options={}){
 const report=options.candidateReport??options.candidateRoot?.report??options.candidateRoot?.userData?.detailCandidateReport,walk=report?.frontRail?.walkSurfaces?.find(w=>Array.isArray(w.centres)&&Array.isArray(w.up)),count=walk?.centres?.length??0;
 const indices=options.landingSampleIndices??[0,16,32,48,64,80,96,112].filter(i=>i<count-1||i===0);
 if(!Array.isArray(indices)||!indices.length||indices.length>8||indices.some(i=>!Number.isInteger(i)||i<0||(count&&i>=count-1))||new Set(indices).size!==indices.length)throw new TypeError('landingSampleIndices requires 1..8 distinct valid rail sections');
 const samples=new Map(),cached=(fn,key)=>(x,z)=>{const k=key+':'+x.toFixed(6)+','+z.toFixed(6);if(!samples.has(k))samples.set(k,fn(x,z));return samples.get(k);};
 const attempts=[];let first=null,last=null;
 for(const sampleIndex of indices){const asset=createAtLanding({...options,candidateReport:report,sampleTerrain:typeof options.sampleTerrain==='function'?cached(options.sampleTerrain,'terrain'):options.sampleTerrain,sampleSea:typeof options.sampleSea==='function'?cached(options.sampleSea,'sea'):options.sampleSea,dockSampleIndex:sampleIndex});if(!first)first=asset.report;
  attempts.push({sampleIndex,status:asset.report.status,built:asset.report.built,dock:asset.report.dock,selected:asset.report.selected?{index:asset.report.selected.index,length:asset.report.selected.length,maxRise:asset.report.selected.maxRise,maxGrade:asset.report.selected.maxGrade}:null,shipAudit:asset.report.shipAudit,supportConflicts:asset.report.supportConflicts,routeAttempts:asset.report.attempts,clearance:asset.report.clearance,transition:asset.report.transition?{maxGrade:asset.report.transition.maxGrade,failures:asset.report.transition.failures,protectedConflicts:asset.report.transition.protectedConflicts}:null});
  last=asset;if(asset.report.built||asset.report.status==='feasible-sampled-geometry-plan')break;asset.dispose();
 }
 last.report.landingSearch={candidateIndices:indices,attempts,selectedIndex:last.report.built||last.report.status==='feasible-sampled-geometry-plan'?attempts.at(-1).sampleIndex:null,originalLandingReport:indices[0]===0&&first!==last.report?first:null,uniqueSurfaceSamples:samples.size/2,staticPoseOnly:true};return last;
}
function createAtLanding({castle,candidateRoot,candidateReport=candidateRoot?.report??candidateRoot?.userData?.detailCandidateReport,sampleTerrain,sampleSea,width=2.4,maxSlope=.65,maxRise=.22,waypointRoutes=null,protectedVolumes=[],shipWorldBoxes=[],obstacleGroups=[],collisionGroups=[],build=true,dockSampleIndex=0,supportStyle='stone-arcade'}={}){
 if(!castle?.isObject3D||typeof sampleTerrain!=='function'||typeof sampleSea!=='function')throw new TypeError('castle and final surface samplers required');
 if(!candidateReport?.oldCity?.geometry||!candidateReport?.frontRail)throw new TypeError('complete candidate report including oldCity/frontRail required');
 if(!Number.isFinite(width)||width<2.4||!Number.isFinite(maxSlope)||maxSlope<=0||maxSlope>.65||!Number.isFinite(maxRise)||maxRise<=0||maxRise>.22)throw new RangeError('width >=2.4, slope <=.65 and rise <=.22 required');
 if(!['stone-arcade','posts'].includes(supportStyle))throw new TypeError('supportStyle must be stone-arcade or posts');
 const group=new T.Group();group.name='target-old-city-waterfront-stairs';group.userData.preserveCitadelMaterials=true;
 const report={version:TARGET_OLD_CITY_WATERFRONT_STAIRS_VERSION,status:'surveying',built:false,accepted:false,terrainMutation:false,railMutation:false,width,maxSlope,maxRise,attempts:[],protectedVolumes:[],limitations:['Read-only finite terrain/sea survey, not continuous collision or engineering proof.','Only explicitly supplied ship volumes are protected; no complete shipping lane data is available.','Rail end interface must use an actual promenade cross-section before any geometry is built.']};
 let disposed=false;const geometries=[],materials=[];function dispose(){if(disposed)return;disposed=true;group.removeFromParent();geometries.forEach(g=>g.dispose());materials.forEach(m=>m.dispose());group.clear();}
 const finish=()=>{group.userData.waterfrontStairReport=report;return{group,report,dispose};};
 const old=candidateReport.oldCity,yaw=old.yawDegrees*Math.PI/180,approach=old.geometry.footprints.find(p=>p.id==='gate-approach'&&p.walkable),rail=candidateReport.frontRail;
 if(!approach||!finite3(old.position)||!Number.isFinite(yaw)){report.status='no-public-start';return finish();}
 const front=Math.max(...approach.polygon.map(p=>p[1]))-.05,x=(Math.min(...approach.polygon.map(p=>p[0]))+Math.max(...approach.polygon.map(p=>p[0])))/2,start=transform([x,approach.roofY,front],old.position,yaw);
 castle.updateWorldMatrix(true,false);const inverse=castle.matrixWorld.clone().invert();
 const promenade=rail.walkSurfaces?.find(w=>Array.isArray(w.centres)&&Array.isArray(w.up)),dock=promenade?.centres?.[dockSampleIndex],railEnd=finite3(rail.endpoints?.[0])?new T.Vector3(...rail.endpoints[0]).applyMatrix4(inverse).toArray():null;
 report.start={position:start,source:'oldCity.geometry.footprints gate-approach front edge',preservedEntry:old.geometry.entry};report.railEnd={position:railEnd,source:'frontRail.endpoints[0] world transformed to castle'};
 if(!finite3(dock)||!finite3(promenade?.centres?.[dockSampleIndex+1])||!finite3(promenade?.up?.[dockSampleIndex])){report.status='rail-promenade-interface-missing';report.bestCandidate={start,end:railEnd};report.reason='rail track centre is not a safe pedestrian endpoint; current promenade centres/up required';return finish();}
 const direction=new T.Vector3(...promenade.centres[dockSampleIndex+1]).sub(new T.Vector3(...dock)).normalize(),up=new T.Vector3(...promenade.up[dockSampleIndex]).normalize(),right=new T.Vector3().crossVectors(up,direction).normalize(),dockEdges=[-width/2,width/2].map(s=>new T.Vector3(...dock).addScaledVector(right,s).toArray());
 const transitionLength=dockSampleIndex?6:4,arrivalLift=dockSampleIndex?1.5:.02,approachDock=[dock[0]-direction.x*transitionLength,dock[1],dock[2]-direction.z*transitionLength],end=[approachDock[0],Math.max(...dockEdges.map(p=>p[1]))+arrivalLift,approachDock[2]];
 report.dock={sampleIndex:dockSampleIndex,arrivalLift,centre:[...dock],edges:dockEdges,approach:end,sideHeightDifference:Math.abs(dockEdges[0][1]-dockEdges[1][1]),requiredTransitionLength:transitionLength,railEndUnchanged:true};
 const obstacles=[],shipBounds=[];
 for(const fp of old.geometry.footprints.filter(f=>f.id.startsWith('house-')||f.id==='old-city-high-tower')){const pts=fp.polygon.map(p=>transform([p[0],0,p[1]],old.position,yaw));obstacles.push({id:fp.id,polygon:pts.map(p=>[p[0],p[2]]),minY:old.position[1]+fp.floorY,maxY:old.position[1]+fp.roofY});}
 const waterfall=candidateReport.waterfall;if(waterfall?.built){const b=waterfall.geometry.boundingBox,y=waterfall.yawDegrees*Math.PI/180;const poly=[[b.min[0]-1,b.min[2]-1],[b.max[0]+1,b.min[2]-1],[b.max[0]+1,b.max[2]+1],[b.min[0]-1,b.max[2]+1]].map(p=>transform([p[0],0,p[1]],waterfall.position,y));obstacles.push({id:'protected-waterfall-and-spray',polygon:poly.map(p=>[p[0],p[2]]),minY:waterfall.position[1]+b.min[1],maxY:waterfall.position[1]+b.max[1]});}
 for(const surface of candidateReport.bridge?.walkSurfaces??[])obstacles.push({id:surface.id,polygon:surface.polygon,minY:Math.min(...surface.corners.map(p=>p[1]))-2,maxY:Math.max(...surface.corners.map(p=>p[1]))+2});
 for(const v of protectedVolumes){if(!Array.isArray(v.polygon)||v.polygon.length<3||!Number.isFinite(v.minY)||!Number.isFinite(v.maxY))throw new TypeError('protectedVolumes require finite polygon and minY/maxY');obstacles.push(v);}
 // Explicit current ship bounds are conservative static constraints, never a
 // claim about an entire vessel route. No existing ship is hidden or moved.
 for(const [i,input]of [...shipWorldBoxes,...obstacleGroups.map(o=>{o.updateWorldMatrix(true,true);return new T.Box3().setFromObject(o);})].entries()){
  const min=input.isBox3?input.min.toArray():input.min,max=input.isBox3?input.max.toArray():input.max;if(!finite3(min)||!finite3(max))throw new TypeError('shipWorldBoxes must contain finite world min/max');
  const corners=[];for(const x of[min[0],max[0]])for(const y of[min[1],max[1]])for(const z of[min[2],max[2]])corners.push(new T.Vector3(x,y,z).applyMatrix4(inverse));
  const lo=[Math.min(...corners.map(p=>p.x)),Math.min(...corners.map(p=>p.z))],hi=[Math.max(...corners.map(p=>p.x)),Math.max(...corners.map(p=>p.z))];shipBounds.push({id:'static-ship-world-box-'+i,polygon:[lo,[hi[0],lo[1]],hi,[lo[0],hi[1]]],minY:Math.min(...corners.map(p=>p.y)),maxY:Math.max(...corners.map(p=>p.y)),conservativeWorldBox:true});
 }
 const dockEndStrip=[dockEdges[0],dockEdges[1]].map(p=>new T.Vector3(...p)),dockEndPolygon=[dockEndStrip[0].clone().addScaledVector(direction,-.15),dockEndStrip[1].clone().addScaledVector(direction,-.15),dockEndStrip[1].clone().addScaledVector(direction,.15),dockEndStrip[0].clone().addScaledVector(direction,.15)].map(p=>[p.x,p.z]),dockEndConflicts=shipBounds.filter(o=>Math.max(...dockEdges.map(p=>p[1]))+2>o.minY&&Math.min(...dockEdges.map(p=>p[1]))-.32<o.maxY&&polygonOverlap(dockEndPolygon,o.polygon));
 if(dockEndConflicts.length)report.shipAudit={broadPhase:dockEndConflicts.map(o=>({ship:o.id,overlappingParts:['dock-transition'],stage:'actual dock end cross-section',conservative:true})),triangles:[],currentPoseOnly:true,completeShippingLane:false};
 if(rail.rails?.left&&rail.rails?.right){const centres=rail.rails.left.map((p,i)=>new T.Vector3(...p).add(new T.Vector3(...rail.rails.right[i])).multiplyScalar(.5).applyMatrix4(inverse)),sides=rail.rails.left.map((p,i)=>new T.Vector3(...rail.rails.right[i]).sub(new T.Vector3(...p)).normalize().transformDirection(inverse));
  for(let i=1;i<centres.length;i++){const A=centres[i-1],B=centres[i],v=[A.clone().addScaledVector(sides[i-1],-1.65),B.clone().addScaledVector(sides[i],-1.65),B.clone().addScaledVector(sides[i],1.65),A.clone().addScaledVector(sides[i-1],1.65)];obstacles.push({id:'protected-rail-body-'+i,polygon:v.map(p=>[p.x,p.z]),minY:Math.min(...v.map(p=>p.y))-.3,maxY:Math.max(...v.map(p=>p.y))+3.2});}
 }
 const supply=candidateReport.waterSupply;for(let i=1;i<(supply?.waterProfile?.length??0);i++){const A=supply.waterProfile[i-1],B=supply.waterProfile[i],dx=B[0]-A[0],dz=B[2]-A[2],l=Math.hypot(dx,dz),nx=-dz/l*(supply.width/2+.3),nz=dx/l*(supply.width/2+.3);obstacles.push({id:'protected-water-supply-'+i,polygon:[[A[0]+nx,A[2]+nz],[B[0]+nx,B[2]+nz],[B[0]-nx,B[2]-nz],[A[0]-nx,A[2]-nz]],minY:Math.min(A[1],B[1])-.6,maxY:Math.max(A[1],B[1])+1});}
 report.protectedVolumes=obstacles.map(o=>({id:o.id,polygon:o.polygon,minY:o.minY,maxY:o.maxY}));report.shippingCoverage={explicitVolumes:protectedVolumes.length,staticShipBoxes:shipWorldBoxes.length+obstacleGroups.length,complete:false};
 const cache=new Map();const sampled=(x,z)=>{const key=x.toFixed(5)+','+z.toFixed(5);if(!cache.has(key)){const ground=value(sampleTerrain(x,z)),sea=value(sampleSea(x,z));cache.set(key,{ground:Number.isFinite(ground)?ground:null,sea:Number.isFinite(sea)?sea:null});}return cache.get(key);};
 const railVolumes=obstacles.filter(o=>o.id.startsWith('protected-rail-body-'));const inside=(p,poly)=>poly.every((a,i)=>{const b=poly[(i+1)%poly.length];return(b[0]-a[0])*(p[1]-a[1])-(b[1]-a[1])*(p[0]-a[0])>=-1e-7;})||poly.every((a,i)=>{const b=poly[(i+1)%poly.length];return(b[0]-a[0])*(p[1]-a[1])-(b[1]-a[1])*(p[0]-a[0])<=1e-7;});
 // A required deck elevation above the measured rail envelope is separate from terrain samples.
 const requiredRailHeight=(x,z)=>dockSampleIndex?Math.max(-Infinity,...railVolumes.filter(o=>inside([x,z],o.polygon)).map(o=>o.maxY+1.2)):-Infinity;
 const sx=start[0],sz=start[2],ex=end[0],ez=end[2],exitPoint=[sx+4*Math.sin(yaw),sz+4*Math.cos(yaw)];
 const anchorIndex=Math.min(16,dockSampleIndex),anchor=dockSampleIndex?new T.Vector3(...promenade.centres[anchorIndex]):null,anchorDirection=dockSampleIndex?new T.Vector3(...promenade.centres[anchorIndex+1]).sub(anchor).normalize():null,anchorRight=dockSampleIndex?new T.Vector3(...promenade.up[anchorIndex]).cross(anchorDirection).normalize():null;
 const routes=waypointRoutes??[
  [exitPoint],
  ...[-40,-44,-48].flatMap(inner=>[-60,-65,-70].map(outer=>[exitPoint,[inner,34],[outer,44],[inner-2,53],[outer,ez-6]])),
  ...[-43,-48,-53].map(inner=>[exitPoint,[inner,33],[inner,45],[ex-3,56],[ex-3,ez-3]]),
 ...(dockSampleIndex?[-72,-80,-92,-96].map(west=>[exitPoint,[-43,33],[west,34],[west,78],[ex-5,ez-5]]):[]),
 ...(dockSampleIndex?[8,12,16].map(out=>[exitPoint,[-43,40],[-43,76],[ex-out,ez+out],[ex-out,ez]]):[]),
 ...(dockSampleIndex?[6,10,14].map(out=>[exitPoint,[-43,40],[-43,76],[anchor.x-anchorRight.x*out,anchor.z-anchorRight.z*out],[ex-right.x*out-direction.x*4,ez-right.z*out-direction.z*4],[ex-direction.x*4,ez-direction.z*4]]):[])
 ];
 let best=null,shortest=null;const scale=.4,step=Math.min(.32,maxRise/maxSlope*.98);
 for(let index=0;index<routes.length;index++){
  const data=solveTargetNewCityStairRoute({sampleSurface:(x,z)=>{const s=sampled(x,z);return s.ground===null||s.sea===null?null:{height:Math.max(s.ground+.08,requiredRailHeight(x,z))*scale};},start:[start[0],start[1]*scale,start[2]],end:[end[0],end[1]*scale,end[2]],width:width+.24,maxSlope:maxSlope*scale,step,waypointRoutes:[routes[index]],entryLanding:{height:start[1]*scale,outward:[Math.sin(yaw),Math.cos(yaw)],backLength:.05}});
  const attempt={index,waypoints:routes[index],status:data.status,failures:data.failures};report.attempts.push(attempt);if(!data.selected)continue;
  const selected=data.selected,treads=selected.treads.map(t=>({...t,top:t.top/scale,bottom:Math.min(...t.samples.map(s=>sampled(s.x,s.z).ground))-.2,groundMax:Math.max(...t.samples.map(s=>sampled(s.x,s.z).ground)),required:t.required/scale,samples:t.samples.map(s=>({...s,height:sampled(s.x,s.z).ground,sea:sampled(s.x,s.z).sea}))}));
  const conflicts=[];let rise=0,grade=0,previous=start[1];for(const t of treads){rise=Math.max(rise,previous-t.top);if(t.kind==='tread')grade=Math.max(grade,(previous-t.top)/t.ds);previous=t.top;
   for(const o of (dockSampleIndex?[...obstacles,...shipBounds]:obstacles))if((o.conservativeWorldBox||(t.top+2>o.minY&&t.top-.32<o.maxY))&&polygonOverlap(t.polygon,o.polygon))conflicts.push({tread:treads.indexOf(t),obstacle:o.id});
  }
  const loop=treads.some((t,i)=>treads.slice(i+1).some(u=>Math.abs(t.distance-u.distance)>width*2&&polygonOverlap(t.polygon,u.polygon)));if(loop){attempt.status='self-overlapping-plan';continue;}
  const missing=treads.some(t=>t.samples.some(s=>s.sea===null)),groundIntrusions=treads.filter(t=>t.groundMax>t.top+.001),marine=treads.filter(t=>t.samples.some(s=>s.height<s.sea-.2));
  attempt.metrics={length:selected.length,treads:treads.length,maxRise:rise,maxGrade:grade,protectedConflicts:conflicts.length,groundIntrusions:groundIntrusions.length,marineTreads:marine.length,missing};attempt.conflicts=conflicts.slice(0,12);
  if(conflicts.length||groundIntrusions.length||missing||rise>maxRise+1e-7||grade>maxSlope+1e-7){attempt.status='protected-or-body-conflict';continue;}
  const signs=selected.points.slice(1).map((p,i)=>Math.sign(p[0]-selected.points[i][0])).filter(v=>v!==0),switchbacks=signs.slice(1).filter((v,i)=>v!==signs[i]).length;
  const choice={index,switchbacks,points:selected.points,treads,length:selected.length,walkPath:[start,...treads.map(t=>[t.x,t.top,t.z]),end],marineTreads:marine.length,maxRise:rise,maxGrade:grade};if(!shortest||choice.length<shortest.length)shortest=choice;if(!best||choice.length<best.length-1e-7||Math.abs(choice.length-best.length)<=1e-7&&choice.points.length<best.points.length)best=choice;
 }
 report.surfaceSamples=cache.size;report.selected=best;report.shortestTerrainCandidate=shortest?{index:shortest.index,length:shortest.length}:null;report.bestCandidate=best??report.attempts.filter(a=>a.metrics).sort((a,b)=>a.metrics.protectedConflicts-b.metrics.protectedConflicts||a.metrics.length-b.metrics.length)[0]??null;
 if(dockEndConflicts.length){report.status='static-ship-broadphase-unresolved';return finish();}
 if(!best){report.status='no-feasible-sampled-route';return finish();}
 report.selection='shortest protected sampled route; fewer corners breaks equal-length ties; no mandatory lateral reversals';
 // Build a ruled transition using the ACTUAL last tread edge and slanted rail
 // promenade edge. A flat substitute would leave the measured .7 m side gap.
 const last=best.treads.at(-1),A=last.quad?[last.quad[1],last.quad[2]]:null;
 if(!A){report.status='dock-start-section-unavailable';return finish();}
 let edges=dockEdges.slice();const distance=(a,b)=>Math.hypot(a[0]-b[0],a[1]-b[2]);if(distance(A[0],edges[1])+distance(A[1],edges[0])<distance(A[0],edges[0])+distance(A[1],edges[1]))edges.reverse();
 const transition=[[A[0][0],last.top,A[0][1]],edges[0],edges[1],[A[1][0],last.top,A[1][1]]],triangles=[[transition[0],transition[1],transition[2]],[transition[0],transition[2],transition[3]]];
 const transitionSamples=[],transitionFailures=[];let transitionGrade=0;
 for(const tri of triangles){const [a,b,c]=tri.map(p=>new T.Vector3(...p)),normal=b.clone().sub(a).cross(c.clone().sub(a));transitionGrade=Math.max(transitionGrade,Math.hypot(normal.x,normal.z)/Math.abs(normal.y));for(let u=0;u<=4;u++)for(let v=0;v<=4-u;v++){const p=a.clone().multiplyScalar(1-(u+v)/4).addScaledVector(b,u/4).addScaledVector(c,v/4),s=sampled(p.x,p.z);transitionSamples.push({position:p.toArray(),auditPosition:p.clone().multiplyScalar(.998).addScaledVector(a,.002/3).addScaledVector(b,.002/3).addScaledVector(c,.002/3).toArray(),...s});if(s.ground===null||s.sea===null||s.ground>p.y+.001)transitionFailures.push({position:p.toArray(),...s});}}
 const transitionPoly=transition.map(p=>[p[0],p[2]]),transitionConflicts=obstacles.filter(o=>Math.max(...transition.map(p=>p[1]))+2>o.minY&&Math.min(...transition.map(p=>p[1]))-.32<o.maxY&&polygonOverlap(transitionPoly,o.polygon)).map(o=>o.id);
 report.transition={vertices:transition,triangles,maxGrade:transitionGrade,samples:transitionSamples,failures:transitionFailures,protectedConflicts:transitionConflicts,radialDockEdgesPreserved:true};
 if(transitionGrade>maxSlope+1e-7||transitionFailures.length||transitionConflicts.length){report.status='dock-transition-rejected';return finish();}
 // Guard feet follow the two actual transition triangle planes. Their
 // narrow curb extends sideways from the slab; no crossbar closes either end.
 const guardSides=[],guardFailures=[],transitionCentre=transition.reduce((v,p)=>v.add(new T.Vector3(...p)),new T.Vector3()).multiplyScalar(.25);
 for(const [side,edge]of [[transition[0],transition[1]],[transition[3],transition[2]]].entries()){
  const [a,b]=edge,[p,q,r]=triangles[side].map(v=>new T.Vector3(...v)),plane=q.clone().sub(p).cross(r.clone().sub(p)),len=Math.hypot(b[0]-a[0],b[2]-a[2]);let nx=-(b[2]-a[2])/len,nz=(b[0]-a[0])/len;if(nx*(transitionCentre.x-(a[0]+b[0])/2)+nz*(transitionCentre.z-(a[2]+b[2])/2)>0){nx=-nx;nz=-nz;}
  const heightAt=(x,z)=>p.y-(plane.x*(x-p.x)+plane.z*(z-p.z))/plane.y;
  const strip=(lo,hi)=>{const poly=[[a[0]+nx*lo,a[2]+nz*lo],[b[0]+nx*lo,b[2]+nz*lo],[b[0]+nx*hi,b[2]+nz*hi],[a[0]+nx*hi,a[2]+nz*hi]],area=poly.reduce((sum,v,i)=>{const w=poly[(i+1)%4];return sum+v[0]*w[1]-w[0]*v[1];},0);if(area<0)poly.reverse();return poly;};
  const curb=strip(0,.24),wall=strip(.10,.18),feet=wall.map(([x,z])=>[x,heightAt(x,z),z]),tops=feet.map(v=>[v[0],v[1]+.95,v[2]]),samples=[];
  for(const f of[0,.25,.5,.75,1])for(const d of[0,.10,.18,.24]){const x=a[0]+(b[0]-a[0])*f+nx*d,z=a[2]+(b[2]-a[2])*f+nz*d,y=heightAt(x,z),s=sampled(x,z);samples.push({position:[x,y,z],...s});if(s.ground===null||s.sea===null||s.ground>y-.08)guardFailures.push({side,reason:'missing-or-intruding-guard-footing',position:[x,y,z],...s});}
  const minY=Math.min(...feet.map(p=>p[1]))-.32,maxY=Math.max(...tops.map(p=>p[1]));for(const o of obstacles)if(maxY>o.minY&&minY<o.maxY&&polygonOverlap(curb,o.polygon))guardFailures.push({side,obstacle:o.id});
  guardSides.push({side,edge,innerEdge:[a,b].map(v=>[v[0]+nx*.10,heightAt(v[0]+nx*.10,v[2]+nz*.10),v[2]+nz*.10]),curb,wall,feet,tops,curbTop:curb.map(([x,z])=>heightAt(x,z)),minY,maxY,samples});
 }
 const guardWidths=Array.from({length:21},(_,i)=>{const t=i/20,points=guardSides.map(s=>new T.Vector3(...s.innerEdge[0]).lerp(new T.Vector3(...s.innerEdge[1]),t));return points[0].distanceTo(points[1]);});if(Math.min(...guardWidths)<width-1e-7)guardFailures.push({reason:'guard-clear-width',minimum:Math.min(...guardWidths),required:width});
 report.transition.guards={minimumSampledClearWidth:Math.min(...guardWidths),widthSamples:guardWidths,height:.95,wallThickness:.08,outsideClearEdgeOffset:.10,clearWidthAtLeast:width,openEnds:true,walkable:false,sides:guardSides,failures:guardFailures};
 if(guardFailures.length){report.status='transition-guard-surface-rejected';return finish();}
 // Every detached span receives real seabed/ground posts. No nominal height
 // substitutes or bottomless supports; only sampled load-bearing footprints.
 const supports=[],supportConflicts=[],railSpans=[];let lastDistance=-Infinity;
 for(const [i,t]of best.treads.entries()){if(i!==0&&i!==best.treads.length-1&&t.kind==='tread'&&t.distance-lastDistance<3)continue;lastDistance=t.distance;
  const probes=[];for(const dx of[-.45,0,.45])for(const dz of[-.45,0,.45]){const s=sampled(t.x+dx,t.z+dz);probes.push({x:t.x+dx,z:t.z+dz,...s});}if(probes.some(p=>p.ground===null||p.sea===null)){supportConflicts.push({id:'support-'+i,reason:'missing-actual-footing'});continue;}
  const bottom=Math.min(...probes.map(p=>p.ground))-.15,top=t.top-.20,poly=[[t.x-.45,t.z-.45],[t.x+.45,t.z-.45],[t.x+.45,t.z+.45],[t.x-.45,t.z+.45]];if(top-bottom>26){supportConflicts.push({id:'support-'+i,reason:'support-too-tall'});continue;}const conflicts=obstacles.filter(o=>top>o.minY&&bottom<o.maxY&&polygonOverlap(poly,o.polygon)).map(o=>o.id);if(dockSampleIndex&&conflicts.length&&conflicts.every(id=>id.startsWith('protected-rail-body-'))){railSpans.push({tread:i,distance:t.distance,reason:'reserved rail envelope remains open below deck'});continue;}supportConflicts.push(...conflicts.map(obstacle=>({id:'support-'+i,obstacle})));if(top-bottom>.12)supports.push({id:'support-'+i,distance:t.distance,x:t.x,z:t.z,bottom,top,polygon:poly,samples:probes,marine:probes.some(p=>p.ground<p.sea-.2)});
 }
 // Independent posts under both transition ends; rail remains unchanged.
 for(const fraction of[.15,.85]){const centre=[0,1,2].map(k=>(transition[0][k]+transition[3][k])/2*(1-fraction)+(transition[1][k]+transition[2][k])/2*fraction),poly=[[centre[0]-.35,centre[2]-.35],[centre[0]+.35,centre[2]-.35],[centre[0]+.35,centre[2]+.35],[centre[0]-.35,centre[2]+.35]],probes=poly.map(([x,z])=>({x,z,...sampled(x,z)})),id='transition-support-'+fraction;if(probes.some(p=>p.ground===null||p.sea===null)){supportConflicts.push({id,reason:'missing-actual-footing'});continue;}const bottom=Math.min(...probes.map(p=>p.ground))-.15,top=centre[1]-.18;if(top-bottom>26){supportConflicts.push({id,reason:'support-too-tall'});continue;}for(const o of obstacles)if(top>o.minY&&bottom<o.maxY&&polygonOverlap(poly,o.polygon))supportConflicts.push({id,obstacle:o.id});supports.push({id,x:centre[0],z:centre[2],bottom,top,polygon:poly,samples:probes,marine:probes.some(p=>p.ground<p.sea-.2)});}

 const arcadePlan=supportStyle==='stone-arcade'?planStoneArcades({supports,treads:best.treads,points:best.points,sample:sampled,obstacles,shipBounds}):{arches:[],replacements:new Map(),retired:new Set(),rejected:[],eligible:false};
 const originalSupports=supports.map(s=>({id:s.id,polygon:s.polygon,bottom:s.bottom,top:s.top,marine:s.marine}));for(let i=supports.length-1;i>=0;i--){if(arcadePlan.retired.has(supports[i].id))supports.splice(i,1);else if(arcadePlan.replacements.has(supports[i].id))supports[i]=arcadePlan.replacements.get(supports[i].id);}
 const areaOf=poly=>Math.abs(poly.reduce((sum,p,i)=>{const q=poly[(i+1)%poly.length];return sum+p[0]*q[1]-q[0]*p[1];},0))/2;
 report.supportArchitecture={originalPierPlanArea:originalSupports.reduce((n,s)=>n+areaOf(s.polygon),0),pierPlanArea:supports.reduce((n,s)=>n+areaOf(s.polygon),0),originalMarinePierPlanArea:originalSupports.filter(s=>s.marine).reduce((n,s)=>n+areaOf(s.polygon),0),marinePierPlanArea:supports.filter(s=>s.marine).reduce((n,s)=>n+areaOf(s.polygon),0),requested:supportStyle,applied:arcadePlan.arches.length?'stone-arcade':'posts',eligibleShortStraightFlight:arcadePlan.eligible,originalSupports,removedPostIds:[...arcadePlan.retired],arches:arcadePlan.arches,rejected:arcadePlan.rejected,terrainChanged:false,routeChanged:false,structuralEngineeringVerified:false,completeVesselRouteVerified:false};
 report.railOverpass={reservedTopClearance:1.2,skippedFootings:railSpans,spans:[],engineeringVerified:false};for(const skip of railSpans){const left=supports.filter(s=>Number.isFinite(s.distance)&&s.distance<skip.distance).at(-1),right=supports.find(s=>Number.isFinite(s.distance)&&s.distance>skip.distance);if(left&&right&&!report.railOverpass.spans.some(s=>s.left===left.id&&s.right===right.id))report.railOverpass.spans.push({left:left.id,right:right.id,length:right.distance-left.distance});if(!left||!right||right.distance-left.distance>10)supportConflicts.push({id:'unsupported-rail-span',tread:skip.tread,length:left&&right?right.distance-left.distance:null});}report.supports=supports;report.supportConflicts=supportConflicts;report.transition.railBearing='edge-to-edge actual promenade section; transition has two independent sampled posts, no original rail pier modified';
 if(supportConflicts.length){report.status='support-or-static-ship-rejected';return finish();}
 const broadPhase=[];for(const b of shipBounds){const matches=[...best.treads.map((t,i)=>({id:'tread-'+i,polygon:t.polygon,minY:t.top-.32,maxY:t.top+2})),...supports.map(s=>({...s,minY:s.bottom,maxY:s.top})),...arcadePlan.arches.map(a=>({...a})),...guardSides.map(s=>({id:'transition-guard-'+s.side,polygon:s.curb,minY:s.minY,maxY:s.maxY})),{id:'dock-transition',polygon:transitionPoly,minY:Math.min(...transition.map(p=>p[1]))-.32,maxY:Math.max(...transition.map(p=>p[1]))+2}].filter(v=>v.maxY>b.minY&&v.minY<b.maxY&&polygonOverlap(v.polygon,b.polygon));if(matches.length)broadPhase.push({ship:b.id,overlappingParts:matches.map(v=>v.id),conservative:true});}
 report.surfaceSamples=cache.size;report.shipAudit={broadPhase,triangles:[],currentPoseOnly:true,completeShippingLane:false};report.status='feasible-sampled-geometry-plan';report.buildRequested=build;if(!build){if(broadPhase.length)report.status='static-ship-broadphase-unresolved';return finish();}
 const stone=new T.MeshStandardMaterial({color:'#ebdcc0',roughness:.93}),trim=new T.MeshStandardMaterial({color:'#f2e5ca',roughness:.94});stone.userData.preserveCitadelMaterial=trim.userData.preserveCitadelMaterial=true;materials.push(stone,trim);
 function prism(poly,tops,bottoms){const pos=[],tri=(a,b,c)=>pos.push(...a,...b,...c),upper=poly.map((p,i)=>[p[0],tops[i],p[1]]),lower=poly.map((p,i)=>[p[0],bottoms[i],p[1]]);for(let i=1;i<poly.length-1;i++){tri(upper[0],upper[i+1],upper[i]);tri(lower[0],lower[i],lower[i+1]);}for(let i=0;i<poly.length;i++){const j=(i+1)%poly.length;tri(upper[i],upper[j],lower[j]);tri(upper[i],lower[j],lower[i]);}return pos;}
 function make(name,positions,material,walkable=false){const geo=new T.BufferGeometry();geo.setAttribute('position',new T.Float32BufferAttribute(positions,3));geo.computeVertexNormals();geometries.push(geo);const mesh=new T.Mesh(geo,material);mesh.name=name;mesh.castShadow=mesh.receiveShadow=true;mesh.userData={preserveCitadelMaterials:true,targetWalkable:walkable};group.add(mesh);return mesh;}
 const vertices=[],walkSurfaces=[];best.treads.forEach((t,i)=>{vertices.push(...prism(t.polygon,t.polygon.map(()=>t.top),t.polygon.map(()=>t.top-.32)));walkSurfaces.push({id:'old-waterfront-tread-'+i,polygon:t.polygon,topY:t.top,kind:t.kind});});const deck=make('old-waterfront-continuous-stair-decks',vertices,stone,true);
 // prism expects CCW XZ; normalise only the construction order, not endpoints.
 let dockPolygon=transition.slice();const area=dockPolygon.reduce((n,p,i)=>{const q=dockPolygon[(i+1)%4];return n+p[0]*q[2]-q[0]*p[2];},0);if(area<0)dockPolygon=[dockPolygon[0],dockPolygon[3],dockPolygon[2],dockPolygon[1]];const dockMesh=make('old-waterfront-twisted-rail-landing',prism(dockPolygon.map(p=>[p[0],p[2]]),dockPolygon.map(p=>p[1]),dockPolygon.map(p=>p[1]-.32)),stone,true);
 const guardVertices=[];for(const side of guardSides){guardVertices.push(...prism(side.curb,side.curbTop,side.curbTop.map(y=>y-.32)));guardVertices.push(...prism(side.wall,side.tops.map(p=>p[1]),side.feet.map(p=>p[1])));}const guardMesh=make('old-waterfront-twisted-landing-parapets',guardVertices,trim,false);guardMesh.userData.targetArchitecturalRole='non-walkable-parapet';
 const posts=[];for(const s of supports){s.topParts=[];for(const t of best.treads){const poly=clipPolygon(s.polygon,t.polygon);if(poly.length<3)continue;const heights=poly.map(()=>t.top-.2);s.topParts.push({polygon:poly,heights});posts.push(...prism(poly,heights,poly.map(()=>s.bottom)));}for(const tri of triangles){let poly=tri.map(p=>[p[0],p[2]]);const area=(poly[1][0]-poly[0][0])*(poly[2][1]-poly[0][1])-(poly[1][1]-poly[0][1])*(poly[2][0]-poly[0][0]);if(area<0)poly.reverse();poly=clipPolygon(s.polygon,poly);if(poly.length<3)continue;const [a,b,c]=tri.map(p=>new T.Vector3(...p)),n=b.clone().sub(a).cross(c.clone().sub(a)),heights=poly.map(([x,z])=>a.y-(n.x*(x-a.x)+n.z*(z-a.z))/n.y-.2);s.topParts.push({polygon:poly,heights});posts.push(...prism(poly,heights,poly.map(()=>s.bottom)));}}make('old-waterfront-actual-seabed-supports',posts,stone);
 const arcadeVertices=[];for(const arch of arcadePlan.arches){const at=(s,w)=>[arch.origin[0]+arch.u[0]*s+arch.n[0]*w,arch.origin[1]+arch.u[1]*s+arch.n[1]*w],soffit=p=>{const s=(p[0]-arch.origin[0])*arch.u[0]+(p[1]-arch.origin[1])*arch.u[1];return arch.spring+arch.rise*Math.sqrt(Math.max(0,1-((s-arch.length/2)/(arch.clearWidth/2))**2));};for(let i=0;i<arch.segments;i++){const a=arch.pierWidth/2+arch.clearWidth*i/arch.segments,b=arch.pierWidth/2+arch.clearWidth*(i+1)/arch.segments,strip=[at(a,-arch.depth/2),at(b,-arch.depth/2),at(b,arch.depth/2),at(a,arch.depth/2)];for(const tread of best.treads){const poly=clipPolygon(strip,tread.polygon);if(poly.length<3)continue;arcadeVertices.push(...prism(poly,poly.map(()=>tread.top-.2),poly.map(soffit)));}}}
 if(arcadeVertices.length){const m=make('old-waterfront-open-stone-support-arcades',arcadeVertices,stone,false);m.userData.targetArchitecturalRole='non-walkable-true-open-arcade';}
 const rails=[];for(const t of best.treads){if(t.distance<4)continue;for(const edge of t.sideEdges)for(let i=1;i<edge.length;i++){const a=edge[i-1],b=edge[i],dx=b[0]-a[0],dz=b[1]-a[1],len=Math.hypot(dx,dz);if(len<.02)continue;const nx=-dz/len*.045,nz=dx/len*.045,poly=[[a[0]-nx,a[1]-nz],[b[0]-nx,b[1]-nz],[b[0]+nx,b[1]+nz],[a[0]+nx,a[1]+nz]];const signed=poly.reduce((sum,p,j)=>{const q=poly[(j+1)%4];return sum+p[0]*q[1]-q[0]*p[1];},0);if(signed<0)poly.reverse();rails.push(...prism(poly,poly.map(()=>t.top+.95),poly.map(()=>t.top)));}}make('old-waterfront-side-parapets-open-ends',rails,trim);
 group.updateMatrixWorld(true);const testMaterial=new T.MeshBasicMaterial({side:T.DoubleSide}),proxies=group.children.map(m=>{const proxy=new T.Mesh(m.geometry,testMaterial);proxy.matrixAutoUpdate=false;proxy.matrixWorld.copy(m.matrixWorld);proxy.name=m.name;return proxy;}),ray=new T.Raycaster();const failures=[];let bodyRays=0,supportRays=0;
 const externalProxies=[];for(const external of collisionGroups){external.updateWorldMatrix(true,true);external.traverse(mesh=>{if(!mesh.isMesh)return;for(let p=mesh;p;p=p.parent)if(!p.visible)return;const matrix=inverse.clone().multiply(mesh.matrixWorld),add=m=>{const proxy=new T.Mesh(mesh.geometry,testMaterial);proxy.name=mesh.name;proxy.matrixAutoUpdate=false;proxy.matrixWorld.copy(m);externalProxies.push(proxy);};if(mesh.isInstancedMesh){const instance=new T.Matrix4();for(let i=0;i<mesh.count;i++){mesh.getMatrixAt(i,instance);if(Math.abs(instance.determinant())>1e-12)add(matrix.clone().multiply(instance));}}else add(matrix);});}const bodyProxies=[...proxies,...externalProxies];
 const path=[...best.walkPath,[...dock]];for(let i=1;i<path.length;i++){const a=new T.Vector3(...path[i-1]),b=new T.Vector3(...path[i]),delta=b.clone().sub(a),len=Math.hypot(delta.x,delta.z);if(len<.001)continue;const side=new T.Vector3(-delta.z/len,0,delta.x/len);for(const offset of[-1.2,-.4,0,.4,1.2])for(const h of[.55,1.2,1.8]){const A=a.clone().addScaledVector(side,offset).add(new T.Vector3(0,h,0)),B=b.clone().addScaledVector(side,offset).add(new T.Vector3(0,h,0)),d=B.sub(A);ray.set(A,d.clone().normalize());ray.near=.003;ray.far=d.length()-.003;bodyRays++;const hit=ray.intersectObjects(bodyProxies,false)[0];if(hit&&failures.length<12)failures.push({segment:i,offset,height:h,mesh:hit.object.name,external:externalProxies.includes(hit.object)});}}
 for(const t of best.treads)for(const probe of [{x:t.x,z:t.z},...t.samples.map(s=>({x:s.x*.99+t.x*.01,z:s.z*.99+t.z*.01}))]){ray.set(new T.Vector3(probe.x,t.top+.2,probe.z),new T.Vector3(0,-1,0));ray.near=0;ray.far=.3;supportRays++;const hit=ray.intersectObjects(proxies,false)[0];if(!hit||Math.abs(hit.point.y-t.top)>.025)failures.push({kind:'support-height',x:probe.x,z:probe.z,expected:t.top,actual:hit?.point.y??null});}for(const probe of transitionSamples){const p=probe.auditPosition;ray.set(new T.Vector3(p[0],p[1]+.2,p[2]),new T.Vector3(0,-1,0));ray.near=0;ray.far=.3;supportRays++;const hit=ray.intersectObjects(proxies,false)[0];if(!hit||Math.abs(hit.point.y-p[1])>.025)failures.push({kind:'transition-support-height',position:p,actual:hit?.point.y??null});}testMaterial.dispose();
 report.walkSurfaces=walkSurfaces;report.clearance={bodyRays,supportRays,failures,finiteOnly:true,externalTriangleCollisionVerified:false,externalBodyMeshes:externalProxies.length,externalBodyVerified:collisionGroups.length>0};report.performance={draws:group.children.length,triangles:group.children.reduce((n,m)=>n+m.geometry.attributes.position.count/3,0)};
 if(failures.length){report.status='own-geometry-clearance-rejected';dispose();return finish();}
 // Actual current-pose triangle crossings supplement conservative boxes.
 // This finite edge/triangle test does not prove containment, coplanar overlap,
 // vessel motion clearance or a navigable shipping corridor.
 const worldMatrix=castle.matrixWorld,meshRecords=group.children.map(mesh=>{const proxy=new T.Mesh(mesh.geometry,mesh.material);proxy.matrixAutoUpdate=false;proxy.matrixWorld.copy(worldMatrix);proxy.geometry.computeBoundingBox();return{mesh:proxy,box:proxy.geometry.boundingBox.clone().applyMatrix4(worldMatrix)};}),worldBox=new T.Box3();meshRecords.forEach(r=>worldBox.union(r.box));

 const shipTriangles=obstacleGroups.map((ship,i)=>{ship.updateWorldMatrix(true,true);const engine=createWarshipClearance(ship,[{box:worldBox,meshes:meshRecords}]),position=new T.Vector3(),quaternion=new T.Quaternion(),scale=new T.Vector3();ship.matrixWorld.decompose(position,quaternion,scale);return{index:i,ship:ship.name,triangleCount:engine.triangleCount,...engine.clear(position,quaternion,scale)};});
 report.shipAudit={broadPhase,triangles:shipTriangles,currentPoseOnly:true,completeShippingLane:false,triangleTestLimitations:['Triangle edge crossings only; coplanar overlap and full containment are not certified.','Positive broad phase with no triangle crossing remains unresolved, not cleared.']};
 if(broadPhase.length||shipTriangles.some(t=>!t.clear)){report.status=shipTriangles.some(t=>!t.clear)?'static-ship-triangle-conflict':'static-ship-broadphase-unresolved';dispose();return finish();}
 report.status='built-unaccepted-waterfront-stair-candidate';report.built=true;report.limitations.push('Static ship boxes are conservative. Caller still must audit actual current ship triangles and complete vessel routes.','No gameplay registration, continuous support proof or GPU review. Transition has a true slanted top, with open endpoints.','Transition guards are independent non-walkable meshes; external body checks only cover supplied collisionGroups, not complete dynamic navigation.');
 return finish();
}
