import * as T from 'three';
const inside=(x,z,p)=>{let c=false;for(let i=0,j=p.length-1;i<p.length;j=i++){const a=p[i],b=p[j];if((a[1]>z)!==(b[1]>z)&&x<(b[0]-a[0])*(z-a[1])/(b[1]-a[1])+a[0])c=!c;}return c;};
function hull(points){const p=points.sort((a,b)=>a[0]-b[0]||a[1]-b[1]),cross=(a,b,c)=>(b[0]-a[0])*(c[1]-a[1])-(b[1]-a[1])*(c[0]-a[0]);const lo=[],hi=[];for(const q of p){while(lo.length>1&&cross(lo.at(-2),lo.at(-1),q)<=0)lo.pop();lo.push(q);}for(const q of [...p].reverse()){while(hi.length>1&&cross(hi.at(-2),hi.at(-1),q)<=0)hi.pop();hi.push(q);}return lo.slice(0,-1).concat(hi.slice(0,-1));}
/** Offline/default-off exterior retreat. Projects the complete world vehicle
 * swept prisms into the castle heightfield, and extends each footprint ONLY
 * seaward. Actual public triangle projections retain their full vertical
 * support columns. This deliberately conservative 2.5D cut is NOT a certified
 * 3D boolean, structural analysis, or a release installer. */
export function createEastLoadedCliffCandidate({enabled=false,curves=[],castleMatrix,publicMeshes=[],sampleSea,landwardPoint=[62,76],sampleStep=1,landMargin=2.5,bearingMargin=.35,seaReach=40,domain={minX:60,maxX:108,minZ:54,maxZ:105}}={}){
 const report={version:'east-loaded-cliff-1',enabled,accepted:false,installed:false,changed:0,protected:0,maxDrop:0,protectedExamples:[],footprints:0,protectionTriangles:0,actorsVerified:false,waterWaveVerified:false};
 if(!enabled)return{height:(x,z,y)=>y,report};
 if(!castleMatrix?.isMatrix4||castleMatrix.elements.some(x=>!Number.isFinite(x))||Math.abs(castleMatrix.determinant())<1e-12||!curves.length||typeof sampleSea!=='function'||![sampleStep,landMargin,bearingMargin,seaReach,...landwardPoint,...Object.values(domain)].every(Number.isFinite)||sampleStep<=0||landMargin<0||bearingMargin<0||seaReach<=0)throw new TypeError('finite matrix, curves, sea and dimensions required');
 const inv=castleMatrix.clone().invert(),polygons=[],protectedFaces=[];
 for(const mesh of publicMeshes){if(!mesh?.isMesh||mesh.isInstancedMesh)throw new TypeError('explicit noninstanced public meshes required');const p=mesh.geometry.attributes.position,idx=mesh.geometry.index,m=inv.clone().multiply(mesh.matrixWorld);for(let i=0;i<(idx?.count??p.count);i+=3){const tri=[0,1,2].map(j=>new T.Vector3().fromBufferAttribute(p,idx?idx.getX(i+j):i+j).applyMatrix4(m));const poly=tri.map(q=>[q.x,q.z]);if(Math.abs((poly[1][0]-poly[0][0])*(poly[2][1]-poly[0][1])-(poly[1][1]-poly[0][1])*(poly[2][0]-poly[0][0]))>1e-8)protectedFaces.push({poly,minX:Math.min(...poly.map(p=>p[0]))-bearingMargin,maxX:Math.max(...poly.map(p=>p[0]))+bearingMargin,minZ:Math.min(...poly.map(p=>p[1]))-bearingMargin,maxZ:Math.max(...poly.map(p=>p[1]))+bearingMargin});}}
 // Explicit bearing margin around true triangle edges, not its AABB.
 // Caller must include its terrain-cell diagonal for vertex-only deformation.
 function protectedAt(x,z){return protectedFaces.some(f=>{if(x<f.minX||x>f.maxX||z<f.minZ||z>f.maxZ)return false;if(inside(x,z,f.poly))return true;return f.poly.some((a,i)=>{const b=f.poly[(i+1)%3],dx=b[0]-a[0],dz=b[1]-a[1],t=T.MathUtils.clamp(((x-a[0])*dx+(z-a[1])*dz)/(dx*dx+dz*dz),0,1);return Math.hypot(x-a[0]-t*dx,z-a[1]-t*dz)<=bearingMargin;});});}
 for(const curve of curves){const n=Math.ceil(curve.getLength()/sampleStep);for(let i=0;i<=n;i++){const p=curve.getPointAt(i/n),l=p.clone().applyMatrix4(inv);if(l.x<domain.minX||l.x>domain.maxX||l.z<domain.minZ||l.z>domain.maxZ)continue;const t=curve.getTangentAt(i/n).normalize(),right=p.clone().normalize().cross(t).normalize(),up=t.clone().cross(right).normalize(),lr=right.clone().transformDirection(inv),sign=Math.sign(lr.x*(landwardPoint[0]-l.x)+lr.z*(landwardPoint[1]-l.z))||1,points=[];for(const dx of[-2.32-seaReach,2.32+landMargin])for(const dz of[-3.49-sampleStep,3.49+sampleStep])for(const h of[-.6,5.71]){const q=p.clone().addScaledVector(right,sign*dx).addScaledVector(t,dz).addScaledVector(up,h).applyMatrix4(inv);points.push([q.x,q.z]);}polygons.push(hull(points));}}
 report.footprints=polygons.length;report.protectionTriangles=protectedFaces.length;
 function height(x,z,y){if(![x,z,y].every(Number.isFinite))throw new TypeError('finite chart query required');if(x<domain.minX||x>domain.maxX||z<domain.minZ||z>domain.maxZ||!polygons.some(p=>inside(x,z,p)))return y;const sea=sampleSea(x,z);if(!Number.isFinite(sea)){report.missingSea=(report.missingSea??0)+1;return y;}if(y<=sea-3)return y;if(protectedAt(x,z)){report.protected++;if(report.protectedExamples.length<20)report.protectedExamples.push({x,z,y});return y;}const next=sea-3;report.changed++;report.maxDrop=Math.max(report.maxDrop,y-next);return next;}
 return{height,report,polygons,protectedAt};
}
