import * as T from 'three';
const EPS=1e-8,area=p=>p.reduce((s,a,i)=>{const b=p[(i+1)%p.length];return s+a[0]*b[1]-b[0]*a[1];},0)/2;
const orient=p=>area(p)<0?[...p].reverse():p;
function half(p,a,b,sign){const out=[],d=q=>sign*((b[0]-a[0])*(q[1]-a[1])-(b[1]-a[1])*(q[0]-a[0]));for(let i=0;i<p.length;i++){const x=p[i],y=p[(i+1)%p.length],u=d(x),v=d(y);if(u>=-EPS)out.push(x);if((u>EPS&&v<-EPS)||(u<-EPS&&v>EPS)){const t=u/(u-v);out.push([x[0]+t*(y[0]-x[0]),x[1]+t*(y[1]-x[1])]);}}return out.filter((p,i)=>!i||Math.hypot(p[0]-out[i-1][0],p[1]-out[i-1][1])>EPS);}
function split(subject,clip){let remainder=subject;const outside=[];for(let i=0;i<clip.length&&remainder.length>=3;i++){const a=clip[i],b=clip[(i+1)%clip.length],q=half(remainder,a,b,-1);if(q.length>=3&&Math.abs(area(q))>EPS)outside.push(q);remainder=half(remainder,a,b,1);}return{inside:remainder.length>=3&&Math.abs(area(remainder))>EPS?remainder:null,outside};}
const box=p=>({x0:Math.min(...p.map(p=>p[0])),x1:Math.max(...p.map(p=>p[0])),z0:Math.min(...p.map(p=>p[1])),z1:Math.max(...p.map(p=>p[1]))});
const overlap=(a,b)=>a.x0<=b.x1+EPS&&a.x1>=b.x0-EPS&&a.z0<=b.z1+EPS&&a.z1>=b.z0-EPS;
/** Isolated, closed, exact-face-constrained cliff patch. This does NOT replace
 * the live terrain or join the patch boundary to a surrounding world mesh.
 * Original top-face barycentric height is preserved on protected footprints;
 * cutting inserts exact boundary vertices and vertical rock faces. */
export function buildEastCliffRemeshPatch({enabled=false,topTriangles=[],protectedTriangles=[],cutPolygons=[],bounds,seaAt,floor=-70,floorAt=null,sourceHeightAt=null,bearingMargin=.05}={}){
 const bottom=(x,z)=>floorAt?floorAt(x,z):floor;
 const report={version:'east-cliff-remesh-patch-1',enabled,accepted:false,installed:false,isolatedPatch:true,worldSeamJoined:false};if(!enabled)return{geometry:null,report};
 if(!bounds||!Object.values(bounds).every(Number.isFinite)||bounds.minX>=bounds.maxX||bounds.minZ>=bounds.maxZ||!Number.isFinite(floor)||typeof seaAt!=='function')throw new TypeError('finite patch bounds/floor and actual sea required');
 const domain=[[bounds.minX,bounds.minZ],[bounds.maxX,bounds.minZ],[bounds.maxX,bounds.maxZ],[bounds.minX,bounds.maxZ]],pieces=[];
 const expand=p=>p.map((q,i)=>{if(!bearingMargin)return q;const a=p[(i+p.length-1)%p.length],b=p[(i+1)%p.length],u=[q[0]-a[0],q[1]-a[1]],v=[b[0]-q[0],b[1]-q[1]],l=Math.hypot(...u),r=Math.hypot(...v),n=[u[1]/l,-u[0]/l],m=[v[1]/r,-v[0]/r],k=bearingMargin/Math.max(1e-8,1+n[0]*m[0]+n[1]*m[1]);return[q[0]+k*(n[0]+m[0]),q[1]+k*(n[1]+m[1])];});
 const protects=protectedTriangles.map(t=>orient(t.map(p=>[p[0],p[2]]))).filter(p=>Math.abs(area(p))>EPS).map(expand).filter(p=>Math.abs(area(p))>EPS).map(p=>({p,b:box(p)}));
 const cuts=cutPolygons.map(orient).map(p=>({p,b:box(p)}));
 function extractUnion(polygons,clips){const matched=[];let pending=polygons;for(const c of clips){const next=[];for(const p of pending){if(!overlap(box(p),c.b)){next.push(p);continue;}const s=split(p,c.p);if(s.inside)matched.push(s.inside);next.push(...s.outside);}pending=next;}return{matched,pending};}
 for(const tri of topTriangles){if(tri.length!==3||tri.flat().some(n=>!Number.isFinite(n)))throw new TypeError('finite source triangles required');const poly=orient(tri.map(p=>[p[0],p[2]]));if(Math.abs(area(poly))<EPS)continue;const q=split(poly,domain).inside;if(!q)continue;const[a,b,c]=tri,den=(b[2]-c[2])*(a[0]-c[0])+(c[0]-b[0])*(a[2]-c[2]);const old=(x,z)=>{if(sourceHeightAt)return sourceHeightAt(x,z);const u=((b[2]-c[2])*(x-c[0])+(c[0]-b[0])*(z-c[2]))/den,v=((c[2]-a[2])*(x-c[0])+(a[0]-c[0])*(z-c[2]))/den;return u*a[1]+v*b[1]+(1-u-v)*c[1];};
 const cut=extractUnion([q],cuts);for(const p of cut.pending)pieces.push({p,height:old,cut:false});const protection=extractUnion(cut.matched,protects);for(const p of protection.matched)pieces.push({p,height:old,cut:false});for(const p of protection.pending)pieces.push({p,height:(x,z)=>{const sea=seaAt(x,z);if(!Number.isFinite(sea))throw new Error('missing actual sea within cut patch');return Math.min(old(x,z),sea-3);},cut:true});}
 // Split every polygon edge at shared 2D vertices, including T-junctions from
 // adjacent source/protection faces. Isolated patch is deliberately small.
  const points=new Map(),key=p=>p.map(v=>v.toFixed(7)).join(',');for(const piece of pieces)for(const p of piece.p)points.set(key(p),p);const all=[...points.values()];
 for(const piece of pieces){const p=[];for(let i=0;i<piece.p.length;i++){const a=piece.p[i],b=piece.p[(i+1)%piece.p.length],dx=b[0]-a[0],dz=b[1]-a[1],len=dx*dx+dz*dz;const edge=all.map(q=>({q,t:((q[0]-a[0])*dx+(q[1]-a[1])*dz)/len,c:Math.abs(dx*(q[1]-a[1])-dz*(q[0]-a[0]))})).filter(q=>q.t>=-EPS&&q.t<1-EPS&&q.c<1e-7*Math.sqrt(len)).sort((a,b)=>a.t-b.t);p.push(...edge.map(q=>q.q));}piece.p=p;}
 const positions=[],indices=[],vertices=new Map(),edges=new Map();let minArea=Infinity;
 function vertex(p,y){if(!Number.isFinite(y)||y<bottom(...p)-EPS)throw new Error('patch top below floor');const k=[p[0],y,p[1]].map(v=>v.toFixed(7)).join(',');if(!vertices.has(k)){vertices.set(k,positions.length/3);positions.push(p[0],y,p[1]);}return vertices.get(k);}
 function triangle(a,b,c){if(a===b||b===c||a===c)return;const va=new T.Vector3().fromArray(positions,a*3),vb=new T.Vector3().fromArray(positions,b*3),vc=new T.Vector3().fromArray(positions,c*3),ar=vb.sub(va).cross(vc.sub(va)).length()/2;if(ar<1e-9)return;indices.push(a,b,c);minArea=Math.min(minArea,ar);}
 for(const piece of pieces){const p=piece.p;if(p.length<3)continue;const center=p.reduce((r,q)=>[r[0]+q[0]/p.length,r[1]+q[1]/p.length],[0,0]),ct=vertex(center,piece.height(...center)),cb=vertex(center,bottom(...center));for(let i=0;i<p.length;i++){const a=p[i],b=p[(i+1)%p.length],ay=piece.height(...a),by=piece.height(...b);triangle(ct,vertex(b,by),vertex(a,ay));triangle(cb,vertex(a,bottom(...a)),vertex(b,bottom(...b)));const ka=key(a),kb=key(b),k=ka<kb?ka+'|'+kb:kb+'|'+ka;if(!edges.has(k))edges.set(k,[]);edges.get(k).push({a,b,ay,by});}}
 function wall(ids){const ring=[];for(let i=0;i<ids.length;i++){const a=new T.Vector3().fromArray(positions,ids[i]*3),b=new T.Vector3().fromArray(positions,ids[(i+1)%ids.length]*3),ab=b.clone().sub(a),len=ab.lengthSq();if(len<EPS)continue;const candidates=[];for(let j=0;j<positions.length/3;j++){const q=new T.Vector3().fromArray(positions,j*3).sub(a),t=q.dot(ab)/len;if(t>=-EPS&&t<1-EPS&&q.clone().addScaledVector(ab,-t).length()<1e-7)candidates.push({j,t});}candidates.sort((a,b)=>a.t-b.t);ring.push(...candidates.map(x=>x.j));}const c=ring.reduce((s,i)=>s.add(new T.Vector3().fromArray(positions,i*3)),new T.Vector3()).multiplyScalar(1/ring.length),ci=vertex([c.x,c.z],c.y);for(let i=0;i<ring.length;i++)triangle(ci,ring[i],ring[(i+1)%ring.length]);}
 let wallEdges=0;for(const use of edges.values()){if(use.length>2)throw new Error('overlapping top partition');let a=use[0],b=use[1];if(b&&a.ay+a.by<b.ay+b.by)[a,b]=[b,a];const lowA=b?(key(a.a)===key(b.a)?b.ay:b.by):bottom(...a.a),lowB=b?(key(a.b)===key(b.a)?b.ay:b.by):bottom(...a.b);if(Math.abs(a.ay-lowA)<EPS&&Math.abs(a.by-lowB)<EPS)continue;wall([vertex(a.a,a.ay),vertex(a.b,a.by),vertex(a.b,lowB),vertex(a.a,lowA)]);wallEdges++;}
 const origin=[(bounds.minX+bounds.maxX)/2,0,(bounds.minZ+bounds.maxZ)/2],localPositions=positions.map((n,i)=>n-origin[i%3]);const geometry=new T.BufferGeometry();geometry.setAttribute('position',new T.Float32BufferAttribute(localPositions,3));geometry.setIndex(indices);geometry.computeVertexNormals();geometry.computeBoundingBox();geometry.computeBoundingSphere();const edgeCounts=new Map();let signedVolume=0;for(let i=0;i<indices.length;i+=3){const ids=indices.slice(i,i+3);for(let j=0;j<3;j++){const a=ids[j],b=ids[(j+1)%3],k=a<b?a+','+b:b+','+a;edgeCounts.set(k,(edgeCounts.get(k)??0)+1);}const[a,b,c]=ids.map(i=>new T.Vector3().fromArray(positions,i*3));signedVolume+=a.dot(b.cross(c))/6;}
 let floatCollapsed=0,minFloatArea=Infinity;for(let i=0;i<indices.length;i+=3){const[a,b,c]=indices.slice(i,i+3).map(k=>new T.Vector3().fromBufferAttribute(geometry.attributes.position,k)),ar=b.sub(a).cross(c.sub(a)).length()/2;if(ar<=1e-12)floatCollapsed++;minFloatArea=Math.min(minFloatArea,ar);}
 Object.assign(report,{geometryOrigin:origin,floatCollapsed,minFloatArea,pieces:pieces.length,triangles:indices.length/3,vertices:positions.length/3,wallEdges,minArea,signedVolume,nonManifoldEdges:[...edgeCounts.values()].filter(n=>n!==2).length,closed:[...edgeCounts.values()].every(n=>n===2)});return{geometry,origin,report};
}
