import{chromium}from'/Users/panglaohu/Downloads/TigerInBamboo/tools/shot/node_modules/playwright/index.mjs';import{writeFileSync}from'node:fs';const dir='/Users/panglaohu/Downloads/TigerInBamboo/TigerMessenger/artifacts/pipeline/robot-mobile-fire';const b=await chromium.launch({channel:'chrome',headless:true,args:['--use-angle=metal']}),p=await b.newPage({viewport:{width:1400,height:900}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://localhost:8931/TigerMessenger/?autostart=1&baseReview=1');await p.waitForFunction(()=>window.__tm?.robotOperations,{timeout:90000});const result=await p.evaluate(async()=>{const t=__tm,T=t.THREE,o=t.robotOperations,l=o.logistics,tram=t.messenger.landmarks.tramSystem,base=t.messenger.landmarks.bookshop.userData.steampunkRobots;const{createBaseDefense}=await import('/TigerMessenger/src/gameplay/robotOps/baseDefense.js');const{seatTownObject,townSurfacePoint}=await import('/TigerMessenger/src/world/bookshopTownSite.js');
// A visible test target is used only in this isolated browser, never production code.
const enemy=new T.Mesh(new T.SphereGeometry(.8),new T.MeshBasicMaterial({color:0xff5544}));enemy.name='validation-target';t.scene.add(enemy);enemy.userData.robotHullHealth=100000;
const original=base.userData.models,clones=original.map(m=>{const c=m.clone(true);base.add(c);return c;});base.userData.models=clones;clones.forEach((m,i)=>seatTownObject(base,m,-14+i*14,37,0));enemy.position.copy(base.localToWorld(townSurfacePoint(base,0,62))).setLength(166);const defense=createBaseDefense({scene:t.scene,base,logistics:l,models:new Map(),combat:o.combat,getFleet:()=>({userData:{members:[enemy]}}),getAssault:()=>null});const starts=clones.map(m=>m.getWorldPosition(new T.Vector3()));for(let n=0;n<100;n++)defense.update(.05);const ground={...defense.snapshot(),movement:clones.map((m,i)=>({kind:m.userData.robotType,metres:m.getWorldPosition(new T.Vector3()).distanceTo(starts[i]),animation:m.userData.mobileFire}))};clones.forEach(m=>m.removeFromParent());base.userData.models=original;enemy.visible=false;
for(const m of t.messenger.landmarks.aircraftSquad?.userData.members||[])m.visible=false;t.scene.getObjectByName('vanguard-squad')?.traverse(m=>{m.visible=false;});
for(let n=0;n<3000;n++){tram.update(.5);o.update(.5);if(['red','blue'].every(id=>l.trains[id].slots.filter(Boolean).length===9&&l.trains[id].slots.every(x=>l.get(x)?.status==='transit')))break;}
tram.seekFreight('red',.15);o.update(0);const models=new Map([...o.models].filter(([id])=>l.get(id)?.train==='red'));const savedDisplay=base.userData.models;base.userData.models=[];const trainDefense=createBaseDefense({scene:t.scene,base,logistics:l,models,combat:o.combat,getFleet:()=>({userData:{members:[enemy]}}),getAssault:()=>null});enemy.visible=true;const mounted=[];
for(const kind of['locust','ant','beetle']){const m=[...models.values()].find(m=>m.userData.robotType===kind),before=trainDefense.snapshot(),progress=tram.freightServices[0].progress;if(!m)throw Error(JSON.stringify({missing:kind,trains:l.trains,units:l.units.map(u=>({id:u.id,kind:u.kind,status:u.status,defending:u.defending})),message:o.message}));let maxAnchorError=0;for(let n=0;n<100;n++){tram.update(.05);o.update(.05);const expected=m.position.clone();enemy.position.copy(m.localToWorld(new T.Vector3(0,4,22)));enemy.userData.robotHullHealth=100000;trainDefense.update(.05);maxAnchorError=Math.max(maxAnchorError,m.position.distanceTo(expected));}mounted.push({kind,shots:trainDefense.snapshot().weaponEffects[kind]-before.weaponEffects[kind],progressChanged:tram.freightServices[0].progress!==progress,maxAnchorError,animation:m.userData.mobileFire});}
base.userData.models=savedDisplay;t.cameraRig.update=()=>{};const car=tram.freightServices[0].wagons[4];t.camera.position.copy(car.localToWorld(new T.Vector3(0,20,-40)));t.camera.up.copy(car.position).normalize();t.camera.lookAt(car.position);t.camera.updateMatrixWorld();t.renderer.render(t.scene,t.camera);const image=t.renderer.domElement.toDataURL();return{ground,mounted,train:trainDefense.snapshot(),errors:[],image};});writeFileSync(dir+'/transport-fire.png',Buffer.from(result.image.split(',')[1],'base64'));delete result.image;writeFileSync(dir+'/check.json',JSON.stringify({result,errors},null,2));console.log(JSON.stringify({result,errors}));await b.close();
