import {chromium} from '/Users/panglaohu/Downloads/TigerInBamboo/tools/shot/node_modules/playwright/index.mjs';
import {writeFile} from 'node:fs/promises';
const out='TigerMessenger/artifacts/pipeline/crystal-core-review',b=await chromium.launch({channel:'chrome',headless:true,args:['--use-angle=metal']});
try{const p=await b.newPage({viewport:{width:1200,height:800}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://localhost:8931/TigerMessenger/?autostart=1',{waitUntil:'domcontentloaded'});await p.waitForFunction(()=>window.__tm?.messenger?.landmarks?.tramSystem,null,{timeout:180000});await p.waitForTimeout(2000);
const data=await p.evaluate(async()=>{const t=window.__tm,T=t.THREE,l=t.messenger.landmarks,{dirToCityLocal}=await import('/TigerMessenger/src/world/crystalCityLayout.js');t.cameraRig.update=()=>{};t.P.daySpeed=0;t.P.timeOfDay=.38;t.scene.updateMatrixWorld(true);const swamp=l.moebiusSwamp.userData.inner||l.moebiusSwamp,focus=swamp.localToWorld(new T.Vector3(-4,35,-3)),water=swamp.localToWorld(new T.Vector3(0,25,0)),rows=[],tracks={};
for(const color of['red','blue']){const cv=l.tramSystem.curves[color],sign=color==='red'?1:-1;tracks[color]=[];for(let i=0;i<=600;i++){const u=.20+i/600*.22,v=cv.getPointAt(u);tracks[color].push({u,...dirToCityLocal(v.clone().normalize())});}for(const u of[.27,.30,.33]){const eye=cv.getPointAt(u),up=eye.clone().normalize(),fwd=cv.getTangentAt(u).multiplyScalar(sign),to=focus.clone().sub(eye),ground=to.clone().addScaledVector(up,-to.dot(up)).normalize(),right=new T.Vector3().crossVectors(fwd,up).normalize();rows.push({color,u,eye:eye.clone().addScaledVector(up,2.5).toArray(),up:up.toArray(),fwd:fwd.toArray(),distance:eye.distanceTo(focus),trackRadius:eye.length(),waterRadius:water.length(),side:to.dot(right)>0?'right':'left',bearing:Math.atan2(to.dot(right),to.dot(fwd))*180/Math.PI,elevation:Math.asin(to.clone().normalize().dot(up))*180/Math.PI});}}
window.coreView=(i,forward)=>{const v=rows[i],eye=new T.Vector3(...v.eye),up=new T.Vector3(...v.up);t.camera.position.copy(eye);t.camera.up.copy(up);t.camera.lookAt(forward?eye.clone().addScaledVector(new T.Vector3(...v.fwd),40):focus);t.camera.fov=65;t.camera.updateProjectionMatrix();t.distanceCulling.recollect();t.distanceCulling.update(3);};return {towers:l.moebius.crystals.map((r,i)=>({i,lx:r.lx,lz:r.lz})),swamp:dirToCityLocal(water.clone().normalize()),tracks,rows};});
for(let i=0;i<data.rows.length;i++)for(const forward of[false,true]){await p.evaluate(([i,f])=>window.coreView(i,f),[i,forward]);await p.waitForTimeout(300);const img=await p.evaluate(()=>{const t=window.__tm;t.renderer.render(t.scene,t.camera);return t.renderer.domElement.toDataURL()});const v=data.rows[i];await writeFile(`${out}/${v.color}-${v.u}-${forward?'forward':'core'}.png`,Buffer.from(img.split(',')[1],'base64'));}
data.errors=errors;await writeFile(out+'/survey.json',JSON.stringify(data,null,2));console.log(JSON.stringify({rows:data.rows,errors}));}finally{await b.close();}
