"""Central assets inventory including out-of-catalog modelling and runtime geometry."""
import json,re,hashlib
from pathlib import Path
root=Path(__file__).resolve().parents[2]
base=root/'assets/models';archive=base/'originals'
ledger=json.loads((archive/'source-ledger.json').read_text())
moves={r['original']:r['canonical'] for r in json.loads((base/'source-moves.json').read_text())}
splits={r['original']:r for r in json.loads((base/'source-splits.json').read_text())}
catalog=json.loads((archive/'catalog.json').read_text())
rows=[]
def group(path):
    p=path.lower()
    if any(x in p for x in ['swamp','tiger','whale']):return '湖沼与生物'
    if any(x in p for x in ['citadel','highland','town','gate']):return '圣城与建筑'
    if any(x in p for x in ['saihoji','moss','garden','pine']):return '苔庭与植被'
    if any(x in p for x in ['tram','airship','aircraft','boat','craft','pod']):return '载具'
    if any(x in p for x in ['player','messenger','paper','trooper','flock','bird']):return '角色与鸟群'
    if any(x in p for x in ['render','ui/','core/','weather','cloud','fx']):return '渲染与辅助几何'
    return '地形与场景构件'
for item in ledger:
    if not item['geometryConstructors']:continue
    path=item['path'];canonical=moves.get(path,path)
    if path in splits:canonical=splits[path]['canonical']
    auxiliary=path.startswith(('src/core/','src/ui/','src/render/','src/story/','src/procgen/'))
    exports=[e['name'] for e in item['exports']]
    if canonical!=path:
        exports=re.findall(r'export\s+(?:function|const|class)\s+(\w+)',(root/canonical).read_text())
    row={'id':path.removeprefix('src/').removesuffix('.js').replace('/','__'),'category':group(path),'originalSource':path,'canonicalSource':canonical,'exports':exports,'geometry':item['geometryConstructors'],'sourceStatus':'model extracted; behavior remains in world' if path in splits else 'moved to assets; compatibility entry retained' if path in moves else 'already in assets' if path.startswith('src/assets/') else 'runtime/helper; assets entry only' if auxiliary else 'mixed module; extraction pending','reading':item['review'],'blenderStatus':'per-model capture required; source module is not a single mesh'}
    if path in moves or path in splits or path == 'src/assets/bookshop.js':
        row['reading']='reviewed for extraction or geometry-preserving optimization'
    rows.append(row)
manifest={'version':1,'scope':'Original authored assets; generated shader/debug geometry is distinguished from authored models','sources':rows,'catalog':[]}
for c in catalog:
    ident=c['id'];revision='blender-r3/' if (archive/'blender-r3'/f'{ident}.blend').exists() else ''
    report=archive/f'{revision}{ident}.import-report.json'
    imported=json.loads(report.read_text()) if report.exists() else None
    manifest['catalog'].append({'id':ident,'label':c['label'],'sourceSnapshot':f'originals/{ident}.source.json','blend':f'originals/{revision}{ident}.blend' if (archive/f'{revision}{ident}.blend').exists() else None,'importReport':imported,'optimization':json.loads((base/'optimized'/f'{ident}.optimization.json').read_text()) if (base/'optimized'/f'{ident}.optimization.json').exists() else 'pending','runtimeReplacement':False})
    item=manifest['catalog'][-1]
    item['runtimeReplacement']=isinstance(item['optimization'],dict) and item['optimization'].get('runtimeIntegrated',False)
    candidate=base/'optimized/batch-candidates-v2'/f'{ident}.json'
    if candidate.exists():
        details=json.loads(candidate.read_text())
        item['batchCandidate']={'blend':f'optimized/batch-candidates-v2/{ident}.blend','changedMeshes':details.get('changedMeshes',0),'status':'candidate only; source review, visual parity and runtime integration pending'}
manifest['generationSupport']=[{'source':r['path'],'exports':[e['name'] for e in r['exports']],'status':'generation rules/data; review pending'} for r in ledger if not r['geometryConstructors'] and (r['path'].startswith('src/procgen/') or r['path'].startswith('src/world/citadel/'))]
(base/'inventory.json').write_text(json.dumps(manifest,ensure_ascii=False,indent=2))
# All model-producing source modules can be discovered from one assets entry.
js=['// Generated by tools/originals/build_inventory.py. Lazy loaders preserve runtime ownership.','export const ORIGINAL_MODEL_SOURCES = Object.freeze({']
import os
entry=root/'src/assets/originalSources.js'
for r in rows:
    rel=os.path.relpath(root/r['canonicalSource'],entry.parent).replace(os.sep,'/')
    if not rel.startswith('.'):rel='./'+rel
    js.append(f'  {json.dumps(r["id"])}: {{ source: {json.dumps(r["canonicalSource"])}, load: () => import({json.dumps(rel)}) }},')
js+=['});','']
entry.write_text('\n'.join(js))
md=['# 全量模型与几何来源清单','',f'覆盖 {len(rows)} 个几何来源模块，以及原地图目录的 {len(catalog)} 项资产。不是所有来源都是独立模型；调试线、天气粒子和碰撞辅助网格单列，避免误作建筑模型。','', '## 原地图资产（Blender 工作入口）','', '| 原资产 | ID | 原作快照 | Blender 导入 | 优化/回接 |','|---|---|---|---|---|']
for r in manifest['catalog']:
    blend=f'[打开]({r["blend"]})' if r['blend'] else '待导入'
    state='几何整理已回接 Web；像素对照通过；待用户验收' if r['runtimeReplacement'] else '重复顶点整理完成；未回接' if isinstance(r['optimization'],dict) else '待优化、未替换原作'
    if not r['runtimeReplacement'] and r.get('batchCandidate'):
        state=f'[批量候选]({r["batchCandidate"]["blend"]})；待视觉/动画验证与回接'
    md.append(f'| {r["label"]} | {r["id"]} | [原数据]({r["sourceSnapshot"]}) | {blend} | {state} |')
md+=['','## 全量来源（含目录外模型）','','| 分组 | 原代码 | 资产层位置 / 当前来源 | 导出入口 | 状态 |','|---|---|---|---|---|']
for r in rows:md.append(f'| {r["category"]} | `{r["originalSource"]}` | `{r["canonicalSource"]}` | {", ".join(r["exports"])} | {r["sourceStatus"]} |')
md+=['','## 程序生成与拼装规则（不直接创建 Three 网格）','','这些规则也属于原作的一部分，不因没有 Mesh 构造器而遗漏。它们保留为生成逻辑，不能简单转换成单个 Blender 模型。','','| 来源 | 导出入口 | 状态 |','|---|---|---|']
for r in manifest['generationSupport']:md.append(f'| `{r["source"]}` | {", ".join(r["exports"])} | 待读取与模型映射 |')
(base/'全量模型清单.md').write_text('\n'.join(md)+'\n')
print('INVENTORY_OK',len(rows),'source modules;',len(catalog),'catalog assets;',sum(bool(r['blend']) for r in manifest['catalog']),'Blender archives')
