"""Export the authored Blender building into the existing synchronous Web factory.

Read the saved v3 copy in BACKGROUND Blender. Never save it or touch the foreground
session. Preserve the game's terrain adapter, editable sign material and ink shader;
the evaluated building meshes/transforms and new joinery come from Blender.
"""
import bpy
import hashlib
import json
import math
from pathlib import Path
from mathutils import Matrix

root = Path(__file__).resolve().parents[2]
source = root / 'assets/models/optimized/bookshop-art-v3.blend'
bpy.ops.wm.open_mainfile(filepath=str(source))
scene = bpy.data.scenes['Bookshop Art V1']
bpy.context.window.scene = scene
shop = next(o for o in scene.objects if o.name == 'hard-to-find-bookshop' and o.parent is None)
original = json.loads(bpy.data.texts[scene['source_text']].as_string())
objects = {o['three_node_id']: o for o in [shop, *shop.children_recursive] if 'three_node_id' in o}
assert len(objects) == len(original['nodes'])
C = Matrix.Rotation(math.pi / 2, 4, 'X')
inverse = C.inverted()
depsgraph = bpy.context.evaluated_depsgraph_get()

def array(matrix):
    return [round(matrix[row][col], 8) for col in range(4) for row in range(4)]

def geometry(ob, transform=None):
    evaluated = ob.evaluated_get(depsgraph)
    mesh = evaluated.to_mesh()
    mesh.calc_loop_triangles()
    transform = transform or inverse
    normal_matrix = transform.to_3x3().inverted().transposed()
    attrs = {'position': [], 'normal': []}
    uv = mesh.uv_layers.active
    if uv:
        attrs['uv'] = []
    for triangle in mesh.loop_triangles:
        for li in triangle.loops:
            vi = mesh.loops[li].vertex_index
            attrs['position'].extend(transform @ mesh.vertices[vi].co)
            attrs['normal'].extend((normal_matrix @ mesh.corner_normals[li].vector).normalized())
            if uv:
                attrs['uv'].extend(uv.data[li].uv)
    evaluated.to_mesh_clear()
    return {k: [round(v, 7) for v in values] for k, values in attrs.items()}

records = []
for n in original['nodes']:
    ob = objects[n['id']]
    record = {k: n[k] for k in ['id', 'name', 'type']}
    # Ground is sampled/adapted by the live world; studio terrain is not portable.
    is_ground = n['id'] in ['n0', 'n1', 'n2', 'n3', 'n4']
    if not is_ground and not n.get('userData', {}).get('isOutline'):
        record['matrix'] = array(inverse @ ob.matrix_local @ C)
        if ob.type == 'MESH':
            record['geometry'] = geometry(ob)
    records.append(record)

# Merge the 50 small Blender frame members into one static draw. Their placement
# is evaluated from the real Blender hierarchy (including the moved windows).
joinery = {'position': [], 'normal': []}
frame_objects = [o for o in shop.children_recursive if 'three_node_id' not in o and o.type == 'MESH']
assert len(frame_objects) == 50
for ob in frame_objects:
    attrs = geometry(ob, inverse @ shop.matrix_world.inverted() @ ob.matrix_world)
    for key in joinery:
        joinery[key].extend(attrs[key])
material = frame_objects[0].data.materials[0]
data = {
    'version': 3,
    'source': str(source.relative_to(root)),
    'sha256': hashlib.sha256(source.read_bytes()).hexdigest(),
    'nodes': records,
    'joinery': {'geometry': joinery, 'color': list(material.diffuse_color[:3]), 'members': len(frame_objects)},
    'preservedRuntime': ['terrain berm', 'editable sign', 'toon materials', 'brush outlines', 'hydrangeas', 'collider and quest references'],
}
output = root / 'assets/models/optimized/bookshopArtGeometryData.js'
output.write_text('// Generated by export_bookshop_art_runtime.py from the saved Blender v3 model.\nexport default ' + json.dumps(data, separators=(',', ':')) + ';\n')
report = {
    'source': data['source'], 'sha256': data['sha256'], 'output': str(output.relative_to(root)),
    'buildingMeshes': sum('geometry' in n for n in records),
    'joineryMembers': len(frame_objects), 'joineryDrawCalls': 1,
    'triangles': sum(len(n.get('geometry', {}).get('position', [])) // 9 for n in records) + len(joinery['position']) // 9,
    'bytes': output.stat().st_size, 'sourceModified': False, 'preservedRuntime': data['preservedRuntime'],
}
folder = root / 'artifacts/bookshop-integration'
folder.mkdir(exist_ok=True)
(folder / 'web-export.json').write_text(json.dumps(report, indent=2))
print('BOOKSHOP_ART_EXPORT_OK', json.dumps(report))
