import assert from 'node:assert/strict';import fs from 'node:fs';
import * as T from '../../vendor/three.module.js';
import {createMountainCloudBanksCandidate,TARGET_CITY_CLOUD_FRONTS} from '../../src/world/citadel/mountainCloudBanksCandidate.js';
import {buildMountainSurfaceIndex} from '../../src/world/citadel/mountainSurfaceIndex.js';
import {canopyClearOfConstraints} from '../../src/world/citadel/mountainCanopyCandidate.js';
const castle=new T.Group();castle.quaternion.setFromEuler(new T.Euler(.25,.3,-.15));castle.position.copy(new T.Vector3(0,175,0).applyQuaternion(castle.quaternion));
const g=new T.PlaneGeometry(250,190,64,48);g.rotateX(-Math.PI/2);const pos=g.attributes.position;for(let i=0;i<pos.count;i++)pos.setY(i,12+Math.sin(pos.getX(i)*.022)*4+Math.cos(pos.getZ(i)*.031)*3);g.computeVertexNormals();const rock=new T.Mesh(g,new T.MeshBasicMaterial({side:T.DoubleSide}));rock.name='test-final-cloud-ridge';castle.add(rock);castle.updateMatrixWorld(true);
const source=Array.from(pos.array),index=buildMountainSurfaceIndex([rock]),boxes=[new T.Box3(new T.Vector3(-25,0,-15),new T.Vector3(15,40,15)).applyMatrix4(castle.matrixWorld)],rail=[];for(let x=-110;x<110;x+=4)rail.push(castle.localToWorld(new T.Vector3(x,12,28)));
assert.equal(createMountainCloudBanksCandidate(castle).group,null);assert.throws(()=>createMountainCloudBanksCandidate(castle,{enabled:true}),/surfaceIndex/);
assert.throws(()=>createMountainCloudBanksCandidate(castle,{enabled:true,surfaceIndex:index,clusteredComposition:true}),/actual sampleSea/);
const opts={enabled:true,surfaceIndex:index,protectedBoxes:boxes,rail},start=performance.now(),result=createMountainCloudBanksCandidate(castle,opts),buildMs=performance.now()-start;assert.ok(result.report.count>0);assert.ok(result.report.count<=8);assert.equal(castle.children.length,1);castle.add(result.group);castle.updateMatrixWorld(true);
const ray=new T.Raycaster(),down=new T.Vector3(0,-1,0).transformDirection(castle.matrixWorld),inv=castle.matrixWorld.clone().invert();let samples=0,maxSupportError=0;
for(const bank of result.report.banks){const b=new T.Box3(new T.Vector3(...bank.sweptBounds.min),new T.Vector3(...bank.sweptBounds.max));assert.ok(canopyClearOfConstraints(b,boxes,rail,4,6));for(const p of bank.path){const world=new T.Vector3(...p.world),local=world.clone().applyMatrix4(inv),origin=new T.Vector3(local.x,160,local.z).applyMatrix4(castle.matrixWorld);ray.set(origin,down);const h=ray.intersectObject(rock,false)[0];assert.ok(h);maxSupportError=Math.max(maxSupportError,h.point.distanceTo(world));samples++;}}
assert.ok(maxSupportError<1e-5);
assert.equal(new Set(result.report.banks.map(b=>b.cluster)).size,3);
for(const cluster of result.report.composition.clusters){assert.ok(result.report.banks.filter(b=>b.cluster===cluster.id).length<=cluster.quota);}
assert.ok(result.report.banks.every(b=>b.local[2]<-16));
for(const bank of result.report.banks){
 assert.ok(bank.lobeCount>=3&&bank.lobeCount<=5);assert.ok(bank.minimumSampledClearance>=2-1e-6);
 const b=new T.Box3(new T.Vector3(...bank.localSweptBounds.min),new T.Vector3(...bank.localSweptBounds.max));
 for(const f of TARGET_CITY_CLOUD_FRONTS)assert.equal(b.intersectsBox(new T.Box3(new T.Vector3(...f.min),new T.Vector3(...f.max))),false);
 const size=b.getSize(new T.Vector3());assert.ok(size.x<=38&&size.z<=38&&size.y<=20);
}
result.update(0);const p0=result.group.children.map(m=>m.position.clone());result.update(10);assert.ok(result.group.children.every((m,i)=>m.position.distanceTo(p0[i])>.1));

// A straight centreline and positive rings prevent the former tight-bend tube folds.
for(const mesh of result.group.children){const p=mesh.geometry.attributes.position,centres=[];for(let r=0;r<p.count/20;r++){const c=new T.Vector3();for(let k=0;k<20;k++)c.add(new T.Vector3().fromBufferAttribute(p,r*20+k));centres.push(c.multiplyScalar(1/20));}const a=centres[0],chord=centres.at(-1).clone().sub(a),dir=chord.clone().normalize();let previous=-Infinity;for(const c of centres){const d=c.clone().sub(a),along=d.dot(dir);assert.ok(along>=previous-1e-4);assert.ok(d.addScaledVector(dir,-along).length()<.1);previous=along;}}
let maxMotion=0;for(let t=0;t<400;t+=7){result.update(t);castle.updateMatrixWorld(true);result.group.children.forEach((m,i)=>{const swept=new T.Box3(new T.Vector3(...result.report.banks[i].sweptBounds.min),new T.Vector3(...result.report.banks[i].sweptBounds.max)),actual=m.geometry.boundingBox.clone().applyMatrix4(m.matrixWorld);assert.ok(swept.clone().expandByScalar(1e-5).containsBox(actual));assert.ok(m.material.depthTest&&m.material.depthWrite&&!m.material.alphaHash&&!m.material.transparent&&m.material.opacity===1);maxMotion=Math.max(maxMotion,m.position.length());});}
result.update(100);const positions=result.group.children.map(m=>m.position.toArray());result.update(3);result.update(100);assert.deepEqual(result.group.children.map(m=>m.position.toArray()),positions);assert.deepEqual(Array.from(pos.array),source);
const repeat=createMountainCloudBanksCandidate(castle,opts);repeat.update(100);assert.deepEqual(repeat.report.banks,result.report.banks);repeat.dispose();
// Every bank crosses the old reset point without popping or alpha stipple.
for(const t of [0,result.report.period*(1-.2),result.report.period*2]){
 result.update(t-1e-4);const before=result.group.children.map(m=>m.position.clone());result.update(t+1e-4);result.group.children.forEach((m,i)=>{assert(m.position.distanceTo(before[i])<=result.report.speed*.0002+1e-8);assert.equal(m.material.opacity,1);});
}

// CPU source contract only. Actual renderer shader compilation and alpha-depth view remain UI tests.
result.update(100,.5);const noonOpacity=result.report.opacity,noonColor=result.group.children[0].material.color.clone();result.update(100,0);assert.equal(result.report.opacity,noonOpacity);assert(result.group.children[0].material.color.r<noonColor.r);result.update(100,.5);assert.equal(result.report.opacity,noonOpacity);assert(result.group.children[0].material.color.equals(noonColor));assert(result.group.children.every(m=>m.material.vertexColors));
const summary={pass:true,fixture:'rotated castle, final undulating terrain, protected building box and railway',count:result.report.count,triangles:result.report.triangles,drawCalls:result.report.drawCalls,buildMs,pathSamples:samples,maxSupportError,maxMotion,deterministic:true,absoluteTime:true,sourceUnchanged:true,sweptBoundsPassed:true,shaderGPU:'not tested; actual browser required',rejected:result.report.rejected,clusters:Object.fromEntries(result.report.composition.clusters.map(c=>[c.id,result.report.banks.filter(b=>b.cluster===c.id).length]))};
fs.mkdirSync(new URL('../../artifacts/pipeline/citadel-four-hour-20261005/',import.meta.url),{recursive:true});fs.writeFileSync(new URL('../../artifacts/pipeline/citadel-four-hour-20261005/cloud-banks-candidate-test.json',import.meta.url),JSON.stringify(summary,null,2));console.log(JSON.stringify(summary,null,2));result.dispose();

import {compileOfficialOcean} from '../../src/world/waterV8/officialOcean.js';
import {applyTargetTerrainCandidate} from '../../src/world/citadel/targetTerrainCandidate.js';
function frozenScene() {
  const scene = new T.Group(), castle = new T.Group(); scene.add(castle);
  castle.matrixAutoUpdate = false;
  castle.matrix.fromArray([-.5771265090244172,.12463062405961449,.807088718870361,0,.6354855835814281,.689249750214348,.3479839865419536,0,-.5129162364767383,.7137240288626759,-.4769852670498,0,124.43456408079132,72.61606956254715,90.15650671642375,1]);
  const source = new T.Mesh(new T.BoxGeometry(), new T.MeshBasicMaterial({side: T.DoubleSide}));
  source.name = 'citadel-oskar-grid-mountain-surface'; castle.add(source);
  const previous = globalThis.location;
  globalThis.location = {search: '?citadelTerrainFirst=1&citadelTargetRemesh=1&citadelTerraceAprons=1&citadelRecessedSaddle=1&citadelValleyBenches=1'};
  try {const obsolete = source.geometry; applyTargetTerrainCandidate(castle); obsolete.dispose();}
  finally {if (previous === undefined) delete globalThis.location; else globalThis.location = previous;}
  const compiled = compileOfficialOcean().ocean, geometry = new T.BufferGeometry();
  geometry.setAttribute('position', new T.BufferAttribute(compiled.positions, 3));
  geometry.setIndex(new T.BufferAttribute(compiled.indices, 1)); geometry.computeVertexNormals();
  const ocean = new T.Mesh(geometry, new T.MeshBasicMaterial({side: T.DoubleSide})); ocean.name = 'planet-v8-curved-ocean'; scene.add(ocean);
  const originalBuilding = new T.Group(); originalBuilding.name = 'old-city-preserved'; castle.add(originalBuilding);
  scene.updateMatrixWorld(true);
  return {scene, castle, source, ocean, originalBuilding, dispose() {for (const m of [source, ocean]) {m.geometry.dispose(); m.material.dispose();}}};
}

{const f=frozenScene(),si=buildMountainSurfaceIndex([f.source]),oi=buildMountainSurfaceIndex([f.ocean]),inv=f.castle.matrixWorld.clone().invert(),down=new T.Vector3(0,-1,0).transformDirection(f.castle.matrixWorld),ray=new T.Ray(),before=[...f.source.geometry.attributes.position.array];const sampleSea=(x,z)=>{ray.set(new T.Vector3(x,160,z).applyMatrix4(f.castle.matrixWorld),down);const hit=oi.sample(ray,0,500);return hit?{height:hit.point.clone().applyMatrix4(inv).y}:null;};const started=performance.now(),clouds=createMountainCloudBanksCandidate(f.castle,{enabled:true,surfaceIndex:si,sampleSea,maxBanks:8}),buildMs=performance.now()-started;const data={pass:clouds.report.count>0,fixture:'full frozen r17 asymmetric shoulder and actual compiled ocean triangle index',buildMs,...clouds.report};console.log(JSON.stringify({seaMode:true,count:data.count,rejected:data.rejected,centres:data.banks.map(b=>({cluster:b.cluster,local:b.local,box:b.localSweptBounds,lift:b.lift}))}));assert.ok(data.count>=3,'at least three real rear bands must survive');assert.ok(data.triangles<=20000);assert.ok(data.drawCalls<=12);assert.equal(new Set(data.banks.map(b=>b.cluster)).size,3);assert.ok(clouds.group.children.every(m=>m.geometry.boundingBox.max.x-m.geometry.boundingBox.min.x<33));for(const mesh of clouds.group.children){const p=mesh.geometry.attributes.position,tops=[];for(let ring=0;ring<p.count/20;ring++){let top=-Infinity;for(let k=0;k<20;k++)top=Math.max(top,p.getY(ring*20+k));tops.push(top);}const peaks=tops.map((v,i)=>i>1&&i<tops.length-2&&v>tops[i-1]&&v>tops[i+1]?i:-1).filter(i=>i>=0);assert.ok(peaks.length>=2,'cumulus must have multiple unequal top peaks');assert.ok(Math.max(...tops)-Math.min(...tops)>2,'rounded lobes retain real volume');const crest=tops.indexOf(Math.max(...tops));assert.ok(crest>0&&crest<tops.length-1);assert.ok(tops[crest]-Math.max(tops[crest-1],tops[crest+1])<.18,'highest crown must be broad, not a one-ring spike');assert.ok(mesh.geometry.boundingBox.getSize(new T.Vector3()).y/mesh.geometry.boundingBox.getSize(new T.Vector3()).x<.4,'cloud should be an oblate bank, not a conical peak');const index=mesh.geometry.index,edges=new Map();for(let i=0;i<index.count;i+=3)for(let k=0;k<3;k++){const a=index.getX(i+k),b=index.getX(i+(k+1)%3),key=a<b?a+','+b:b+','+a;edges.set(key,(edges.get(key)||0)+1);}assert.ok([...edges.values()].every(n=>n===2),'single closed cloud shell');}assert.ok(new Set(data.banks.map(b=>b.lobeCount)).size>1,'banks must not repeat one identical lobe count');assert.ok(new Set(data.banks.map(b=>b.bankScale.width.toFixed(3))).size>=3,'bank thickness varies deterministically');
for(const mesh of clouds.group.children){const p=mesh.geometry.attributes.position;for(const start of[0,p.count-20]){const cap=new T.Box3();for(let k=0;k<20;k++)cap.expandByPoint(new T.Vector3().fromBufferAttribute(p,start+k));assert.ok(cap.getSize(new T.Vector3()).length()<.03,'end must close to a rounded tip, not a broad flat end plate');}}
assert.ok(clouds.group.children.every(m=>m.material.isMeshStandardMaterial&&m.material.depthWrite&&!m.material.transparent&&!m.material.alphaHash),'opaque normal-lit volume avoids translucent duplicate edges');assert.ok(data.banks.every(b=>b.bankScale.length<1),'v13 retains bounded bank lengths');data.shapeChecks={normalLit:true,multiPeak:true,closedIndexedShell:true,internalTransparentLobes:false,variableBankThickness:true,variableLobeCount:true,smallEndCaps:true};f.castle.add(clouds.group);for(let time=0;time<80;time+=.7){clouds.update(time);f.castle.updateMatrixWorld(true);for(let i=0;i<clouds.group.children.length;i++){const actual=clouds.group.children[i].geometry.boundingBox.clone().applyMatrix4(clouds.group.children[i].matrixWorld),b=data.banks[i].sweptBounds;assert.ok(new T.Box3(new T.Vector3(...b.min),new T.Vector3(...b.max)).expandByScalar(1e-4).containsBox(actual));}}const obstacles=new T.Group(),block=new T.Mesh(new T.BoxGeometry(400,400,400),new T.MeshBasicMaterial());obstacles.add(block);f.castle.add(obstacles);const refused=createMountainCloudBanksCandidate(f.castle,{enabled:true,surfaceIndex:si,sampleSea,protectedBoxes:[new T.Box3(new T.Vector3(-200,-200,-200),new T.Vector3(200,200,200)).applyMatrix4(f.castle.matrixWorld)]});assert.equal(refused.report.count,0);refused.dispose();obstacles.removeFromParent();block.geometry.dispose();block.material.dispose();assert.ok(data.banks.every(b=>b.surfaceMisses===0&&b.minimumSampledClearance>=2-1e-5));clouds.update(0);const points=clouds.group.children.map(m=>m.position.clone());clouds.update(10);assert.ok(clouds.group.children.every((m,i)=>m.position.distanceTo(points[i])>.1));assert.deepEqual([...f.source.geometry.attributes.position.array],before);
const clustered=createMountainCloudBanksCandidate(f.castle,{enabled:true,surfaceIndex:si,sampleSea,maxBanks:9,clusteredComposition:true});
console.log('CLUSTER',JSON.stringify({banks:clustered.report.banks.map(b=>({cluster:b.cluster,member:b.member,local:b.local})),rejected:clustered.report.rejected}));assert(clustered.report.count>=6&&clustered.report.count<=9,'rear groups need multiple surviving banks');
assert(clustered.report.triangles<=20000&&clustered.report.drawCalls<=9);
for(const cl of clustered.report.composition.clusters){const banks=clustered.report.banks.filter(b=>b.cluster===cl.id);assert(banks.length>=2,'each group has depth layers');assert(new Set(banks.map(b=>b.member)).size===banks.length);assert(Math.max(...banks.map(b=>b.local[2]))-Math.min(...banks.map(b=>b.local[2]))>=9);}
assert(clustered.report.banks.every(b=>b.surfaceMisses===0&&b.minimumSampledClearance>=2-1e-5));
f.castle.add(clustered.group);clustered.update(0);const starts=clustered.group.children.map(m=>m.position.clone());clustered.update(10);assert(clustered.group.children.every((m,i)=>m.position.distanceTo(starts[i])>.1));
for(let t=0;t<100;t+=1.9){clustered.update(t);f.castle.updateMatrixWorld(true);clustered.group.children.forEach((m,i)=>{const b=clustered.report.banks[i].sweptBounds;assert(new T.Box3(new T.Vector3(...b.min),new T.Vector3(...b.max)).expandByScalar(1e-4).containsBox(m.geometry.boundingBox.clone().applyMatrix4(m.matrixWorld)));});}
assert.deepEqual([...f.source.geometry.attributes.position.array],before);
fs.mkdirSync(new URL('../../artifacts/pipeline/citadel-cloud-clusters-20261006/',import.meta.url),{recursive:true});fs.writeFileSync(new URL('../../artifacts/pipeline/citadel-cloud-clusters-20261006/fixture.json',import.meta.url),JSON.stringify(clustered.report,null,2));clustered.dispose();assert.equal(clustered.group.children.length,0);
fs.writeFileSync(new URL('../../artifacts/pipeline/citadel-four-hour-20261005/cloud-banks-r17-test.json',import.meta.url),JSON.stringify(data,null,2));clouds.dispose();f.dispose();}

