import assert from 'node:assert/strict';
import * as T from '../../vendor/three.module.js';
import {addMountainGroundcover} from '../../src/world/citadel/mountainGroundcover.js';
import {buildMountainSurfaceIndex} from '../../src/world/citadel/mountainSurfaceIndex.js';
globalThis.location={search:'?citadelTurfPass=6'};
const castle=new T.Group();castle.position.y=175;castle.rotation.set(.03,.12,-.02);castle.scale.set(1.2,.9,1.1);
const geo=new T.PlaneGeometry(28,24,7,6);geo.rotateX(-Math.PI/2);geo.translate(-10,0,-9);const a=geo.attributes.position;for(let i=0;i<a.count;i++)a.setY(i,Math.sin(a.getX(i)*.08)*.2);geo.computeVertexNormals();const n=geo.attributes.normal;for(let i=0;i<n.count;i++)n.setXYZ(i,n.getX(i)*2,n.getY(i)*2,n.getZ(i)*2);
const rock=new T.Mesh(geo,new T.MeshBasicMaterial({side:T.DoubleSide}));rock.name='citadel-oskar-grid-mountain-surface';castle.add(rock);const root=new T.Group();castle.add(root);castle.updateMatrixWorld(true);const before=JSON.stringify(Array.from(a.array)),index=buildMountainSurfaceIndex([rock]);const report=addMountainGroundcover(root,[rock],{radius:160,rail:[],protectedBoxes:[],surfaceIndex:index});root.updateMatrixWorld(true);const turf=root.getObjectByName('citadel-study-groundcover'),p=turf.geometry.attributes.position,norm=turf.geometry.attributes.normal,col=turf.geometry.attributes.color,ray=new T.Ray(),nm=new T.Matrix3().getNormalMatrix(rock.matrixWorld),toRoot=new T.Matrix3().getNormalMatrix(root.matrixWorld.clone().invert());let maxGap=0,maxNormal=0,duplicates=0;const shared=new Map();
for(let i=0;i<p.count;i++){const w=new T.Vector3().fromBufferAttribute(p,i).applyMatrix4(root.matrixWorld),up=w.clone().normalize();ray.set(w.clone().addScaledVector(up,130),up.clone().negate());let hit=index.sample(ray,0,260);if(!hit){let best=Infinity;for(let k=0;k<geo.index.count;k+=3){const ids=[0,1,2].map(j=>geo.index.getX(k+j)),tri=new T.Triangle(...ids.map(j=>new T.Vector3().fromBufferAttribute(a,j).applyMatrix4(rock.matrixWorld))),point=tri.closestPointToPoint(w,new T.Vector3()),distance=point.distanceTo(w);if(distance<best){best=distance;hit={point,face:{a:ids[0],b:ids[1],c:ids[2]}};}}assert.ok(best<1e-5,'Float32 boundary vertex must stay on original triangle within 10 micrometres');}maxGap=Math.max(maxGap,Math.abs(w.length()-hit.point.length()));const f=hit.face,vs=[f.a,f.b,f.c].map(j=>new T.Vector3().fromBufferAttribute(a,j).applyMatrix4(rock.matrixWorld)),b=new T.Triangle(...vs).getBarycoord(w,new T.Vector3()),expected=new T.Vector3();[f.a,f.b,f.c].forEach((j,k)=>expected.addScaledVector(new T.Vector3().fromBufferAttribute(n,j).normalize().applyMatrix3(nm).normalize(),b.getComponent(k)));expected.normalize();if(expected.dot(up)<0)expected.negate();expected.applyMatrix3(toRoot).normalize();maxNormal=Math.max(maxNormal,expected.distanceTo(new T.Vector3().fromBufferAttribute(norm,i)));const key=w.toArray().map(x=>Math.round(x*1e4)).join(',');if(shared.has(key)){duplicates++;assert.ok(shared.get(key).distanceTo(new T.Vector3().fromBufferAttribute(col,i))<1e-5);}else shared.set(key,new T.Vector3().fromBufferAttribute(col,i));}
assert.ok(p.count>0);assert.ok(maxGap<1e-5);assert.ok(maxNormal<1e-5);assert.equal(JSON.stringify(Array.from(a.array)),before);assert.ok(report.refinement.splitEdgesPerLevel.length<=2);assert.ok(report.refinement.splitEdgesPerLevel.reduce((s,n)=>s+n,0)<=6000);
const grass=root.getObjectByName('citadel-study-meadow-grass');assert.ok(grass&&!grass.isInstancedMesh);let maxGrassGap=0;const gp=grass.geometry.attributes.position;for(let i=0;i<gp.count;i+=3)for(const j of[i,i+1]){const w=new T.Vector3().fromBufferAttribute(gp,j).applyMatrix4(grass.matrixWorld),up=w.clone().normalize();ray.set(w.clone().addScaledVector(up,130),up.clone().negate());const hit=index.sample(ray,0,260);assert.ok(hit);maxGrassGap=Math.max(maxGrassGap,Math.abs(w.length()-hit.point.length()));}assert.ok(maxGrassGap<1e-5);console.log(JSON.stringify({pass:true,triangles:p.count/3,maxGap,maxNormal,duplicates,grassBasePoints:gp.count/3*2,maxGrassGap,refinement:report.refinement},null,2));
