import fs from 'node:fs';import crypto from 'node:crypto';import {performance} from 'node:perf_hooks';import assert from 'node:assert/strict';import * as T from '../../vendor/three.module.js';import {insetMountainTurf} from '../../src/world/citadel/mountainTurfInset.js';
const path=new URL('../../artifacts/pipeline/citadel-five-hour-20261005/r12-overview-day-cloud-plants-turf-geometry.json',import.meta.url),raw=fs.readFileSync(path),hash=crypto.createHash('sha256').update(raw).digest('hex'),data=JSON.parse(raw),source=[];for(const mesh of data.meshes){const matrix=new T.Matrix4().fromArray(mesh.matrixWorld),count=mesh.index?.length??mesh.positions.length/3;for(let i=0;i<count;i+=3)source.push(new T.Triangle(...[0,1,2].map(j=>new T.Vector3().fromArray(mesh.positions,(mesh.index?mesh.index[i+j]:i+j)*3).applyMatrix4(matrix))));}const before=JSON.stringify(source),start=performance.now();const result=insetMountainTurf(source);console.log(JSON.stringify({generationMs:performance.now()-start,stats:{...result.stats,items:undefined}}));
let maxSupportGap=0;for(const o of result.output)for(const p of[o.triangle.a,o.triangle.b,o.triangle.c])maxSupportGap=Math.max(maxSupportGap,source[o.source].closestPointToPoint(p,new T.Vector3()).distanceTo(p));assert.ok(maxSupportGap<1e-5);assert.equal(JSON.stringify(source),before);assert.equal(crypto.createHash('sha256').update(fs.readFileSync(path)).digest('hex'),hash);
const inv=new T.Matrix4().fromArray(data.castleMatrix).invert();function region(tris,x0,x1,z0,z1){let area=0,count=0;for(const tri of tris){let poly=[tri.a,tri.b,tri.c].map(p=>({w:p,l:p.clone().applyMatrix4(inv)}));for(const [axis,bound,sign]of [['x',x0,1],['x',x1,-1],['z',z0,1],['z',z1,-1]]){const next=[];for(let i=0;i<poly.length;i++){const a=poly[i],b=poly[(i+1)%poly.length],da=(a.l[axis]-bound)*sign,db=(b.l[axis]-bound)*sign;if(da>=0)next.push(a);if((da>=0)!==(db>=0)){const t=da/(da-db);next.push({w:a.w.clone().lerp(b.w,t),l:a.l.clone().lerp(b.l,t)});}}poly=next;}if(poly.length>=3){count++;for(let i=1;i+1<poly.length;i++)area+=new T.Triangle(poly[0].w,poly[i].w,poly[i+1].w).getArea();}}return {area,count,method:'exact world triangle area after castle-local rectangle polygon clipping'};}

const regions={};for(const[name,bounds]of Object.entries({left:[-32,-4,-26,0],leftCore:[-21,-14,-16,-12],right:[32,58,-35,-8]}))regions[name]={before:region(source,...bounds),after:region(result.output.map(o=>o.triangle),...bounds)};
// Independent component/edge extraction and boundary probe test. This checks
// seven actual points per output triangle, separate from production exact test.
const edgeKey=(a,b)=>[a,b].map(v=>v.toArray().map(x=>Math.round(x*1e4)).join(',')).sort().join('|'),parents=source.map((_,i)=>i),find=i=>{while(parents[i]!==i){parents[i]=parents[parents[i]];i=parents[i];}return i;},edges=new Map();source.forEach((tri,i)=>{const vs=[tri.a,tri.b,tri.c];for(let j=0;j<3;j++){const k=edgeKey(vs[j],vs[(j+1)%3]),old=edges.get(k);if(old){parents[find(i)]=find(old.i);old.count++;}else edges.set(k,{i,a:vs[j],b:vs[(j+1)%3],count:1});}});const bins=new Map(),cell=1,margin=.250001;for(const e of edges.values())if(e.count===1){const comp=find(e.i),box=new T.Box3().setFromPoints([e.a,e.b]).expandByScalar(margin),line=new T.Line3(e.a,e.b);for(let x=Math.floor(box.min.x/cell);x<=Math.floor(box.max.x/cell);x++)for(let y=Math.floor(box.min.y/cell);y<=Math.floor(box.max.y/cell);y++)for(let z=Math.floor(box.min.z/cell);z<=Math.floor(box.max.z/cell);z++){const key=`${comp}:${x},${y},${z}`;if(!bins.has(key))bins.set(key,[]);bins.get(key).push(line);}}let probes=0,minimum=Infinity;const scratch=new T.Vector3();for(const o of result.output){const tri=o.triangle,comp=find(o.source);for(const p of[tri.a,tri.b,tri.c,tri.a.clone().add(tri.b).multiplyScalar(.5),tri.b.clone().add(tri.c).multiplyScalar(.5),tri.c.clone().add(tri.a).multiplyScalar(.5),tri.getMidpoint(new T.Vector3())]){probes++;for(const line of bins.get(`${comp}:${Math.floor(p.x/cell)},${Math.floor(p.y/cell)},${Math.floor(p.z/cell)}`)||[])minimum=Math.min(minimum,line.closestPointToPoint(p,true,scratch).distanceTo(p));}}assert.ok(minimum>=.25-1e-7);const independentBoundary={probes,minimum,threshold:.25,tolerance:1e-7,method:'independently reconstructed shared-edge components and expanded-segment spatial bins; all output vertices/edge midpoints/centroids; continuous guarantee additionally provided by generation exact triangle-segment check'};
const report={input:path.pathname,inputSHA256:hash,elapsedMs:performance.now()-start,maxSupportGap,sourceUnchanged:true,independentBoundary,regions,stats:result.stats};fs.writeFileSync(new URL('../../artifacts/pipeline/citadel-five-hour-20261005/turf4-actual-geometry-audit.json',import.meta.url),JSON.stringify(report,null,2));console.log(JSON.stringify({pass:true,regions,maxSupportGap,elapsedMs:report.elapsedMs}));
