import{chromium}from'/Users/panglaohu/Downloads/TigerInBamboo/tools/shot/node_modules/playwright/index.mjs';import{writeFile}from'node:fs/promises';
const dir='artifacts/pipeline/base-four-hour';const b=await chromium.launch({channel:'chrome',headless:true,args:['--use-angle=metal']});try{
 const p=await b.newPage({viewport:{width:1600,height:1000}}),errors=[],stages=[];p.on('pageerror',e=>errors.push(e.stack));await p.goto('http://localhost:8931/TigerMessenger/?autostart=1&baseReview=1&robotOps=1');await p.waitForFunction(()=>window.__tm?.robotOperations,null,{timeout:180000});await p.waitForTimeout(1500);const start=p.getByRole('button',{name:'开始送信',exact:true});if(await start.isVisible())await start.click();
 const preparation=await p.evaluate(()=>{
  const o=__tm.robotOperations,t=__tm.messenger.landmarks.tramSystem;o.panel.element.hidden=true;o.logistics.update(271);o.update(.01);
  for(const kind of['locust','ant','beetle']){const s=t.freightServices[0],load=s.loadingStops.find(x=>x.name===kind);t.seekFreight('red',load.progress-.001);t.update(1);o.update(38);const unload=s.loadingStops.find(x=>x.name==='frontline');t.seekFreight('red',unload.progress-.001);t.update(1);o.update(62);}
  const units=o.combat.units.filter(u=>u.team==='friendly');o.combat.command(units.map(u=>u.id),'cease');window.actors={locust:units.filter(u=>u.kind==='locust'),ant:units.filter(u=>u.kind==='ant'),beetle:units.filter(u=>u.kind==='beetle')};
  units.forEach((u,i)=>{u.x=-21+i*5.2;u.z=12;u.heading=Math.PI;});
  o.startExercise();for(const e of o.combat.units.filter(u=>u.team==='enemy'))e.order={type:'cease'};
  const camera=()=>{const T=__tm.THREE,field=o.field,focus=window.combatFocus||{x:0,z:-2};const target=field.localToWorld(new T.Vector3(focus.x,1,focus.z)),eye=field.localToWorld(new T.Vector3(focus.x+11,13,focus.z+19));__tm.camera.position.copy(eye);__tm.camera.up.copy(target.clone().normalize());__tm.camera.lookAt(target);__tm.camera.updateMatrixWorld();};o.updateCamera=camera;
  return{invariants:o.logistics.assertInvariants(),ids:units.map(u=>({id:u.id,kind:u.kind}))};
 });
 const stage=async name=>{await p.waitForTimeout(100);const image=await p.evaluate(()=>{__tm.renderer.render(__tm.scene,__tm.camera);return __tm.renderer.domElement.toDataURL('image/png').split(',')[1]});await writeFile(`${dir}/combat-${name}.png`,Buffer.from(image,'base64'));stages.push(await p.evaluate(name=>({name,combat:__tm.robotOperations.combat.snapshot(),effects:__tm.robotOperations.snapshot().effects,invariants:__tm.robotOperations.logistics.assertInvariants()}),name));};
 await p.evaluate(()=>{const chunks=[],r=new MediaRecorder(__tm.renderer.domElement.captureStream(15),{mimeType:'video/webm',videoBitsPerSecond:2300000});r.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};window.combatVideo=new Promise(resolve=>r.onstop=()=>resolve(new Blob(chunks,{type:'video/webm'})));window.combatRecorder=r;r.start(1000);});
 await p.evaluate(()=>{const c=__tm.robotOperations.combat,u=actors.locust[0];u.x=-17;u.z=0;u.heading=Math.PI;window.combatFocus={x:-15,z:-4};c.command([u.id],'hold');c.skill(u);});await p.waitForTimeout(6500);await stage('locust-braced');
 await p.evaluate(()=>{const c=__tm.robotOperations.combat;c.command([actors.locust[0].id],'cease');const u=actors.ant[0];u.x=14;u.z=-5;u.heading=Math.PI;window.combatFocus={x:14,z:-7};c.command([u.id],'hold');});await p.waitForTimeout(4500);await stage('ant-cannon');
 await p.evaluate(()=>{const c=__tm.robotOperations.combat,u=actors.ant[0];c.skill(u);c.command([u.id],'retreat');});await p.waitForTimeout(1400);await stage('ant-steam');await p.waitForTimeout(5100);
 await p.evaluate(()=>{const c=__tm.robotOperations.combat,u=actors.beetle[0];u.x=20;u.z=2;u.heading=Math.PI;window.combatFocus={x:17,z:-4};c.skill(u);c.command([u.id],'move',{x:20,z:-10});});await p.waitForTimeout(3000);await stage('beetle-moving');await p.waitForTimeout(2500);
 await p.evaluate(()=>{const o=__tm.robotOperations,c=o.combat;window.combatFocus={x:0,z:1};o.panel.open();const u=actors.locust[0];u.hp=220;u.damageParts.legs=.78;});await p.waitForTimeout(1500);await p.screenshot({path:`${dir}/combat-panel.png`});await stage('retreat');
 const video=await p.evaluate(async()=>{combatRecorder.stop();return Array.from(new Uint8Array(await(await combatVideo).arrayBuffer()));});await writeFile(`${dir}/combat-review.webm`,Buffer.from(video));
 const final=await p.evaluate(()=>{const o=__tm.robotOperations;return{invariants:o.logistics.assertInvariants(),events:o.combat.events,save:o.save(),restore:o.load()}});await writeFile(`${dir}/combat-review.json`,JSON.stringify({mode:'actual runtime models; production and loading accelerated for setup, skill chapters use the normal game clock; enemy turrets held for readable demonstration',preparation,stages,final,errors},null,2));console.log(JSON.stringify({preparation,stages:stages.map(s=>({name:s.name,effects:s.effects})),final,errors}));
}finally{await b.close()}
