import{chromium}from'/Users/panglaohu/Downloads/TigerInBamboo/tools/shot/node_modules/playwright/index.mjs';import{writeFile}from'node:fs/promises';
const b=await chromium.launch({channel:'chrome',headless:true,args:['--use-angle=metal']});try{const p=await b.newPage({viewport:{width:1600,height:1000}}),errors=[];p.on('pageerror',e=>{errors.push(e.stack);console.log(e.message)});await p.goto('http://localhost:8931/TigerMessenger/?autostart=1&baseReview=1&robotOps=1');await p.waitForFunction(()=>window.__tm?.robotOperations,null,{timeout:180000});await p.waitForTimeout(1500);const start=p.getByRole('button',{name:'开始送信',exact:true});if(await start.isVisible())await start.click();const snapshots=[];
const stage=async name=>{await p.waitForTimeout(100);await p.screenshot({path:`artifacts/pipeline/base-four-hour/e2e-${name}.png`});snapshots.push(await p.evaluate(name=>({name,state:window.__tm.robotOperations.snapshot()}),name));};
await p.evaluate(()=>{const o=__tm.robotOperations;o.logistics.update(271);o.panel.element.hidden=true;o.update(.01)});await stage('stock');
await p.evaluate(()=>{const t=__tm.messenger.landmarks.tramSystem,s=t.freightServices[0],stop=s.loadingStops.find(x=>x.name==='locust');t.seekFreight('red',stop.progress-.001);t.update(1);__tm.robotOperations.update(3);__tm.robotOperations.focus('factory')});await stage('hoist');
await p.evaluate(()=>{__tm.robotOperations.update(38);__tm.robotOperations.focus('train')});await stage('loaded');
const fit=await p.evaluate(()=>{const o=__tm.robotOperations,T=__tm.THREE,t=__tm.messenger.landmarks.tramSystem;return o.logistics.units.filter(u=>u.status==='transit').map(u=>{const m=o.models.get(u.id),car=t.freightServices[0].wagons[u.slot],inv=car.matrixWorld.clone().invert(),box=new T.Box3(),v=new T.Vector3();m.updateWorldMatrix(true,true);m.traverse(c=>{if(!c.isMesh)return;const a=c.geometry.attributes.position,M=inv.clone().multiply(c.matrixWorld);for(let i=0;i<a.count;i++)box.expandByPoint(v.fromBufferAttribute(a,i).applyMatrix4(M));});return{id:u.id,slot:u.slot,min:box.min.toArray(),max:box.max.toArray(),ground:car.userData.deckHeight};});});
await p.evaluate(()=>{const t=__tm.messenger.landmarks.tramSystem,s=t.freightServices[0],stop=s.loadingStops.find(x=>x.name==='frontline');t.seekFreight('red',stop.progress-.001);t.update(1);__tm.robotOperations.update(3);__tm.robotOperations.focus('field')});await stage('unloading');
await p.evaluate(()=>{__tm.robotOperations.update(62);__tm.robotOperations.startExercise();const o=__tm.robotOperations;o.combat.command(o.combat.units.filter(u=>u.team==='friendly').map(u=>u.id),'move',{x:-17,z:-3})});await stage('deployed');
for(let i=0;i<24;i++)await p.evaluate(()=>__tm.robotOperations.update(.5));await stage('combat');
const state=await p.evaluate(()=>{const o=__tm.robotOperations;return{invariants:o.logistics.assertInvariants(),combat:o.combat.snapshot(),events:o.combat.events,save:o.save(),restore:o.load()}});
await writeFile('artifacts/pipeline/base-four-hour/ops-e2e.json',JSON.stringify({mode:'accelerated diagnostic; actual source models and runtime controllers',fit,snapshots,state,errors},null,2));console.log(JSON.stringify({fit,state,errors}));}finally{await b.close()}
