import{chromium}from'/Users/panglaohu/Downloads/TigerInBamboo/tools/shot/node_modules/playwright/index.mjs';import{writeFile}from'node:fs/promises';import{execFileSync}from'node:child_process';
const dir='artifacts/pipeline/base-four-hour';const b=await chromium.launch({channel:'chrome',headless:true,args:['--use-angle=metal','--disable-background-timer-throttling']});try{const p=await b.newPage({viewport:{width:1400,height:950}}),errors=[];p.on('pageerror',e=>errors.push(e.stack));await p.goto('http://localhost:8931/TigerMessenger/?autostart=1&baseReview=1&robotOps=1');await p.waitForFunction(()=>window.__tm?.robotOperations,null,{timeout:180000});await p.waitForTimeout(1500);const start=p.getByRole('button',{name:'开始送信',exact:true});if(await start.isVisible())await start.click();await p.evaluate(()=>{__tm.robotOperations.panel.element.hidden=true;__tm.robotOperations.focus('field')});
const measure=()=>p.evaluate(()=>new Promise(resolve=>{const times=[],start=performance.now();let last=start;function frame(t){times.push(t-last);last=t;if(t-start<12000){requestAnimationFrame(frame);return;}times.shift();times.sort((a,b)=>a-b);const T=__tm,o=T.robotOperations,gl=T.renderer.getContext(),ext=gl.getExtension('WEBGL_debug_renderer_info');resolve({duration:t-start,frames:times.length,fps:times.length/(t-start)*1000,medianMs:times[Math.floor(times.length*.5)],p95Ms:times[Math.floor(times.length*.95)],p99Ms:times[Math.floor(times.length*.99)],render:{...T.renderer.info.render},memory:{...T.renderer.info.memory},models:o.models.size,combatUnits:o.combat.units.length,activeMove:o.combat.units.filter(u=>u.speed>0).length,graphics:ext?gl.getParameter(ext.UNMASKED_RENDERER_WEBGL):gl.getParameter(gl.RENDERER),userAgent:navigator.userAgent});}requestAnimationFrame(frame);}));
const baseline=await measure();const preparation=await p.evaluate(()=>{
 const o=__tm.robotOperations,t=__tm.messenger.landmarks.tramSystem;o.logistics.update(271);o.update(.01);t.seekFreight('blue',.08);
 const ship=kind=>{const s=t.freightServices[0],load=s.loadingStops.find(x=>x.name===kind);t.seekFreight('red',load.progress-.001);t.update(1);o.update(38);const unload=s.loadingStops.find(x=>x.name==='frontline');t.seekFreight('red',unload.progress-.001);t.update(1);o.update(62);};
 for(const kind of['locust','ant','beetle'])ship(kind);
 for(const kinds of[['locust','ant','beetle'],['locust','ant']]){for(const k of kinds)o.logistics.receive(k,3);o.logistics.update(271);o.update(.01);for(const k of kinds)ship(k);}
 const ids=o.combat.units.filter(u=>u.team==='friendly').map(u=>u.id);o.combat.command(ids,'cease');o.combat.units.filter(u=>u.team==='friendly').forEach((u,i)=>{u.x=-20+(i%6)*8;u.z=-10+Math.floor(i/6)*7;u.heading=0;o.combat.command([u.id],'move',{x:u.x,z:Math.min(13,u.z+5)});});o.focus('field');return{invariants:o.logistics.assertInvariants(),ids};
});await p.waitForTimeout(1000);const twentyFour=await measure();const saved=await p.evaluate(()=>{const o=__tm.robotOperations,ids=o.logistics.units.map(u=>u.id),start=performance.now(),save=o.save(),restore=o.load();o.update(.01);return{save,restore,ms:performance.now()-start,invariants:o.logistics.assertInvariants(),sameIds:JSON.stringify(ids)===JSON.stringify(o.logistics.units.map(u=>u.id)),models:o.models.size};});await p.screenshot({path:`${dir}/performance-24.png`});await writeFile(`${dir}/performance-24.json`,JSON.stringify({environment:{cpu:execFileSync('/usr/sbin/sysctl',['-n','machdep.cpu.brand_string'],{encoding:'utf8'}).trim(),memoryBytes:Number(execFileSync('/usr/sbin/sysctl',['-n','hw.memsize'],{encoding:'utf8'})),viewport:{width:1400,height:950},mode:'Headless Chrome Metal, no other diagnostic Chrome launched by this task during measurement; foreground applications may still be open.'},baseline,preparation,twentyFour,saved,errors},null,2));console.log(JSON.stringify({baseline,preparation,twentyFour,saved,errors}));
}finally{await b.close()}
