// Read-only capture of the assembled original world. No generated substitute layout.
export function exportWorldGLB(scene, THREE, landmarks) {
 scene.updateMatrixWorld(true);
 const doc={asset:{version:'2.0',generator:'TigerMessenger original-world capture'},scene:0,scenes:[{nodes:[]}],nodes:[],meshes:[],materials:[],accessors:[],bufferViews:[],buffers:[{byteLength:0}],images:[],textures:[],samplers:[{wrapS:10497,wrapT:10497,magFilter:9729,minFilter:9987}]};
 const chunks=[];let offset=0;const mats=new Map(),geos=new Map(),nodeRefs=new Map(),textureRefs=new Map(),warnings=[];
 function buffer(bytes,target){const pad=(-offset)&3;if(pad){chunks.push(new Uint8Array(pad));offset+=pad;}const index=doc.bufferViews.length;doc.bufferViews.push({buffer:0,byteOffset:offset,byteLength:bytes.byteLength,...(target?{target}:{})});chunks.push(bytes);offset+=bytes.byteLength;return index;}
 function attr(a,type,target=34962,indices=false){const values=indices?new Uint32Array(a.count):new Float32Array(a.count*a.itemSize);let lo=Array(a.itemSize).fill(Infinity),hi=Array(a.itemSize).fill(-Infinity);for(let i=0;i<a.count;i++)for(let k=0;k<a.itemSize;k++){let v=a.getComponent(i,k);if(!Number.isFinite(v))v=0;values[i*a.itemSize+k]=v;lo[k]=Math.min(lo[k],v);hi[k]=Math.max(hi[k],v);}const id=doc.accessors.length;doc.accessors.push({bufferView:buffer(new Uint8Array(values.buffer),target),componentType:indices?5125:5126,count:a.count,type,...(!indices&&type==='VEC3'?{min:lo,max:hi}:{})});return id;}
 function texture(t){if(textureRefs.has(t))return textureRefs.get(t);try{let canvas=document.createElement('canvas');canvas.width=t.image.width;canvas.height=t.image.height;const c=canvas.getContext('2d');c.drawImage(t.image,0,0);let str=atob(canvas.toDataURL('image/png').split(',')[1]);const bytes=Uint8Array.from(str,c=>c.charCodeAt(0));const image=doc.images.length;doc.images.push({bufferView:buffer(bytes),mimeType:'image/png'});const id=doc.textures.length;doc.textures.push({source:image,sampler:0});textureRefs.set(t,id);return id;}catch(e){warnings.push('Texture unavailable: '+t.name);return null;}}
 function material(m){if(mats.has(m))return mats.get(m);const id=doc.materials.length;const col=m.color||m.uniforms?.baseColor?.value||m.uniforms?.uColor?.value;const rgb=col?.isColor?col.toArray():[.45,.55,.45];const row={name:`${m.name||m.type||"Material"}__material_${id}`,pbrMetallicRoughness:{baseColorFactor:[...rgb,m.opacity??1],metallicFactor:m.metalness??0,roughnessFactor:m.roughness??.85},doubleSided:m.side===2,extras:{sourceType:m.type,shaderAdaptationPending:!!m.isShaderMaterial}};if(m.transparent)row.alphaMode='BLEND';if(m.alphaTest){row.alphaMode='MASK';row.alphaCutoff=m.alphaTest;}if(m.map){const t=texture(m.map);if(t!==null)row.pbrMetallicRoughness.baseColorTexture={index:t};}if(m.emissive)row.emissiveFactor=m.emissive.toArray().map(v=>Math.min(1,v*(m.emissiveIntensity??1)));doc.materials.push(row);mats.set(m,id);return id;}
 function mesh(o){const g=o.geometry;const ms=Array.isArray(o.material)?o.material:[o.material];const key=g.uuid+ms.map(m=>m.uuid).join();if(geos.has(key))return geos.get(key);if(!g.attributes.position)return null;const attrs={POSITION:attr(g.attributes.position,'VEC3')};if(g.attributes.normal)attrs.NORMAL=attr(g.attributes.normal,'VEC3');if(g.attributes.color)attrs.COLOR_0=attr(g.attributes.color,g.attributes.color.itemSize===4?'VEC4':'VEC3');if(g.attributes.uv){const uv=g.attributes.uv.clone();for(let i=0;i<uv.count;i++)uv.setY(i,1-uv.getY(i));attrs.TEXCOORD_0=attr(uv,'VEC2');}
 const max=g.index?g.index.count:g.attributes.position.count;const begin=g.drawRange.start||0;const end=Math.min(max,Number.isFinite(g.drawRange.count)?begin+g.drawRange.count:max);const groups=g.groups.length?g.groups:[{start:0,count:max,materialIndex:0}];const primitives=[];for(const group of groups){const a=Math.max(begin,group.start),b=Math.min(end,group.start+group.count);const count=Math.floor((b-a)/3)*3;if(count<=0)continue;const ix=new Uint32Array(count);for(let i=0;i<count;i++)ix[i]=g.index?g.index.getX(a+i):a+i;primitives.push({attributes:attrs,indices:attr(new THREE.BufferAttribute(ix,1),'SCALAR',34963,true),material:material(ms[group.materialIndex]||ms[0]),mode:4});}if(!primitives.length)return null;const id=doc.meshes.length;doc.meshes.push({name:o.name,primitives});geos.set(key,id);return id;}
 // glTF core has no per-node tint. Share geometry/accessors and make only the
 // required material/mesh variants, multiplying linear instance and base RGB.
 const tintedMeshes=new Map(),tintedMaterials=new Map();
 function tintMesh(id,color){
  const rgb=color.toArray(),suffix=rgb.join(','),key=id+':'+suffix;
  if(tintedMeshes.has(key))return tintedMeshes.get(key);
  const primitives=doc.meshes[id].primitives.map(p=>{
   const mk=p.material+':'+suffix;let materialId=tintedMaterials.get(mk);
   if(materialId===undefined){
    const m=structuredClone(doc.materials[p.material]);
    m.name+='__instance_'+suffix;
    for(let i=0;i<3;i++)m.pbrMetallicRoughness.baseColorFactor[i]*=rgb[i];
    materialId=doc.materials.length;doc.materials.push(m);tintedMaterials.set(mk,materialId);
   }
   return {...p,material:materialId};
  });
  const result=doc.meshes.length;doc.meshes.push({name:doc.meshes[id].name,primitives});tintedMeshes.set(key,result);return result;
 }
 let instances=0;function visit(o,parent,path){if(!o.visible||o.userData?.isOutline||o.name==='sky-background'||o.isLight||o.isCamera)return;const row={name:o.name||o.type,matrix:o.matrix.toArray(),extras:{sourcePath:path,sourceType:o.type,...(typeof o.userData?.sourceId==='string'?{sourceId:o.userData.sourceId}:{}),...(typeof o.userData?.sourceBlender==='string'?{sourceBlender:o.userData.sourceBlender}:{}),...(o.userData?.westCityWalkable===true?{westCityWalkable:true}:{}),...(o.userData?.skipColliders===true?{skipColliders:true}:{}),...(o.userData?.legacyNavonaRetired===true?{legacyNavonaRetired:true}:{}),...(o.userData?.citadelSolidExterior===true?{citadelSolidExterior:true}:{}),behaviorKeys:Object.keys(o.userData||{}).filter(k=>typeof o.userData[k]==='function')}};const id=doc.nodes.length;doc.nodes.push(row);nodeRefs.set(o,id);if(parent===null)doc.scenes[0].nodes.push(id);else(doc.nodes[parent].children??=[]).push(id);
 if(o.isMesh){const m=mesh(o);if(m!==null){if(o.isInstancedMesh){for(let i=0;i<o.count;i++){const matrix=new THREE.Matrix4();o.getMatrixAt(i,matrix);let instanceMesh=m;if(o.instanceColor){const color=new THREE.Color();o.getColorAt(i,color);instanceMesh=tintMesh(m,color);}const child=doc.nodes.length;doc.nodes.push({name:row.name+' instance '+i,mesh:instanceMesh,matrix:matrix.toArray()});(row.children??=[]).push(child);instances++;}}else row.mesh=m;}}
 o.children.forEach((c,i)=>visit(c,id,path+'/'+(c.name||c.type)+'['+i+']'));}
 scene.children.forEach((o,i)=>visit(o,null,(o.name||o.type)+'['+i+']'));
 const refs={};for(const [key,val]of Object.entries(landmarks)){const o=val?.isObject3D?val:val?.group?.isObject3D?val.group:null;if(o){const box=new THREE.Box3().setFromObject(o);refs[key]={node:nodeRefs.get(o)??null,name:o.name,matrix:o.matrixWorld.toArray(),position:o.getWorldPosition(new THREE.Vector3()).toArray(),center:box.isEmpty()?o.getWorldPosition(new THREE.Vector3()).toArray():box.getCenter(new THREE.Vector3()).toArray(),size:box.isEmpty()?[0,0,0]:box.getSize(new THREE.Vector3()).toArray()};}}
 const pad=(-offset)&3;if(pad){chunks.push(new Uint8Array(pad));offset+=pad;}doc.buffers[0].byteLength=offset;let json=new TextEncoder().encode(JSON.stringify(doc));const jp=(-json.byteLength)&3;const jsonPadded=new Uint8Array(json.byteLength+jp);jsonPadded.fill(32);jsonPadded.set(json);const total=12+8+jsonPadded.byteLength+8+offset;const bytes=new Uint8Array(total),view=new DataView(bytes.buffer);view.setUint32(0,0x46546c67,true);view.setUint32(4,2,true);view.setUint32(8,total,true);view.setUint32(12,jsonPadded.byteLength,true);view.setUint32(16,0x4e4f534a,true);bytes.set(jsonPadded,20);let at=20+jsonPadded.byteLength;view.setUint32(at,offset,true);view.setUint32(at+4,0x004e4942,true);at+=8;for(const c of chunks){bytes.set(c,at);at+=c.byteLength;}
 return {bytes,manifest:{radius:160,source:'assembled default Web world; no saved browser edits copied',nodes:doc.nodes.length,meshes:doc.meshes.length,instances,materials:doc.materials.length,textures:doc.textures.length,bytes:total,landmarks:refs,warnings:[...new Set(warnings)],limitations:['Static visible-state capture; source animations, physics, quests and shader logic still require native migration','Hidden states and non-mesh line/point effects excluded from this world overview; separate asset archives retain them']}};
}
