import {auditWalkableProtection} from './sea_stack_walk_audit.js';
// Review-page code only. No browser automation, no production-world mutation.
const $=s=>document.querySelector(s),frame=$('#stage'),status=$('#status'),output=$('#results');
let t,site,rocks=[],generation=0,ready=false,busy=false,view='hero',clock=.5,flat=false,noFog=false,coastalUnlit=false,report=null,errors=[],captureStarted=null;
let savedFog,hidden=[],originalMaterials=new Map(),whiteMaterial,baseline=[],cameraState,closeTarget=null,shaderDiagnostics=[],performanceReport=null;
const nextFrame=()=>new Promise(r=>requestAnimationFrame(r));
const safe=value=>{const seen=new WeakSet();return JSON.parse(JSON.stringify(value,(k,v)=>{if(typeof v==='number'&&!Number.isFinite(v))return String(v);if(v&&typeof v==='object'){if(seen.has(v))return '[shared]';seen.add(v);if(ArrayBuffer.isView(v))return {typedArray:v.constructor.name,length:v.length};}return v;}));};
function emit(){output.textContent=JSON.stringify({status:ready?'ready':'loading',variant:$('#variant').value,view,clock,flat,noFog,coastalUnlit,camera:cameraState,closeTarget,shaderDiagnostics,performanceReport,shoreRuntime:shoreRuntime(),errorCapture:{started:captureStarted,scope:'iframe errors, unhandled rejections and console.error after listener attachment; earlier errors unavailable'},errors,report},null,2);}
function shoreRuntime(){if(!ready||!t)return [];const ocean=t.scene.getObjectByName('planet-v8-curved-ocean'),ancestry=o=>{const a=[];for(let p=o;p;p=p.parent)a.push({name:p.name,type:p.type,visible:p.visible,renderOrder:p.renderOrder});return a;};const result=[];for(const rock of rocks){rock.traverse(o=>{if(o.name==='sea-stack-contact-foam')result.push({seed:rock.geometry.userData.terraces?.seed,visible:visible(o),ancestry:ancestry(o),oceanAncestry:ancestry(ocean),waveBinding:safe(o.userData.waveBinding||null),material:{opacity:o.material.opacity,transparent:o.material.transparent,depthTest:o.material.depthTest,depthWrite:o.material.depthWrite},triangles:o.geometry.attributes.position.count/3});});}return result;}
function controls(){document.querySelectorAll('button:not(#reload)').forEach(b=>b.disabled=!ready||busy);}
function visible(o){for(let p=o;p;p=p.parent)if(!p.visible)return false;return true;}
function attachErrors(w){const mark=()=>{try{if(w.document.__seaStackReviewErrors)return;w.document.__seaStackReviewErrors=true;captureStarted=new Date().toISOString();const original=w.console.error.bind(w.console);w.console.error=(...args)=>{original(...args);errors.push({type:'console.error',message:args.map(a=>{try{return typeof a==='string'?a:JSON.stringify(a);}catch{return String(a);}}).join(' ').slice(0,16000)});if(errors.length>200)errors.shift();emit();};w.addEventListener('error',e=>{errors.push({type:'error',message:e.message,file:e.filename,line:e.lineno});emit();});w.addEventListener('unhandledrejection',e=>{errors.push({type:'unhandledrejection',message:String(e.reason?.stack||e.reason)});emit();});}catch{}};mark();}
async function load(){const serial=++generation;ready=false;busy=false;t=null;report=null;performanceReport=null;errors=[];shaderDiagnostics=[];closeTarget=null;hidden=[];originalMaterials=new Map();controls();status.textContent='加载实际世界，等待岩群、海面、曲线和渲染器…';
 const params=new URLSearchParams(location.search);params.set('autostart','1');params.set('seaStackStudy',$('#variant').value);params.set('timeOfDay',String(clock));frame.src='/TigerMessenger/?'+params;
 const start=performance.now();let stable=0,signature='';
 while(serial===generation){await new Promise(r=>setTimeout(r,100));attachErrors(frame.contentWindow);let game;try{game=frame.contentWindow.__tm;}catch{}const root=game?.messenger?.landmarks?.abandonedGate?.userData?.seatRoot?.userData?.siteRoot;
  const ridge=root?.getObjectByName('g30-distant-ridges'),ocean=game?.scene?.getObjectByName('planet-v8-curved-ocean'),list=[];ridge?.traverse(o=>{if(o.name==='g30-far-mountain'&&!o.userData.excludedSeaStack)list.push(o);});
  const complete=game?.renderer?.domElement?.width&&game.cameraRig&&game.dayNight&&game.P&&game.THREE&&game.distanceCulling&&game.messenger?.landmarks?.tramSystem?.curves&&ocean&&list.length>0&&list.every(o=>o.geometry?.attributes?.position&&o.userData.seaStack?.seaAnchor)&&Array.isArray(game.scene.userData.seaStackTerraceAudit);
  if(complete){const sig=list.map(o=>o.uuid+':'+o.geometry.attributes.position.count).join('|');stable=sig===signature?stable+1:0;signature=sig;if(stable>=12){t=game;site=root;rocks=list;break;}}
  if(performance.now()-start>360000){status.textContent='初始化超时：未得到完整岩群/海面数据。检查 iframe 或重新加载。';emit();return;}
 }
 if(serial!==generation)return;ready=true;t.cameraRig.update=()=>{};t.P.daySpeed=0;savedFog=t.scene.fog;whiteMaterial=new t.THREE.MeshBasicMaterial({color:0xd9d8d1,side:t.THREE.DoubleSide});
 frame.contentDocument.querySelectorAll('body > :not(canvas):not(script):not(style):not(link)').forEach(e=>e.style.visibility='hidden');
 t.scene.updateMatrixWorld(true);baseline=rocks.map(o=>({id:o.userData.seaStack.detailId??o.name,seed:o.geometry.userData.terraces?.seed,position:o.getWorldPosition(new t.THREE.Vector3()).toArray(),seaAnchor:[...o.userData.seaStack.seaAnchor]}));
 const key='twelve-apostles-study-layout-v1';let prior;try{prior=JSON.parse(localStorage.getItem(key));if(!prior)localStorage.setItem(key,JSON.stringify(baseline));}catch{}
 report={initialLayout:baseline,referenceLayout:prior??baseline,referenceNote:prior?'Compared against first harness load in this browser':'First load recorded; external approved-layout evidence still needed'};
 setTime(clock);await setView(view);setFlat(flat);setNoFog(noFog);setUnlit(coastalUnlit);controls();status.textContent=`Ready · ${rocks.length} 座岩柱 · ${frame.contentWindow.location.search}`;emit();
}
function readShaderDiagnostics(){
 if(!t?.renderer)return [];const gl=t.renderer.getContext();return (t.renderer.info.programs||[]).map(p=>{const d=p.diagnostics,result={id:p.id,name:p.name,runnable:d?.runnable,programLog:d?.programLog||'',vertexLog:d?.vertexShader?.log||'',fragmentLog:d?.fragmentShader?.log||''};try{if(p.program){result.linked=gl.getProgramParameter(p.program,gl.LINK_STATUS);result.programLog=gl.getProgramInfoLog(p.program)||result.programLog;result.shaders=(gl.getAttachedShaders(p.program)||[]).map(s=>({type:gl.getShaderParameter(s,gl.SHADER_TYPE)===gl.VERTEX_SHADER?'vertex':'fragment',compiled:gl.getShaderParameter(s,gl.COMPILE_STATUS),log:gl.getShaderInfoLog(s)||''}));}}catch(e){result.inspectionError=String(e);}return result;});
}
function refresh(){t.scene.updateMatrixWorld(true);t.camera.updateProjectionMatrix();t.camera.updateMatrixWorld(true);t.distanceCulling.recollect();t.distanceCulling.update(3);applySuppression();t.renderer.render(t.scene,t.camera);shaderDiagnostics=readShaderDiagnostics();cameraState={position:t.camera.position.toArray(),up:t.camera.up.toArray(),quaternion:t.camera.quaternion.toArray(),aspect:t.camera.aspect,zoom:t.camera.zoom,fov:t.camera.fov,near:t.camera.near,far:t.camera.far};}
function viewOcclusion(target,points,range,sceneOccluders=null){
 const T=t.THREE,ray=new T.Raycaster(),eye=t.camera.position,worldSamples=[],frameSamples=[];
 const owned=o=>{for(let p=o;p;p=p.parent)if(p===target)return true;return false;};
 const firstHit=()=>{const objects=sceneOccluders?sceneOccluders.filter(({box})=>{if(box.containsPoint(ray.ray.origin))return true;const p=ray.ray.intersectBox(box,new T.Vector3());return p&&p.distanceTo(ray.ray.origin)<=ray.far;}).map(b=>b.object):rocks;return ray.intersectObjects(objects,false)[0];};
 for(const point of points){const delta=point.clone().sub(eye);ray.set(eye,delta.clone().normalize());ray.far=delta.length();const first=firstHit();worldSamples.push({point:point.toArray(),blocked:!!first&&!owned(first.object),firstObject:first?.object.name||null,firstSeed:first?.object.geometry.userData.terraces?.seed??null});}
 for(const x of[-.78,-.4,0,.4,.78])for(const y of[-.65,0,.65]){ray.setFromCamera(new T.Vector2(x,y),t.camera);ray.far=range;const first=firstHit();frameSamples.push({ndc:[x,y],blocked:!!first&&!owned(first.object),firstObject:first?.object.name||null,firstSeed:first?.object.geometry.userData.terraces?.seed??null});}
 const targetBlocked=worldSamples.filter(s=>s.blocked).length,frameBlocked=frameSamples.filter(s=>s.blocked).length;return {targetBlocked,frameBlocked,score:targetBlocked*10+frameBlocked,worldSamples,frameSamples,note:sceneOccluders?'Opaque scene meshes with ray-box broadphase; 15 frame samples, not a full pixel visibility proof.':'Actual rock hits; 15 frame samples, not a full pixel visibility proof.'};
}
async function setView(name){if(!ready)return;view=name;closeTarget=null;const T=t.THREE,V=(...v)=>new T.Vector3(...v),camera=t.camera;
 if(['complete','orbit-left','orbit-back'].includes(name)){
 const rock=rocks.find(r=>r.geometry.userData.terraces?.seed===2)||rocks[0];t.scene.updateMatrixWorld(true);
 rock.geometry.computeBoundingBox();const box=rock.geometry.boundingBox.clone(),inverse=rock.matrixWorld.clone().invert();
 rock.traverse(o=>{if(o===rock||!o.geometry)return;const transform=new T.Matrix4().multiplyMatrices(inverse,o.matrixWorld);let childBox;if(o.isInstancedMesh){o.computeBoundingBox();childBox=o.boundingBox;}else{o.geometry.computeBoundingBox();childBox=o.geometry.boundingBox;}if(childBox)box.union(childBox.clone().applyMatrix4(transform));});
 const center=rock.localToWorld(box.getCenter(V())),up=V(0,1,0).transformDirection(rock.matrixWorld),direction=(name==='orbit-left'?V(-1.4,.25,1):name==='orbit-back'?V(-1,.25,-1.4):V(1,.25,1.4)).transformDirection(rock.matrixWorld),corners=[];
 for(const x of[box.min.x,box.max.x])for(const y of[box.min.y,box.max.y])for(const z of[box.min.z,box.max.z])corners.push(rock.localToWorld(V(x,y,z)));
 camera.up.copy(up);camera.fov=50;camera.zoom=1;camera.far=4000;camera.updateProjectionMatrix();const candidates=[],baseDirection=direction.clone(),localCenter=box.getCenter(V()),targetPoints=[center];
 for(const f of[.08,.5,.92])targetPoints.push(rock.localToWorld(V(localCenter.x,box.min.y+(box.max.y-box.min.y)*f,localCenter.z)));
 let distance,fitted,projected;
 const fits=d=>{camera.position.copy(center).addScaledVector(direction,d);camera.lookAt(center);camera.updateMatrixWorld(true);projected=corners.map(p=>p.clone().project(camera));return projected.every(p=>Math.abs(p.x)<=.85&&Math.abs(p.y)<=.85&&p.z>-1&&p.z<1);};
 for(const offset of[0,-10,10,-20,20,-30,30]){direction.copy(baseDirection).applyAxisAngle(up,offset*Math.PI/180);distance=box.getSize(V()).length();for(let step=0;step<100&&!fits(distance);step++)distance*=1.1;let low=0,high=distance;for(let step=0;step<32;step++){const mid=(low+high)/2;if(fits(mid))high=mid;else low=mid;}distance=high;fitted=fits(distance);const occlusion=viewOcclusion(rock,targetPoints,distance+box.getSize(V()).length()*.5);candidates.push({offset,direction:direction.clone(),distance,fitted,occlusion});}
 const selected=candidates.reduce((a,b)=>b.occlusion.score<a.occlusion.score?b:a);direction.copy(selected.direction);distance=selected.distance;fitted=fits(distance);
 closeTarget={seed:rock.geometry.userData.terraces?.seed,selection:'oriented rock bounds, +/-30 degree sampled occlusion avoidance',selectedAzimuthOffset:selected.offset,candidateVisibility:candidates.map(c=>({offset:c.offset,distance:c.distance,fitPass:c.fitted,...c.occlusion})),clearOfOtherRocks:selected.occlusion.score===0,worldCenter:center.toArray(),bbox:{space:'rock local',min:box.min.toArray(),max:box.max.toArray()},fitPass:fitted,ndcCorners:projected.map(p=>p.toArray()),distance};
 }else if(name==='base'){
 const rock=rocks.find(r=>r.geometry.userData.terraces?.seed===2)||rocks[0],anchor=V(...rock.userData.seaStack.seaAnchor),up=V(0,1,0).transformDirection(rock.matrixWorld),outward=V(1,0,1.4).transformDirection(rock.matrixWorld),ocean=t.scene.getObjectByName('planet-v8-curved-ocean');
 const radial=anchor.clone().normalize(),ray=new T.Raycaster(radial.clone().multiplyScalar(400),radial.clone().negate(),0,500),waterHit=ray.intersectObject(ocean,false)[0],water=waterHit?.point||anchor;
 rock.geometry.computeBoundingBox();const box=rock.geometry.boundingBox,size=box.getSize(V()),distance=Math.max(size.x,size.z)*1.6+8;
 const aim=water.clone().addScaledVector(up,2),otherRocks=rocks.filter(r=>r!==rock),candidates=[];
 const sceneOccluders=[];t.scene.updateMatrixWorld(true);t.scene.traverse(o=>{if(!o.isMesh||!visible(o)||o===ocean||/ocean|cloud|mist|fog|steam|foam|particle/i.test(o.name))return;const mats=Array.isArray(o.material)?o.material:[o.material];if(!mats.some(m=>m&&m.visible!==false&&!m.transparent&&m.opacity>.75))return;const box=new T.Box3().setFromObject(o);if(!box.isEmpty())sceneOccluders.push({object:o,box});});
 camera.up.copy(up);camera.fov=48;camera.zoom=1;camera.updateProjectionMatrix();
 for(let i=0;i<12;i++){const angle=i*Math.PI/6,direction=outward.clone().applyAxisAngle(up,angle),eye=water.clone().addScaledVector(direction,distance).addScaledVector(up,6);camera.position.copy(eye);camera.lookAt(aim);camera.updateMatrixWorld(true);const occlusion=viewOcclusion(rock,[aim,water,water.clone().addScaledVector(up,5)],distance+Math.max(size.x,size.z),sceneOccluders);candidates.push({angle,eye,occlusion});}
 const selected=candidates.reduce((a,b)=>b.occlusion.score<a.occlusion.score?b:a);camera.position.copy(selected.eye);camera.lookAt(aim);
 closeTarget={seed:rock.geometry.userData.terraces?.seed,selection:'actual ocean hit, 12 azimuths and opaque scene frame-edge occlusion samples',opaqueOccluderCount:sceneOccluders.length,candidateVisibility:candidates.map(c=>({azimuthDegrees:c.angle*180/Math.PI,...c.occlusion})),selectedAzimuthDegrees:selected.angle*180/Math.PI,clearOfOtherRocks:selected.occlusion.score===0,waterHit:!!waterHit,waterWorld:water.toArray(),seaAnchor:anchor.toArray(),distance};
 }else if(name==='foliage'){
 const planted=rocks.map(rock=>{const roots=[];rock.traverse(o=>{if(/shrubs|grass/.test(o.name))for(const a of o.userData.roots||[]){const p=Array.isArray(a)?a:a.position;if(p?.length>=3)roots.push(V(...p));}});return {rock,roots};}).sort((a,b)=>b.roots.length-a.roots.length)[0];
 if(!planted?.roots.length)throw new Error('No planted roots available for close-up');
 const {rock,roots}=planted;let target=roots[0],score=-Infinity;
 // Select a densely planted terrace; deterministic tie-breaking preserves repeatability.
 for(let i=0;i<roots.length;i+=Math.max(1,Math.floor(roots.length/180))){const p=roots[i];let density=0;for(const q of roots)if(Math.abs(p.y-q.y)<1&&p.distanceToSquared(q)<16)density++;if(density>score){score=density;target=p;}}
 const outward=V(target.x,0,target.z).normalize();if(outward.lengthSq()<.01)outward.set(1,0,0);
 const aim=target.clone().add(V(0,.5,0));camera.position.copy(rock.localToWorld(target.clone().addScaledVector(outward,8).add(V(0,3.5,0))));camera.up.set(0,1,0).transformDirection(rock.matrixWorld);camera.lookAt(rock.localToWorld(aim));camera.fov=45;
 closeTarget={seed:rock.geometry.userData.terraces?.seed,rootCount:roots.length,localRoot:target.toArray(),neighbourRoots:score,selection:'most planted rock, densest occupied terrace'};
 }else if(name==='plaza'){const {bookshopTownPose}=await import('/TigerMessenger/src/world/bookshopTownSite.js');const pose=bookshopTownPose(160),up=pose.up,right=V(1,0,0).applyQuaternion(pose.quaternion),forward=V(0,0,1).applyQuaternion(pose.quaternion);camera.position.copy(pose.position).addScaledVector(up,100).addScaledVector(forward,120).addScaledVector(right,50);camera.up.copy(up);camera.lookAt(pose.position.clone().addScaledVector(forward,20));camera.fov=62;
 }else if(name==='coastline'){const center=V();rocks.forEach(r=>center.add(r.getWorldPosition(V())));center.divideScalar(rocks.length);const up=center.clone().normalize(),tangent=site.getWorldPosition(V()).sub(center);tangent.addScaledVector(up,-tangent.dot(up)).normalize();camera.position.copy(center).addScaledVector(up,75).addScaledVector(tangent,160);camera.up.copy(up);camera.lookAt(center);camera.fov=55;
 }else if(name==='rail'){const tram=t.messenger.landmarks.tramSystem,curve=tram.curve||Object.values(tram.curves)[0],inv=site.matrixWorld.clone().invert();let best=0,distance=Infinity;for(let i=0;i<4000;i++){const l=curve.getPointAt(i/4000).applyMatrix4(inv),d=Math.hypot(l.x-85,l.z);if(l.y>-60&&d<distance){distance=d;best=i/4000;}}const at=curve.getPointAt(best),up=at.clone().normalize();camera.position.copy(at).addScaledVector(up,4);camera.up.copy(camera.position).normalize();camera.lookAt(curve.getPointAt((best+35/curve.getLength())%1).addScaledVector(up,5));camera.fov=58;
 }else{const rock=name==='vegetation'?(rocks.find(r=>r.geometry.userData.terraces?.seed===2)||rocks[0]):(rocks.find(r=>r.userData.seaStack.height>45)||rocks[0]),h=rock.userData.seaStack.height;camera.position.copy(rock.localToWorld(name==='vegetation'?V(24,h*.65,28):V(48,h*.2,68)));camera.up.set(0,1,0).transformDirection(rock.matrixWorld);camera.lookAt(rock.localToWorld(name==='vegetation'?V(0,h*.28,0):V(0,-h*.03,0)));camera.fov=name==='vegetation'?48:55;}
 camera.far=4000;refresh();emit();}
function setUnlit(value){coastalUnlit=value;$('#unlit').setAttribute('aria-pressed',String(value));if(!ready)return;const seen=new Set();t.scene.traverse(o=>{for(const m of Array.isArray(o.material)?o.material:[o.material])if(m?.userData?.coastalLighting&&!seen.has(m)){seen.add(m);m.userData.coastalLighting.unlit=value;}});for(const m of originalMaterials.values())if(m?.userData?.coastalLighting)m.userData.coastalLighting.unlit=value;refresh();emit();}
function trainLightingSummary(){const actors=[];t.scene.traverse(o=>{if(/heritage-tram-|freight-(locomotive|[0-9]+)$/.test(o.name)){const types={},materials=new Set();o.traverse(c=>{for(const m of Array.isArray(c.material)?c.material:[c.material])if(m&&!materials.has(m)){materials.add(m);types[m.type]=(types[m.type]||0)+1;}});actors.push({name:o.name,materialTypes:types,litMaterialCount:[...materials].filter(m=>m.isMeshStandardMaterial||m.isMeshPhysicalMaterial||m.isMeshLambertMaterial||m.isMeshPhongMaterial).length,coastalMaterialCount:[...materials].filter(m=>m.userData.coastalLighting).length});}});return {actors,note:'Material types indicate light participation, not proof of identical shader response; standard lit actors use scene lights.'};}
function setTime(value){clock=Number(value);if(!ready)return;t.P.daySpeed=0;t.P.timeOfDay=clock;t.dayNight.update(.0001);refresh();emit();}
function setFlat(value){flat=value;$('#flat').setAttribute('aria-pressed',String(flat));if(!ready)return;for(const rock of rocks){if(!originalMaterials.has(rock))originalMaterials.set(rock,rock.material);rock.material=flat?whiteMaterial:originalMaterials.get(rock);}refresh();emit();}
function setNoFog(value){noFog=value;$('#noFog').setAttribute('aria-pressed',String(noFog));if(!ready)return;if(!noFog){t.scene.fog=savedFog;hidden.forEach(([o,v])=>o.visible=v);hidden=[];}else{hidden=[];t.scene.traverse(o=>{if(/cloud|mist|fog|plume/i.test(o.name)&&o!==t.scene)hidden.push([o,o.visible]);});}refresh();emit();}
function applySuppression(){if(noFog){t.scene.fog=null;hidden.forEach(([o])=>o.visible=false);}}
function animationGuard(){if(ready){t.P.daySpeed=0;applySuppression();}requestAnimationFrame(animationGuard);}animationGuard();
async function check(){if(!ready||busy)return;busy=true;controls();status.textContent='检查几何、海面、根部及铁路采样…';try{const T=t.THREE,V=(...a)=>new T.Vector3(...a),ray=new T.Raycaster(),ocean=t.scene.getObjectByName('planet-v8-curved-ocean');t.scene.updateMatrixWorld(true);
 const waterAt=p=>{const d=p.clone().normalize();ray.set(d.clone().multiplyScalar(400),d.clone().negate());ray.far=500;return ray.intersectObject(ocean,false)[0]?.point;};
 const geometry=[],support=[],rootsReport=[];let nan=0;
 for(const rock of rocks){const p=rock.geometry.attributes.position,h=rock.userData.seaStack.height;rock.geometry.computeBoundingBox();const min=rock.geometry.boundingBox.min.y;let localNan=0,baseSamples=0,maxAbove=-Infinity,waterMisses=0;for(let i=0;i<p.count;i++){const local=V().fromBufferAttribute(p,i);if(!local.toArray().every(Number.isFinite)){localNan++;continue;}if(local.y<min+Math.max(.02,h*.01)){const world=rock.localToWorld(local),water=waterAt(world);baseSamples++;if(water)maxAbove=Math.max(maxAbove,world.length()-water.length());else waterMisses++;}}
 nan+=localNan;geometry.push({seed:rock.geometry.userData.terraces?.seed,vertices:p.count,triangles:(rock.geometry.index?.count??p.count)/3,nan:localNan,metadata:safe(rock.geometry.userData)});const up=V(0,1,0).transformDirection(rock.matrixWorld),worldUp=V(...rock.userData.seaStack.worldUp),anchor=V(...rock.userData.seaStack.seaAnchor),water=waterAt(anchor);support.push({seed:rock.geometry.userData.terraces?.seed,axisAngleDegrees:up.angleTo(worldUp)*180/Math.PI,anchorGap:water?anchor.distanceTo(water):null,baseSamples,waterMisses,maxBaseAboveWater:Number.isFinite(maxAbove)?maxAbove:null});
 const rootSet=new Set();rock.traverse(o=>{for(const raw of o.userData.roots||[]){const local=Array.isArray(raw)?raw:raw.position;if(!Array.isArray(local)||local.length<3)continue;const key=local.join(',');if(rootSet.has(key))continue;rootSet.add(key);const world=rock.localToWorld(V(...local)),direction=up.clone();ray.set(world.clone().addScaledVector(direction,2),direction.negate());ray.far=4;const hit=ray.intersectObject(rock,false)[0];rootsReport.push({seed:rock.geometry.userData.terraces?.seed,supported:!!hit,gap:hit?world.distanceTo(hit.point):null});}});await nextFrame();}
 const {bookshopTownPose,BOOKSHOP_SITE_OUTLINE}=await import('/TigerMessenger/src/world/bookshopTownSite.js'),invTown=bookshopTownPose(160).quaternion.clone().invert();let plazaMin=Infinity;for(const r of rocks){const p=r.geometry.attributes.position;for(let i=0;i<p.count;i++){const q=r.localToWorld(V().fromBufferAttribute(p,i)).normalize().applyQuaternion(invTown);if(q.y>0)plazaMin=Math.min(plazaMin,Math.hypot(q.x*160/q.y,q.z*160/q.y-BOOKSHOP_SITE_OUTLINE.centerZ)-BOOKSHOP_SITE_OUTLINE.radius);}}
 const obstacles=[...rocks];site.traverse(o=>{if((o.name==='gate-sea-stack-fallen-block'||o.name==='sea-stack-contact-talus')&&o.isMesh&&visible(o))obstacles.push(o);});const bounds=obstacles.map(o=>({o,box:new T.Box3().setFromObject(o).expandByScalar(1)}));let probes=0,hitCount=0;const hits=[];
 for(const [lane,curve]of Object.entries(t.messenger.landmarks.tramSystem.curves)){for(let i=0;i<2600;i++){const q=curve.getPointAt(i/2600),up=q.clone().normalize(),f=curve.getTangentAt(i/2600).normalize(),right=V().crossVectors(up,f).normalize(),candidates=bounds.filter(b=>b.box.distanceToPoint(q)<14).map(b=>b.o);for(const side of[-2.6,0,2.6])for(const height of[.5,3,10]){probes++;if(!candidates.length)continue;ray.set(q.clone().addScaledVector(up,height).addScaledVector(right,side).addScaledVector(f,-1),f);ray.far=2;const hit=ray.intersectObjects(candidates,false)[0];if(hit){hitCount++;if(hits.length<30)hits.push({lane,i,side,height,object:hit.object.name,point:hit.point.toArray()});}}if(i%100===0){status.textContent=`铁路采样 ${lane} ${i}/2600`;await nextFrame();}}}
 let reference=baseline;try{reference=JSON.parse(localStorage.getItem('twelve-apostles-study-layout-v1'))||baseline;}catch{}const layout=rocks.map((r,i)=>{const p=r.getWorldPosition(V()),old=reference.find(o=>o.seed===r.geometry.userData.terraces?.seed)||reference[i];return {seed:r.geometry.userData.terraces?.seed,position:p.toArray(),referenceDelta:old?p.distanceTo(V(...old.position)):null,seaAnchor:r.userData.seaStack.seaAnchor};});
 report={checkedAt:new Date().toISOString(),sceneUrl:frame.contentWindow.location.href,geometry,finiteGeometry:nan===0,layout:{expected:8,actual:rocks.length,countPass:rocks.length===8,reference:'first harness load localStorage; not independent approval evidence',items:layout},waterSupport:support,roots:{count:rootsReport.length,unsupported:rootsReport.filter(r=>!r.supported).length,maxGap:Math.max(0,...rootsReport.filter(r=>r.gap!==null).map(r=>r.gap)),items:rootsReport},rail:{method:'2600 stations per lane, 3 lateral offsets, 3 heights, 2-unit tangent rays; sampled only',probes,hitCount,hits},plaza:{minimumClearance:Number.isFinite(plazaMin)?plazaMin:null,oppositeHemisphereOnly:!Number.isFinite(plazaMin),clear:plazaMin>20},walkableProtection:auditWalkableProtection(t,rocks),sceneAudit:safe(t.scene.userData.seaStackTerraceAudit),surfaceContract:safe(t.scene.userData.seaStackSurfaceContract??null),coastalSurfaces:rocks.map(r=>({seed:r.geometry.userData.terraces?.seed,surface:safe(r.userData.coastalSurface??null)})),trainLighting:trainLightingSummary(),renderer:safe(t.renderer.info),shaderDiagnostics:readShaderDiagnostics(),noFogHiddenNames:hidden.map(([o])=>o.name)};status.textContent=`检查完成 · ${rocks.length}/8 座 · 铁路命中 ${hitCount} · 无承托根 ${report.roots.unsupported}`;
 }catch(e){errors.push({type:'harness-check',message:String(e.stack||e)});status.textContent='检查失败，详情见 JSON';}finally{busy=false;controls();emit();}}
async function samplePerformance(){
 if(!ready||busy)return;busy=true;controls();const serial=generation,w=frame.contentWindow,canvas=t.renderer.domElement,samples=[],calls=[],triangles=[],points=[],lines=[];const started=performance.now();let previous=null,lastStatus=0;
 try{while(performance.now()-started<10000){const timestamp=await new Promise(resolve=>w.requestAnimationFrame(resolve));if(serial!==generation)return;if(previous!==null)samples.push(timestamp-previous);previous=timestamp;const render=t.renderer.info.render;calls.push(render.calls);triangles.push(render.triangles);points.push(render.points);lines.push(render.lines);const elapsed=performance.now()-started;if(elapsed-lastStatus>1000){lastStatus=elapsed;status.textContent=`实际场景性能采样 ${Math.min(10,elapsed/1000).toFixed(1)}/10 秒…`;}}
 const stats=a=>{const b=a.filter(Number.isFinite).sort((x,y)=>x-y);return {samples:b.length,median:b[Math.floor((b.length-1)*.5)]??null,p95:b[Math.floor((b.length-1)*.95)]??null,max:b.at(-1)??null};};
 performanceReport={sampledAt:new Date().toISOString(),durationMs:performance.now()-started,view,clock,flat,noFog,coastalUnlit,variant:$('#variant').value,visibility:w.document.visibilityState,viewport:{iframeInnerWidth:w.innerWidth,iframeInnerHeight:w.innerHeight,cssWidth:canvas.clientWidth,cssHeight:canvas.clientHeight,drawingBufferWidth:canvas.width,drawingBufferHeight:canvas.height,devicePixelRatio:w.devicePixelRatio,rendererPixelRatio:t.renderer.getPixelRatio()},rafIntervalMs:stats(samples),rendererCalls:stats(calls),rendererTriangles:stats(triangles),rendererPoints:stats(points),rendererLines:stats(lines),method:'10 seconds of iframe requestAnimationFrame intervals; renderer.info sampled without forcing renders. CPU/browser scheduling evidence, NOT GPU time or benchmark-comparable FPS. Background throttling and unrelated activity may affect results.'};status.textContent=`采样完成 · rAF 中位 ${performanceReport.rafIntervalMs.median?.toFixed(1)} ms / p95 ${performanceReport.rafIntervalMs.p95?.toFixed(1)} ms`;
 }catch(e){errors.push({type:'performance-sample',message:String(e)});}finally{if(serial===generation){busy=false;controls();emit();}}
}
function download(url,name){const a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();}
function exportStem(){return `sea-stack-variant${$('#variant').value}-${view}-${clock===.5?'day':clock===.75?'dusk':'time'+clock}-flat${Number(flat)}-noFog${Number(noFog)}-unlit${Number(coastalUnlit)}`;}
function exportJson(stem=exportStem()){shaderDiagnostics=readShaderDiagnostics();emit();const url=URL.createObjectURL(new Blob([output.textContent],{type:'application/json'}));download(url,stem+'.json');setTimeout(()=>URL.revokeObjectURL(url),10000);}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view).catch(e=>{errors.push({type:'view',message:String(e)});emit();}));document.querySelectorAll('[data-time]').forEach(b=>b.onclick=()=>setTime(b.dataset.time));
$('#performance').onclick=samplePerformance;$('#unlit').onclick=()=>setUnlit(!coastalUnlit);$('#flat').onclick=()=>setFlat(!flat);$('#noFog').onclick=()=>setNoFog(!noFog);$('#check').onclick=check;$('#json').onclick=()=>exportJson();$('#reload').onclick=load;$('#variant').onchange=load;
$('#export').onclick=()=>{try{refresh();const stem=exportStem();download(t.renderer.domElement.toDataURL('image/png'),stem+'.png');status.textContent='已导出当前实际场景 PNG；检查 JSON 请使用独立按钮。';}catch(e){errors.push({type:'export',message:String(e)});emit();}};
$('#variant').value=new URLSearchParams(location.search).get('seaStackStudy')==='0'?'0':'1';load();
