import assert from "node:assert/strict";
import { buildGeodesicMainAndDualGrid } from "../TigerMessenger/src/procgen/planet/geodesicGrid.js";
import { createLandmarkManifest, validateLandmarkManifest } from "../TigerMessenger/src/world/planetV8/landmarkManifest.js";
import { createTerrainTiles } from "../TigerMessenger/src/procgen/planet/terrainTiles.js";
import { solveSphericalTerrain } from "../TigerMessenger/src/procgen/planet/sphericalWfc.js";
import { compilePlanetV8 } from "../TigerMessenger/src/procgen/planet/planetCompilerV8.js";
import { compileCurvedWater, validateCurvedWater } from "../TigerMessenger/src/world/waterV8/curvedWaterCompiler.js";
import { buildCloudImpostorAtlas } from "../TigerMessenger/src/render/clouds/impostorAtlasBuilder.js";
import { compileCloudClusters } from "../TigerMessenger/src/render/clouds/cloudClusterCompiler.js";

const manifest = createLandmarkManifest({ seed: 42 });
assert.equal(validateLandmarkManifest(manifest).ok, true);
const grid = buildGeodesicMainAndDualGrid({ radius: 160, subdivision: 1, seed: 42, preserve: manifest.map((entry) => entry.direction) });
assert.equal(grid.dual.validate().ok, true);
assert.ok(grid.dual.cellCount > 0);
const wfc = solveSphericalTerrain({ graph: grid.dual, landmarks: manifest, tiles: createTerrainTiles(), seed: 42 });
assert.equal(wfc.ok, true, wfc.report);
assert.equal(Object.keys(wfc.assignmentByCellId).length, grid.dual.cellCount);
const compiled = compilePlanetV8({ seed: 42, subdivision: 1, chartLimit: 2, resolution: 12 });
assert.equal(compiled.ok, true, compiled.report);
assert.ok(compiled.charts.every((chart) => chart.mesh.stats.triangleCount > 0));
assert.ok(compiled.vegetation.every((vegetation) => vegetation.instanceCount >= 0));
assert.ok(typeof compiled.snapshot.vegetation.clusterHash === "string");
assert.equal(compiled.combatSurface.zones.length, 2);
assert.ok(compiled.combatSurface.zones.every((zone) => zone.offSurfacePolicy === "reject-and-reproject"));
assert.ok(compiled.snapshot.nav.combatKeepoutHash.includes("battlefield"));
const moonLake = compiled.manifest.find((entry) => entry.id === "moon-lake");
assert.match(compiled.surface.sample(moonLake.direction).surfaceId, /^water:lake:/);
const water = compileCurvedWater({ grid, radius: 160, basins: manifest.filter((entry) => entry.profile === "curved-lake").map((entry) => ({ direction: entry.direction, angularRadius: entry.angularRadius })) });
assert.equal(validateCurvedWater(water).ok, true);
const atlas = buildCloudImpostorAtlas({ views: 8, size: 16 });
assert.equal(atlas.colorAlpha.length, 8 * 16 * 16 * 4);
const cells = grid.dual.cells().map((cell) => ({ ...cell, direction: grid.dual.directionOf(cell.index) }));
const semantics = new Map(cells.map((cell) => [cell.id, { wetness: cell.index % 3 / 3, height: cell.index % 7 / 2 }]));
const cloudsA = compileCloudClusters({ cells, semantics, seed: 42 });
const cloudsB = compileCloudClusters({ cells, semantics, seed: 42 });
assert.equal(cloudsA.climateHash, cloudsB.climateHash);
console.log(`✅ Planet V8 core: cells=${grid.dual.cellCount}, charts=${compiled.charts.length}, waterLakes=${water.lakes.length}, clouds=${cloudsA.instanceCount}`);
