import assert from "node:assert/strict";
import { buildGeodesicMainAndDualGrid } from "../TigerMessenger/src/procgen/planet/geodesicGrid.js";
import { compileCurvedWater, validateCurvedWater } from "../TigerMessenger/src/world/waterV8/curvedWaterCompiler.js";
import { createWaterRouteFleet, migrateCanalBoatToWaterRoute } from "../TigerMessenger/src/world/waterV8/waterRouteFleet.js";
import { validateWaterSurfaceSemantics } from "../TigerMessenger/src/world/waterV8/waterSemantics.js";
const grid = buildGeodesicMainAndDualGrid({ radius: 160, subdivision: 2, seed: 1 });
const water = compileCurvedWater({ grid, radius: 160, basins: [{ direction: [0, 1, 0], angularRadius: 0.12 }], harborAnchors: [{ id: "a", direction: [1, 0, 0] }, { id: "b", direction: [0, 0, 1] }] });
assert.equal(validateCurvedWater(water).ok, true);
assert.equal(validateWaterSurfaceSemantics(water.surfaceSemantics).ok, true);
assert.ok(water.ocean.positions.some((value, i) => i % 3 === 0 && Math.abs(Math.hypot(value, water.ocean.positions[i + 1], water.ocean.positions[i + 2]) - 160) < 1e-3));
assert.ok(water.routes.every((route) => route.points.every((point) => Math.abs(Math.hypot(...point.position) - water.radius) < 8)), "SLERP 航线必须保持球面半径");
const fleet = createWaterRouteFleet({ routes: water.routes, boats: [] });
assert.equal(migrateCanalBoatToWaterRoute({ routeIndex: 0, u: 0.4 }, water.routes).ok, true);
assert.equal(migrateCanalBoatToWaterRoute({ routeIndex: 0 }, [], [{ id: "old-harbor" }]).dockedAt, "old-harbor");
const directionFleet = createWaterRouteFleet({ routes: water.routes, boats: [] });
const directionBoat = { routeId: water.routes[0].id, u: 0.4 };
const tangent = directionFleet.directionFor(directionBoat);
const targetTangent = directionFleet.directionToTarget(directionBoat, water.routes[0].points.at(-1).position);
assert.ok(Math.abs(Math.hypot(...tangent) - 1) < 1e-6);
assert.ok(Math.abs(Math.hypot(...targetTangent) - 1) < 1e-6);
assert.ok(Math.abs(tangent.reduce((sum, value, index) => sum + value * water.routes[0].points[Math.floor(directionBoat.u * (water.routes[0].points.length - 1))].position[index], 0)) < 1e-3);
fleet.update(1);
console.log(`✅ Planet V8 water: curved ocean/lake, route and canal migration passed (${water.routes.length} routes)`);
