import { spawnSync } from "node:child_process";
import { readFileSync } from "node:fs";
import assert from "node:assert/strict";

const graph = spawnSync(process.execPath, ["tools/test_planet_v8_graph.mjs"], { encoding: "utf8" });
process.stdout.write(graph.stdout || "");
process.stderr.write(graph.stderr || "");
if (graph.status !== 0) process.exit(graph.status || 1);
const wfc = spawnSync(process.execPath, ["tools/test_planet_v8_wfc.mjs"], { encoding: "utf8" });
process.stdout.write(wfc.stdout || "");
process.stderr.write(wfc.stderr || "");
if (wfc.status !== 0) process.exit(wfc.status || 1);
const result = spawnSync(process.execPath, ["tools/test_planet_v8_core.mjs"], { encoding: "utf8" });
process.stdout.write(result.stdout || "");
process.stderr.write(result.stderr || "");
if (result.status !== 0) process.exit(result.status || 1);
for (const test of ["tools/test_planet_v8_semantics.mjs", "tools/test_planet_v8_water.mjs"]) {
  const stage = spawnSync(process.execPath, [test], { encoding: "utf8" });
  process.stdout.write(stage.stdout || "");
  process.stderr.write(stage.stderr || "");
  if (stage.status !== 0) process.exit(stage.status || 1);
}
for (const test of ["tools/test_planet_v8_clouds.mjs", "tools/test_highland_hero_clouds.mjs", "tools/test_planet_v8_mc.mjs"]) {
  const stage = spawnSync(process.execPath, [test], { encoding: "utf8" });
  process.stdout.write(stage.stdout || "");
  process.stderr.write(stage.stderr || "");
  if (stage.status !== 0) process.exit(stage.status || 1);
}
const worker = spawnSync(process.execPath, ["tools/test_planet_v8_worker.mjs"], { encoding: "utf8" });
process.stdout.write(worker.stdout || "");
process.stderr.write(worker.stderr || "");
if (worker.status !== 0) process.exit(worker.status || 1);
const profiles = spawnSync(process.execPath, ["tools/test_planet_v8_profiles.mjs"], { encoding: "utf8" });
process.stdout.write(profiles.stdout || "");
process.stderr.write(profiles.stderr || "");
if (profiles.status !== 0) process.exit(profiles.status || 1);
const deterministic = spawnSync(process.execPath, ["tools/test_planet_v8_determinism.mjs"], { encoding: "utf8" });
process.stdout.write(deterministic.stdout || "");
process.stderr.write(deterministic.stderr || "");
if (deterministic.status !== 0) process.exit(deterministic.status || 1);
const debug = spawnSync(process.execPath, ["tools/test_planet_v8_debug.mjs"], { encoding: "utf8" });
process.stdout.write(debug.stdout || "");
process.stderr.write(debug.stderr || "");
if (debug.status !== 0) process.exit(debug.status || 1);
const navigation = spawnSync(process.execPath, ["tools/test_planet_v8_navigation.mjs"], { encoding: "utf8" });
process.stdout.write(navigation.stdout || "");
process.stderr.write(navigation.stderr || "");
if (navigation.status !== 0) process.exit(navigation.status || 1);
const rider = spawnSync(process.execPath, ["tools/test_planet_v8_rider.mjs"], { encoding: "utf8" });
process.stdout.write(rider.stdout || "");
process.stderr.write(rider.stderr || "");
if (rider.status !== 0) process.exit(rider.status || 1);
const combat = spawnSync(process.execPath, ["tools/test_planet_v8_combat.mjs"], { encoding: "utf8" });
process.stdout.write(combat.stdout || "");
process.stderr.write(combat.stderr || "");
if (combat.status !== 0) process.exit(combat.status || 1);
const sceneMatrix = spawnSync(process.execPath, ["tools/test_planet_v8_scene_matrix.mjs"], { encoding: "utf8" });
process.stdout.write(sceneMatrix.stdout || "");
process.stderr.write(sceneMatrix.stderr || "");
if (sceneMatrix.status !== 0) process.exit(sceneMatrix.status || 1);
const routeMatrix = spawnSync(process.execPath, ["tools/test_planet_v8_routes_1000.mjs"], { encoding: "utf8" });
process.stdout.write(routeMatrix.stdout || "");
process.stderr.write(routeMatrix.stderr || "");
if (routeMatrix.status !== 0) process.exit(routeMatrix.status || 1);
const chainAdjacency = spawnSync(process.execPath, ["tools/test_planet_v8_chain_adjacency.mjs"], { encoding: "utf8" });
process.stdout.write(chainAdjacency.stdout || "");
process.stderr.write(chainAdjacency.stderr || "");
if (chainAdjacency.status !== 0) process.exit(chainAdjacency.status || 1);
const acceptance = spawnSync(process.execPath, ["tools/test_grok_acceptance_matrix.mjs"], { encoding: "utf8" });
process.stdout.write(acceptance.stdout || "");
process.stderr.write(acceptance.stderr || "");
if (acceptance.status !== 0) process.exit(acceptance.status || 1);
const ledger = JSON.parse(readFileSync("tools/out/planet-v8-ledger.json", "utf8"));
assert.equal(ledger.worldSnapshotVersion, 8);
assert.ok(ledger.capabilities.some((capability) => capability.id === "geodesic-main-dual-grid"));
assert.ok(ledger.capabilities.every((capability) => ["DEFINED", "TESTED", "WIRED", "VISUAL_ACCEPTED", "PERF_ACCEPTED", "DEFAULT_ON", "LEGACY_RETIRED"].includes(capability.level)));
console.log(`✅ Planet V8 all gates: ${ledger.capabilities.length} capability records; browser/GPU/owner gates are automated (hardware FPS not inferred)`);
