import {chromium} from '/Users/panglaohu/Downloads/TigerInBamboo/tools/shot/node_modules/playwright/index.mjs';
import {readFile,writeFile,readdir} from 'node:fs/promises';
const out='TigerMessenger/artifacts/pipeline/city-swamp-refinement',label=process.argv[2];
const b=await chromium.launch({channel:'chrome',headless:true,args:['--use-angle=metal']});
try{const p=await b.newPage({viewport:{width:1440,height:900}}),errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
if(label==='before')for(const file of await readdir(out+'/source-before'))await p.route('**/src/world/'+file,async r=>r.fulfill({contentType:'application/javascript',body:await readFile(out+'/source-before/'+file,'utf8')}));
await p.goto('http://localhost:8931/TigerMessenger/?autostart=1',{waitUntil:'domcontentloaded'});await p.waitForFunction(()=>window.__tm?.messenger?.landmarks?.moebiusSwamp,null,{timeout:180000});await p.waitForTimeout(4000);
const audit=await p.evaluate(()=>{const t=window.__tm,T=t.THREE,l=t.messenger.landmarks;t.cameraRig.update=()=>{};t.P.daySpeed=0;t.P.timeOfDay=.38;t.scene.updateMatrixWorld(true);const s=l.moebiusSwamp.userData.inner||l.moebiusSwamp,g=l.abandonedGate.userData.seatRoot;
window.paletteViews=[{name:'swamp',root:s,eye:[40,58,49],at:[0,29,0]},{name:'city',root:l.moebius.grand.group.userData.v9Root,eye:[-17,17,15],at:[-5,14,3]},{name:'swamp-water',root:s,eye:[17,30,21],at:[0,26,0]},{name:'underwater',root:s,eye:[12,18,10],at:[-6,15,-5]},{name:'canopy',root:s,eye:[38,88,42],at:[-8,64,-7]}];
const boats=[];s.traverse(o=>{if(o.userData.warshipV6){const materials={};o.traverse(m=>{if(m.material?.color)materials[m.material.name]=m.material.color.getHexString()});const api=o.userData.warshipV6,n=api.nodes.get("n63"),before=n?.quaternion.toArray();api.update(.05,true);api.update(.05,true);boats.push({name:o.name,palette:o.userData.moebiusPalette,materials,oarMoved:JSON.stringify(before)!==JSON.stringify(n?.quaternion.toArray()),crew:api.crewStatus().length});}});return {boats,crystals:l.moebius.crystals.length,prisms:l.moebius.crystals.reduce((n,r)=>n+r.group.userData.v9Root.children.filter(o=>o.name==='v9-crystal-prism').length,0),tram:!!l.tramSystem.curve,swampUpdate:typeof s.update,gate:g.children.length};});
for(let i=0;i<5;i++){await p.evaluate(i=>{const t=window.__tm,T=t.THREE,v=window.paletteViews[i];t.camera.position.copy(v.root.localToWorld(new T.Vector3(...v.eye)));t.camera.up.set(0,1,0).transformDirection(v.root.matrixWorld);t.camera.lookAt(v.root.localToWorld(new T.Vector3(...v.at)));t.camera.fov=48;t.camera.updateProjectionMatrix();t.distanceCulling.recollect();t.distanceCulling.update(3);},i);await p.waitForTimeout(600);const shot=await p.evaluate(()=>{const t=window.__tm;t.renderer.render(t.scene,t.camera);return t.renderer.domElement.toDataURL()});await writeFile(`${out}/${label}-${['swamp','city','swamp-water','underwater','canopy'][i]}.png`,Buffer.from(shot.split(',')[1],'base64'));}
audit.redSail=await p.evaluate(()=>{const t=window.__tm,T=t.THREE,r=new T.Raycaster();r.setFromCamera(new T.Vector2(1100/1440*2-1,1-200/900*2),t.camera);return r.intersectObjects(t.scene.children,true).slice(0,8).map(h=>{const o=h.object,parents=[];for(let a=o;a;a=a.parent)parents.push(a.name);return {parents,material:o.material?.name,color:o.material?.color?.getHexString()};});});await writeFile(`${out}/${label}-details.json`,JSON.stringify({...audit,errors},null,2));console.log(JSON.stringify({...audit,errors}));}finally{await b.close()}
