/** Default game camera for the user's current city review; no iframe/extra route. */
export function installTargetCityPresentation({THREE:T,castle,camera,cameraRig,renderer,runtime,scene}){
 const panel=document.createElement('section');panel.id='citadel-live-city';panel.style.cssText='position:fixed;right:16px;top:16px;z-index:200;background:#17343ce8;color:#f6f4e7;padding:12px;border-radius:12px;max-width:380px;font:14px system-ui';
 const title=document.createElement('strong');title.textContent='高山圣城';panel.append(title);
 const buttons=document.createElement('div');buttons.style.cssText='display:flex;gap:6px;margin-top:9px;flex-wrap:wrap';panel.append(buttons);
 const views={全景:[[0,68,220],[0,10,5],35],旧城:[[-20,37,55],[-55,27,9],46],新城:[[19,34,89],[71,21,34],45],广场:[[20,20,111],[63,10,68],46]};
 const handle={active:true,view:'全景',setView(name){const [p,q,fov]=views[name];handle.active=true;handle.view=name;castle.updateWorldMatrix(true,false);camera.position.copy(castle.localToWorld(new T.Vector3(...p)));camera.up.set(0,1,0).transformDirection(castle.matrixWorld);camera.lookAt(castle.localToWorld(new T.Vector3(...q)));camera.fov=fov;camera.zoom=1;camera.far=4000;camera.updateProjectionMatrix();camera.updateMatrixWorld(true);},dispose(){panel.remove();}};
 function button(name,action){const b=document.createElement('button');b.textContent=name;b.style.cssText='padding:5px 10px;border:1px solid #abc6ca;border-radius:5px;cursor:pointer';b.onclick=action;buttons.append(b);}
 for(const name of Object.keys(views))button(name,()=>handle.setView(name));
 button('返回送信',()=>{handle.active=false;cameraRig.setFov(cameraRig.getDefaultFov());cameraRig.snapToPlayer();document.getElementById('start-btn')?.click();});
 const details=document.createElement('details'),summary=document.createElement('summary'),out=document.createElement('pre');summary.textContent='加载状态';out.id='citadel-runtime-status';out.style.cssText='white-space:pre-wrap;font-size:11px;max-height:35vh;overflow:auto';details.append(summary,out);panel.append(details);
 function state(){return{at:new Date().toISOString(),view:handle.view,installed:runtime.report.installed,oldCity:runtime.report.cityDetail?.oldCity?.geometry?.version,newStairs:runtime.report.cityDetail?.newCityStairs?.authored?.revision,rock:runtime.report.cityDetail?.rockAppearance,clouds:runtime.report.cityDetail?.clouds?.version,landmarks:runtime.report.landmarkIntegration?.ok,navigation:runtime.report.navigation,tram:runtime.report.tram,gpuProgramCount:renderer.info.programs?.length??0,gpuFailures:(renderer.info.programs||[]).filter(p=>p.diagnostics?.runnable===false).map(p=>p.diagnostics),oldMaterials:(()=>{const a=[];runtime.root.getObjectByName('citadel-target-old-city')?.traverse(o=>{if(o.isMesh&&a.length<12)a.push({name:o.name,color:o.material?.color?.getHexString(),type:o.material?.type});});return a;})(),glError:renderer.getContext().getError(),camera:{position:camera.position.toArray(),quaternion:camera.quaternion.toArray(),fov:camera.fov}};}
 button('检查加载',()=>{out.textContent=JSON.stringify(state(),null,2);details.open=true;});
 button('保存当前画面',async()=>{try{renderer.render(scene,camera);const r=await fetch('http://localhost:8932/capture',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:'runtime-'+Date.now(),png:renderer.domElement.toDataURL('image/png'),state:state()})});if(!r.ok)throw new Error(await r.text());out.textContent=await r.text();details.open=true;}catch(e){out.textContent='截图保存失败：'+e.message;details.open=true;}});
 document.body.append(panel);handle.setView('全景');out.textContent=JSON.stringify({installed:runtime.report.installed,landmarks:runtime.report.landmarkIntegration?.ok});return handle;
}
