import assert from 'node:assert/strict';import * as T from 'three';import{readFileSync,writeFileSync}from'node:fs';
import{actualUserMarkedStructureFixture}from'../../../tests/world/targetUserMarkedStructure.fixture.mjs';
import{createTargetCityDetailCandidate}from'../../../src/world/citadel/targetCityDetailCandidate.js';
const live=JSON.parse(readFileSync(new URL('../citadel-four-hour-20261005/runtime-1791264876725.json',import.meta.url))),f=actualUserMarkedStructureFixture();f.release.walkingConnection={kind:'stacked-connected'};f.release.structureOptions={galleryPierWidths:{oldShore:.9},newCityTransitLinks:true};
const c=createTargetCityDetailCandidate({castle:f.castle,cliffTransitRelease:f.release,fitSunShadow:false});f.castle.add(c.root);f.scene.updateMatrixWorld(true);const main=c.root.getObjectByName('citadel-target-new-city-main'),inverse=main.matrixWorld.clone().invert(),ci=f.castle.matrixWorld.clone().invert(),meshes=[];
f.scene.traverse(o=>{if(!o.isMesh)return;for(let p=o;p;p=p.parent)if(!p.visible)return;meshes.push(o);});
const cast=(a,b,far=a.distanceTo(b))=>{const ray=new T.Raycaster(a,b.clone().sub(a).normalize(),.001,far);return ray.intersectObjects(meshes,false).map(h=>({name:h.object.name,distance:h.distance,mainLocal:h.point.clone().applyMatrix4(inverse).toArray(),castleLocal:h.point.clone().applyMatrix4(ci).toArray(),material:(Array.isArray(h.object.material)?h.object.material[0]:h.object.material)?.name,normal:h.face?.normal.toArray()}));};
const origin=new T.Vector3(...live.camera.position),camera=new T.PerspectiveCamera(live.camera.fov,2830/1944,.1,2000);camera.position.copy(origin);camera.quaternion.fromArray(live.camera.quaternion);camera.updateMatrixWorld(true);camera.updateProjectionMatrix();
const view=[];for(const x of[-2,0,2])for(const y of[3,5,7,9]){const local=[x,y,7.12],point=new T.Vector3(...local).applyMatrix4(main.matrixWorld),ndc=point.clone().project(camera);view.push({aimMain:local,imagePixel:[(ndc.x+1)*2830/2,(1-ndc.y)*1944/2],hits:cast(origin,point,origin.distanceTo(point)+60).slice(0,5)});}
const cameraPixels=[];for(const x of[875,915,955])for(const y of[565,600,635]){const ray=new T.Raycaster();ray.setFromCamera(new T.Vector2(x/2830*2-1,1-y/1944*2),camera);cameraPixels.push({pixel:[x,y],hits:cast(ray.ray.origin,ray.ray.origin.clone().add(ray.ray.direction),300).slice(0,4)});}
const axial=[];for(const x of[-2,-1,0,1,2])for(const y of[1.75,2.4,3,5,7])for(const reverse of[false,true]){const a=new T.Vector3(x,y,reverse?-8.7:7.8).applyMatrix4(main.matrixWorld),b=new T.Vector3(x,y,reverse?7.8:-8.7).applyMatrix4(main.matrixWorld);axial.push({x,y,reverse,hits:cast(a,b)});}
const beyondRear=[];for(const x of[-1,0,1]){const a=new T.Vector3(x,2.4,-8.81).applyMatrix4(main.matrixWorld),b=new T.Vector3(x,2.4,-35).applyMatrix4(main.matrixWorld);beyondRear.push({x,hits:cast(a,b).slice(0,3)});}
const provider=c.getPlayerSupport(),walking=[];let groundCount=0,bodyCount=0;
for(const x of[-.8,0,.8])for(const reverse of[false,true]){let previous=null;for(let i=0;i<=160;i++){const z=reverse?-8.6+16.1*i/160:7.5-16.1*i/160,p=new T.Vector3(x,1.2,z).applyMatrix4(main.matrixWorld),y=provider.ground(p);groundCount++;if(y===null||Math.abs(y-p.length())>.3)walking.push({x,z,reverse,type:'ground',y,ref:p.length(),last:provider.report().lastGround});if(y!==null)p.setLength(y);if(previous){bodyCount++;if(provider.walls(previous,p.clone(),p.clone().sub(previous)))walking.push({x,z,reverse,type:'body',last:provider.report().lastWall});}previous=p;}}
const report={fixture:'actualUserMarkedStructureFixture + current real candidate expanded main',sourceScreenshot:'runtime-1791264876725.png',liveCamera:live.camera,mainVersion:c.report.newCity.geometry.version,passage:c.report.newCity.geometry.passage,cameraInMain:origin.clone().applyMatrix4(inverse).toArray(),view,cameraPixels,axial,beyondRear,walking:{groundCount,bodyCount,failures:walking},gpuReplayed:false};writeFileSync(new URL('./report.json',import.meta.url),JSON.stringify(report,null,2));console.log(JSON.stringify({cameraInMain:report.cameraInMain,view:view.map(q=>({aim:q.aimMain,pixel:q.imagePixel,first:q.hits[0]})),pixels:cameraPixels.map(q=>({pixel:q.pixel,first:q.hits[0]})),axialBlocked:axial.filter(q=>q.hits.length),walking:report.walking,beyondRear},null,2));assert.equal(axial.length,50);assert.equal(axial.filter(q=>q.hits.length).length,0);assert.deepEqual(walking,[]);assert.equal(cameraPixels.find(q=>q.pixel[0]===915&&q.pixel[1]===600).hits[0].name,'main-hall-side-wall');c.dispose();f.dispose();
