import {chromium} from '/Users/panglaohu/Downloads/TigerInBamboo/tools/shot/node_modules/playwright/index.mjs';
import {readFile,writeFile} from 'node:fs/promises';
const label=process.argv[2],out='TigerMessenger/artifacts/pipeline/crystal-track-balance',b=await chromium.launch({channel:'chrome',headless:true,args:['--use-angle=metal']});
try{const p=await b.newPage({viewport:{width:1200,height:800}}),errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
if(label==='before')await p.route('**/src/world/crystalV7Layout.js',async r=>r.fulfill({contentType:'application/javascript',body:await readFile(out+'/source-before/crystalV7Layout.js','utf8')}));
await p.goto('http://localhost:8931/TigerMessenger/?autostart=1',{waitUntil:'domcontentloaded'});await p.waitForFunction(()=>window.__tm?.messenger?.landmarks?.tramSystem,null,{timeout:180000});await p.waitForTimeout(2500);
const audit=await p.evaluate(()=>{const t=window.__tm,T=t.THREE,l=t.messenger.landmarks,cv=l.tramSystem.curves.blue;t.cameraRig.update=()=>{};t.P.daySpeed=0;t.P.timeOfDay=.38;t.scene.updateMatrixWorld(true);
window.balanceView=(u,side)=>{const eye=cv.getPointAt(u),up=eye.clone().normalize(),forward=cv.getTangentAt(u).negate(),right=new T.Vector3().crossVectors(forward,up).normalize();eye.addScaledVector(up,2.5);t.camera.position.copy(eye);t.camera.up.copy(up);t.camera.lookAt(eye.clone().addScaledVector(right,side*35).addScaledVector(forward,12).addScaledVector(up,-8));t.camera.fov=65;t.camera.updateProjectionMatrix();t.distanceCulling.recollect();t.distanceCulling.update(3);};
const solids=[];for(const i of[4,6,11])l.moebius.crystals[i].group.userData.v9Root.traverseVisible(o=>{if(o.isMesh)solids.push(o)});l.moebius.v7Shores.traverseVisible(o=>{if(o.isMesh&&[4,6,11].some(i=>o.name==='v7-bank-rock-'+i))solids.push(o)});
const ray=new T.Raycaster(),hits=[];let rays=0;for(let u=.235;u<.355;u+=.0004)for(const h of[.4,2,4])for(const lateral of[-1.6,0,1.6]){const at=v=>{const pos=cv.getPointAt(v),up=pos.clone().normalize(),right=new T.Vector3().crossVectors(cv.getTangentAt(v).negate(),up).normalize();return pos.addScaledVector(up,h).addScaledVector(right,lateral);};const a=at(u),d=at(u+.0004).sub(a);ray.set(a,d.clone().normalize());ray.far=d.length();rays++;const hit=ray.intersectObjects(solids,false)[0];if(hit)hits.push({u,h,lateral,name:hit.object.name});}
return {rays,hits,clusters:l.moebius.crystals.length,scope:'Blue tram swept line samples against the three moved clusters and their shoreline rocks; not full vehicle mesh collision'};});
for(const [name,u,side]of[['entry-left',.258,-1],['entry-right',.258,1],['middle-left',.29,-1],['middle-right',.29,1],['exit-left',.33,-1],['exit-right',.33,1]]){await p.evaluate(([u,s])=>window.balanceView(u,s),[u,side]);await p.waitForTimeout(400);const data=await p.evaluate(()=>{const t=window.__tm;t.renderer.render(t.scene,t.camera);return t.renderer.domElement.toDataURL()});await writeFile(`${out}/${label}-${name}.png`,Buffer.from(data.split(',')[1],'base64'));}
audit.errors=errors;audit.passed=!errors.length&&!audit.hits.length;await writeFile(`${out}/${label}-check.json`,JSON.stringify(audit,null,2));console.log(JSON.stringify(audit));}finally{await b.close();}
